### PR TITLE
configurable ambassador for running locally

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1147

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6617adcbcc4d494dabdcac10c5da07862b4e3db7 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Seems to have been caused by running an older version of the ambassador chart.

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 31508d0636130a096cb8ed153dca9c22e6935ad0
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 31508d0636130a096cb8ed153dca9c22e6935ad0
* failed to process repo SeldonIO/seldon-core refref 31508d0636130a096cb8ed153dca9c22e6935ad0
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
