### PR TITLE
Operator/deps update - straightforward dependencies update

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Tests seems to fly nicely, if they pass successfully I suggest to merge this one. Closes https://github.com/SeldonIO/seldon-core/issues/2098
@axsaucedo

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jul  8 18:00:36 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=1

**Comment by seldondev** [comment]
Wed Jul  8 18:00:40 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=2

**Comment by seldondev** [comment]
Wed Jul  8 18:00:50 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=3

**Comment by seldondev** [comment]
Thu Jul  9 10:46:58 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=4

**Comment by axsaucedo** [comment]
Integration tests pass as well, looks good 👍 
/test notebooks
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2093#issuecomment-656134258 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-656134258/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jul  9 13:42:28 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=5

**Comment by seldondev** [comment]
Fri Jul 10 08:19:33 UTC 2020
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=6

**Comment by seldondev** [comment]
Fri Jul 10 08:19:36 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2093/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2093 --build=7

**Comment by adriangonz** [comment]
Both notebooks and integration tests have passed. Not sure why they don't get updated though, but this should be good to merge (I'll do it manually) @axsaucedo @RafalSkolasinski :+1:

**Comment by RafalSkolasinski** [comment]
> Both notebooks and integration tests have passed. Not sure why they don't get updated though, but this should be good to merge (I'll do it manually) @axsaucedo @RafalSkolasinski :+1: 

Awesome!

**Pull request merged**
