### PR TITLE
Request logger elastic mapping type unsetting

### LINKED ISSUE #3013: Removal of mapping type from request logger
This issue pertains to the removal of mapping types in new elastic versions, as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_document_apis). 

So we will need to deprecate the `inferencerequest` mapping type in the current request logger implementation in favour of a unique _doc type. [Source Link](https://github.com/SeldonIO/seldon-core/blob/master/components/seldon-request-logger/app/log_helper.py#L20)

### PR DESCRIPTION
**Pull request by SachinVarghese**
**What this PR does / why we need it**:
This PR accomplishes the following objectives
- [x] ~~Updating req logger elasticsearch package to `7.10.0`~~ (Not done as this causes breaking changes)
- [x] Setting mapping type to None as mentioned in issue #3013 
- [x] Sets elements object for request-response pairs to accurate value without the additional dimension
 
**Which issue(s) this PR fixes**:

Fixes #3013 

**Special notes for your reviewer**:

[Elastic Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#removal-of-types)

**Does this PR introduce a user-facing change?**:
So with this PR, we deprecate the `inferencerequest` mapping type in the current request logger implementation in favour of a default `_doc` type. So new indexes created will not have a mapping type. Since we are using dynamic mapping there shouldn't be any breaking changes.

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by SachinVarghese** [comment]
Test on different elastic versions as per doc [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html#_schedule_for_removal_of_mapping_types)

**Comment by SachinVarghese** [comment]
Things to test
 - Upgrading request logger breaks anything? (Removing type has breaking changes?)
 - Previous elastic version >=6.x to be tested

**Comment by SachinVarghese** [comment]
Fails on elastic `6.8.10` with error 
```
request [/inference-log-seldon-seldon-income-classifier-default/_update/xxx] 
contains unrecognized parameter: [retry_on_conflict] 
```
due to elasticsearch dependency version mismatch (updated to 7.10.0)

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ryandawsonuk**
You can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ryandawsonuk — APPROVED** [review]
/lgtm
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ryandawsonuk](https://github.com/SeldonIO/seldon-core/pull/3014#pullrequestreview-626165218 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
