### PR TITLE
Release v1.13.1 for OpenShift

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Upgrade OpenShift release manifests. 

Work was carried in https://github.com/RafalSkolasinski/seldon-core/tree/v1.13.1-release-redhat

In here I squashed everything into a single commit https://github.com/RafalSkolasinski/seldon-core/tree/v1.13.1-release-redhat-rebase 

In branch that I open this PR I cherry picked that single commit on top of master.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Ok I just confirmed the `pyhton-lint` one is broken in master, will add a separate PR for that one

**Comment by axsaucedo** [comment]
Ok just confirmed docs-build is also failing in master, so will also be fixed in https://github.com/SeldonIO/seldon-core/pull/3991

**Comment by axsaucedo** [comment]
@cliveseldon all tests seem to be good (validated from fixes in master) - is the PR good for merge?

**Pull request merged**
