### PR TITLE
upgrade k8s.io and jaeger-client-go libraries

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

To stay up to date

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2088

**Special notes for your reviewer**:

- Bumped k8s.io to v0.17.9
- Bumped github.com/uber/jaeger-client-go to v2.25

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 1 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/1.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2169 --build=1

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 2 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/2.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2169 --build=2

**Comment by seldondev** [comment]
## STARTING TEST [ notebooks # 3 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/3.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2169 --build=3

**Comment by seldondev** [comment]
## STARTING TEST [ integration # 4 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/4.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2169 --build=4

**Comment by seldondev** [comment]
## SUCCESS [lint # 2] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [pr-build # 1] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [notebooks # 3] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [integration # 4] TEST PASSED ✅

Well done! 😎

**Comment by RafalSkolasinski** [comment]
Tests rock solid, on the first try :rocket:

**Comment by RafalSkolasinski** [comment]
Rebased onto master. Triggering tests to verify if we have flakiness or not (tests passed before).

/test notebooks
/test integration

**Comment by seldondev** [comment]
Tue Jul 21 12:51:28 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2169 --build=5

**Comment by seldondev** [comment]
Tue Jul 21 12:51:33 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2169 --build=6

**Comment by seldondev** [comment]
Tue Jul 21 12:51:41 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2169/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2169 --build=8

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2169#issuecomment-661902349 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-661902349/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | d93e0791f61b6a89bf42b74807ac3af872618aa5 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | d93e0791f61b6a89bf42b74807ac3af872618aa5 | [link]() | `/test lint`
pr-build | d93e0791f61b6a89bf42b74807ac3af872618aa5 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
