### PR TITLE
Fix check for separate annotation pid

### PR DESCRIPTION
**Pull request by cliveseldon**
The webhook defaulter was not checking the value but just the existence of this annotation.
Add a central test that can be used by two places in code.

Fixes: #4710

### CODE REVIEW

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 51b73b18a73ae6e3d4e9e49c9ae139df32992a06 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4741-notebooks-4nclw) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 51b73b18a73ae6e3d4e9e49c9ae139df32992a06 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4741-notebooks-4nclw) | `/test notebooks`
integration | 51b73b18a73ae6e3d4e9e49c9ae139df32992a06 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4741-integration-pbklz) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Failed tests:
 integration: TestADServer.test_alibi_detect_cifar10_rclone
 notebooks: server-examples

will retry

**Review by adriangonz — APPROVED** [review]
Looks good!

**Pull request merged**
