### PR TITLE
Update transitive dependencies

### LINKED ISSUE #1002: Update transitive dependencies
## Context

On the Java `engine`, there are a few dependencies which rely on either slightly old versions of sub-dependencies or versions which are lagging a few releases behind. It would be good to keep these up to date. In particular, these are:

- `org.checkerframework:checker-qual` (through `com.google.guava:guava`). The version required by `guava` is `v2.8.1`, but the latest is `v2.11.1`.
- `com.google.api.grpc:proto-google-common-protos` (through `io.grpc:grpc-protobuf`). The version required by `grpc-protobuf` is `v1.12.0`, but the latest is `v1.17.0`.
- `com.squareup.okhttp3:okhttp` (through `io.jaegertracing:jaeger-client`). The version required by `jaeger-client` is `v3.9.0` but the latest is `v4.2.2`.

## Suggested fix

Since we don't have direct control over these libraries, a good short-term solution may be to update them directly on our `pom.xml` (by excluding the indirect dependencies and adding them as direct ones). 

However, it would also be good to submit PRs to the relevant projects so that, in the mid-term, we are able to import new releases of our actual direct dependencies which rely on the newer versions of the indirect ones (after which, the exclusions on our `pom.xml` wouldn't be needed anymore).

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1002.

## Changelog

- Update `checker-qual` to `v2.11.1`. There is an open PR to change it in `guava` here https://github.com/google/guava/pull/3671.
- Update `proto-google-common-protos` to `v1.16.0`. There is an open PR to change it in `grpc-protobuf` here https://github.com/grpc/grpc-java/pull/6336.
- Update `okhttp` to `v4.2.2`. There is an open issue to change it in `jaeger-client` here https://github.com/jaegertracing/jaeger-client-java/issues/666.  

## Notes

The latest version of `proto-google-common-protos` seems to be `v1.17.0` according to [Maven Repository](https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos/1.17.0). However, as it's pointed out in this issue https://github.com/grpc/grpc-java/pull/6336, the https://github.com/googleapis/common-protos-java repo seems to be still pointing to `v1.16.0`. Therefore, it seems sensible to update to `v1.16.0` until it's confirmed which one is the latest version.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Looks solid! Did all the e2e tests run successfully?

**Comment by adriangonz** [comment]
@axsaucedo Yuup, e2e tests seem to pass!

**Pull request merged**
