### PR TITLE
Fix dead links in docs and add linter

### LINKED ISSUE #1760: Fix broken documentation links
Slack thread: https://seldondev.slack.com/archives/C8Y9A8G0Y/p1588085733389600

Many documentation links are broken.

A tool like [muffet](https://github.com/raviqqe/muffet) may be helpful to check for dead links when building the documentation.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Fix most warnings thrown by Sphinx, some dead links, and upgrade the versions of the docs' dependencies. This PR also adds a `/docs` command which runs some linters on the docs and also crawls all external links to verify they are working.

**Which issue(s) this PR fixes**:

Fixes #1760

**Special notes for your reviewer**:
- The external link crawling is a bit heavy, so we probably can't run it on every PR. That's why I've split into a separate `/docs` command. 
- I've replaced all links between notebooks outside of the `/doc` folder for absolute links to the Seldon Core docs. This is to work around a limitation on `nbsphinx-link`.
- I've removed all notebooks' static assets from the `/doc` folder to use instead the `extra-media` key on the `nblink` file.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Oct  8 16:47:08 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=2

**Comment by seldondev** [comment]
Thu Oct  8 16:47:23 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=1

**Comment by seldondev** [comment]
Thu Oct  8 16:59:13 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=3

**Comment by seldondev** [comment]
Thu Oct  8 16:59:17 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=4

**Comment by seldondev** [comment]
Thu Oct  8 17:06:08 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=5

**Comment by seldondev** [comment]
Thu Oct  8 17:06:08 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=6

**Comment by seldondev** [comment]
Thu Oct  8 17:09:13 UTC 2020
The logs for [docs] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=7

**Comment by axsaucedo** [comment]
This is great! Looks good! Seems there may need to be a small change on the image as build looks like pandoc is missing, but other than that looks great!

**Comment by adriangonz** [comment]
@axsaucedo good spot! I've now pushed a new version of the image.

**Comment by seldondev** [comment]
Fri Oct  9 11:17:10 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=8

**Comment by seldondev** [comment]
Fri Oct  9 11:17:22 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=9

**Comment by seldondev** [comment]
Fri Oct  9 11:20:16 UTC 2020
The logs for [docs] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=10

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
docs | 92cf38981034616dd539e0cce52f3f9ce4c0fd6e | [link]() | `/test docs`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Oct  9 13:02:35 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=12

**Comment by seldondev** [comment]
Fri Oct  9 13:02:50 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=11

**Comment by seldondev** [comment]
Fri Oct  9 13:03:52 UTC 2020
The logs for [docs] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=13

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2538#issuecomment-706229461 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-706229461/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
@adriangonz seems there are some merge conflicts, but other than that should be good to go

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2538#issuecomment-706229461 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Oct  9 16:27:38 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=15

**Comment by seldondev** [comment]
Fri Oct  9 16:27:53 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2538/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2538 --build=14

**Pull request merged**
