### PR TITLE
Upgrade to use KEDA v2.0 GA version in the demo

### LINKED ISSUE #2614: Update KEDA example to use v2.0 GA version
## Describe the bug

Right now the KEDA example is using v2.0 beta version, since KEDA v2.0 GA just released, should update to use it.

### PR DESCRIPTION
**Pull request by anggao**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2614

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @anggao. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2615#issuecomment-725983585 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-725983585/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Nov 12 10:19:05 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=2

**Comment by seldondev** [comment]
Thu Nov 12 10:19:12 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=1

**Comment by seldondev** [comment]
Thu Nov 12 10:43:27 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=3

**Comment by anggao** [comment]
@axsaucedo do you know why notebooks testings are still running, it has been running for over 10 hours ?

**Comment by axsaucedo** [comment]
@anggao thank you for the heads up, I have just had alook, it seems the notebooks test got stuck - here are the logs:
image

The test is still running - it seems the KEDA test failed, and then the tracing test which ran afterwards started - it's not clear what is failing from the logs unfortunately.

**Comment by anggao** [comment]
That's weird, I don't think they did any breaking changes between beta and GA

**Comment by anggao** [comment]
Can we stop the current testing and try again ?

**Comment by axsaucedo** [comment]
Yeah I just restarted all the components - let's retrigger
/test notebooks

**Comment by seldondev** [comment]
Fri Nov 13 17:21:52 UTC 2020
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=4

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2615#issuecomment-725983585 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Nov 18 17:17:44 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=6

**Comment by seldondev** [comment]
Wed Nov 18 17:19:28 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2615/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2615 --build=5

**Pull request merged**
