### PR TITLE
Fixed AD Server Dependencies and Added notebook integration test

### LINKED ISSUE #2533: ADServer Crashes due to updated dependencies
The adserver is currently failing when re-built with latest dependencies. This is primarily due to the google-cloud-core update from `1.4.1` to `1.4.3`. The error is:

```
>>> import kfserving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/kfserving/__init__.py", line 18, in <module>
    from .storage import Storage
  File "/opt/conda/lib/python3.7/site-packages/kfserving/storage.py", line 23, in <module>
    from google.cloud import storage
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
    from google.cloud.storage.batch import Batch
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 31, in <module>
    from google.cloud.storage._http import Connection
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 17, in <module>
    from google.cloud import _http
  File "/opt/conda/lib/python3.7/site-packages/google/cloud/_http.py", line 22, in <module>
    from six.moves import collections_abc
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)
```

It is confirmed that the issue is due to an uncompatible version of being installed, which results in the installation of six to cause issues, and which seems to be caused due to a recent 1st / 2nd level dependency change.

### LINKED ISSUE #2535: Add integration test for outlier detection server
To ensure the outlier detection server image builds are tested, adding a simple integration test on the adserver would ensure at least that the container runs without issues.

### PR DESCRIPTION
**Pull request by axsaucedo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2533 

Fixes #2535

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Oct  8 14:55:13 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=2

**Comment by seldondev** [comment]
Thu Oct  8 14:55:15 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=1

**Comment by seldondev** [comment]
Thu Oct  8 15:59:59 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=3

**Comment by seldondev** [comment]
Thu Oct  8 16:00:23 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=4

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 4f3c2ddc8fbed71bfde01d209c43fd0aaf934b7a | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
It seems failed tests are unrelated, namely the `test_custom_metrics` - the errors seem similar to the proto error in the explainer notebook tests tho. Re-running to confirm whether it's flakiness.
/test notebooks

**Comment by seldondev** [comment]
Thu Oct  8 18:24:13 UTC 2020
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 4f3c2ddc8fbed71bfde01d209c43fd0aaf934b7a | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Oct  8 19:49:37 UTC 2020
The logs for [notebooks] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=7

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 4f3c2ddc8fbed71bfde01d209c43fd0aaf934b7a | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Oct  9 07:17:12 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=9

**Comment by seldondev** [comment]
Fri Oct  9 07:17:24 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=10

**Comment by seldondev** [comment]
Fri Oct  9 07:17:46 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=8

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 4f3c2ddc8fbed71bfde01d209c43fd0aaf934b7a | [link]() | `/test notebooks`
pr-build | bd2ec595225196ba7ca491bd4e217597be2bb669 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Oct  9 07:38:33 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=11

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | bd2ec595225196ba7ca491bd4e217597be2bb669 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
I just ran the custom_metrics test locally and works as expected, so seems it's due to flakiness

**Comment by seldondev** [comment]
Fri Oct  9 12:19:32 UTC 2020
The logs for [notebooks] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2536/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2536 --build=12

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | bd2ec595225196ba7ca491bd4e217597be2bb669 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2536#issuecomment-706228556 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-706228556/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by anggao** [comment]
@axsaucedo I think I have the similar issue with my PR :( 

https://github.com/SeldonIO/seldon-core/pull/2506

**Comment by anggao** [comment]
Ah just saw your comments :) thanks!

**Pull request merged**
