### PR TITLE
Extending Alibi Detect Server to expose prometheus metrics for outliers

### PR DESCRIPTION
**Pull request by axsaucedo**
Following the same structure as with the Alibi Drift implementation, exposing metrics for the outlier detector component which could enable simpler visualisation of outliers.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sat Dec 12 13:50:40 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=2

**Comment by seldondev** [comment]
Sat Dec 12 13:50:48 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=1

**Comment by seldondev** [comment]
Mon Dec 14 09:29:17 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6e9b48995885269119cf18c1e0b73f46d7c4127c | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@cliveseldon do you think we still want this or should we close PR?

**Comment by cliveseldon** [comment]
@axsaucedo What's the reason to not have it anymore?

**Comment by axsaucedo** [comment]
Just to confirm, mainly as we don't currently have a "default dashboard" for it, but I think it would still be worth having actually. Ok - I will fix the lint by rebasing.

**Comment by seldondev** [comment]
Mon Jan  4 16:49:08 UTC 2021
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=5

**Comment by seldondev** [comment]
Mon Jan  4 16:49:25 UTC 2021
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 730ea862d4624fb565c48b2bb12737c8f217e4fc | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems failed on executor test (which is unrelated to pr), have seen this before if too many jx tests are building the golang binary at the same time
/test this

**Comment by seldondev** [comment]
Mon Jan  4 17:14:32 UTC 2021
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2770/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2770 --build=7

**Comment by axsaucedo** [comment]
Ok cool, should be good to review @cliveseldon

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2770#issuecomment-758151241 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-758151241/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
