### PR TITLE
Update docs concerning default image user id

### LINKED ISSUE #2142: Default user ID is always set to 8888
## Describe the bug

Since `1.2`, the Seldon Core operator will always inject by default a `securityContext` at the pod level which runs every container as user `8888`. This is in line with OpenShift's best practices. The user can always change the default user ID through the `defaultUserID` property of Seldon Core's Helm chart, or by overriding the `securityContext` at the container level.

Seldon Core's images (i.e. executor and Python wrapper) will always run with this user. However when using a custom Docker image the user ID could change, in which case the user would run into permissions problems.

We should document this change, how it can affect the user and how to change it. Alternatively, we could always set the `defaultUserID` to empty and start using the `runAsNonRoot` field. I.e. injecting the following `securityContext` by default:

```yaml
securityContext:
  runAsNonRoot: true
```

That would mean that containers can only be ran as non-root users (unless overriden), and that K8s will use the user ID in the Docker's image metadata. 

## To reproduce

1. Install SC with the default parameters.
2. Deploy a `SeldonDeployment` using SC 1.2.
3. Check that the pod has a `securityContext` with `runAsUser: 8888`.

## Expected behaviour

We should make it clear to the user that containers will run by default as user `8888`. Alternatively, we should change the operator so that it doesn't enforce a particular user ID and instead uses the container's user from the image's metadata (the default if you don't specify a `runAsUser`).

## Environment

- Seldon Core 1.2

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

 * Adds docs for clarifying the container userId

**Which issue(s) this PR fixes**:

Fixes #2142 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sun Sep  6 15:41:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2384/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2384 --build=2

**Comment by seldondev** [comment]
Sun Sep  6 15:41:41 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2384/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2384 --build=1

**Comment by adriangonz** [comment]
/approve

@cliveseldon change looks good!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[adriangonz](https://github.com/SeldonIO/seldon-core/pull/2384#issuecomment-688239973 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-688239973/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Sep  7 10:46:11 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2384/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2384 --build=3

**Comment by seldondev** [comment]
Mon Sep  7 10:46:13 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2384/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2384 --build=4

**Pull request merged**
