### PR TITLE
Upgrade alibi component to use alibi 0.5.4

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:
Upgrades alibi-explain-server to use `alibi=0.5.4`.

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
updates alibi to version 0.5.4
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Sep 15 09:22:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2439/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2439 --build=2

**Comment by seldondev** [comment]
Tue Sep 15 09:22:47 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2439/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2439 --build=1

**Comment by axsaucedo** [comment]
This was fixed by a subsequent PR

**Pull request closed without merging**
