### PR TITLE
Upgrade/alibi/0.5.4

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

alibi upgrade: 0.5.2 -> 0.5.4

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Upgrades alibi to version 0.5.4
```

### CODE REVIEW

**Comment by seldondev** [comment]
Thu Sep 10 14:16:14 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2411/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2411 --build=2

**Comment by seldondev** [comment]
Thu Sep 10 14:16:25 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2411/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2411 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9423d53b7f33370778b0e810f535050937fb70f1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9423d53b7f33370778b0e810f535050937fb70f1 | [link]() | `/test integration`
notebooks | 9423d53b7f33370778b0e810f535050937fb70f1 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
going to included that in https://github.com/SeldonIO/seldon-core/pull/2404

**Pull request closed without merging**
