### PR TITLE
fix notebook server_examples to not fail on MLFlow server

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
It seems that fix introduced in https://github.com/SeldonIO/seldon-core/commit/baa3f14baad082ceb39bda761d1efec6ff28a640 didn't apply to notebook test as the notebook is overwriting `elasticnet_wine.yaml` manifest.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rafalskolasinski**

If they are not already assigned, you can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jun 30 12:44:47 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2050/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2050 --build=2

**Comment by seldondev** [comment]
Tue Jun 30 12:44:48 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2050/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2050 --build=3

**Comment by seldondev** [comment]
Tue Jun 30 12:44:57 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2050/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2050 --build=1

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 56c584431ddedd2cb4f2c4df5b0f025e9ac4db93 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Just to comment that modified notebook passed the test. Failure reported is in `TestNotebooks.test_metadata` that was not modified by this PR. Probably flakiness.

**Pull request merged**
