### PR TITLE
Clean up and document charts

### PR DESCRIPTION
**Pull request by adriangonz**
This PR is a first stab at #1879 . It explores how we can leverage [`helm-docs`](https://github.com/norwoodj/helm-docs) to generate the documentation of our Helm charts. This tool, `helm-docs`, will parse the chart's `values.yaml`, extracting the different options that we can configure, as well as:

- Their default values
- Their types (inferred from their default values)
- Comments describing what they do

From these, it generates a `README.md` with a table documenting all the chart's values. To showcase how this works, this PR just generates this `README.md` for a couple charts: 

- `seldon-single-model` 
- `seldon-openvino`

## Changelog

- Generate document for `seldon-single-model` and `seldon-openvino`
- Simplify `seldon-single-model` and update part of its structure
- Flag `seldon-openvino` as deprecated
- Document values of `seldon-single-model`
- Add `.helmdocsignore` to ignore every other chart
- Add `docs` target in `helm-charts/Makefile`

## TODO

- [x] Generated docs for `seldon-core-operator`'s chart
- [x] Expose docs in docs.seldon.io

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun  1 14:09:57 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=2

**Comment by seldondev** [comment]
Mon Jun  1 14:10:18 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=1

**Comment by axsaucedo** [comment]
@adriangonz this is great! We actually already have the helm chart for seldon-core-operator semi-documented in https://docs.seldon.io/projects/seldon-core/en/latest/reference/helm.html Would this work with the seldon-core-operator chart as well? It would be great to add the README.md page in there instead of the reference of the YAML!

Looks good from my side, happy to approve based on whether we'd want to do the above on a separate PR

**Comment by adriangonz** [comment]
@axsaucedo I'm happy to add it on this PR. I also noticed that I haven't tried yet how we can expose the generated docs in the docs at docs.seldon.io. What's done it's still useful to assess if we like this direction or not. 

I'm gonna turn this one into a WIP, and I'll add:

- Generated docs for `seldon-core-operator`'s chart
- Expose docs in docs.seldon.io

**Comment by axsaucedo** [comment]
@adriangonz I think it woudl just be a matter of generating the readme.md, and then just linking that directly from one of the doc pages - I believe all the linked readme documents are packaged together in the live docs. You can try building the docs locally (using the makefile in the docs folder)

**Comment by seldondev** [comment]
Thu Jun  4 12:52:42 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=3

**Comment by seldondev** [comment]
Thu Jun  4 12:52:42 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=4

**Comment by seldondev** [comment]
Thu Jun  4 12:54:10 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=5

**Comment by seldondev** [comment]
Thu Jun  4 12:54:34 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=6

**Comment by seldondev** [comment]
Thu Jun  4 13:52:08 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=8

**Comment by seldondev** [comment]
Thu Jun  4 13:52:11 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=7

**Comment by seldondev** [comment]
Thu Jun  4 14:47:32 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=9

**Comment by seldondev** [comment]
Thu Jun  4 14:47:35 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=10

**Comment by seldondev** [comment]
Fri Jun  5 09:41:07 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=11

**Comment by seldondev** [comment]
Fri Jun  5 09:41:12 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1906/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1906 --build=12

**Comment by axsaucedo** [comment]
Looks good!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1906#issuecomment-639494309" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
