### PR TITLE
Updating podinfo volume name to be seldon specific

### PR DESCRIPTION
**Pull request by SachinVarghese**
Related to https://github.com/istio/istio/issues/22246

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **sachinvarghese**

If they are not already assigned, you can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu May 21 11:39:39 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=1

**Comment by seldondev** [comment]
Thu May 21 11:39:39 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=2

**Comment by seldondev** [comment]
Thu May 21 13:07:06 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=3

**Comment by SachinVarghese** [comment]
@cliveseldon @adriangonz Was wondering if we should change the volume mount path from `/etc/podinfo` to `/etc/seldon/podinfo` (similar to Istio) to avoid clashes as a part of this PR? Do you foresee any issues with that?

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1863#pullrequestreview-417263045" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
@SachinVarghese I think the path is fine. Istio does use [an istio-specific mount path](https://github.com/istio/istio/blob/954110286bab41a32e09d480b356d5c4fa9d6d25/pkg/kube/inject/testdata/inject/hello-multi.yaml.injected#L374) but I don't think it's necessary. The mount path is only at the container level so there shouldn't be a clash there. The clash on the volume name is because that's at pod level.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1863#issuecomment-633010576" title="LGTM">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue May 26 10:10:25 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=5

**Comment by seldondev** [comment]
Wed May 27 10:35:52 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=6

**Comment by seldondev** [comment]
Wed May 27 10:50:57 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=8

**Comment by seldondev** [comment]
Wed May 27 10:51:41 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1863/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1863 --build=9

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref c0c7738fe3ac058d8dcb3275277cfd45a3953188
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha c0c7738fe3ac058d8dcb3275277cfd45a3953188
* failed to process repo SeldonIO/seldon-core refref c0c7738fe3ac058d8dcb3275277cfd45a3953188
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
