### PR TITLE
WIP: Batch processor example for optimized batch processing / gang scheduling with Argo & Volcano

### PR DESCRIPTION
**Pull request by axsaucedo**
This PR is exploring the implemenation of optimised processing of batch data using Seldon Core, which can be leveraged with third party tools like Argo Workflows and Volcano.

The initial premise was created with an example consisting of a batch job with the following features:
* 100k datapoints
* Each datapoint processing requires 100mb RAM
* Each processing requires 1CPU
* Each Processing takes 10 seconds
* Assuming case where resources will be at disposal but time is limited

This PR explores adding functionality to add capabilities within seldon core to handle optimised processing of batch data through a generalised structure as follows:
image

The current implementation of the gang scheduler architecture was taken from some of the Volcano examples that use MPI, however at this poitn it's only a dummy implementation for exploration on how it would fit when executed by 3rd party tools such as Argo Workflows and Volcano.

## Examples using the gang scheduler

In the examples below the "process-batch-inputs" step is the component that leverages the gang scheduling / optimised batch processor.

The first example basically shows a simple processing of data with the following workflow:
image

The second provides an example on how a user is able to leverage an object store and custom steps to download the data such that it's made available for the optimised gang scheduler / processing step:
image

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Apr 20 08:08:45 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=1

**Comment by seldondev** [comment]
Mon Apr 20 08:08:51 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=2

**Comment by seldondev** [comment]
Tue Apr 21 20:03:36 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=3

**Comment by seldondev** [comment]
Tue Apr 21 20:03:44 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=4

**Comment by seldondev** [comment]
Thu Apr 30 19:58:15 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=5

**Comment by seldondev** [comment]
Thu Apr 30 19:58:24 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=6

**Comment by seldondev** [comment]
Thu Apr 30 20:01:55 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=8

**Comment by seldondev** [comment]
Thu Apr 30 20:01:59 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=7

**Comment by seldondev** [comment]
Sat May  2 11:19:11 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=9

**Comment by seldondev** [comment]
Sat May  2 11:19:20 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=10

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7bf123537b44a7b3f776d501970f8fdacae0a447 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 18 21:41:16 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=11

**Comment by seldondev** [comment]
Mon May 18 21:41:19 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=12

**Comment by seldondev** [comment]
Mon May 18 21:59:56 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=13

**Comment by seldondev** [comment]
Mon May 18 22:00:03 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=14

**Comment by seldondev** [comment]
Mon May 18 22:04:23 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=15

**Comment by seldondev** [comment]
Mon May 18 22:04:29 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=16

**Comment by seldondev** [comment]
Tue May 19 05:56:59 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=17

**Comment by seldondev** [comment]
Tue May 19 05:58:13 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1714/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1714 --build=18

**Comment by axsaucedo** [comment]
Closing in favour of #1915

**Pull request closed without merging**
