### PR TITLE
Remove executor's dependency on k8s.io/client-go

### LINKED ISSUE #2092: Remove Executor's dependency on client-go
Sub Issue of https://github.com/SeldonIO/seldon-core/issues/2088.

Client-go seems to be a historical dependency in Executor when SeldonDeployment CRD was requested by it using k8s API.
Right now it seems that Executor gets CRD through environmental variable.

This commit https://github.com/SeldonIO/seldon-core/pull/2083/commits/3c0ed3dc9b44f331dca4342fb371a2f39bba2186 (from cruft branch) shows that removal is quite straightforward. Probably enough to cherry-pick this commit into a tiny PR.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Remove `k8s.io/client-go` as a direct dependency of the `executor` by getting rid of the `SeldonDeploymentClient`. This means that, from now on, the `executor` will only be able to read `SeldonDeployment` resources passed explicitly from the environment or as files. 

Note that `k8s.io/client-go` may still be present in the `go.sum` as a 2nd-level dependency through the `operator`. 

**Which issue(s) this PR fixes**:

Fixes #2092

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jul 10 15:29:16 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=2

**Comment by seldondev** [comment]
Fri Jul 10 15:29:36 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=1

**Comment by seldondev** [comment]
Fri Jul 10 15:34:08 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=3

**Comment by RafalSkolasinski** [comment]
Looks good to me! Nice one.

@agm do we have results of notebooks / integration tests for this one? 
Good to merge if confirmed that they're passing (don't see reason they shouldn't).

**Comment by seldondev** [comment]
Mon Jul 13 12:07:25 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=4

**Comment by seldondev** [comment]
Mon Jul 13 12:22:00 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=5

**Comment by seldondev** [comment]
Mon Jul 13 15:02:46 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2106/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2106 --build=6

**Comment by RafalSkolasinski** [comment]
Notebook tests have passed, now waiting for integration tests (there was one failure, hence restart).

**Comment by RafalSkolasinski** [comment]
Tests passed!
:rocket:

**Comment by RafalSkolasinski** [comment]
Merging manually

**Pull request merged**
