### PR TITLE
DO NOT MERGE: 1.17.0 Release

### PR DESCRIPTION
**Pull request by adriangonz**

### CODE REVIEW

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-9p49b) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-9p49b) | `/test notebooks`
release-build-push | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-9dpfx) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-9dpfx) | `/test release`
notebooks | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-t54zj) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 6a8801a1c4a9f9cb9e6cb3023ebe4fa5310273db | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-9dpfx) | `/test release`
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`
release-build-push | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-w8p4d) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`
release-build-push | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-w8p4d) | `/test release`
integration | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-5005-integration-7fhpx) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`
integration | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-5005-integration-7fhpx) | `/test integration`
release-build-push | 460da4b4213792efe5fe46d78c26fedf9df48fac | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-c67zb) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`
integration | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-5005-integration-7fhpx) | `/test integration`
release-build-push | 2e8ad9beab44144994b4129dd9166d0cf5e901bd | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-5005-release-build-push-w5d9w) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9932c8b8d8e5ff9e48739024541d9913508c32ed | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-5005-notebooks-w6fk7) | `/test notebooks`
integration | 5f3687efa4d3434036b6a65177bfacf5bb3beebb | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-5005-integration-b8d8s) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
All tests passing:

image

**Comment by adriangonz** [comment]
Seldon Core `1.17.0` has now been released. Closing PR.

**Pull request closed without merging**
