### PR TITLE
Process text and binary payloads

### PR DESCRIPTION
**Pull request by Teagan42**
Convert string and binary payloads to SeldonMessage payloads

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @Teagan42. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by cliveseldon** [comment]
Thanks @Teagan42

**Comment by seldondev** [comment]
Tue Mar 31 06:47:49 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=2

**Comment by seldondev** [comment]
Tue Mar 31 06:47:56 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=1

**Comment by seldondev** [comment]
@Teagan42: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c48190dd216c058e6d9788f7559de836c3208fbc | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Mar 31 16:51:56 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=3

**Comment by seldondev** [comment]
@Teagan42: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c48190dd216c058e6d9788f7559de836c3208fbc | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Looks like the build is failing - have you tested locally with `make build_jar`?

**Comment by seldondev** [comment]
Tue Mar 31 18:44:50 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=4

**Comment by seldondev** [comment]
@Teagan42: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c48190dd216c058e6d9788f7559de836c3208fbc | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by Teagan42** [comment]
@cliveseldon yes I've used the makefiles to build the JAR and custom image and it is running in my k8s. The link to the logs don't seem to give a lot of info

**Comment by Teagan42** [comment]
@cliveseldon weird, I ran this yesterday fine and now it's failing. I'll look into it.

**Comment by cliveseldon** [comment]
@Teagan42 https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/4.log
shows
```
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 66 source files to /workspace/source/engine/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31.892 s
[INFO] Finished at: 2020-03-31T18:47:16Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project seldon-engine: Fatal error compiling: CompilerException: NullPointerException -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
make: *** [Makefile:8: build_jar] Error 1
make: Leaving directory '/workspace/source/engine'
```

Which is indeed not clear!  Any ideas @axsaucedo

**Comment by seldondev** [comment]
Tue Mar 31 19:57:42 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=6

**Comment by seldondev** [comment]
Tue Mar 31 19:57:43 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=5

**Comment by Teagan42** [comment]
@cliveseldon I'm stupid today. Needed these changes for my job, but we only have enterprise github, so had to mirror it up to our repository and make changes. When I verified it all worked, I forked it from my personal public org and made the changes, but 1. I forgot to update the swagger as I had in the enterprise repo and 2. I missed two imports. Apologies for the brain fart

**Comment by Teagan42** [comment]
@cliveseldon I diagnosed this by adding the `-X -e` flags to the maven invocation, it gave me a little better idea (the root exception was a MojoExecutionException) and those are thrown only for a few reasons, one being missing imports :-)

**Comment by cliveseldon** [comment]
@Teagan42  Looks great. Is it possible to add a couple of junit tests?
See for a previous PR for form data: https://github.com/SeldonIO/seldon-core/blob/be662dcc50ddcf642a115f8864f6f3e0566045cb/engine/src/test/java/io/seldon/engine/api/rest/TestRestClientController.java#L311-L337

**Comment by Teagan42** [comment]
@cliveseldon Absolutely! I will do that in the morning. 

I guess I misunderstood the PR instructions as optional (This is a simplified description of our full PR testing and merge workflow that conveniently forgets about the existence of tests, to focus solely on the roles driven by OWNERS files. Please see below for details on how specific aspects of this process may be configured on a per-repo basis.).

**Comment by seldondev** [comment]
Thu Apr  2 18:54:26 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=8

**Comment by seldondev** [comment]
Thu Apr  2 18:54:36 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1642/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1642 --build=7

**Comment by Teagan42** [comment]
@cliveseldon Usually unit tests are a must for me, was in a hurry I guess. But I added tests and everything passes. I may make a PR to update the PR documentation to explicitly state code should be unit tested as the instructions were a little misleading (but that's no excuse for not doing it anyway).

**Comment by cliveseldon** [comment]
@Teagan42 Thanks for this!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1642#issuecomment-608059781" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref b9e44eb9a8c5bb5897a8415e6834d8a9cc954d5f
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha b9e44eb9a8c5bb5897a8415e6834d8a9cc954d5f
* failed to process repo SeldonIO/seldon-core refref b9e44eb9a8c5bb5897a8415e6834d8a9cc954d5f
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
