### PR TITLE
include notebook nbqa as part of python lint

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

Includes nbqa as part of python lint 

**Which issue(s) this PR fixes**:

Fixes https://github.com/SeldonIO/seldon-core/issues/2885

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/3548#issuecomment-908357150 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by MarcoGorelli** [comment]
Just FYI, [black now has a Jupyter hook](https://black.readthedocs.io/en/stable/integrations/source_version_control.html), I'd advise switching to that from `nbqa-black`

**Comment by RafalSkolasinski** [comment]
Hey @MarcoGorelli, thanks for the tip. I think currently we also use `nbqa` to call `isort` on notebooks - do you also plan to contribute that to the upstream project? 

We adopted `nbqa` mostly to run `black` in notebooks indeed. Is your plan for `nbqa` to just contribute to upstream tools what they're missing and keep `nbqa` as a fallback?

**Comment by MarcoGorelli** [comment]
>  Is your plan for nbqa to just contribute to upstream tools what they're missing and keep nbqa as a fallback?

Some (pyupgrade, mypy, flake8, pylint) would either certainly or almost certainly not accept a PR to support notebooks directly, so I'll keep maintaining nbqa for them.

I'd like to suggest this to isort too, but not in the near future

**Pull request merged**
