### PR TITLE
Fixed Flask breaking version by werkzeug dependency limit to 2.1

### LINKED ISSUE #4017: Error importing BaseRespnse from werkzeug.wrappers due breaking Flask update
## Describe the bug

As it has been reported in https://github.com/SeldonIO/seldon-core/issues/4014 we have found that the base python wrapper when built from scratch will fail with the error below. This is because of a 2nd-level+ dependency from Flask where werkzeug removed/moved the BaseResponse class resulting in this breaking. The solution is to pin werkzeug to version 2.0.3 in the base image, and rebuild all relevant images from there.

```
from werkzeug.wrappers import BaseResponse
ImportError: cannot import name 'BaseResponse' from 'werkzeug.wrappers' (/usr/local/lib/python3.9/site-packages/werkzeug/wrappers/__init__.py)
```

## Workaround

The workaround is relatively simple, and just requires users to pin `werkzeug==2.0.3` in the respective requirements.txt.

## To reproduce

This can be reproduced by rebuilding an image with the existing dependencies as this is broken on the version of Flask until they pin/update it.

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #4017

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 945dfcbdd78991eafb78f080a192326c79deed82 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4018-integration-xqk8n) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems good as only failed test was a flaky one `test_label_update` - merging
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/4018#issuecomment-1087432591 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
