### PR TITLE
log request and response when environment variable configured

### PR DESCRIPTION
**Pull request by CatTail**
**What this PR does / why we need it**:

seldon executor is a replacement to engine, however previous engine support using environment variable to control whether we should send request or response payload into stdout, the new executor ignore these environment variables and simply send payload to logger as cloudevents

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @CatTail. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
@CatTail Interesting, thanks for submitting this PR. We were previously suggesting to capture req and resp payloads from stdout using fluentd. We then introduced request logger that could better join up req and resp and enrich for searching and also to not be limited by size of payload. But you mention the logger so you’ve already looked at that. Are you using fluentd? Or do you just want to see the req and resp for debugging? Would be great if you could share a little about your use case.

**Comment by seldondev** [comment]
Wed Jul 29 08:36:24 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2209/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2209 --build=1

**Comment by seldondev** [comment]
Wed Jul 29 08:36:45 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2209/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2209 --build=2

**Comment by seldondev** [comment]
@CatTail: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 9721e782c344f180925222fb1cb28a210f04988e | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Looks like flakiness in our tests and not a problem with this PR:
```
________ ERROR at setup of test_model_template_app_grpc[microservice0] _________
Traceback (most recent call last):
  File "/workspace/source/python/.tox/py3/lib/python3.7/site-packages/tenacity/__init__.py", line 412, in call
    result = fn(*args, **kwargs)
  File "/workspace/source/python/tests/helpers.py", line 86, in _wait_until_ready
    raise EOFError("Server not ready yet")
EOFError: Server not ready yet
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/workspace/source/python/tests/helpers.py", line 71, in __enter__
    self._wait_until_ready()
  File "/workspace/source/python/.tox/py3/lib/python3.7/site-packages/tenacity/__init__.py", line 329, in wrapped_f
    return self.call(f, *args, **kw)
  File "/workspace/source/python/.tox/py3/lib/python3.7/site-packages/tenacity/__init__.py", line 409, in call
    do = self.iter(retry_state=retry_state)
  File "/workspace/source/python/.tox/py3/lib/python3.7/site-packages/tenacity/__init__.py", line 369, in iter
    six.raise_from(retry_exc, fut.exception())
  File "<string>", line 3, in raise_from
tenacity.RetryError: RetryError[<Future at 0x7f5f1c6ee7f0 state=finished raised EOFError>]
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/workspace/source/python/tests/conftest.py", line 43, in microservice
    with wrapper:
  File "/workspace/source/python/tests/helpers.py", line 76, in __enter__
    raise RuntimeError("Server did not bind to 127.0.0.1:5000")
RuntimeError: Server did not bind to 127.0.0.1:5000
```
Re-running to check
/test this

**Comment by seldondev** [comment]
Wed Jul 29 10:45:49 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2209/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2209 --build=3

**Comment by CatTail** [comment]
Hi @ryandawsonuk, thanks for your reply. In my use case, I'm using [datadog](https://www.datadoghq.com/) to collect our application logs, datadog doesn't provide a way to collect cloudevents but it can capture docker container logs. I also thinking of collecting application logs along with req and res in a single place (container logs). Can I ask what is the design purpose of req/res payload logging, why it's separate from application logs?

**Comment by CatTail** [comment]
Hi @ryandawsonuk, it's been a while, can you help to take a look at this PR again

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2209#issuecomment-681852893 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-681852893/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Aug 27 10:04:26 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2209/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2209 --build=4

**Review by ryandawsonuk — APPROVED** [review]
/lgtm
/approve

**Comment by seldondev** [comment]
@CatTail: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9721e782c344f180925222fb1cb28a210f04988e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request closed without merging**
