### PR TITLE
add managed-by label

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1936

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jun 11 16:22:17 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=3

**Comment by seldondev** [comment]
Thu Jun 11 16:28:50 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=1

**Comment by seldondev** [comment]
Thu Jun 11 16:28:52 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=2

**Comment by seldondev** [comment]
Mon Jun 15 08:37:49 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=5

**Comment by seldondev** [comment]
Mon Jun 15 08:37:52 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=4

**Comment by ryandawsonuk** [comment]
When testing in KIND I'm finding that the label is not currently getting onto the Pod. It does get onto the service (the one on port 9000).

**Comment by ryandawsonuk** [comment]
Oh the label is on the Deployment and just not on the Pod. Will try moving it into the spec section.

**Comment by seldondev** [comment]
Mon Jun 15 09:23:49 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=7

**Comment by seldondev** [comment]
Mon Jun 15 09:25:13 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=6

**Comment by ryandawsonuk** [comment]
It is coming through now. And services are still correctly matching to deployments as I'm able to make requests and get responses.

**Comment by seldondev** [comment]
Tue Jun 16 12:47:48 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=9

**Comment by seldondev** [comment]
Tue Jun 16 12:47:50 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=8

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1937#issuecomment-644936891" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jun 16 18:36:16 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=11

**Comment by seldondev** [comment]
Tue Jun 16 18:36:24 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1937/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1937 --build=10

**Pull request merged**
