### PR TITLE
Adding test case for SeldonDeploymentWatcher

### PR DESCRIPTION
**Pull request by ro7m**
Adding test case for SeldonDeploymentWatcher.
@cliveseldon

### CODE REVIEW

**Comment by ro7m** [comment]
@cliveseldon  i choose something which does not match the SeldonDeployment to mimic a failure scenario

**Comment by cliveseldon** [comment]
I think the issue is actually this test is failing: testModifiedSeldonMLDeploymentsForMultiNamespaceCluster

**Comment by ro7m** [comment]
fixed that

**Comment by cliveseldon** [comment]
Great. Thanks for the contribution!

**Pull request merged**
