### PR TITLE
Make inclusion of metrics in SeldonMessage configurable in 1.1

### LINKED ISSUE #1582: Make inclusion of metrics in SeldonMessage configurable in 1.1
With model services directly exposing their own prometheus metrics the use cases for including them in the SeldonMessage diminish. We should make the inclusion of them in the returned SeldonMessage configurable through an environment variable (maybe `SELDON_SHOULD_SERIALIZE_METRICS`?) defaulting to `true`. In an upcoming release the default could be changed to `false`.

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Reopening https://github.com/SeldonIO/seldon-core/pull/1590 that closes #1582

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **gsunner**

If they are not already assigned, you can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Mar 27 16:43:50 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=2

**Comment by seldondev** [comment]
Fri Mar 27 16:43:52 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=1

**Comment by RafalSkolasinski** [comment]
Waiting for fix to integration tests being merged in https://github.com/SeldonIO/seldon-core/pull/1623 before running integration tests on this one.

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | d43c4dd811e324ffece19ba1e8df75f71fce8fa2 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Mar 27 17:05:36 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=3

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | d43c4dd811e324ffece19ba1e8df75f71fce8fa2 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Mar 27 17:29:24 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=4

**Comment by seldondev** [comment]
Fri Mar 27 17:30:04 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=5

**Comment by seldondev** [comment]
Sat Mar 28 17:04:02 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=6

**Comment by seldondev** [comment]
Sat Mar 28 17:05:23 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=7

**Comment by seldondev** [comment]
Sat Mar 28 17:05:42 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=8

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9e792978fb1379f7d468604ecff4d350bde1177f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Mar 28 21:09:12 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=9

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9e792978fb1379f7d468604ecff4d350bde1177f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Failure on 
```
[gw3] FAILED test_rolling_updates.py::test_rolling_deployment[graph1.json-graph5.json-True-ambas] 
```
\retest

**Comment by seldondev** [comment]
Sat Mar 28 21:42:33 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=10

**Comment by RafalSkolasinski** [comment]
Integration tests passed! Let's merge this! :)

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1625#issuecomment-605938635" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Mar 30 11:16:44 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=11

**Comment by seldondev** [comment]
Mon Mar 30 11:16:46 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1625/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1625 --build=12

**Pull request merged**
