### PR TITLE
Fixes for tests

### LINKED ISSUE #1948: Notebook Test Updates
* Flakiness updates
 * Fixes for new helm charts

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1948 

Various fixes to make tests less flaky and fix failing tests due to helm updates.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 15 12:46:10 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=2

**Comment by seldondev** [comment]
Mon Jun 15 12:47:16 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=1

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 0c0874c2ab1c35ff3501fa098df948c33005d1a1 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 15 13:47:51 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=3

**Comment by seldondev** [comment]
Mon Jun 15 14:09:14 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 0c0874c2ab1c35ff3501fa098df948c33005d1a1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Restarted controllerbuild so logs can be displayed
/test integration

**Comment by seldondev** [comment]
Mon Jun 15 16:43:41 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=5

**Comment by seldondev** [comment]
Mon Jun 15 17:14:56 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=7

**Comment by seldondev** [comment]
Mon Jun 15 17:15:00 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=6

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 0c0874c2ab1c35ff3501fa098df948c33005d1a1 | [link]() | `/test integration`
pr-build | 0e2c647905e30ce6c01fb312f905fb41f0da9a55 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 15 17:18:12 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=8

**Comment by seldondev** [comment]
Mon Jun 15 19:04:43 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=9

**Comment by seldondev** [comment]
Mon Jun 15 21:08:42 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=10

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 0e2c647905e30ce6c01fb312f905fb41f0da9a55 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 07:13:33 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=11

**Comment by seldondev** [comment]
Tue Jun 16 07:13:34 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=12

**Comment by seldondev** [comment]
Tue Jun 16 07:23:23 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=13

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 10:10:09 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=14

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 12:39:54 UTC 2020
The logs for [integration] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=15

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test notebooks`
integration | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 13:44:19 UTC 2020
The logs for [lint] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=17

**Comment by seldondev** [comment]
Tue Jun 16 13:44:25 UTC 2020
The logs for [pr-build] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=16

**Comment by seldondev** [comment]
Tue Jun 16 13:51:10 UTC 2020
The logs for [notebooks] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=18

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test integration`
notebooks | 3031313a55e588b5c3e2059e0664090d9e09acdd | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 17:32:36 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=20

**Comment by seldondev** [comment]
Tue Jun 16 17:32:37 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=19

**Comment by seldondev** [comment]
Tue Jun 16 17:36:31 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=21

**Comment by seldondev** [comment]
Tue Jun 16 17:36:32 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=22

**Comment by seldondev** [comment]
Tue Jun 16 17:49:36 UTC 2020
The logs for [notebooks] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=23

**Comment by seldondev** [comment]
Tue Jun 16 19:21:00 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=24

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b79332cfa5fcd602ce6c8765b85094941d6abbc9 | [link]() | `/test integration`
notebooks | 7703ebe0d0afaed29a3d69eaf29b1ba48b768d2a | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7703ebe0d0afaed29a3d69eaf29b1ba48b768d2a | [link]() | `/test notebooks`
integration | 7703ebe0d0afaed29a3d69eaf29b1ba48b768d2a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Jun 17 09:12:58 UTC 2020
The logs for [lint] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=26

**Comment by seldondev** [comment]
Wed Jun 17 09:13:10 UTC 2020
The logs for [pr-build] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=25

**Comment by seldondev** [comment]
Wed Jun 17 09:20:02 UTC 2020
The logs for [notebooks] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=27

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 7703ebe0d0afaed29a3d69eaf29b1ba48b768d2a | [link]() | `/test integration`
notebooks | 6f387ba007570fd11ae20149e12fc85e6e99823e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Jun 17 12:37:49 UTC 2020
The logs for [lint] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=29

**Comment by seldondev** [comment]
Wed Jun 17 12:37:52 UTC 2020
The logs for [pr-build] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=28

**Comment by seldondev** [comment]
Wed Jun 17 12:40:06 UTC 2020
The logs for [notebooks] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1950/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1950 --build=30

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 7703ebe0d0afaed29a3d69eaf29b1ba48b768d2a | [link]() | `/test integration`
notebooks | d5257eba61b1a819ed107deba9d88efee11b0a66 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
