### PR TITLE
Prefix v1 workflows

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

This prefixes existing GitHub Workflows with V1 such that they will be distinguishable in the UI from new V2 workflows.

It also adds a placeholder for V2 release workflow (required on master as this is `on_dispatch` workflow).
**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by agrski — APPROVED** [review]
:rocket:

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[agrski](https://github.com/SeldonIO/seldon-core/pull/4464#pullrequestreview-1200748417 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [agrski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4464]: [not Found]

**Pull request merged**
