### PR TITLE
reduce number of times connecting to elastic

### PR DESCRIPTION
**Pull request by ryandawsonuk**
for https://github.com/SeldonIO/seldon-core/issues/2109

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ryandawsonuk**
You can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 13 16:53:27 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=2

**Comment by seldondev** [comment]
Mon Jul 13 16:53:27 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=1

**Comment by seldondev** [comment]
Tue Jul 14 17:14:35 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=3

**Comment by seldondev** [comment]
Tue Jul 14 17:14:38 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=4

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | e9f8ee1545de526e3e0f126307aa7c9c725d8d5e | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 17:31:25 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=6

**Comment by seldondev** [comment]
Tue Jul 14 17:31:50 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=5

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6e629c5ce7c00db19ba4e35904d56a67e9e51fbe | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Looks good! Seems you need to run the linter, may be worth setting up the pre-commit hook https://docs.seldon.io/projects/seldon-core/en/v1.1.0/developer/contributing.html#coding-conventions or just running it directly. Once that's in should be good to merge!

**Comment by seldondev** [comment]
Wed Jul 15 09:41:16 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=8

**Comment by seldondev** [comment]
Wed Jul 15 09:41:17 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=7

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2120#issuecomment-658754406 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-658754406/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Completely forgot to mention, would be good to add a note to the UPGRADING.md, maybe given the next release is 1.2.2, it may be worth just updating the header from 1.2.1->1.2.2 and add it as an extra heads up (ie that requst logger has been upgraded to new release). Not sure if there are other places in the docs where we provide the images.

**Comment by ryandawsonuk** [comment]
Perhaps it needs adding to https://docs.seldon.io/projects/seldon-core/en/latest/reference/images.html

**Comment by axsaucedo** [comment]
Yeah, good point, it may be worth adding it onthe PR, and perhaps also on the upgrading section, although thinking about it there's not really a place where you would specify this in the seldon core config, so probably it's not as pressing.

/hold cancel

**Comment by seldondev** [comment]
Wed Jul 15 19:05:40 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=10

**Comment by seldondev** [comment]
Wed Jul 15 19:05:47 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2120/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2120 --build=9

**Pull request merged**
