### PR TITLE
deliberately empty whitespace change to check e2e tests

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Just want to run e2e in jx cluster against same code as master.

Aim is to help diagnose why https://github.com/SeldonIO/seldon-core/pull/1118 seemingly works everywhere except the jx-based e2e tests

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c786a3f92efb8f84e279bc4336ee0c43e748030e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
[One failure in the e2es that looks like an intermittent ambassador thing](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1162/3.log#L3086)

/test integration

**Comment by ryandawsonuk** [comment]
https://github.com/SeldonIO/seldon-core/pull/1156 is a recent PR that e2es [were triggered on ](https://github.com/SeldonIO/seldon-core/pull/1156#issuecomment-559735792) but the [only files are 1.log and 2.log ](https://github.com/SeldonIO/seldon-core/tree/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1158) which don't show any e2es running for it at all

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c786a3f92efb8f84e279bc4336ee0c43e748030e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Going to rebase this and re-trigger the tests. If they pass then it'll confirm [my theory about why the other PR was failing](https://github.com/SeldonIO/seldon-core/pull/1118#issuecomment-559872477).

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 10d853e2c5964f4e4391f582b935d021fc0fbca9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
No, looks like e2e tests are [now failing against this branch](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1162/4.log#L1811). That suggests my theory is wrong and I am none the wiser as to why the in-cluster e2e tests are failing. Also situation is rather worse now https://github.com/SeldonIO/seldon-core/pull/1118 was auto-merged. Not sure whether to revert it, even though it definitely works.

/test integration

**Comment by ryandawsonuk** [comment]
Ok now I see what the problem is. I managed to recreate it locally. It's

```
E1129 20:28:51.788349       1 reflector.go:126] pkg/mod/k8s.io/client-go@v11.0.1-0.20190409021438-1a26190bd76a+incompatible/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:seldon-system:seldon-manager" cannot list resource "configmaps" in API group "" at the cluster scope
```

**Comment by ryandawsonuk** [comment]
Will open a new PR to fix the configmap read issue.

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 10d853e2c5964f4e4391f582b935d021fc0fbca9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 10d853e2c5964f4e4391f582b935d021fc0fbca9
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 10d853e2c5964f4e4391f582b935d021fc0fbca9
* failed to process repo SeldonIO/seldon-core refref 10d853e2c5964f4e4391f582b935d021fc0fbca9
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
