### PR TITLE
Fixing Alibi Detect Server response cloud event data is json marshalled string

### PR DESCRIPTION
**Pull request by SachinVarghese**
Albi Detect Server logs the detector response to a configured `replyURL` as a cloud event. The data in the cloud event at the moment is a stringified json sting,  for example if the model response is
```json
{
	"data": {
		"outlier": {
			"is_outlier": [1]
		}
	}
}
```
then the binary could event data is 
```
 b`"{\"data":{\"outlier":{\"is_outlier\":[1]}}}"`
```
This is because the reponse dict is converted to a json string twice using `json.dumps` method. This PR removes the extra string convertion, so that the expected binary cloud event data is

```
 b`{"data":{"outlier":{"is_outlier":[1]}}}`
```

Note that the detect server response remains the same and the test is updated only for the replyURL cloud event.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by axsaucedo — APPROVED** [review]
Nice one - notebook and upgrading.md looks good

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/3907#pullrequestreview-871985530 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
