### PR TITLE
upgrade alibi and alibi-detect in components

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

Fixes failing integration tests and upgrades alibi and alibi-detect in components.

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2403
Closes https://github.com/SeldonIO/seldon-core/issues/2408

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
- updates alibi-detect to version 0.4.2
- updates alibi to 0.5.4
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Sep  9 10:11:53 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=3

**Comment by seldondev** [comment]
Wed Sep  9 10:13:03 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=1

**Comment by seldondev** [comment]
Wed Sep  9 10:13:12 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=2

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 03eb4bbd204c411aadad915c7f7f5a279be32c1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 12:21:04 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 03eb4bbd204c411aadad915c7f7f5a279be32c1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
fail on `TestPrepack.test_text_alibi_explainer`
/retest

**Comment by seldondev** [comment]
Wed Sep  9 13:49:15 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=5

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 03eb4bbd204c411aadad915c7f7f5a279be32c1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 10 09:14:51 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=7

**Comment by seldondev** [comment]
Thu Sep 10 09:14:52 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=6

**Comment by seldondev** [comment]
Thu Sep 10 09:17:26 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=8

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | a4ad9d0c00ef1a84be1efbee1d34b3329454e466 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
present integration test failure (TestPrepack::test_test_alibi_explainer) should be fixed in https://github.com/SeldonIO/seldon-core/pull/2409 (need to rebase once that one is merged and retriggered the integraton tests)

**Comment by RafalSkolasinski** [comment]
https://github.com/SeldonIO/seldon-core/pull/2409 is merged; restarting tests
/test integration

**Comment by seldondev** [comment]
Thu Sep 10 15:06:47 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=9

**Comment by seldondev** [comment]
Thu Sep 10 15:07:03 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=11

**Comment by seldondev** [comment]
Thu Sep 10 15:08:29 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=10

**Comment by RafalSkolasinski** [comment]
weird problem at the beginning of integration tests
```
ERROR: failed to create cluster: failed to init node with kubeadm: command "docker exec --privileged kind-control-plane kubeadm init --ignore-preflight-errors=all --config=/kind/kubeadm.conf --skip-token-print --v=6" failed with error: exit status 137
make: *** [Makefile:8: kind_create_cluster] Error 1
`kind get kubeconfig-path` is deprecated!

KIND will export and merge kubeconfig like kops, minikube, etc.
This command is now unnecessary and will be removed in a future release.

For more info see: https://github.com/kubernetes-sigs/kind/issues/1060
See also the output of `kind create cluster`

Existing kind cluster or failure starting - 2
kind delete cluster
Deleting cluster "kind" ...
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
kind_test_all.sh: line 212: RUN_EXIT_VALUE: unbound variable
```


/retest

**Comment by seldondev** [comment]
Thu Sep 10 15:13:55 UTC 2020
The logs for [integration] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=12

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | dc66c7b5b81ae54401fde6ee0ac73c6f97b5b704 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 10 16:31:06 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=13

**Comment by seldondev** [comment]
Thu Sep 10 16:31:16 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=14

**Comment by seldondev** [comment]
Thu Sep 10 16:48:39 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=15

**Comment by seldondev** [comment]
Thu Sep 10 16:49:39 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=18

**Comment by seldondev** [comment]
Thu Sep 10 16:49:40 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=17

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test integration`
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 08:40:42 UTC 2020
The logs for [integration] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=20

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 13:45:14 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=22

**Comment by seldondev** [comment]
Fri Sep 11 13:45:14 UTC 2020
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=23

**Comment by seldondev** [comment]
Fri Sep 11 13:45:14 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=21

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | 3f21d7d8552c19b16844f8a18ffec33cc6835f7a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 15:41:04 UTC 2020
The logs for [integration] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=26

**Comment by seldondev** [comment]
Fri Sep 11 15:41:07 UTC 2020
The logs for [pr-build] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=24

**Comment by seldondev** [comment]
Fri Sep 11 15:41:15 UTC 2020
The logs for [lint] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=25

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | e537849e829330566b7a4f4d3f83998c63306b19 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 17:13:45 UTC 2020
The logs for [lint] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=28

**Comment by seldondev** [comment]
Fri Sep 11 17:13:51 UTC 2020
The logs for [pr-build] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=27

**Comment by seldondev** [comment]
Fri Sep 11 17:14:11 UTC 2020
The logs for [integration] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=29

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | c46f97de3c7111a093a2c83324c53c63d1dbd06d | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 18:20:37 UTC 2020
The logs for [integration] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=32

**Comment by seldondev** [comment]
Fri Sep 11 18:20:47 UTC 2020
The logs for [pr-build] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=30

**Comment by seldondev** [comment]
Fri Sep 11 18:20:51 UTC 2020
The logs for [lint] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=31

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | 5f8acf647d48194aed032ae10c733ba30f0f88e9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 19:42:55 UTC 2020
The logs for [integration] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=33

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | 5f8acf647d48194aed032ae10c733ba30f0f88e9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 14 10:29:38 UTC 2020
The logs for [integration] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2404/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2404 --build=34

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e637a7e35100ee601c257c492d69a10df56cafb5 | [link]() | `/test notebooks`
integration | 5f8acf647d48194aed032ae10c733ba30f0f88e9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Superseded by https://github.com/SeldonIO/seldon-core/pull/2431 and https://github.com/SeldonIO/seldon-core/pull/2432

**Pull request closed without merging**
