### PR TITLE
Replace print with logging.info in python/tests. Closes #1372

### LINKED ISSUE #1372: replace print with logging in tests
Some tests, e.g. `python/tests/test_router_microservice.py`, are using `print` statements to ease debugging on failure.

It may be a good idea to replace them with proper logging.

(Though, personally I am not sure if there is much benefit from doing that for tests).

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
As in title. Fixes #1372.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Feb 11 13:38:46 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=1

**Comment by seldondev** [comment]
Tue Feb 11 13:38:49 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=2

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 517c8e2bda885cf2fa6b657093767c71924ca490 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 517c8e2bda885cf2fa6b657093767c71924ca490 | [link]() | `/test lint`
pr-build | 517c8e2bda885cf2fa6b657093767c71924ca490 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Feb 11 13:57:09 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=4

**Comment by seldondev** [comment]
Tue Feb 11 13:57:09 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=3

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 517c8e2bda885cf2fa6b657093767c71924ca490 | [link]() | `/test this`
lint | 412215bc4b8b429bca93f986f6cb994189744bf4 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Feb 11 14:12:39 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=6

**Comment by seldondev** [comment]
Tue Feb 11 14:12:42 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=5

**Comment by seldondev** [comment]
Wed Feb 12 07:55:42 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=7

**Comment by axsaucedo** [comment]
@rafalskolasinski nice one! Looking at some of these files I think the issue probably wasn't as specific in scope as some would benefit more from being replaced with logging as having the output would still be valuable. Probably we should rename this issue from remove print statements to move fully to logging,as I think it's also useful to put all of the current ones under a logger.info or logger.debug

**Comment by seldondev** [comment]
I think having good logging is important for the main wrapper code as this
one will be executed always in normal operation.

So in principle if something is meant to help debug issues should be
independent of being defined on methods of user-defined model.

Let's discuss more later today!

**Comment by seldondev** [comment]
Wed Feb 12 10:59:32 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=9

**Comment by seldondev** [comment]
Wed Feb 12 10:59:33 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=8

**Comment by seldondev** [comment]
Wed Feb 12 11:01:40 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=10

**Comment by seldondev** [comment]
Wed Feb 12 11:01:43 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=11

**Comment by RafalSkolasinski** [comment]
@axsaucedo replaced `print` with `logging.info` and enabled that logging level in tests

**Comment by seldondev** [comment]
Wed Feb 12 11:08:26 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=13

**Comment by seldondev** [comment]
Wed Feb 12 11:08:47 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=12

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 83dc13781bac71621460250921dbdce4eb2b08e7 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Just in case:
/test integration

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 83dc13781bac71621460250921dbdce4eb2b08e7 | [link]() | `/test lint`
integration | 83dc13781bac71621460250921dbdce4eb2b08e7 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb 12 11:11:22 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=15

**Comment by seldondev** [comment]
Wed Feb 12 11:11:28 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=16

**Comment by RafalSkolasinski** [comment]
Just in case:
/test integration

**Comment by seldondev** [comment]
Wed Feb 12 11:13:29 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1424/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1424 --build=17

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1424#issuecomment-585687162" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
