### PR TITLE
Tidy up Java

### LINKED ISSUE #937: Tidy up Java project
## Context

The Java code on the engine currently has a mix of spaces and tabs, unused dependencies, deprecation notices, different coding styles, etc. It would be good to add linters which check for these (i.e. static checks) and auto-formatters which force the code to comply with a certain style guideline.

## Suggestions

We can look into large Java projects (e.g. [`spring-framework`](https://github.com/spring-projects/spring-framework)) to see which tools they use.   Ideally both the linters and autoformatters should be integrated with `mvn` and the former should get triggered by git hooks, to ensure that the conventions are always followed. 

Ideally, the build should stop if any of the checks fails.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #937.

## Changes

- Run [`tidy`](https://github.com/htacg/tidy-html5) on `pom.xml`.
- Add `checkstyle` linter to `mvn validate` which will flag violations of [Google's Java style guide](https://google.github.io/styleguide/javaguide.html).
- Add `-Xlint:all` flag to `mvn compile`, which will flag usage of features marked as deprecated. 
- Remove some dependencies which were flagged as unused by `mvn dependency:analyze`.
- Add [`pre-commit`](https://pre-commit.com/) config to manage local Git hooks. There is currently a single hook configured which will run [`google-java-format`](https://github.com/google/google-java-format) on modified `*.java` files on each commit.
- Run [`google-java-format`](https://github.com/google/google-java-format) across all `*.java` files to make style consistent.
- Add note to `CONTRIBUTING.md` about [`pre-commit`](https://pre-commit.com/) and  [Google's Java style guide](https://google.github.io/styleguide/javaguide.html).

## Notes

[`pre-commit`](https://pre-commit.com/) is a cross-language tool to handle Git hooks. We can also use it to handle `python` or `go` formatters. For `python`, `black` already offers integration [out of the box](https://github.com/psf/black#version-control-integration) and therefore could also be interesting for #947.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Awesome! Nice one @adriangonz !

**Comment by axsaucedo** [comment]
Are we going for 2 spaces?

**Comment by adriangonz** [comment]
@axsaucedo I'm just going with whatever [`google-java-format`](`https://github.com/google/google-java-format`) wants to do. I don't have much mileage with Java, that's what I went for a **very** opinionated formatter.

Google seems to like [2 spaces](https://google.github.io/styleguide/javaguide.html#s4.2-block-indentation).

**Comment by axsaucedo** [comment]
Fair enough! I think on this one @gsunner and @cliveseldon wouuld be the main Java ones, so if they are happy then let's press the button!

**Comment by axsaucedo** [comment]
More specifically, Jenkins X basically runs the jenkins-x.yaml command, which runs `make install-dev` - this acutally installs it with the requirements.txt, so if you remove the dependency, it should be enough https://github.com/adriangonz/seldon-core/blob/extra-python-dependencies/jenkins-x.yml

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/951#issuecomment-543098220" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref be8fa227ca427046485cb7575d9b3ea49377ec85
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha be8fa227ca427046485cb7575d9b3ea49377ec85
* failed to process repo SeldonIO/seldon-core refref be8fa227ca427046485cb7575d9b3ea49377ec85
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
