### PR TITLE
operator: controller-runtime upgrade to v0.5.8

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

controller-runtime upgrade to v0.5.8

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2116

**Special notes for your reviewer**:

subtask of https://github.com/SeldonIO/seldon-core/issues/2088

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 13 10:42:39 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2117/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2117 --build=1

**Comment by seldondev** [comment]
Mon Jul 13 10:42:50 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2117/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2117 --build=2

**Comment by seldondev** [comment]
Mon Jul 13 10:43:28 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2117/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2117 --build=3

**Comment by seldondev** [comment]
Mon Jul 13 10:44:54 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2117/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2117 --build=4

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2117#issuecomment-657671552 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-657671552/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Integration and notebook tests pass 👍

**Pull request merged**
