### PR TITLE
Jenkins X add comment when pipeline finishes 

### PR DESCRIPTION
**Pull request by axsaucedo**
PR contains:
* Update all dependencies of Core Builder (will increase build speeds)
* Moved Python Builder use to Core Builder as we use it for integration tests, and prepack builds for consistent environments
* Added comment when build finishes so we can get notified (especially for long running tests like integration, notebooks and engine)
* Modified Python tox tests so they can be run in parallel
* Changed 0.0.0.0 to localhost on python tests so they can be run in parallel

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | fef171f7d4110d0823798702ba7b3468236cb094 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jul 16 20:32:07 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=2

**Comment by seldondev** [comment]
Thu Jul 16 20:34:53 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=4

**Comment by seldondev** [comment]
Fri Jul 17 10:39:41 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | fd73daa0dbf8ea4270effe173563d12e59224bd2 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 10:45:49 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=8

**Comment by seldondev** [comment]
Fri Jul 17 10:55:33 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=10

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | d2bdaebf8a877abbbc11b2213e6a799204d01ffb | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 10:59:47 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=12

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ea7064b58b3154053c131140aa3c99169ea5a0bf | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 11:52:03 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=14

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | aa7524c33f2c1a0e8e504af170597c96a6114af5 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 11:54:11 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=16

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7be1b1c519eb67fb6f17efe0635f1794b8345c81 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 11:58:27 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=18

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7585c98cc808449df55f276e5624a515fe36e98e | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul 17 17:06:42 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=20

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7585c98cc808449df55f276e5624a515fe36e98e | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a04ed2882adafc5994b239ea12fe2bdf4aec86ee | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 06:00:38 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=23

**Comment by seldondev** [comment]
Sat Jul 18 06:05:49 UTC 2020
The logs for [lint] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=25

**Comment by seldondev** [comment]
Sat Jul 18 06:05:57 UTC 2020
The logs for [pr-build] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=24

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | af8d5ee4560a6cb1b1d71ce23f63ad65007f1334 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 06:21:49 UTC 2020
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=26

**Comment by seldondev** [comment]
Sat Jul 18 06:22:01 UTC 2020
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=27

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 90dae5ff01e238b045be87c4579a11785ff11d5b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 06:43:51 UTC 2020
The logs for [pr-build] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=28

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 90dae5ff01e238b045be87c4579a11785ff11d5b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 06:57:31 UTC 2020
The logs for [pr-build] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=29

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 90dae5ff01e238b045be87c4579a11785ff11d5b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 07:32:39 UTC 2020
The logs for [lint] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=31

**Comment by seldondev** [comment]
Sat Jul 18 07:32:47 UTC 2020
The logs for [pr-build] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=30

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 925e1e1759bfb982e03c8e5c610f5e5b65ac5397 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 08:04:04 UTC 2020
The logs for [pr-build] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=32

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dc2112fe848f1db552f0b9f20aef786fae1ffff8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dc2112fe848f1db552f0b9f20aef786fae1ffff8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 08:30:39 UTC 2020
The logs for [lint] [39] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/39.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=39

**Comment by seldondev** [comment]
Sat Jul 18 08:30:46 UTC 2020
The logs for [pr-build] [38] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/38.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=38

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c9757cc5db5ff71eeb3c54bc5cb46466ab9b4f5f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Jul 18 08:55:42 UTC 2020
The logs for [lint] [41] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/41.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=41

**Comment by seldondev** [comment]
Sat Jul 18 08:55:45 UTC 2020
The logs for [pr-build] [40] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/40.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=40

**Comment by seldondev** [comment]
Sat Jul 18 09:13:39 UTC 2020
The logs for [lint] [45] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/45.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2149 --build=45

**Comment by seldondev** [comment]
pr-build - 44 [SUCCESS ✅] Well done! 😎

**Comment by seldondev** [comment]
pr-build - 44 [SUCCESS ✅] Well done! 😎

**Comment by seldondev** [comment]
TEST STARTED [lint #47]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/47.log

impatient try
jx get build logs SeldonIO/seldon-core/PR-2149 --build=47

**Comment by seldondev** [comment]
TEST STARTED [pr-build #46]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/46.log

impatient try
jx get build logs SeldonIO/seldon-core/PR-2149 --build=46

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ca07c4678defc9c6ad507b7f6c8629971028f6a2 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
# STARTING TEST [ lint # 49 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/49.log

impatient try

**Comment by seldondev** [comment]
# STARTING TEST [ pr-build # 48 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/48.log

impatient try

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ca07c4678defc9c6ad507b7f6c8629971028f6a2 | [link]() | `/test lint`
pr-build | 0df0492aee4932e4a0384c2192082f481591e13b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 51 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/51.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=51

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 50 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/50.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=50

**Comment by seldondev** [comment]
## SUCCESS [lint #51] ✅

Well done! 😎

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dc1bf628a09d6b7ec36e29e7a06072b5ac5c0edf | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 53 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/53.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=53

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 52 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/52.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=52

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 55 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/55.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=55

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 54 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/54.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=54

**Comment by seldondev** [comment]
## SUCCESS [lint # 55] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [pr-build # 54] TEST PASSED ✅

Well done! 😎

**Comment by axsaucedo** [comment]
PR contains:
* Update all dependencies of Core Builder (will increase build speeds)
* Moved Python Builder use to Core Builder as we use it for integration tests, and prepack builds for consistent environments
* Added comment when build finishes so we can get notified (especially for long running tests like integration, notebooks and engine)
* Modified Python tox tests so they can be run in parallel
* Changed 0.0.0.0 to localhost on python tests so they can be run in parallel

/cc @cliveseldon 
/cc @adriangonz 

/test integration
/test notebooks
/test engine

**Comment by seldondev** [comment]
## STARTING TEST [ notebooks # 56 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/56.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=56

**Comment by seldondev** [comment]
## STARTING TEST [ integration # 58 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/58.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=58

**Comment by seldondev** [comment]
## STARTING TEST [ engine # 57 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/57.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=57

**Comment by seldondev** [comment]
## SUCCESS [engine # 57] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [integration # 58] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## SUCCESS [notebooks # 56] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2149#issuecomment-660959361 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-660959361/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 60 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/60.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=60

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 59 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/59.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=59

**Comment by seldondev** [comment]
## SUCCESS [lint # 60] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 70b8516aec68f3c860c83ea5da4599b434bede08 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Strange, it seems the `controller` `suite_test` has failed with:
```
[90m------------------------------[0m
[91m[1mFailure [34.980 seconds][0m
[91m[1m[BeforeSuite] BeforeSuite [0m
[37m/workspace/source/operator/controllers/suite_test.go:142[0m

  [91mUnexpected error:
      <*errors.errorString | 0xc0003656c0>: {
          s: "timed out waiting for the condition",
      }
      timed out waiting for the condition
  occurred[0m

  /workspace/source/operator/controllers/suite_test.go:158
[90m------------------------------[0m
```

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 61 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2149/61.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2149 --build=61

**Comment by seldondev** [comment]
## SUCCESS [pr-build # 61] TEST PASSED ✅

Well done! 😎

**Comment by axsaucedo** [comment]
Strange, it seems the operator test had a spike in the memory usage:
image

It went up to 7.2GB, we should investigate further

**Pull request merged**
