### PR TITLE
Add Chainer MNIST example

### PR DESCRIPTION
**Pull request by dtaniwaki**
I'm going to use Seldon in my project and since we use Chainer as an ML framework, I started it from the train mnist example first. I think this example will be helpful for Chainer users. Could you consider adding this example?

### CODE REVIEW

**Comment by axsaucedo** [comment]
Looks great @dtaniwaki , thank you for the contribution, we'll review. Can you please make sure you add an `.nblink` file that points to your ipynb file as well?

**Comment by dtaniwaki** [comment]
@axsaucedo Added and tested it with `make html` in the doc dir in my local env.

**Comment by axsaucedo** [comment]
Lgtm!

**Comment by axsaucedo** [comment]
Awesome, thanks for the contribution!

**Pull request merged**
