### PR TITLE
check for duplicate svc-name annotations

### LINKED ISSUE #4730: Should warn/reject predictors with the same svc-name
## Describe the bug

If the user requests the same `seldon.io/svc-name` for multiple predictors in the same SeldonDeployment seldon should reject such SeldonDeployment because only one DestinationRule will be created and the VirtualService will not work.

## To reproduce

`kubectl apply -f example.yaml`

example.yaml:
```
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-for-testing
  labels:
    'istio-injection': 'enabled'
---
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: testing-svc-name
  namespace: ns-for-testing
spec:
  annotations:
    seldon.io/engine-separate-pod: "true"
  predictors:
    - componentSpecs:
        - spec:
            containers:
              - image: seldonio/mock_classifier:1.9.0-dev
                name: query
      graph:
        name: query
      name: baseline
      annotations:
        seldon.io/svc-name: some-name
      replicas: 1
      traffic: 70
    - componentSpecs:
        - spec:
            containers:
              - image: seldonio/mock_classifier:1.9.0-dev
                name: query
      graph:
        name: query
      name: variant
      annotations:
        seldon.io/svc-name: some-name
      replicas: 1
      traffic: 30
  protocol: v2
```

## Expected behaviour

The deployment of the SeldonDeployment  fails and there is a error visible to the user that the name "some-name" is used twice.

## Environment
* Deployed Seldon System Images:  `value: docker.io/seldonio/seldon-core-executor:1.15.0  image: docker.io/seldonio/seldon-core-operator:1.15.0`

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #4730

### CODE REVIEW

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4744-notebooks-n2g2n) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4744-notebooks-n2g2n) | `/test notebooks`
integration | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4744-integration-nsl54) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
For the integration tests, the only error seems to be on `test_rolling_deployment[graph1.json-graph4.json-True-ambas]` (which is a known flaky one).

For the notebook tests, it keeps failing to set up the cluster. I think it can be considered a flaky one though:

```
Error: conversion webhook for getambassador.io/v3alpha1, Kind=Module failed: Post "https://emissary-apiext.emissary-system.svc:443/webhooks/crd-convert?timeout=30s": dial tcp 10.96.51.103:443: connect: connection refused
```

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4744-integration-nsl54) | `/test integration`
notebooks | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4744-notebooks-rq2nq) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4744-notebooks-rq2nq) | `/test notebooks`
integration | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4744-integration-slwgl) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 257012d0204b81f0c8867c3186fcccd0bf84a2e6 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4744-notebooks-btdfl) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
All good to go @cliveseldon 

image

**Comment by RafalSkolasinski** [comment]
Really don't know what happened :sweat_smile: - I am pretty sure I wanted to merge it

**Pull request merged**
