### PR TITLE
Lint licenses

### LINKED ISSUE #1932: Automate license check in CI linting pipeline
Reject of licenses have changed.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1932 

## Changelog

- In Python server, rename `make run_lint` and `make run_linter_check` to `make fmt` and `make lint`.
- Add target `make lint` to operator and executor (and add them to JX lint pipeline).
- Across packages, make sure that `make lint` checks if licenses have changed.

## Notes

~On Python, lint seems to fail because the output of `pip-licenses` depends on the environment. Therefore, JX is generating a slightly different license doc.  I've opened up an issue on `pip-licenses` reporting this: https://github.com/raimon49/pip-licenses/issues/69~

~In the meantime, we can generate the output locally so that it matches what gets generated in the JX cluster.~

The issue with `pip-licenses` has now been resolved.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 22 12:46:26 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=2

**Comment by seldondev** [comment]
Mon Jun 22 12:47:57 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=1

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | db9ed4318ffca375e96f184a297ab1fac6507c04 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | db9ed4318ffca375e96f184a297ab1fac6507c04 | [link]() | `/test lint`
pr-build | db9ed4318ffca375e96f184a297ab1fac6507c04 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 22 15:27:05 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=4

**Comment by seldondev** [comment]
Mon Jun 22 15:28:37 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=3

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | db9ed4318ffca375e96f184a297ab1fac6507c04 | [link]() | `/test this`
lint | 16f6282e8ff7a8a4fb17a340735ba55488119e01 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 08:16:10 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=5

**Comment by seldondev** [comment]
Tue Jun 23 08:45:50 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=7

**Comment by seldondev** [comment]
Tue Jun 23 08:45:57 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=6

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 16f6282e8ff7a8a4fb17a340735ba55488119e01 | [link]() | `/test lint`
pr-build | c3590d43104544e468ba19407a2dd0eaf2fe15ac | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c3590d43104544e468ba19407a2dd0eaf2fe15ac | [link]() | `/test this`
lint | c3590d43104544e468ba19407a2dd0eaf2fe15ac | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 09:11:04 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=9

**Comment by seldondev** [comment]
Tue Jun 23 09:11:08 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=8

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c3590d43104544e468ba19407a2dd0eaf2fe15ac | [link]() | `/test this`
lint | 3c7dfae6d36c23bfa8ef7ccddc2bd5f7f8f7198f | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 15:57:52 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=10

**Comment by seldondev** [comment]
Tue Jun 23 15:57:57 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=11

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | f3a6746001447f3f1a5b37cb520a3138ce75b26a | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 16:12:46 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=13

**Comment by seldondev** [comment]
Tue Jun 23 16:13:45 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=12

**Comment by seldondev** [comment]
Thu Jun 25 09:33:03 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=15

**Comment by seldondev** [comment]
Thu Jun 25 09:33:16 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=14

**Comment by RafalSkolasinski** [comment]
\lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1995#issuecomment-651023510" title="LGTM">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 29 08:55:44 UTC 2020
The logs for [lint] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=17

**Comment by seldondev** [comment]
Mon Jun 29 08:57:33 UTC 2020
The logs for [pr-build] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=16

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 13cfd3df6fd7f84a2b0d4bcde7980da316d33c3b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
/hold

@RafalSkolasinski this actually highlights a problem with this approach. Every time a new dependency gets updated, it will block the PR from getting merged. The same applies to `dependabot` PRs (which would be particularly painful).

Therefore, we should also consider how to auto-run `make licenses` on every PR. Or maybe this is something that could happen only at build time (as part of the `Dockerfile`), so that only the Docker image has an updated list of images.

**Comment by RafalSkolasinski** [comment]
I thought that check is good because it'd force people to run script to update licences when they introduce new one - so it shouldn't be problem for manually brought dependencies - unless I am missing sth here?

I only see problem with dependabot as I am not sure if it possible to instruct it to run licence updates.

**Comment by seldondev** [comment]
Mon Jul  6 15:43:46 UTC 2020
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=18

**Comment by seldondev** [comment]
Mon Jul  6 15:48:10 UTC 2020
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=19

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 13cfd3df6fd7f84a2b0d4bcde7980da316d33c3b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/1995#issuecomment-651023510 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jul  7 08:15:54 UTC 2020
The logs for [lint] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=21

**Comment by seldondev** [comment]
Tue Jul  7 08:16:01 UTC 2020
The logs for [pr-build] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=20

**Comment by seldondev** [comment]
Tue Jul  7 15:10:19 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=22

**Comment by seldondev** [comment]
Tue Jul  7 15:11:06 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=23

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 7645535bdb0f6b987ead71b7b391acaceb92d200 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul  7 15:47:41 UTC 2020
The logs for [lint] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=25

**Comment by seldondev** [comment]
Tue Jul  7 15:47:45 UTC 2020
The logs for [pr-build] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=24

**Comment by seldondev** [comment]
Tue Jul  7 15:50:35 UTC 2020
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=26

**Comment by seldondev** [comment]
Tue Jul  7 15:50:36 UTC 2020
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=27

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 86f4c8ef1193be14ea5b1f963c82871a82d82075 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Jul  8 08:41:34 UTC 2020
The logs for [pr-build] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=28

**Comment by seldondev** [comment]
Wed Jul  8 08:41:39 UTC 2020
The logs for [lint] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1995/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1995 --build=29

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 924ea12720ab53917f4be95c405c114f00a8fff1
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 924ea12720ab53917f4be95c405c114f00a8fff1
* failed to process repo SeldonIO/seldon-core refref 924ea12720ab53917f4be95c405c114f00a8fff1
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
