### PR TITLE
WIP: Extracted templates from helm charts for offline deployments

### PR DESCRIPTION
**Pull request by axsaucedo**
This PR contains the extracted manifests from the helm chart commands that would enable for offline installations. This was tested to work. It could be possible to pass a flag to select that we'd want to use the manifests instead of helm.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
@gsunner although this could serve as a quickfix, perhaps the cleaner way to address this would be by actually downloading the helm chart templates into the Seldon Core helm-charts folder, which could actually be a pretty reasonable solution. What do you think?

**Comment by cliveseldon** [comment]
I think we should consider kustomize as the solution rather than creating templates from helm. The templates could be basis for the kustomize. There is this project I have used before:https://github.com/ContainerSolutions/helm-convert

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 608aec507d3362d4c5abb52cac9761dfd2da7156
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 608aec507d3362d4c5abb52cac9761dfd2da7156
* failed to process repo SeldonIO/seldon-core refref 608aec507d3362d4c5abb52cac9761dfd2da7156
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
