### PR TITLE
Add note that Ansible is not for production

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Add note that Ansible is not for production

### CODE REVIEW

**Comment by agrski** [comment]
Duplicated by #4695 ?

**Review by edshee — CHANGES_REQUESTED** [review]
Could we add a link to the helm installation page?

**Comment by edshee** [comment]
> Duplicated by #4695 ?

Yes both seem to be merging to v2, did you mean to do one for v2 and one for v1?

**Comment by RafalSkolasinski** [comment]
Yeah, my fault

**Pull request closed without merging**
