### PR TITLE
Cleanup examples

### LINKED ISSUE #1467: Clean up examples
Which notebooks to keep:

Ambassador

- [x] Ambassador Canary
- [x]     Ambassador Shadow
- [x]     Ambassador Headers
- [x]     Ambassador Custom Config

Cloud
- [ ]     Alibaba Cloud Container Service for Kubernetes Deep Mnist
- [ ]     AWS Elastic Kubernetes Service (EKS) Deep MNIST
- [ ]     Azure Kubernetes Service (AKS) Deep MNIST

Rest

Alibi
- [ ]     Tabular, Text and Image Model Explainers
- [ ]     Explainer Alibi Anchor Tabular
- [ ]     Seldon deployment of Alibi Outlier detector
- [ ]     Train and test outliers detector

Incubating
- [ ]     Go Model
- [ ]     Train and test loanclassifier

- [ ]     Autoscaling Example
- [ ]     Custom Endpoints
- [ ]     Example Helm Deployments

- [ ]     Contenerise your models
- [ ]     Deploy your models separately
- [ ]     Deploy loanclassifier and outliersdetector with combiner

- [ ]     GPU Tensorflow Deep MNIST
- [ ]     H2O Java MoJo
- [ ]     Istio Canary
- [ ]     Istio Examples
- [ ]     Keras MNIST Model Deployment
- [ ]     Test using Minikube
- [ ]     Chainer MNIST Model Deployment
- [ ]     Test using Minikube
- [ ]     Kubeflow Seldon E2E Pipeline
- [ ]     Max gRPC Message Size
- [ ]     Metrics
- [ ]     Model with Custom Metrics
- [ ]     MLflow
- [ ]     MLflow Pre-packaged MOdel Server A/B Test
- [ ]     NodeJS MNIST
- [ ]     NodeJS Tensorflow
- [ ]     NVIDIA TensorRT MNIST
- [ ]     OpenVINO ImageNet
- [ ]     OpenVINO ImageNet Ensemble
- [ ]     ONNX ResNet with Intel nGraph
- [ ]     Payload Logging
- [ ]     Protocol Examples
- [ ]     R Iris Classifier
- [ ]     R MNIST Classifier
- [ ]     REST timeouts
- [ ]     Sagemaker SKLearn Example
- [ ]     SKLearn Iris Classifier
- [ ]     SKLearn MNIST
- [ ]     SKLearn SpaCy Reddit Text Classifier Example
- [ ]     Sklearn, Xgboost, Tensorflow Server Examples
- [ ]     Tensorflow MNIST
- [ ]     TFserving MNIST
- [ ]     Tracing
- [ ]     Spam Classification TRANSFORMER component
- [ ]     Spam Classification Model (Sklearn)
- [ ]     Spam Classification Model (keras)

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1467

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Mar  3 09:24:55 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=2

**Comment by seldondev** [comment]
Tue Mar  3 09:25:08 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=1

**Comment by seldondev** [comment]
Mon Mar  9 14:04:47 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=3

**Comment by seldondev** [comment]
Mon Mar  9 14:04:51 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=4

**Comment by seldondev** [comment]
Wed Mar 11 19:10:30 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=5

**Comment by seldondev** [comment]
Wed Mar 11 19:10:47 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=6

**Comment by axsaucedo** [comment]
Looks good - only thing I think it may be good to leave the Tensorflow MNIST as it's referenced in quite a few places as links, but other than that looks good @cliveseldon

**Comment by axsaucedo** [comment]
As discussed deep mnist link was typo as there is no notebook, so just removed dead link
/approve
/lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1495#issuecomment-598608198" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Mar 13 08:34:13 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=8

**Comment by seldondev** [comment]
Fri Mar 13 08:35:33 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1495/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1495 --build=7

**Pull request merged**
