### PR TITLE
WIP: V1.5.2 release

### PR DESCRIPTION
**Pull request by axsaucedo**
**What this PR does / why we need it**:

* 1.5.2 release, only to run tests - do not merge

## Outstanding

* A patch was required to account for webhook still present, namely f9bc19e

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/v1.5.1-release/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Feb 11 20:23:02 UTC 2021
The logs for [notebooks] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2950/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2950 --build=2

**Comment by seldondev** [comment]
Thu Feb 11 20:23:07 UTC 2021
The logs for [integration] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2950/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2950 --build=1

**Comment by axsaucedo** [comment]
A patch was required to account for webhook still present, namely https://github.com/SeldonIO/seldon-core/pull/2950/commits/f9bc19eb77942102385eff7fa8a8dfa30236c950

**Comment by seldondev** [comment]
Thu Feb 11 22:01:09 UTC 2021
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2950/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2950 --build=3

**Comment by seldondev** [comment]
Thu Feb 11 22:01:20 UTC 2021
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2950/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2950 --build=4

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to process repo SeldonIO/seldon-core refref c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to list files in directory /var/tmp/gitrepo059637228/.lighthouse
* open /var/tmp/gitrepo059637228/.lighthouse
* no such file or directory

**Comment by RafalSkolasinski** [comment]
Run integration tests locally using Kind Cluster v1.18.5. 
Skipped operator update tests due to https://github.com/SeldonIO/seldon-core/issues/2966.

```
============================================================================== 76 passed, 2 skipped, 1 warning in 4416.32s (1:13:36) ===============================================================================
```


The operator update tests passed on Kind Cluster v1.17.5.

**Comment by axsaucedo** [comment]
Release 1.5.2 has been completed successfully

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to process repo SeldonIO/seldon-core refref c1d040be2c456f8883e5915b985ab1bd259e4730
* failed to list files in directory /var/tmp/gitrepo598506571/.lighthouse
* open /var/tmp/gitrepo598506571/.lighthouse
* no such file or directory

**Pull request closed without merging**
