### PR TITLE
Use kubectl version v1.17.0 in test scripts

### LINKED ISSUE #1802: Kind test script Istio install failing with kubectl version v1.18.x
testing/scripts/kind_test_setup.sh fails with following errors due to CRD not being present:

```
unable to recognize "istio-1.4.2.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "VirtualService" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "EnvoyFilter" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "Policy" in version "authentication.istio.io/v1alpha1"
unable to recognize "istio-1.4.2.yaml": no matches for kind "Gateway" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "Sidecar" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "MeshPolicy" in version "authentication.istio.io/v1alpha1"
unable to recognize "istio-1.4.2.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
unable to recognize "istio-1.4.2.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "attributemanifest" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "handler" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "rule" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "instance" in version "config.istio.io/v1alpha2"
unable to recognize "istio-1.4.2.yaml": no matches for kind "DestinationRule" in version "networking.istio.io/v1alpha3"
```

This has only been found to happen when using the following version of kubectl client:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-21T01:25:41Z", GoVersion:"go1.13.10", Compiler:"gc", Platform:"linux/amd64"}
```

Versions v1.17.x and v1.16.x of kubectl client do not fail.

Additionally if using v1.18.x, if the CRDs are installed separately as shown [here](https://istio.io/docs/setup/install/helm/#installation-steps) before Istio is installed, then the errors do not occur.

### PR DESCRIPTION
**Pull request by glindsell**
Fixes #1802 
Signed-off-by: glindsell <gl@seldon.io>

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **glindsell**

If they are not already assigned, you can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu May  7 10:00:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=2

**Comment by seldondev** [comment]
Thu May  7 10:01:17 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=1

**Comment by seldondev** [comment]
Thu May  7 10:02:45 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=4

**Comment by seldondev** [comment]
Thu May  7 10:03:53 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=3

**Comment by seldondev** [comment]
Thu May  7 10:08:22 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=6

**Comment by seldondev** [comment]
Thu May  7 10:09:17 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1808/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1808 --build=5

**Comment by glindsell** [comment]
Replaced by comments in README > #1810

**Pull request closed without merging**
