### PR TITLE
Update k8s libs to 1.18.6

### LINKED ISSUE #1949: Upgrade k8s client API to 1.18+
Multiple dependencies will shortly necessitate moving to k8s v1.18+ client libraries. This is a breaking change due to introduction of `context` on most of the API surface for creating resources and such. Istio is the main current feature that will require this upgrade to happen soon however Contour will need it too in order to update to the v1.5.0 client version.

### LINKED ISSUE #2360: Update operator & executor k8s libraries to 1.18 (or 1.19)
Separate from the task of making SC compatible with 1.18 clusters, we'll have to upgrade the operator libraries, this issue encompassing moving to the 1.18 libraries (or alternatively 1.19 as it's now released)

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
Update ks8 libs to 1.18 latest

**Which issue(s) this PR fixes**:

Fixes #1949 
Fixes #2360 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sun Sep  6 18:35:40 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=1

**Comment by seldondev** [comment]
Sun Sep  6 18:35:44 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=2

**Comment by seldondev** [comment]
Sun Sep  6 19:09:53 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=3

**Review by RafalSkolasinski — APPROVED** [review]
/lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2385#issuecomment-688777261 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-688777261/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by RafalSkolasinski** [comment]
@axsaucedo do you know maybe why this got stuck in the merge pool?

**Comment by axsaucedo** [comment]
@RafalSkolasinski it seems lint is still running
/test lint

**Comment by seldondev** [comment]
Wed Sep  9 12:15:36 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6829ac70bbf384e778bf9b964eacfdbe4e1ecebd | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@RafalSkolasinski @cliveseldon it seems lint is failing

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2385#issuecomment-688777261 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Sep 14 16:05:19 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=6

**Comment by seldondev** [comment]
Mon Sep 14 16:05:36 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=5

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | fab3bca42fa41bff54734911f856a04c48ceb005 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 14 16:41:10 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=8

**Comment by seldondev** [comment]
Mon Sep 14 16:41:13 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=7

**Comment by seldondev** [comment]
Mon Sep 14 21:06:33 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=9

**Comment by seldondev** [comment]
Tue Sep 15 06:33:44 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=10

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5230ecaa64263a5643d1cd02f11d6897a6d0ba65 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 15 06:57:25 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=11

**Comment by seldondev** [comment]
Tue Sep 15 06:57:34 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=12

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5230ecaa64263a5643d1cd02f11d6897a6d0ba65 | [link]() | `/test lint`
pr-build | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test this`
lint | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 16 18:03:21 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=13

**Comment by seldondev** [comment]
Wed Sep 16 18:03:31 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=14

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test this`
lint | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 17 07:18:43 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=15

**Comment by seldondev** [comment]
Thu Sep 17 07:18:46 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=16

**Comment by seldondev** [comment]
Thu Sep 17 07:19:43 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=17

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 8e113b06f5195984d2978764713316ddf5e82269 | [link]() | `/test lint`
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 17 07:33:17 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=18

**Comment by axsaucedo** [comment]
Oh wasn't aiming to run the `securitychecks` and `engine` - I've stopped those two pipelines so may show as failed but ignore.

**Comment by seldondev** [comment]
Thu Sep 17 18:14:08 UTC 2020
The logs for [notebooks] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=20

**Comment by seldondev** [comment]
Thu Sep 17 18:14:19 UTC 2020
The logs for [integration] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=22

**Comment by seldondev** [comment]
Thu Sep 17 18:14:20 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=19

**Comment by seldondev** [comment]
Thu Sep 17 18:14:28 UTC 2020
The logs for [lint] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=24

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`
lint | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test lint`
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test lint`
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`
notebooks | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 18 08:02:10 UTC 2020
The logs for [pr-build] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=25

**Comment by seldondev** [comment]
Fri Sep 18 08:02:21 UTC 2020
The logs for [lint] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=26

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`
notebooks | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test notebooks`
lint | cf625f85647abf877131372d009e9f48b6ca955f | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 18 08:20:56 UTC 2020
The logs for [pr-build] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=27

**Comment by seldondev** [comment]
Fri Sep 18 08:20:56 UTC 2020
The logs for [lint] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=28

**Comment by seldondev** [comment]
Fri Sep 18 08:31:51 UTC 2020
The logs for [pr-build] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=29

**Comment by seldondev** [comment]
Fri Sep 18 08:31:52 UTC 2020
The logs for [lint] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=30

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test integration`
notebooks | 4590c762e5ac18581c7dbbb8481481a9f07414c9 | [link]() | `/test notebooks`
lint | 5c064511b4b45549c9b933186acca8e2b2c1d297 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 21 08:18:54 UTC 2020
The logs for [pr-build] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=31

**Comment by seldondev** [comment]
Mon Sep 21 08:18:55 UTC 2020
The logs for [lint] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=32

**Comment by seldondev** [comment]
Mon Sep 21 09:14:15 UTC 2020
The logs for [lint] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=34

**Comment by seldondev** [comment]
Mon Sep 21 09:14:21 UTC 2020
The logs for [pr-build] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2385/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2385 --build=33

**Pull request merged**
