### PR TITLE
Decompress prediction events before logging to kafka topics

### LINKED ISSUE #4004: Submit kafka events uncompressed until consumers supports it
Related to https://github.com/SeldonIO/seldon-core/issues/3749 but for kafka events. We should for the produce kafka events without gzip compression - event if they come as such, e.g. from Triton server.

### PR DESCRIPTION
**Pull request by SachinVarghese**
**What this PR does / why we need it**:
Related to https://github.com/SeldonIO/seldon-core/issues/3749 but for kafka events. 

**Which issue(s) this PR fixes**:

Fixes #4004

**Special notes for your reviewer**:
We should for the produce kafka events without gzip compression - event if they come as such, e.g. from Triton server.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Nice one @SachinVarghese - LGTM

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/4005#issuecomment-1080939146 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
