### PR TITLE
WIP: read index from input file and write it back in the meta data part

### LINKED ISSUE #3409: Enable index filed in batch_processor
Background:
We have one model working with tabular data. In the request data, there is one field " user id" which is not used for model prediction.  We need it to be put back in the prediction results for pipeline next step processing.  

Feature request:
Enable pre-defined column data put back in the result in the output file.

Possible solutions:
1,  replace the current "batch_idx" in the output file with the content of pre-defined column data in the input file. or
2, add the pre-defined column data back to the output field.

### PR DESCRIPTION
**Pull request by yaliqin**
**What this PR does / why we need it**:
1,  read index from input file and write it back in the metadata part for easier results parse in post-processing pipeline step
2, keep the data as the original data type when converting it with ndarray after JSON load to allow multiple data types elements in one line in the input file

**Which issue(s) this PR fixes**:

Fixes #3409

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @yaliqin. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you very much @yaliqin ! We'll be able to have a look and add thoughts / provide updates 👍

**Comment by axsaucedo** [comment]
Closing as addressed via #3718

**Pull request closed without merging**
