### PR TITLE
add `--no-cache-dir` inside s2i wrappers

### LINKED ISSUE #2581: Pip cache removal in wrappers/s2i/python/s2i/bin/assemble
Hello,
While packaging python model wrapper into a docker image, I observed considerable difference in image sizes built using `s2i` and my own `Dockerfile` (s2i image is always larger)

One of the reasons for this is that, the image built using `s2i retains the pip cache` whereas I'm removing pip caches in the Dockerfile by using `pip install` with `--no-cache-dir` flag

I think the s2i based build can also produce smaller images if --no-cache-dir is added to the s2i assemble script ( [here](https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/s2i/bin/assemble#L63) and [here](https://github.com/SeldonIO/seldon-core/blob/master/wrappers/s2i/python/s2i/bin/assemble#L66) )

This would be particularly useful for models which have a lot of dependencies.

I built a local s2i python builder image which has the `--no-cache-dir` flag added in the pip install commands in the assemble script. Using this builder image, I have wrapped the [deep-mnist](https://github.com/SeldonIO/seldon-core/tree/master/examples/models/deep_mnist) model

I see savings of ~140MB

```shell
$ docker images | grep -e REPO -e tf-example-mnist
REPOSITORY                                                                       TAG                     IMAGE ID            CREATED             SIZE
seldonio/tf-example-mnist-local                                                  0.2                     491dc6c9684b        4 seconds ago       1.33GB
seldonio/tf-example-mnist                                                        0.2                     d1d9f7b229b7        2 minutes ago       1.47GB
```

Later, I tried adding `torch` (pytorch) which is ~750MB in size as a dependency in `requirements.txt` for testing even though this model does not use pytorch. 

Here, there's a savings of 880MB

```shell
$ docker images | grep -e REPO -e tf-example-mnist
REPOSITORY                                                                       TAG                     IMAGE ID            CREATED             SIZE
seldonio/tf-example-mnist-local                                                  0.2                     b4c7c0ebacd9        11 minutes ago      2.84GB
seldonio/tf-example-mnist                                                        0.2                     f56e02f0b1f3        13 minutes ago      3.72GB
```

### PR DESCRIPTION
**Pull request by M46F**
**What this PR does / why we need it**:
add `--no-cache-dir`  to remove pip cache

**Which issue(s) this PR fixes**:

Fixes #2581

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @M46F. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Great, thanks @M46F 
/ok-to-test
/test integration

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2725#issuecomment-736730393 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-736730393/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Dec  1 18:18:30 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2725/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2725 --build=1

**Comment by seldondev** [comment]
Tue Dec  1 18:18:36 UTC 2020
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2725/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2725 --build=2

**Comment by seldondev** [comment]
Tue Dec  1 18:18:40 UTC 2020
The logs for [lint] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2725/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2725 --build=3

**Comment by seldondev** [comment]
Tue Dec  1 20:11:53 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2725/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2725 --build=5

**Comment by seldondev** [comment]
Tue Dec  1 20:12:07 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2725/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2725 --build=4

**Pull request merged**
