### PR TITLE
Add pidfile config for gunicorn

### LINKED ISSUE #2546: Add pidfile config for gunicorn
Right now we are configuring auto reload for gunicorn, it seems useful to add a pidfile config for gunicorn, so we can refer the master process easily

### PR DESCRIPTION
**Pull request by anggao**
**What this PR does / why we need it**:

Right now we are configuring auto reload for gunicorn, it seems useful to add a pidfile config for gunicorn, so we can refer the master process easily

**Which issue(s) this PR fixes**:

Fixes #2546

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @anggao. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you for the contribution @anggao - very interesting! Could you add a line in the docs section here: https://docs.seldon.io/projects/seldon-core/en/latest/python/python_server.html#configuration

/ok-to-test

**Comment by anggao** [comment]
sure will do!

**Comment by seldondev** [comment]
Wed Oct 14 15:33:30 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=1

**Comment by seldondev** [comment]
Wed Oct 14 15:40:31 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=4

**Comment by seldondev** [comment]
Wed Oct 14 15:40:46 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=3

**Comment by seldondev** [comment]
@anggao: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 7d48c7f31529da327ad6a58bceb9e268afc2c75b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@anggao you'll have to run rebase and `make license` in the `python/` folder to ensure the `lint` checks pass

**Comment by anggao** [comment]
@axsaucedo Yeah I always forgot that :)

**Comment by seldondev** [comment]
@anggao: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 7d48c7f31529da327ad6a58bceb9e268afc2c75b | [link]() | `/test lint`
pr-build | 7d48c7f31529da327ad6a58bceb9e268afc2c75b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@anggao: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7d48c7f31529da327ad6a58bceb9e268afc2c75b | [link]() | `/test this`
lint | 3c84c6f0b7c445b78b6047513f98cf3f1dc20bb6 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Thanks! This is one we've been thinking of potentially adding to the github actions, so we coudl just run something like `/rebuild-license` to have this done in the background..

**Comment by seldondev** [comment]
Wed Oct 14 15:48:44 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=5

**Comment by seldondev** [comment]
Wed Oct 14 15:48:56 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=6

**Comment by seldondev** [comment]
Wed Oct 14 15:49:23 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=7

**Comment by seldondev** [comment]
Wed Oct 14 15:49:51 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=8

**Comment by anggao** [comment]
@axsaucedo that's would be great or add some git hooks to prevent commit works as well

**Comment by seldondev** [comment]
@anggao: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ab3a11c16bbae62bd26933ad661a79df05a41c3a | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Oct 14 16:03:45 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=9

**Comment by seldondev** [comment]
@anggao: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ab3a11c16bbae62bd26933ad661a79df05a41c3a | [link]() | `/test lint`
pr-build | ab3a11c16bbae62bd26933ad661a79df05a41c3a | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@anggao: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ab3a11c16bbae62bd26933ad661a79df05a41c3a | [link]() | `/test this`
lint | ab3a11c16bbae62bd26933ad661a79df05a41c3a | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Oct 14 16:16:06 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2547/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2547 --build=10

**Comment by anggao** [comment]
@axsaucedo let me check that

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2547#issuecomment-708528096 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-708528096/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
