### PR TITLE
Update other helm charts

### LINKED ISSUE #1879: Update SeldonDeployment Helm charts
## Context

We've got a few Helm charts under the [`helm-charts/`](https://github.com/SeldonIO/seldon-core/tree/master/helm-charts) folder whose aim is to simplify the creation / deployment of `SeldonDeployment` specs. Some of them, like [`seldon-single-model`](https://github.com/SeldonIO/seldon-core/tree/master/helm-charts/seldon-single-model) could be very useful to simplify the creation of a 
complex (but very standard) `SeldonDeployment` with a single inference node.

## Proposal

These Helm charts are currently a bit obscure. It would be good to bring them up to date (maybe even removing some of them) and document their usage. Moving forward, we could also recommend using Helm charts for your models as a good practice for config management.

### LINKED ISSUE #2072: Make the helm chart generator part of the release script
Make the helm chart generator part of the release script and update the versions ie https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/README.md

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Following the work started in #1906, this PR adds docs for the rest of the charts in `./helm-charts`. It also adds the charts docs generation to the release pipeline.   

**Which issue(s) this PR fixes**:

Fixes #1879
Fixes #2072 

**Special notes for your reviewer**:
This PR also builds a new version of `seldonio/core-builder` (`0.17`), including the `helm-docs` tool that we use to generate the charts docs.

**Does this PR introduce a user-facing change?**:

```release-note
Added documentation for all Helm charts.
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6fa02051e2d7836c4a2b1193d8ced674908b3c37 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep  7 15:39:43 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=1

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6fa02051e2d7836c4a2b1193d8ced674908b3c37 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6fa02051e2d7836c4a2b1193d8ced674908b3c37 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | dbf919b933a051eb1812ae4ae01c9b29bb9f6ad0 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep  8 08:32:09 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=5

**Comment by seldondev** [comment]
Tue Sep  8 08:33:46 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=7

**Comment by seldondev** [comment]
Tue Sep  8 08:34:42 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=8

**Comment by seldondev** [comment]
Tue Sep  8 08:36:40 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=9

**Comment by seldondev** [comment]
Tue Sep  8 08:36:43 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2396/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2396 --build=10

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dbf919b933a051eb1812ae4ae01c9b29bb9f6ad0 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Great stuff @adriangonz ! This will help a lot of people navigate the helm charts 
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2396#issuecomment-688776463 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-688776463/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
