### PR TITLE
[WIP] feat(dataflow): Add Prometheus JMX exporter Java agent

### PR DESCRIPTION
**Pull request by agrski**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
This is still a work in progress and should not be merged in its current form.  It's an early draft of the PR to enable collaboration around collecting JVM metrics.

### CODE REVIEW

**Comment by sakoush** [comment]
btw `chmod` requires buildkit

```
{
  "features": {
    "buildkit": true
  }
}
```

**Comment by agrski** [comment]
> btw `chmod` requires buildkit
> 
> ```
> {
>   "features": {
>     "buildkit": true
>   }
> }
> ```

Ah yes.  I have buildkit enabled by default, so tend to forget which bits require it vs. don't.

Any suggestions on ensuring this is clear to users and for CI?

**Comment by RafalSkolasinski** [comment]
> btw chmod requires buildkit

we can just have a simple `RUN chmod ...` step to not introduce requirement for buildkit if we do not want it.

**Comment by sakoush** [comment]
> > btw chmod requires buildkit
> 
> we can just have a simple `RUN chmod ...` step to not introduce requirement for buildkit if we do not want it.

actually for myself I can only set the permissions using `RUN chmod ...` maybe I have an outdated buildkit

**Pull request closed without merging**
