### PR TITLE
Fix Ambassador Weight Assignments

### LINKED ISSUE #1271: Ambassador 404s on Canary Test
Intermittent 404s for requests during a canary update to Ambassador.
Open issue on Ambassador https://github.com/datawire/ambassador/issues/2111

### PR DESCRIPTION
**Pull request by cliveseldon**
* Seems to also fix the 404s in rolling updates. run several hundred tests with zero failures locally.

Fixes #1271

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Dec 13 19:26:13 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=2

**Comment by seldondev** [comment]
Fri Dec 13 19:26:23 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=1

**Comment by seldondev** [comment]
Sat Dec 14 09:26:02 UTC 2019
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=3

**Comment by seldondev** [comment]
Sat Dec 14 09:26:07 UTC 2019
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=4

**Comment by seldondev** [comment]
Sat Dec 14 09:27:04 UTC 2019
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=5

**Comment by seldondev** [comment]
Sat Dec 14 09:27:12 UTC 2019
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=6

**Comment by seldondev** [comment]
Sat Dec 14 09:28:18 UTC 2019
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=7

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | fcc0873c4fd6dc97e4940e43a63ac6ce0575d6b1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sat Dec 14 10:22:49 UTC 2019
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1268/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1268 --build=8

**Comment by cliveseldon** [comment]
Closing as working on wider fix for this and hpas

**Pull request closed without merging**
