### PR TITLE
Update XGBoost

### LINKED ISSUE #1394: Support for Xgboost 0.9
Current release of Seldon [Xgboost server](https://docs.seldon.io/projects/seldon-core/en/latest/servers/xgboost.html#xgboost-server) supports XgBoost 0.82 release. Requesting support for [Xgboost 0.9](https://github.com/dmlc/xgboost/tree/v0.90) as it has several performance improvements.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1394 

## Changelog

- Update `xgboost` to 1.0.1 on `XGBOOST_SERVER`
- Build and push `0.3-SNAPSHOT` versions of `XGBOOST_SERVER` (and `MLFLOW_SERVER`)
- Use `0.3-SNAPSHOT` on `seldon-config` values so that they get tested during integration

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Feb 26 09:32:59 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=1

**Comment by seldondev** [comment]
Wed Feb 26 09:33:03 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=2

**Comment by adriangonz** [comment]
/cc @gsunner @RafalSkolasinski 
/test integration

@gsunner I've built a new `0.3-SNAPSHOT` version for the `MLFLOW_SERVER` (which was still on `0.2`) and `XGBOOST_SERVER` (including these changes). Are these taken into account as part of the release process? (i.e. will they get promoted to `0.3` and the version changed to `0.4-SNAPSHOT`?)

**Comment by seldondev** [comment]
Wed Feb 26 09:35:35 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=3

**Comment by adriangonz** [comment]
We can use `0.3` directly on the pre-packaged servers.

**Comment by seldondev** [comment]
Mon Mar  2 13:47:19 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=5

**Comment by seldondev** [comment]
Mon Mar  2 13:47:32 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=6

**Comment by seldondev** [comment]
Mon Mar  2 13:48:59 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=4

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1483#pullrequestreview-371063136" title="Approved">RafalSkolasinski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1483#issuecomment-596453222" title="Approved">RafalSkolasinski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1483#issuecomment-596570225" title="Approved">adriangonz</a>*, *<a href="https://github.com/SeldonIO/seldon-core/pull/1483#issuecomment-596453222" title="Approved">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Mar  9 14:37:20 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=7

**Comment by seldondev** [comment]
Mon Mar  9 14:37:24 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1483/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1483 --build=8

**Pull request merged**
