### PR TITLE
feat(examples/pachyderm-simple): Update and improve Pachyderm example

### PR DESCRIPTION
**Pull request by philwinder**
This PR updates and improves the current pachyderm integration demo. This demo highlights the use of Pachyderm's S3 gateway and how seldon-core deployments can read directly from a version-controlled model artefact.

More sophisticated demos will come next.

**What this PR does / why we need it**:
Update Pachyderm demo.

**Special notes for your reviewer**:
This demo requires a public docker image to be built and pushed to seldonio's docker hub (following on from how the previous demo worked).

Someone with access to seldonio's docker hub account needs to:

```sh
# login to docker hub then...
cd examples/pachyderm-simple/iris-train-python-svm/
make build
make push
```
This will push a new version of the already existing training image to here: https://hub.docker.com/r/seldonio/pachyderm-iris-trainer 

**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Dec 16 12:15:57 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2764/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2764 --build=2

**Comment by seldondev** [comment]
Wed Dec 16 12:15:58 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2764/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2764 --build=1

**Review by RafalSkolasinski — CHANGES_REQUESTED** [review]
Awesome work @philwinder!

Few comments, it would be good to:
- use `seldon` namespace for deployments to be consistent with most of the examples we have
- add one more `kubectl rollout status` before sending requests to updated deployment at the end of the notebook

I also noticed that the docs don't build, you may need to update path in https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/pachyderm.nblink
to be 
``` 
"path": "../../../examples/pachyderm-simple/index.ipynb"
```

It may be required to copy  images to `doc/source/examples` wherever required. 
You may build docs locally to test it by using
```
make livehtml
```
in the `doc` directory

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jan  5 14:38:17 UTC 2021
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2764/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2764 --build=4

**Comment by seldondev** [comment]
Tue Jan  5 14:38:29 UTC 2021
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2764/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2764 --build=3

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2764#pullrequestreview-561843030 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-754676110/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
