### PR TITLE
Import Java wrapper

### PR DESCRIPTION
**Pull request by adriangonz**
Related to #1344 

## Changelog
- Import Java wrapper from https://github.com/SeldonIO/seldon-java-wrapper
- Update `Makefile` and format code (as per our [guidelines](https://docs.seldon.io/projects/seldon-core/en/latest/developer/contributing.html#java))
- Update Spring and other dependencies

## Notes
This PR doesn't change any functionality over the Java wrapper (besides updating some of the dependencies). There are still a few more things to do so that it can "graduate" to a stable wrapper. These are discussed on #1344.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jan 29 14:10:29 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1382 --build=2

**Comment by seldondev** [comment]
Wed Jan 29 14:10:36 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1382 --build=1

**Comment by axsaucedo** [comment]
One step closer towards Java wrapper graduation! Looks good - basically a port of the wrapper, nice one with the gitignore adds. @cliveseldon anything you'd add or good to merge?

**Comment by axsaucedo** [comment]
There doesn't seem to be any destructive additions in this PR that could add any repercussions, so happy to land - @cliveseldon anything you would catch may be required before landing?

**Comment by axsaucedo** [comment]
Testing lint

/test lint

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1382#issuecomment-581392879" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Feb  3 12:34:13 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1382 --build=3

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c0c026e8e6b8765d54f1f004af5bd696507dac29 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Feb  3 14:42:02 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1382 --build=4

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c0c026e8e6b8765d54f1f004af5bd696507dac29 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems it failed to install Seldon Core 
image

**Comment by seldondev** [comment]
Tue Feb  4 11:57:42 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1382 --build=5

**Comment by adriangonz** [comment]
@axsaucedo it times out while waiting for the `istio-ingressgateway` pod to come up (related to #1402). We could probably change the CI scripts so that if it fails during `kind_setup` it just stops there and considers the build as failed.

https://github.com/SeldonIO/seldon-core/blob/f21fa8e8f16baef2455158eb67ae10c826c0f4ec/jenkins-x/logs/SeldonIO/seldon-core/PR-1382/4.log#L340-L344

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c0c026e8e6b8765d54f1f004af5bd696507dac29 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
@axsaucedo I've run the integration tests locally and they seem to pass, so the failure above was probably related to #1402

**Comment by axsaucedo** [comment]
Ok, thank you for the confirmation.
/approve
/lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1382#issuecomment-581987472" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
