### PR TITLE
Remove tf binary from args when creating image for tfserving

### LINKED ISSUE #2133: duplicate tensorflow_model_server command between entrypoint and args using prepackaged inference server
## Describe the bug

Hi team, thank you for your great work!

I've deployed prepackaged inference server in kubeflow.
It seems `tfserving` container execute duplicate `tensorflow_model_server` command.

```
tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=model --model_base_path=/models/model /usr/bin/tensorflow_model_server --port=2000 --rest_api_port=2001 --model_name=cifar10 --model_base_path=/mnt/models
```

## To reproduce

Deploy SeldonDeployment using following yaml file.

``` yaml
---
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: cifar10
  namespace: imokuri-app
spec:
  name: cifar10
  predictors:
  - graph:
      children: []
      implementation: TENSORFLOW_SERVER
      modelUri: s3://model
      envSecretRefName: minio-secret
      name: cifar10
      parameters:
        - name: signature_name
          type: STRING
          value: serving_default
        - name: model_name
          type: STRING
          value: cifar10
    name: cifar10
    replicas: 1
```

It looks running pod.

```
$ kubectl get all -n imokuri-app
NAME                                           READY   STATUS    RESTARTS   AGE
pod/cifar10-cifar10-1864198-6cfbbf49cc-f82bw   3/3     Running   0          28m

NAME                                                                TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)             AGE
service/cifar10-cifar10-cifar10                                     ClusterIP   10.0.165.139   <none>        8000/TCP,5001/TCP   28m
service/cifar10-cifar10-cifar10-seldonio-tfserving-proxy-rest-0-7   ClusterIP   10.0.28.160    <none>        9000/TCP            28m

NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/cifar10-cifar10-1864198   1/1     1            1           28m

NAME                                                 DESIRED   CURRENT   READY   AGE
replicaset.apps/cifar10-cifar10-1864198-6cfbbf49cc   1         1         1       28m
```

But there is `unknown argument: /usr/bin/tensorflow_model_server` error in `tfserving` container logs

```
$ kubectl logs pod/cifar10-cifar10-1864198-6cfbbf49cc-f82bw -n imokuri-app -c tfserving
unknown argument: /usr/bin/tensorflow_model_server
usage: tensorflow_model_server
Flags:
        --port=8500                             int32   Port to listen on for gRPC API
(omit)
```

I've noticed duplicate `tensorflow_model_server` command in `tfserving` container.

```
$ kubectl exec -it -n imokuri-app pod/cifar10-cifar10-1864198-6cfbbf49cc-f82bw -c tfserving bash
root@cifar10-cifar10-1864198-6cfbbf49cc-f82bw:/# ps -ef | grep tensorflow_model_server
root          1      0  0 06:48 ?        00:00:00 /bin/bash /usr/bin/tf_serving_entrypoint.sh /usr/bin/tensorflow_model_server --port=2000 --rest_api_port=2001 --model_name=cifar10 --model_base_path=/mnt/models
root          6      1  0 06:48 ?        00:00:00 tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=model --model_base_path=/models/model /usr/bin/tensorflow_model_server --port=2000 --rest_api_port=2001 --model_name=cifar10 --model_base_path=/mnt/models
root         49     39  0 07:22 pts/1    00:00:00 grep --color=auto tensorflow_model_server
root@cifar10-cifar10-1864198-6cfbbf49cc-f82bw:/#
```

Describe pod, set args as follows.

```
  tfserving:
    Container ID:  docker://547e5bd82c3c99af608bbf524d4be00f64ab77de6d35a3c286bbb0e6f51556ac
    Image:         tensorflow/serving:latest
    Image ID:      docker-pullable://tensorflow/serving@sha256:4a45f9bcaf96e71ef1b6d824e490562cc962ea66e1213ab06015a7da8054a53b
    Ports:         2000/TCP, 2001/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      /usr/bin/tensorflow_model_server
      --port=2000
      --rest_api_port=2001
      --model_name=cifar10
      --model_base_path=/mnt/models
```

## Expected behaviour

execute tensorflow_model_server only once.

## Environment

* Cloud Provider: Azure AKS
* Kubernetes Cluster Version [Output of `kubectl version`] 

```
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-beta.0", GitCommit:"e7f962ba86f4ce7033828210ca3556393c377bcc", GitTreeState:"clean", BuildDate:"2020-01-15T08:26:26Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.7", GitCommit:"5737fe2e0b8e92698351a853b0d07f9c39b96736", GitTreeState:"clean", BuildDate:"2020-06-24T19:54:11Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

* Deployed Seldon System Images: 

```
$ kubectl get --namespace kubeflow deploy seldon-controller-manager -o yaml  | grep seldonio
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"seldon","app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-1.15","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"1.15","control-plane":"seldon-controller-manager"},"name":"seldon-controller-manager","namespace":"kubeflow"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"seldon","app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-1.15","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"1.15","control-plane":"seldon-controller-manager"}},"template":{"metadata":{"annotations":{"prometheus.io/scrape":"true","sidecar.istio.io/inject":"false"},"labels":{"app":"seldon","app.kubernetes.io/component":"seldon","app.kubernetes.io/instance":"seldon-1.15","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"seldon-core-operator","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"1.15","control-plane":"seldon-controller-manager"}},"spec":{"containers":[{"args":["--enable-leader-election","--webhook-port=443",""],"command":["/manager"],"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"CONTROLLER_ID","value":""},{"name":"AMBASSADOR_ENABLED","value":"true"},{"name":"AMBASSADOR_SINGLE_NAMESPACE","value":"false"},{"name":"ENGINE_CONTAINER_IMAGE_AND_VERSION","value":"docker.io/seldonio/engine:1.0.1"},{"name":"ENGINE_CONTAINER_IMAGE_PULL_POLICY","value":"IfNotPresent"},{"name":"ENGINE_CONTAINER_SERVICE_ACCOUNT_NAME","value":"default"},{"name":"ENGINE_CONTAINER_USER","value":"8888"},{"name":"ENGINE_LOG_MESSAGES_EXTERNALLY","value":"false"},{"name":"PREDICTIVE_UNIT_SERVICE_PORT","value":"9000"},{"name":"ENGINE_SERVER_GRPC_PORT","value":"5001"},{"name":"ENGINE_SERVER_PORT","value":"8000"},{"name":"ENGINE_PROMETHEUS_PATH","value":"prometheus"},{"name":"ISTIO_ENABLED","value":"true"},{"name":"ISTIO_GATEWAY","value":"kubeflow-gateway"},{"name":"ISTIO_TLS_MODE","value":""}],"image":"docker.io/seldonio/seldon-core-operator:1.0.1","imagePullPolicy":"IfNotPresent","name":"manager","ports":[{"containerPort":443,"name":"webhook-server","protocol":"TCP"},{"containerPort":8080,"name":"metrics","protocol":"TCP"}],"resources":{"limits":{"cpu":"100m","memory":"30Mi"},"requests":{"cpu":"100m","memory":"20Mi"}},"volumeMounts":[{"mountPath":"/tmp/k8s-webhook-server/serving-certs","name":"cert","readOnly":true}]}],"serviceAccountName":"seldon-manager","terminationGracePeriodSeconds":10,"volumes":[{"name":"cert","secret":{"defaultMode":420,"secretName":"seldon-webhook-server-cert"}}]}}}}
          value: docker.io/seldonio/engine:1.0.1
        image: docker.io/seldonio/seldon-core-operator:1.0.1
```

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
Fixes suprious tf serving binary in args for tfserving image. Not needed as it has binary as default entrypoint.

**Which issue(s) this PR fixes**:

Fixes #2133 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Aug 28 15:08:54 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=1

**Comment by seldondev** [comment]
Fri Aug 28 15:08:59 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=2

**Comment by axsaucedo** [comment]
Nice! This will get rid of the annoying error message on startup
/test integration
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2343#issuecomment-684509083 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-684509083/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Sep  1 07:21:38 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=3

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems the CI may be having problems, 30 tests failed but doesn't seem it could be from currnet PR - re-triggering tests to re-test before diving into it further
/test integration
/hold

**Comment by seldondev** [comment]
Tue Sep  1 12:22:10 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  2 07:25:42 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=5

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  2 13:30:18 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=6

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep  3 07:30:08 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=7

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems like there is quite a lot of failures in integration test (errors look consistent), may require rebase if it passed locally

**Comment by seldondev** [comment]
Wed Sep 16 18:06:37 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=8

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 17 18:22:52 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=9

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ca612fe95bbbbb127d3d217ca300e327377612b0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 17 19:32:27 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2343/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2343 --build=10

**Pull request merged**
