### PR TITLE
pvc tfjob example

### PR DESCRIPTION
**Pull request by ryandawsonuk**
This captures the steps I used [to run this before](https://github.com/SeldonIO/seldon-core/issues/1106#issuecomment-558225067). Works on GKE

On DigitalOcean initially had trouble creating the PVC but got past that [after they increased volume limit ](https://www.digitalocean.com/community/questions/max-amount-of-volume-block-storage-volumes). Then hit problems running the TFJob (even though the same commands work on GKE):

```
  Warning  FailedAttachVolume  4m41s                attachdetach-controller       Multi-Attach error for volume "pvc-edbb5cee-5c9a-4028-8029-9f9931cd6a57" Volume is already used by pod(s) tfjob-021-worker-0, tfjob-021-ps-0
  Warning  FailedMount         25s (x2 over 2m43s)  kubelet, pool-vhdvdk83b-5dh2  Unable to mount volumes for pod "tfjob-021-chief-0_kubeflow(71a71629-9408-477d-acef-6efecc7ad490)": timeout expired waiting for volumes to attach or mount for pod "kubeflow"/"tfjob-021-chief-0". list of unmounted volumes=[local-storage]. list of unattached volumes=[local-storage default-token-vqvnb]
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Dec 30 10:24:20 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=1

**Comment by seldondev** [comment]
Mon Dec 30 10:24:26 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=2

**Comment by ryandawsonuk** [comment]
Got it working on DigitalOcean by switching to a non-distributed job.

**Comment by seldondev** [comment]
Mon Dec 30 15:22:27 UTC 2019
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=3

**Comment by seldondev** [comment]
Mon Dec 30 15:22:33 UTC 2019
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=4

**Comment by seldondev** [comment]
Mon Dec 30 17:07:36 UTC 2019
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=5

**Comment by seldondev** [comment]
Mon Dec 30 17:07:54 UTC 2019
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=6

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1308#issuecomment-570531626" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan  3 10:29:01 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=8

**Comment by seldondev** [comment]
Fri Jan  3 10:29:03 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1308/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1308 --build=7

**Pull request merged**
