### PR TITLE
Updated setup.py to work with security CI 

### LINKED ISSUE #2065: Ensure all model servers have pinned requirements and the full requirements.txt is included in the docs
Currently the requirements on the sklearn model server are not pinned down, resulting in un-predictable "latest" versions for the dependencies available. We'll need to pin down these versions and ensure that all the dependencies are explicitly provided in the documentation. It may be worth adding a mention in the prepackaged server pages linking to the custom server doc page to specify that the image can be overriden with custom images with specific dependencies as required.  Relevant to #2012.

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #2065 

### Context

* Moving to setup.py broke the CI script
* After investigation it was the `open("local/path/file")` that was breaking snyk
* This relative path was removed and updated release.py

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Sep  8 10:19:55 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2398/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2398 --build=2

**Comment by seldondev** [comment]
Tue Sep  8 10:20:02 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2398/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2398 --build=1

**Comment by seldondev** [comment]
Tue Sep  8 10:20:23 UTC 2020
The logs for [securitychecks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2398/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2398 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
securitychecks | 0d7ec76aec0726712e04db28a56db9a8854b055c | [link]() | `/test securitychecks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Perfect, @adriangonz it seems it now has failed for the right reason (the pyyaml security check), so all working with python now, should be good to go!

**Comment by seldondev** [comment]
Tue Sep  8 11:49:48 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2398/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2398 --build=4

**Comment by seldondev** [comment]
Tue Sep  8 11:49:56 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2398/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2398 --build=5

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2398#issuecomment-688832265 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-688832265/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
