### PR TITLE
feat(defaults): Add default resources to engine/executor container

### LINKED ISSUE #2475: Explicitly define default requests and limits for engine container
## Describe the bug

The controller only defines a default [CPU Request](https://github.com/SeldonIO/seldon-core/blob/master/operator/controllers/seldondeployment_engine.go#L371-L378) currently, with custom specification of resources on the engine available through the `svcOrch` specification.  As we tighten up our underlying K8s installation with [OPA](https://www.openpolicyagent.org/docs/latest/) policies (specifically a policy requiring both requests and limits for CPU and memory be set), `SeldonDeployments` without engine resources defined in the `svcOrch` spec fail to deploy.

## To reproduce

1. Deploy any SeldonDeployment with `svcOrch` resources specified in a cluster with an OPA policy requiring that containers have resources defined.

## Expected behaviour

The default installation can come up without being blocked by OPA.

## Environment

K8s installation with OPA policies enabled (specifically requiring requests/limits).

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

### PR DESCRIPTION
**Pull request by groszewn**
Defines default requests and limits on the engine/executor container.

Contributes to #2475

Signed-off-by: Nick Groszewski <groszewn@gmail.com>

**What this PR does / why we need it**:

Addition of default engine/executor container resources, which helps in clusters with OPA policies defined to require requests and limits be set.

**Which issue(s) this PR fixes**:

Fixes #2475 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Added default resources to engine/executor container
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @groszewn. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cliveseldon** [comment]
@groszewn I'm just wondering if we should be more conservative on the CPU as a value of 1 implies continuous usage in a cluster. Given we are not serverless I am wondering if this could cause issues to existing users that have over-commits for their cluster?

**Comment by groszewn** [comment]
@cliveseldon I think that's a very valid concern.  Would it make sense for this value to be configurable via the helm chart install so that cluster admins can specify what meets their needs best and have a lower default (maybe 0.5 or lower)?

**Comment by cliveseldon** [comment]
@groszewn Yes I think that makes sense
Adding things to the helm chart values that appear as env vars is a bit fiddly at present.
You need to 

  1. add the envvar to manager kustomize yaml
  1. modify https://github.com/SeldonIO/seldon-core/blob/490651c9c088010ec563b9097510cde17e3ecbaf/operator/helm/split_resources.py#L33-L59 to add new mapping
  1. regenerate the helm chart templates with https://github.com/SeldonIO/seldon-core/blob/490651c9c088010ec563b9097510cde17e3ecbaf/operator/helm/Makefile#L6
  1. add new var to values.yaml for operator helm chart
  1. modify operator code to use envvar

**Comment by groszewn** [comment]
@cliveseldon updated to make the default resources configurable via the helm chart install.

**Comment by seldondev** [comment]
Mon Oct  5 12:49:33 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=1

**Comment by seldondev** [comment]
Mon Oct  5 12:49:35 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=2

**Comment by groszewn** [comment]
@cliveseldon do the test need to be rekicked?

**Comment by seldondev** [comment]
Tue Oct  6 13:09:43 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=3

**Comment by seldondev** [comment]
Wed Oct  7 12:34:13 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=4

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 98c4d11d495052a404fe145dd609883b2165454d | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Oct  9 13:06:16 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=5

**Comment by seldondev** [comment]
Fri Oct  9 13:06:50 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=6

**Comment by groszewn** [comment]
@cliveseldon seems like the `lint` stage is hanging.  Does this need to be kicked in some way?

**Comment by seldondev** [comment]
Tue Oct 13 16:53:56 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=7

**Comment by groszewn** [comment]
@axsaucedo looks like PR checks have passed, do you need to kick the longer-running tests (I'm not sure if I have this capability and don't want to overstep and strain the build system).

**Comment by seldondev** [comment]
Thu Oct 15 14:26:10 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=9

**Comment by seldondev** [comment]
Thu Oct 15 14:26:19 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2514/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2514 --build=8

**Comment by axsaucedo** [comment]
Thank you @groszewn !

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2514#issuecomment-709412247 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-709412247/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
