### PR TITLE
Address ambassador deprecation warnings

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/1928.

To Do:
- [x] update ambassador installation in testing scripts
- [x] update docs

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rafalskolasinski**

If they are not already assigned, you can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jul  3 14:00:07 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=2

**Comment by seldondev** [comment]
Fri Jul  3 14:00:20 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=3

**Comment by seldondev** [comment]
Fri Jul  3 14:00:22 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=1

**Comment by seldondev** [comment]
Fri Jul  3 14:49:21 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=5

**Comment by seldondev** [comment]
Fri Jul  3 14:49:34 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 35b76c16f08fb228a58d823ba90f0330de9b45a6 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jul  3 15:13:36 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=6

**Comment by seldondev** [comment]
Mon Jul  6 09:27:04 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=7

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 35b76c16f08fb228a58d823ba90f0330de9b45a6 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 10:09:27 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=9

**Comment by seldondev** [comment]
Mon Jul  6 10:09:29 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=8

**Comment by seldondev** [comment]
Mon Jul  6 10:11:01 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=10

**Comment by axsaucedo** [comment]
Looks good! Let's merge as soon as integration tests pass 👍

**Comment by seldondev** [comment]
Tue Jul  7 08:23:42 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=11

**Comment by RafalSkolasinski** [comment]
Failure on ` test_rolling_deployment[graph1.json-graph4.json-True-ambas]`.

**Comment by seldondev** [comment]
Tue Jul  7 15:00:10 UTC 2020
The logs for [integration] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2069/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2069 --build=12

**Comment by axsaucedo** [comment]
All tests pass 👍 
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2069#issuecomment-655009301 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-655009301/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
