### PR TITLE
Add UTF-8 support for Flask jsonify

### LINKED ISSUE #4261: response from Seldon-core unable to show Unicode charaters
## Describe the bug

We use _seldon-core-microservice_ to run our own Python translation model. The return value of the _predict_  method of our customer python model class wrapper is type  of `numpy.ndarray` which is converted from a `List` of `Dict`.

```python
class MyTranslationModel:
    ...

    def predict(self, X, features_names=None, meta=None) -> np.array:
      ...
      # translated_result is a Python List which looks like this: [{"translated_text":"कैसे"}]
      return np.array(translated_result)
```

It is normal when we  **directly** call the `predict` method. if we print the returned value, it will look like this:
```python
>>> print(MyTranslationModel.predict(X=...))
>>> [{'translated_text':'कैसे'}]
```

But when we use _seldon-core-microservice_ to run our model as a service, we always get the response from  Seldon-core only showing the **raw Unicode code** instead of the characters.
The response looks like this:
```json
{
   "data":{
      "names":[],
      "ndarray":[{"translated_text":"\u0915\u0948\u0938\u0947"}]
   },
   "meta":{}
}

```

## To reproduce

1. Use any Python Model Class Wrapper as long as the return of the `predict` method contains Unicode characters.
2. Then use _seldon-core-microservice_ to run the model (at a local machine or inside a Docker container).
3. Try to send a prediction request to the service and check the response.
## Expected behaviour

We expect the response from the model service can show the characters instead of the raw Unicode code.

## Environment

(seems to be) environment independent.
(This issue has nothing to do with the _seldon deployment_ part.)

## Model Details 
See the description above.

### PR DESCRIPTION
**Pull request by caozhuozi**
**What this PR does / why we need it**:

Make Flask jsonify encoding configurable, that is, add UTF-8 support for Flask jsonify

**Which issue(s) this PR fixes**:

Fixes #4261

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @caozhuozi. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jklaise**
You can assign the PR to them by writing `/assign @jklaise` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you for the contribution @caozhuozi 👍 

/test integration

**Comment by seldondev** [comment]
@caozhuozi: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1097de1c693ffcb9ce9f83b4e022f9acdc2142e9 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4271-integration-sfpdk) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
NIce one - thank you for the contribution @caozhuozi !

**Pull request merged**
