### PR TITLE
Fix tensorflow prediction from explainer

### LINKED ISSUE #2664: Explainer wrapper should not add model to path for Tensorflow protocol
The issue is the model name may not equal the model name loaded by tenorflow serving which is based on the name of the graph element. Explanations are at a predictor level so should just call predict and not focus on any particular model.

https://github.com/SeldonIO/seldon-core/blob/f48d5b32b59d384a8f4203aad99c9b423be8c411/components/alibi-explain-server/alibiexplainer/explainer.py#L46

Should remove `{1}`

This is ok as we don't share this wrapper with KFServing.

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
 * Fixes the calling of a tensorflow model via seldon for the explainer wrapper

**Which issue(s) this PR fixes**:

Fixes #2664 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Nov 19 14:45:54 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=1

**Comment by seldondev** [comment]
Thu Nov 19 14:46:17 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=2

**Comment by seldondev** [comment]
Thu Nov 19 15:30:29 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=3

**Review by SachinVarghese — COMMENTED** [review]
/lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2671#issuecomment-730616543 "Approved")*, *[SachinVarghese](https://github.com/SeldonIO/seldon-core/pull/2671#pullrequestreview-534613985 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-730616543/SeldonIO/seldon-core/blob/master/OWNERS)~~ [SachinVarghese,axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Seems notebooks test is again stuck on tracing test:
```
release "seldon-core-analytics" uninstalled
FAILED
test_notebooks.py::TestNotebooks::test_tracing [NbConvertApp] Converting notebook ../../examples/models/tracing/tracing.ipynb to script
[NbConvertApp] Writing 4792 bytes to ../../examples/models/tracing/tracing.py
```
Stopping manually and re-running. also opening an issue as it seems this is happening a few times.
/test notebooks

**Comment by seldondev** [comment]
Thu Nov 19 21:07:39 UTC 2020
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=4

**Comment by seldondev** [comment]
Fri Nov 20 09:39:09 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=5

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2671#issuecomment-730616543 "Approved")*, *[SachinVarghese](https://github.com/SeldonIO/seldon-core/pull/2671#pullrequestreview-534613985 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [SachinVarghese,axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Nov 20 10:15:39 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=7

**Comment by seldondev** [comment]
Fri Nov 20 10:15:37 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=6

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 386dcce56e6dea9394d52d97dfe2f774c8aa94e4 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Nov 20 10:35:13 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=8

**Comment by seldondev** [comment]
Fri Nov 20 10:35:21 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=9

**Comment by seldondev** [comment]
Fri Nov 20 10:45:25 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2671/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2671 --build=10

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | a696a4287c8f37a612dd3a8f7b0f8294c0b050e7 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Merging as notebook failures are no to do with this PR.

**Pull request merged**
