### PR TITLE
Remove cloud storage from Python package

### LINKED ISSUE #1371: azure-storage-blob package update to 12.1.0
the latest azure-storage-blob is 12.1.0, Seldon is using `azure-storage-blob >= 2.0.1, < 3.0.0`, which is the legacy version. It will be great to update to the latest package.

### LINKED ISSUE #2140: Remove storage.py from python module

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Removes cloud storage integrations (e.g. S3, GCS, Azure) from the `seldon_core` Python package. The current implementation interacts with these services through a separate image coming from the KFServing project, so they are not needed in the `seldon_core` package anymore.

In particular, whenever we need to fetch something remotely (e.g. setting `modelUri: s3://...` in `SeldonDeployment` resources), this separate image will do that through an init container. After that's downloaded, the only thing that the `seldon_core` wrapper will need to do is copy these resources into a local path. 

This PR also removes the `requirements.txt` file so that `setup.py` is now the single source-of-truth for dependencies. Note that we still have a `requirements-dev.txt` file there, to list dependencies for testing, linting, etc. 

**Which issue(s) this PR fixes**:

Fixes #2140 
Fixes #1371 

**Special notes for your reviewer**:
I've still kept the `storage.py` file and the same `Storage.download()` interface to avoid changing the different places where we call `Storage.download()`. **However**, it will now only support the  `_download_local()` method, which is the one copying over the files to a local path. 

**Does this PR introduce a user-facing change?**:

```release-note
Remove S3, GCS and Azure logic from the `seldon_core.storage.Storage` class included in the Python package as this interaction now happens outside of the Python wrapper. 
```

### CODE REVIEW

**Comment by seldondev** [comment]
Mon Aug 24 07:59:54 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2310/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2310 --build=13

**Comment by axsaucedo** [comment]
@adriangonz looks good in general, although I just noticed that the storage.py dependency wasn't removed from the prepackaged models (not sure how it's passing the integration tests) - may be worth ensuring that the prepackaged servers no longer depend on the storage.py library.

Another thing that would be important is to add an entry on the UPGRADING.md about the breaking change (in case anyone is using the storagepy) and perhaps the alternative of installing the kfserving component (unless there is an alternative we want to explore)

**Comment by adriangonz** [comment]
@axsaucedo that's described above. I've kept the same `storage.py` interface to keep compatibility with everything else that was using it. The only difference is that it will now only support "local downloads" (which are just copies).

**Comment by axsaucedo** [comment]
Thanks for confirming - makes sense, good shout.
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[anggao](https://github.com/SeldonIO/seldon-core/pull/2310#pullrequestreview-472637426 "Approved")*, *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2310#issuecomment-679211705 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-679211705/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Aug 24 15:57:38 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2310/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2310 --build=15

**Comment by seldondev** [comment]
Mon Aug 24 15:58:11 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2310/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2310 --build=14

**Pull request merged**
