### PR TITLE
Bring back integration tests for Java engine

### LINKED ISSUE #1878: Add back Java engine's integration tests
After the introduction of the `executor`, the integration tests are now running just against the Go executor. It would be good to be able to also run them using the Java engine.

This could be ran on a separate `/test integration-engine` Prow command, so that we only run them manually on certain PRs which include changes to the Java engine (e.g. maintenance or `dependabot` updates).

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1878 

## Changelog
- Created `e2e_utils` package to hold all utilities for the integration tests 
- Disable executor depending on environment variable
- Add new Jenkins X config for engine tests

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue May 26 15:43:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=1

**Comment by seldondev** [comment]
Tue May 26 15:43:53 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=2

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue May 26 16:01:19 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=3

**Comment by seldondev** [comment]
Tue May 26 16:01:19 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=4

**Comment by seldondev** [comment]
Tue May 26 16:05:29 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=7

**Comment by seldondev** [comment]
Tue May 26 16:05:42 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=6

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | 7051087623b6d942b5bfb66aa893ed638fcbc285 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue May 26 16:08:24 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=9

**Comment by seldondev** [comment]
Tue May 26 16:10:05 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=10

**Comment by seldondev** [comment]
Tue May 26 16:10:42 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=11

**Comment by seldondev** [comment]
Tue May 26 16:11:08 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=12

**Comment by seldondev** [comment]
Tue May 26 16:12:30 UTC 2020
The logs for [engine] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=13

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | f429307ba72818bfee75c70965acf8475e9cf151 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed May 27 08:37:24 UTC 2020
The logs for [engine] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=14

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | f429307ba72818bfee75c70965acf8475e9cf151 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed May 27 15:37:21 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=15

**Comment by seldondev** [comment]
Wed May 27 15:37:28 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=16

**Comment by seldondev** [comment]
Thu May 28 08:43:04 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=17

**Comment by seldondev** [comment]
Thu May 28 08:44:44 UTC 2020
The logs for [engine] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=19

**Comment by seldondev** [comment]
Thu May 28 08:44:45 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=18

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | ad621b59b0021ca90a762a9445ad00c9cb01d0fc | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri May 29 10:52:29 UTC 2020
The logs for [engine] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=20

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | ad621b59b0021ca90a762a9445ad00c9cb01d0fc | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri May 29 13:40:01 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=21

**Comment by seldondev** [comment]
Fri May 29 13:40:09 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=22

**Comment by seldondev** [comment]
Fri May 29 13:50:51 UTC 2020
The logs for [engine] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=23

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | ae75fed2b289ec6677d81346ea740b3b160c35a4 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri May 29 17:14:03 UTC 2020
The logs for [engine] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=24

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | ae75fed2b289ec6677d81346ea740b3b160c35a4 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun  1 10:14:26 UTC 2020
The logs for [engine] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=25

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | ae75fed2b289ec6677d81346ea740b3b160c35a4 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun  1 16:04:21 UTC 2020
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=27

**Comment by seldondev** [comment]
Mon Jun  1 16:04:22 UTC 2020
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=26

**Comment by seldondev** [comment]
Mon Jun  1 16:07:18 UTC 2020
The logs for [engine] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=28

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | 0ac81d885fc5a3525a9b71e20280e7f8886a9153 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun  2 08:24:07 UTC 2020
The logs for [engine] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=29

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | 0ac81d885fc5a3525a9b71e20280e7f8886a9153 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Jun  3 15:37:11 UTC 2020
The logs for [engine] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=30

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration-engine | af6807d7d3d448bad7aa9d9d9e404c86278ff425 | [link]() | `/test integration-engine`
engine | 0ac81d885fc5a3525a9b71e20280e7f8886a9153 | [link]() | `/test engine`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jun  4 09:58:00 UTC 2020
The logs for [pr-build] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=31

**Comment by seldondev** [comment]
Thu Jun  4 09:58:09 UTC 2020
The logs for [lint] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=32

**Comment by seldondev** [comment]
Thu Jun  4 10:00:20 UTC 2020
The logs for [engine] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=33

**Comment by RafalSkolasinski** [comment]
Nice one!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1882#issuecomment-642736535" title="Approved">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jun 11 15:30:10 UTC 2020
The logs for [pr-build] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=34

**Comment by seldondev** [comment]
Thu Jun 11 15:30:20 UTC 2020
The logs for [lint] [35] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1882/35.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1882 --build=35

**Pull request merged**
