### PR TITLE
Executor/deps update

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
DO NOT MERGE!

this is just to experiment on executor dependency updates and try to generated scaled-down go.sum

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jul  7 12:29:34 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=2

**Comment by seldondev** [comment]
Tue Jul  7 12:29:53 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=1

**Comment by seldondev** [comment]
Tue Jul  7 12:30:15 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=3

**Comment by seldondev** [comment]
Tue Jul  7 12:30:34 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=4

**Comment by seldondev** [comment]
Tue Jul  7 16:55:12 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=6

**Comment by seldondev** [comment]
Tue Jul  7 16:55:14 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=5

**Comment by seldondev** [comment]
Tue Jul  7 17:03:47 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=7

**Comment by seldondev** [comment]
Tue Jul  7 17:03:49 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=8

**Comment by seldondev** [comment]
Tue Jul  7 17:33:54 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=10

**Comment by seldondev** [comment]
Tue Jul  7 17:34:12 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=9

**Comment by seldondev** [comment]
Tue Jul  7 18:24:57 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=11

**Comment by seldondev** [comment]
Tue Jul  7 18:24:57 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2083/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2083 --build=12

**Comment by axsaucedo** [comment]
@RafalSkolasinski given the rest of the PRs have gone in, should we close this one?

**Comment by RafalSkolasinski** [comment]
Totally

**Pull request closed without merging**
