### PR TITLE
Add more deps to cover whitebox TreeShap explainers

### LINKED ISSUE #2812: Alibi whitebox explainers unsupported due to missing dependencies in the Alibi explain server
## Describe the bug
First raised here: https://github.com/SeldonIO/alibi/issues/332

When attempting to serve a whitebox Alibi explainer (e.g. a TreeSHAP explainer on a LightGBM model), the Alibi explain server cannot load the serialized explainer as it contains the whitebox predictor for which the server does not have the required depencencies.

## To reproduce
Try loading a serialized TreeSHAP explainer with a LightGBM model embedded in the Alibi explain server: [ExplainerTicket.zip](https://github.com/SeldonIO/seldon-core/files/5769430/ExplainerTicket.zip)

## Expected behaviour
Alibi explain server succeeds in loading the serialized explainer which has a whitebox LightGBM model instance inside it.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Add `catboost` and `lightgbm` as extra dependencies of the image. The overall size doesn't increase by that much (around 200MBs).

This PR also includes some changes that make the overall image a bit smaller than before. 

**Which issue(s) this PR fixes**:

Fixes #2812

**Special notes for your reviewer**:

Note that this PR doesn't fully address the issue. As `alibi` evolves, the list of dependencies would need to keep growing. However, it's a simple enough short-term workaround which includes the most common GBT frameworks. 

On the longer term, we are exploring a better solution from the MLServer side (https://github.com/SeldonIO/MLServer/pull/123) which would allow users to specify custom environments on their explainers. This could be leveraged to match the training and production environments up to the exact library version.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jklaise** [comment]
/approve

LGTM. Agree with being more flexible in the future, even with different versions of the same libraries that users may want to specify instead.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[jklaise](https://github.com/SeldonIO/seldon-core/pull/2935#issuecomment-775301878 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-775301878/SeldonIO/seldon-core/blob/master/OWNERS)~~ [jklaise]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
