### PR TITLE
Don't specify version in Tox

### LINKED ISSUE #1247: Tox tests fail if py37 is not present
`tox` is configured to run the tests on a `py37` environment. However, if Python 3.7 is not present the tests fail. 

https://github.com/SeldonIO/seldon-core/blob/1ae79570dfd9307902ec0784cae6943eb31d3250/python/setup.cfg#L6

It seems that `tox` doesn't do anything besides checking if there is a `python3.7` interpreter present. We should either change `tox`'s config to run the tests on whatever environment is present or add some way for `tox` to fetch the relevant versions if they are not present.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1247 

## Changelog
- Run `tox` with whatever Python version is present

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Feb 13 10:35:23 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1433/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1433 --build=1

**Comment by seldondev** [comment]
Thu Feb 13 10:35:30 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1433/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1433 --build=2

**Comment by adriangonz** [comment]
/cc @cliveseldon @RafalSkolasinski 

@cliveseldon this should fix the Python tests whenever `py37` is not present (e.g. because `py36` is installed). 

@RafalSkolasinski to run the tests across multiple versions we could add more versions to the `envlist` in the `setup.cfg` file and then install them as well on the `seldonio/python-builder` image. We could explore this for #1357.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1433#issuecomment-585678886" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
