### PR TITLE
Tls istio ingress example

### PR DESCRIPTION
**Pull request by omerfsen**
**What this PR does / why we need it**:

Add Istio SSL/TLS Ingres examples.

**Which issue(s) this PR fixes**:

It does not fix anything but adds a new  feature

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @omerfsen. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by os-virtualretail** [comment]
I can add it a reference but it can be there only for example so someone that picks that can use it. Because sometimes a seperate file would be useful as a seperate yaml file instead of embedding it on the document ( md file).

**Comment by omerfsen** [comment]
I can add it a reference but it can be there only for example so someone that picks that can use it. Because sometimes a seperate file would be useful as a seperate yaml file instead of embedding it on the document ( md file).

**Comment by ryandawsonuk** [comment]
Also just occurred to me that maybe we should that this is one way and an alternative way to manage the secret is with [cert-manager](https://istio.io/latest/docs/ops/integrations/certmanager/)

**Comment by omerfsen** [comment]
Cert manager is adding to much complexity for a simple setup. I could write one but it requires more commands and for this it would be simply too much overhead.

My suggestion would be to implement it afterwards with its own PR. I can gladly work after this one merged.

**Comment by ryandawsonuk** [comment]
Yeah I don't mean to include a cert-manager example. I was just thinking we could mention that it's an alternative. So instead of saying `To create self-signed certificate` we could say `Assuming we're not using [cert-manager](https://istio.io/latest/docs/ops/integrations/certmanager/) then create self-signed certificate with`

**Comment by omerfsen** [comment]
Ok got it. Made your requested change just now

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ryandawsonuk](https://github.com/SeldonIO/seldon-core/pull/2255#pullrequestreview-464182768 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Aug 10 13:33:16 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2255/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2255 --build=1

**Comment by seldondev** [comment]
Mon Aug 10 13:33:17 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2255/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2255 --build=2

**Comment by seldondev** [comment]
@omerfsen: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | f17715edd1b8ebcaf8d79edc7f12421c895be5ac | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Aug 10 14:04:07 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2255/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2255 --build=3

**Comment by seldondev** [comment]
@omerfsen: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | f17715edd1b8ebcaf8d79edc7f12421c895be5ac | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Aug 10 14:39:02 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2255/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2255 --build=4

**Pull request merged**
