### PR TITLE
WIP: Seldon Core Async "Batch" Processing with Long Running Capability

### PR DESCRIPTION
**Pull request by axsaucedo**
# Overview

This PR contains an implementation that addresses #1413 by extending functionality of the Seldon Deployment which enables the following requirements from #1413 :
* 1.1. Non-long running batch jobs
* 1.1. Long running batch jobs
* 2.1. Jobs that are asynchronous, defined as being able to pull resources from a data source and push resources to another data source when it's done

# Not addressed in PR
The requirements that are not addressed by this PR are:
* 2.2 Jobs that only run to process the data and terminate when the finite dataset has been processed
* 2.3 Jobs that encompass [2.2] and can be triggered on a schedule

The step-by-step example on how to deploy a model: https://github.com/SeldonIO/seldon-core/blob/ad506d2ec6cffe32abd007fdfce2299e280aed6b/examples/streaming/async_stream_processing/README.md

## Implementation 
This implementation is build to enable a Seldon Python Container to have long running jobs, multiple which can be handled in parallel by multiple workers, and with the ability to connect to an external kafka queue. The architectural diagram is as follows:
image

Given that this implementation is Async, the requester must ensure they are able to match the initially sent request with the current sent request. For this, we will require per-request-metadata (as defined in our terminology overview of metadata in #1362) to be provided with a unique REQUESTER ID, which the requester will then be able to find in the resulting output metadata.

# Key points to discuss 
* One of the bigger challenges of introducing batch processing into Seldon Deployment capabilities is not as much the technical implementation, but the management infrastructure that will be required above - tracking async job errors, notifying on job termination/commencement, etc. This is an overhead that we should evaluate and scope out before going ahead with the technical implementation itself.
* Given that the Kafka worker is started as a server, we face the issue that the HEALTH and STATUS endpoints are not available (as per #1387) - however this could be addressed without much complexity by separating these 3 endpoints, and creating them as a separate flask API leveraging the multiprocessing library, which woudl ensure that both the KAFKA and GRPC implementations also expose the REST APIs for HEALTH and STATUS (and also the new METADATA) endpoints that are expected. [*EDIT:* it seems that there may be a solution for this which is being discussed in #1362]

Current problems:
* The library that was chosen for the Python service is [Faust](https://github.com/robinhood/faust) which is the most popular stream processing library. Faust currently has support for Tracing, but doesn't support Python OpenTracing 2.0.0, which was a recent change we introduced to ensure all our libraries were current. There is an ongoing issue in https://github.com/robinhood/faust/issues/528 which will address this however. This needs to be addressed, potentially having to move faust into `extra_required`.\

For completeness, there are a couple of extra pieces to consider which are outlined below.

### Batch processing option

Besides a Kafka Specific option, one thing that was also considered was a more generic Batch functionality, which was explored by extending the Python class implementation with three new functions: namely `fetch()` and `process()`. Where this would allow users to extend each of these commands to basically do exactly what they imply. For explicitness, the way these functions would interact would be as follows:
1) When the container starts, the relevant database/datasource connection would be initialised in the `__init__` function on the model wrapper class implemented by the user
2) The `fetch()` function would be called in a loop, and would include the user logic to fetch new data from the required source
3) When the fetch() function returns a non-False value, the process function would be called with the relevant data, and the user would be expected to handle the logic to send that to the relevant output

However the decision to not go ahead with this was primarily as this could result in quite a broad number of implementations which would then result in *extremely* complex and ambiguous management infrastructure requirements (as mentioned in "key points to discuss" section)

### Work in Progress: Basic Executor Functionality

Currently the work in progress for exploration are the many ways in which the executor could be implemented. Below is an overview of what the architectural diagram would look like for an implementation of the kafka topic input-output approach. However, there are many more ways in which this could be implemented. Some that would be worth considering include: 
* Using kafka message passing internally for intra-graph communication but supporting something like [Benthos](https://github.com/Jeffail/benthos) to connect / listen from other supported sink/sources

Below is the architectural diagram of how this implementation would work as the executor is extended to support the same functionality. One thing to note however is that this example below is limited to only process "predict", which means that "route" and "aggregate" are not taken into account (to reduce complexity), but are covered in the next section.

The key things to note are that the high level architecture is the same, but the executor is the key responsible of managing the data flow once data comes into the DEPLOYMENT INPUT topic. From then on, the executor will push the data into the input topic of the first model, and subscribe to the output which would then be passed to the next model, etc. 

One thing to note is that in this initial implementation the objective 
image

### Multi-node full graph support

This would be the implementation of the KAFKA streaming version for multi-node graphs that would also enable for route and aggreagate methods. 

The implementation of this would be the same architecture as the section above, and would have the exact same data flow requirements as the REST / GRPC. 

#### Edit 11:29-16/02/2020

Pushed a few additions which include:
* Example with kubernetes (with a no-engine deployment) 
* Workaround for #1449 by setting the PREDICTIVE_UNIT variables manually
* Addition of REST API based on discussion on #1387 (to allow readiness probe to work)

#### Edit 8:28 - 19/02/2020:
* Using new env variable SELDON_SERVICE_STREAMING_BROKER instead of host/port and using seldon deployment service_port variable to provide rest health endpoints as per discussion in #1449

#### Edit 18:36 - 22/02/2020
Added new functionality in separate branch / PR to add graph capabilities to this stream processing application through https://github.com/axsaucedo/seldon-core/pull/1 which allowed for a lot of insights to be uncovered on the complexity that this implementation would have.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sat Feb 15 12:53:04 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=2

**Comment by seldondev** [comment]
Sat Feb 15 12:53:17 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=1

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 1295def28c9c3d084a452d2d30d9776d131ccfaf | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun Feb 16 10:50:06 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=4

**Comment by seldondev** [comment]
Sun Feb 16 10:50:08 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | fb1a86c514eed0492bf795ccac6aeadcc51db4eb | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Pushed a few additions which include:
* Example with kubernetes (with a no-engine deployment) 
* Workaround for #1449 by setting the PREDICTIVE_UNIT variables manually
* Addition of REST API based on discussion on #1387 (to allow readiness probe to work)

**Comment by seldondev** [comment]
Sun Feb 16 11:36:32 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=5

**Comment by seldondev** [comment]
Sun Feb 16 11:36:42 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ad506d2ec6cffe32abd007fdfce2299e280aed6b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb 19 08:28:09 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=8

**Comment by seldondev** [comment]
Wed Feb 19 08:28:18 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1447/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1447 --build=7

**Comment by axsaucedo** [comment]
Using new env variable SELDON_SERVICE_STREAMING_BROKER instead of host/port and using seldon deployment service_port variable to provide rest health endpoints as per discussion in #1449

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | e2543ffed7d0c52be1a76002fe4b5ae1d8b734ad | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Added new functionality in separate branch / PR to add graph capabilities to this stream processing application through https://github.com/axsaucedo/seldon-core/pull/1 which allowed for a lot of insights to be uncovered on the complexity that this would have.

## Contents of https://github.com/axsaucedo/seldon-core/pull/1:
In this pull request I started an exploration around adding simple graph processing capabilities to the current batch exploration PR https://github.com/SeldonIO/seldon-core/pull/1447. This implementation allows for linear graphs for Models, and can be easily extended to also include InputTransformers, OutputTransformers and Routers.

An example of a 3-node prediction graph orchestrated by the engine can be found here: https://github.com/axsaucedo/seldon-core/blob/735c08cd40aa12ee6be6d17336bf88227e1cad84/examples/streaming/stream_processing_graph/README.md

The visual implementation of the example is as follows:
image


Putting together this PR also provided some insight around the following areas:
* Implementing linear and single-route routers is not complex with executor
* Implementing Aggregate/Combine would be more complex
* Currently it's not possible to re-use fully the SeldonClientApi interface due to extra requirements
* It is not possible to re-use the predictor module as it is due to its Sync flow requirement by default
* The way UUID can be dealt with can be through Kafka Metadata or Key
* It is possible to leverage quite a lot of the tooling to perform benchmarking
* Error handling and retries can be handled on a granular level but require alignment with REST/GRPC
* It's not possible to re-use pre-packaged proxy-based prepackaged model servers

**Comment by axsaucedo** [comment]
Closing in favour of #1447

**Pull request closed without merging**
