### PR TITLE
bad json should be 400 not 500

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/943

### CODE REVIEW

**Comment by adriangonz** [comment]
It makes sense to return a `400` if the JSON request is incorrect, but should we also return a `400` in this case? https://github.com/SeldonIO/seldon-core/blob/ec18ddf4c2caa5b95b5bf9a772300c1392aa6ed3/engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java#L231-L249

I'm assuming that in that case, the downstream predictive service returned a invalid JSON. It's not clear to me if that should be considered a server or client error.

PS: I'm aware this is a bit nitpicky.

**Comment by cliveseldon** [comment]
> It makes sense to return a `400` if the JSON request is incorrect, but should we also return a `400` in this case?
> 
> https://github.com/SeldonIO/seldon-core/blob/ec18ddf4c2caa5b95b5bf9a772300c1392aa6ed3/engine/src/main/java/io/seldon/engine/api/rest/RestClientController.java#L231-L249
> 
> I'm assuming that in that case, the downstream predictive service returned a invalid JSON. It's not clear to me if that should be considered a server or client error.
> 
> PS: I'm aware this is a bit nitpicky.

I suppose its a 500 as the bad JSON is coming from the model rather than the client?

**Comment by ryandawsonuk** [comment]
Yeah I guess bad request and bad response should actually be separated as different cases

**Comment by ryandawsonuk** [comment]
Have updated now

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/944#pullrequestreview-300758228" title="Approved">adriangonz</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/944#issuecomment-541114611" title="Approved">adriangonz</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/944#issuecomment-541114611" title="Approved">adriangonz</a>*, *<a href="https://github.com/SeldonIO/seldon-core/pull/944#issuecomment-541116061" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
