### PR TITLE
Add summary metrics to executor

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:
Adds https://github.com/SeldonIO/seldon-core/pull/2895 on master.
Solves https://github.com/SeldonIO/seldon-core/issues/2765 on master.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Wed Feb  3 17:38:30 UTC 2021
The logs for [notebooks] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=1

**Comment by seldondev** [comment]
Wed Feb  3 17:38:44 UTC 2021
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=2

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fa1b710ec501771e99548ea4277a1cd77d6abe0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fa1b710ec501771e99548ea4277a1cd77d6abe0 | [link]() | `/test integration`
notebooks | 6fa1b710ec501771e99548ea4277a1cd77d6abe0 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 17:49:57 UTC 2021
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=3

**Comment by seldondev** [comment]
Wed Feb  3 18:12:04 UTC 2021
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 6fa1b710ec501771e99548ea4277a1cd77d6abe0 | [link]() | `/test notebooks`
integration | 61a0b31f84988fd9870c1b203c0e7e9d7e19f2d7 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Feb  4 10:11:45 UTC 2021
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=5

**Comment by RafalSkolasinski** [comment]
Notebooks and integrations passed in previous runs, repeating for completness.
/test integration
/test notebooks

**Comment by seldondev** [comment]
Thu Feb  4 13:23:32 UTC 2021
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=6

**Comment by seldondev** [comment]
Thu Feb  4 13:23:45 UTC 2021
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2922/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2922 --build=7

**Comment by RafalSkolasinski** [comment]
Same as https://github.com/SeldonIO/seldon-core/pull/2895 this one is ready to land. All checks are green.

**Comment by axsaucedo** [comment]
Looks good! On this one that will go to `master` would be good to add further docs on the metrics page

**Comment by RafalSkolasinski** [comment]
> Looks good! On this one that will go to master would be good to add further docs on the metrics page

Good idea, though, shall maybe follow on separate PR so we don't loose the "all green" status?

**Comment by axsaucedo** [comment]
@RafalSkolasinski probably best to do it together to make sure it doesn't slip.

For explicitness we can keep confirmation that all integration tests passed:
image

**Comment by RafalSkolasinski** [comment]
Updated doc page 
image

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2922#issuecomment-774134902 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-774134902/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
