### PR TITLE
Update microservice.R

### PR DESCRIPTION
**Pull request by LueJian**
Input data type persistence and null value persistence.

**What this PR does / why we need it**:

### Input data type persistence

In all endpoint functions, if there are character and numeric value in input data simultaneously, the default of `fromJSON(json)` always convert numeric value to character type, therefore, the data type of columns in dataframe will be wrong after `create_dataframe(jdf)`.

if the input data is like that:

`json={"data":{"name":["col_must_be_char", "col_must_be_num"], "ndarray":[["A",12],[ "B",20]]}}`

the data schema after `fromJSON(json)` **now**:
image

the data schema after `create_dataframe(jdf)` **now**:
image

**expect** data schema after `create_dataframe(jdf)`:
image

The reason is that the outcome of `fromJSON(json)` will be "matrix" class, but the matrix in R only been allowed one data type at the same time. By adding an argument `simplifyVector = False` to `fromJSON(json)` can avoid that because the outcome of `fromJSON(json, simplifyVector = False)` will be "list" class:
image

Then we should add `rbind()` and `lappy()` into `create_dataframe()` to combine those list value and add an argument `stringsAsFactors = False` in `data.frame()` to avoid character data type transform to Factor automatically, because it always transform string to Factor using `data.frame()` by default in R. Therefore, we can get expect dataframe schema:
image

### Convert input NULL value to NA 

In general, we always express missing value by `""` (string) and `null` (numeric). If we edit the script like demonstrate above, the null value (numeric missing value) will be convert to `"NULL"` after `fromJSON(json, simplifyVectors=False)` originally, so we have to add `df[df == "NULL"] <-  NA` in `create_dataframe()` to replace NULL by NA.

if the input data is like that: (with null)
`json={"data":{"name":["col_must_be_char", "col_must_be_num"], "ndarray":[["A",12],[ "",null]]}}`

the outcome of `fromJSON(json, simplifyVectors=False)` and `create_dataframe()` **without** replace NULL by NA:
image
image

the outcome of `fromJSON(json, simplifyVectors=False)` and `create_dataframe()` **with** replace NULL by NA:
image

### Convert response NA value to null

Like descriptions above, in general, we always express missing value by `""` (string) and `null` (numeric), so we have to add an argument `na = null` to the `toJSON()` function in `create_response()`, then the NA in output will be null.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```"NONE"
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @LueJian. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cliveseldon** [comment]
@LueJian Thanks for this! This is great. It would be great to provide some better examples of real R use cases in the docs in a future PR.

**Comment by seldondev** [comment]
Tue Aug  4 06:31:11 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2239/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2239 --build=2

**Comment by seldondev** [comment]
Tue Aug  4 06:31:16 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2239/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2239 --build=1

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2239#issuecomment-668413871 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-668413871/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
