### PR TITLE
Add the option to add configurations to Kafka

### LINKED ISSUE #3225: Kafka - Add the option to add configurations
Currently, the Kafka executor in seldon-core uses specific configurations for the Consumer/Producer.
For example, this is the predetermined configuration for the Consumer:

> {
        		"bootstrap.servers":     ks.Broker,
        		"broker.address.family": "v4",
        		"group.id":              ks.getGroupName(),      
        		"session.timeout.ms":    6000
}

There should be a way to let the users add or maybe even override those parameters when needed.
The best example is that sometimes Kafka requires a username and password and there is no way to currently add them.
I opened a PR to do here: #3223 
Some questions from @axsaucedo there were:

> 1. Are the expected parameters supposed to be lower case with "."? The normal convention of env vars is capital letter and underscores. Is there a standard in which kafka expects these to be in that format or is this assumption on what you're defining?
> 2. Are there other configurations other than producer / consumer that should also be added when creating the resources?

For the first question, what I was trying to do in the PR is to get the variable in the env vars convention (capital letters and underscores) and convert them into the Kafka convention (lower case and dots).
So for example, the env var will be "KAFKA_CONSUMER_GROUP_ID" and it will be converted by the code to "group.id" for Kafka.

For the second question, I don't know of any other configurations other than producer/consumer but I'm not very knowledgeable about Kafka so I may be wrong.

### PR DESCRIPTION
**Pull request by naor2013**
**What this PR does / why we need it**:
It allows adding Kafka configurations in the env variables of Seldon.

**Which issue(s) this PR fixes**:

Fixes #3225 

**Special notes for your reviewer**:
I did not run tests because I don't know Golang very well. I am not sure this even compiles.
I would like some help from the Seldon core maintainers on this one :)

**Does this PR introduce a user-facing change?**:

```release-note
Kafka configurations can be added with env variables.
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @naor2013. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by naor2013** [comment]
@cliveseldon I would like to get some help with this PR 😄

**Comment by cliveseldon** [comment]
Thanks @naor2013 for this.

Can I suggest a few changes
  * To make env vars upper case
  * To add some docs to Kafka page: https://github.com/SeldonIO/seldon-core/blob/master/doc/source/streaming/kafka.md

We also now have Kafka payload logging: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/logging.html#logging-direct-to-kafka
So we need to make sure this functionality could be extended to that either here or in a future PR.

**Comment by naor2013** [comment]
@cliveseldon Thanks for the quick answer.
I did assume the env varaibles are upper-case, I'm using "lower" just for that.
I do not check if it is actually upper-case because I don't know how to do it in golang but it does work with upper-case.

For my use cases, we won't be using the kafka logger probably, so it would be great if you guys can help with adding it there, either in this PR or a future one.

I'll add documentation in a bit.

On another note, I didn't actually test this change (because again, no idea how).
Can you generate for me a docker image based on this branch so I can test that it works correctly before we push it?

Again, thank you so much for the help :)

**Comment by cliveseldon** [comment]
Hi @naor2013 

You can build the images locally and run a cluster in Kind to test. Playbooks for seldon and kafka can be used to deploy see: https://github.com/SeldonIO/seldon-core/tree/master/ansible
You would need to modify to use master and `kind image install` your modified executor.

Adding an example notebook in `examples/kafka` would be useful. We can see if we can add it to tests when its created.

**Comment by axsaucedo** [comment]
@naor2013 would you have a chance to have a look at adding the naming convetions and the example?

**Comment by naor2013** [comment]
@axsaucedo what do you mean by naming conventions?
And I don't think I'll have time soon but if it'll wait I'll do it eventually.

**Comment by axsaucedo** [comment]
@naor2013 this would be the suggestions that clive provided above, namely:

> Can I suggest a few changes
> 
>     To make env vars upper case
>     To add some docs to Kafka page: https://github.com/SeldonIO/seldon-core/blob/master/doc/source/streaming/kafka.md
> 
> We also now have Kafka payload logging: https://docs.seldon.io/projects/seldon-core/en/latest/analytics/logging.html#logging-direct-to-kafka
> So we need to make sure this functionality could be extended to that either here or in a future PR.

**Comment by naor2013** [comment]
@axsaucedo @cliveseldon I don't really have any time to get into this PR, especially because it requires learning a lot of new stuff that is unrelated to my day-to-day job.
Is there any way you guys can either add what's necessary or even start from scratch if you prefer to finish this feature?

**Comment by axsaucedo** [comment]
Closing as this is to be tackled on a new PR

**Pull request closed without merging**
