### PR TITLE
fixed noEngine

### LINKED ISSUE #1976: re-define noEngine annotation
this is original codes:
`_, noEngine := p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE]`

if `machinelearningv1.ANNOTATION_NO_ENGINE` in annotations, `noEngine` is true, otherwise, it is false.

This is confusing. we need check the value of `p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE]` instead of whether it exists in the annotations map or not.

there is same concern about `_, hasSeparateEnginePod := mlDep.Spec.Annotations[machinelearningv1.ANNOTATION_SEPARATE_ENGINE].`

Please leave comments, so that I can update the pr: https://github.com/SeldonIO/seldon-core/pull/1970

### PR DESCRIPTION
**Pull request by chengchengpei**
Fixes #1976

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @chengchengpei. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by chengcheng-pei** [comment]
this is original codes:
```_, noEngine := p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE]```

if machinelearningv1.ANNOTATION_NO_ENGINE in annotations, noEngine is true, otherwise, it is false.

This is confusing. we need check the value of p.Annotations[machinelearningv1.ANNOTATION_NO_ENGINE] instead of whether it exists in the annotations map or not.

there is same concern about `_, hasSeparateEnginePod := mlDep.Spec.Annotations[machinelearningv1.ANNOTATION_SEPARATE_ENGINE]`.

Please leave comments, so that I can update the above codes.

**Comment by chengcheng-pei** [comment]
https://github.com/SeldonIO/seldon-core/issues/1976

**Comment by seldondev** [comment]
Thu Jun 25 10:01:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=1

**Comment by seldondev** [comment]
Thu Jun 25 10:03:01 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=2

**Comment by seldondev** [comment]
Thu Jun 25 11:48:06 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=3

**Comment by RafalSkolasinski** [comment]
@chengcheng-pei are you planning to add anything more to this PR?

**Comment by seldondev** [comment]
@chengchengpei: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b0ebe9ea18677d3c17040aad098b6db79df0e618 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jun 25 12:26:50 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=4

**Comment by chengchengpei** [comment]
> @chengcheng-pei are you planning to add anything more to this PR?

@RafalSkolasinski I updated my pr. that is all.

**Comment by seldondev** [comment]
Wed Jul  1 21:59:00 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=6

**Comment by seldondev** [comment]
Wed Jul  1 21:59:01 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=5

**Comment by cliveseldon** [comment]
Can you add test to operator?

**Comment by seldondev** [comment]
Fri Jul  3 20:01:31 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=8

**Comment by seldondev** [comment]
Fri Jul  3 20:01:39 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=7

**Comment by chengcheng-pei** [comment]
> Can you add test to operator?

I added tests.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/1970#issuecomment-656054138 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-656054138/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jul  9 10:45:29 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=9

**Comment by seldondev** [comment]
Wed Jul 15 13:36:05 UTC 2020
The logs for [engine] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1970/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1970 --build=10

**Comment by axsaucedo** [comment]
Engine tests and integration test pass

**Pull request merged**
