### PR TITLE
Add support to deploy SKLearn and XGBoost models with MLServer

### LINKED ISSUE #1648: Support NVIDIA/KFServing V2 Data Plane
Integrate proposed [NVIDIA/KFServing V2 data plane](https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2)

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Add support to deploy SKLearn and XGBoost models compatible with the [V2 Dataplane proposed by NVIDIA / KFServing](https://github.com/kubeflow/kfserving/tree/master/docs/predict-api/v2), by leveraging [MLServer](https://github.com/seldonio/mlserver).

On most cases, the user will be able to enable the V2 dataplane by specifying `kfserving` as the protocol on their `SKLEARN_SERVER` and `XGBOOST_SERVER` deployments. For example, one can do:

```yaml
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: xgboost
spec:
  name: iris
  protocol: kfserving
  predictors:
  - graph:
      children: []
      implementation: XGBOOST_SERVER
      modelUri: gs://seldon-models/xgboost/iris
      name: classifier
    name: default
    replicas: 1
``` 

**To Do**

- [ ] ~Add examples with V2 protocol~ (moved to #2479)

**Which issue(s) this PR fixes**:

Fixes #1648 

**Special notes for your reviewer**:

This PR is based on #2023. Once that one gets merged, I'll rebase this one to `master` to clean up Git's history. 

**Does this PR introduce a user-facing change?**:

```release-note
Added support to use the V2 Dataplane with SKLearn and XGBoost models.
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | aff0b4fc8fba8a578516cea11d026549cb2ff0f4 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
/cc @cliveseldon @RafalSkolasinski @axsaucedo 

There are still a few details left on this PR, like rebasing once #2023 gets merged, but I think that the rest is ready for review. It would be great to get your thoughts!

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | aff0b4fc8fba8a578516cea11d026549cb2ff0f4 | [link]() | `/test this`
lint | aff0b4fc8fba8a578516cea11d026549cb2ff0f4 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 22 09:24:59 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=3

**Comment by seldondev** [comment]
Tue Sep 22 09:25:00 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=4

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7a8e9f212cdd8c0630648c9c111b137b69d39493 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 23 09:14:05 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=6

**Comment by seldondev** [comment]
Wed Sep 23 09:14:09 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=5

**Comment by seldondev** [comment]
Wed Sep 23 09:24:13 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=8

**Comment by seldondev** [comment]
Wed Sep 23 09:24:16 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=7

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 64ee9fb8f7a1143441c283719aeaebb4bad049e6 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 23 14:16:33 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=10

**Comment by seldondev** [comment]
Wed Sep 23 14:16:44 UTC 2020
The logs for [notebooks] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=9

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 24 13:32:24 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=11

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 24 15:47:54 UTC 2020
The logs for [integration] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=12

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 28 10:39:06 UTC 2020
The logs for [integration] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=15

**Comment by seldondev** [comment]
Mon Sep 28 10:39:19 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=13

**Comment by seldondev** [comment]
Mon Sep 28 10:39:21 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=14

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`
lint | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test integration`
lint | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test lint`
pr-build | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 28 11:04:55 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=16

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
pr-build | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test this`
integration | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 28 13:51:56 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=17

**Comment by seldondev** [comment]
Mon Sep 28 13:51:59 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=18

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 8ea2afed5e5cb0686ad21c543ed92cca7bbbecd8 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 29 09:40:19 UTC 2020
The logs for [integration] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=21

**Comment by seldondev** [comment]
Tue Sep 29 09:40:24 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=20

**Comment by seldondev** [comment]
Tue Sep 29 09:40:34 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=19

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 241f6faafa2e03df2b4f423789bb3151943c8d28 | [link]() | `/test notebooks`
integration | 816c5e5a575c5534aca860d98cc95f126869bd47 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 29 10:52:05 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=24

**Comment by seldondev** [comment]
Tue Sep 29 10:52:11 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=23

**Comment by seldondev** [comment]
Tue Sep 29 10:52:13 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=22

**Comment by seldondev** [comment]
Tue Sep 29 13:22:27 UTC 2020
The logs for [notebooks] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=25

**Review by RafalSkolasinski — APPROVED** [review]
Nice one, solid work!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2450#pullrequestreview-498559533 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 0c76496e8e6e7fc389e39d28ff16f30ae7120a4c | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 30 13:33:31 UTC 2020
The logs for [notebooks] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=26

**Comment by seldondev** [comment]
Wed Sep 30 15:43:56 UTC 2020
The logs for [pr-build] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=27

**Comment by seldondev** [comment]
Wed Sep 30 15:44:18 UTC 2020
The logs for [lint] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2450/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2450 --build=28

**Pull request merged**
