### PR TITLE
Allow non-model specific predict for Tensorflow protocol

### LINKED ISSUE #1611: url with tensorflow protocol
Currently part of the url comes from a model_name parameter. See:

https://github.com/SeldonIO/seldon-core/blob/f182052cda260fe2c2d27bf0a5b07f455b422344/servers/tfserving/samples/halfplustwo_rest.yaml#L15

https://github.com/SeldonIO/seldon-core/search?q=halfplustwo&unscoped_q=halfplustwo
https://github.com/SeldonIO/seldon-core/search?q=ModelHttpPathVariable&unscoped_q=ModelHttpPathVariable

We don't want to require this parameter in constructing the url. We should update our examples to reflect this. (Otherwise could lead to problems with canaries.)

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1611

 * Allows `/v1/models/:predict`
 * Fixes error payload handling
 * Adds tests and updates docs

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sun Apr 12 10:00:15 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1684/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1684 --build=2

**Comment by seldondev** [comment]
Sun Apr 12 10:00:19 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1684/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1684 --build=1

**Comment by ryandawsonuk** [comment]
Just checking I've understood the change at https://github.com/SeldonIO/seldon-core/pull/1684/files#diff-a047655e38112373418dfdc7e8b71227R292 correctly. It means the [model_name](https://github.com/SeldonIO/seldon-core/blob/f182052cda260fe2c2d27bf0a5b07f455b422344/servers/tfserving/samples/halfplustwo_rest.yaml#L15) parameter will be optional? So if it's not set then you can still make a request to the graph-level endpoint by hitting `/v1/models/:predict`

**Comment by cliveseldon** [comment]
> Just checking I've understood the change at https://github.com/SeldonIO/seldon-core/pull/1684/files#diff-a047655e38112373418dfdc7e8b71227R292 correctly. It means the [model_name](https://github.com/SeldonIO/seldon-core/blob/f182052cda260fe2c2d27bf0a5b07f455b422344/servers/tfserving/samples/halfplustwo_rest.yaml#L15) parameter will be optional? So if it's not set then you can still make a request to the graph-level endpoint by hitting `/v1/models/:predict`

Yes the model_name is needed just for Seldon protocol as it needs to run the tensorflow proxy server and in that it needs to know the model_name. For tensorflow protocol the name of the graph component will need to match the model loaded as that will be used.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1684#pullrequestreview-392712051" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Apr 14 08:33:32 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1684/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1684 --build=4

**Comment by seldondev** [comment]
Tue Apr 14 08:33:39 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1684/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1684 --build=3

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 7de281fcbc91e46ab450e1a787b2ca917faab216
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 7de281fcbc91e46ab450e1a787b2ca917faab216
* failed to process repo SeldonIO/seldon-core refref 7de281fcbc91e46ab450e1a787b2ca917faab216
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
