### PR TITLE
include reward in metrics on wrapper

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

It makes sure that `reward metrics` is recorded when model's `send-feedback` is hit.

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2115

**Special notes for your reviewer**:

- adds `SELDON_EXECUTOR_ENABLED` environmental variable on the wrapper
- fixes custom metrics tags (keep wrong ones until 1.3 for compatibility reasons)

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jul 16 22:09:45 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=2

**Comment by seldondev** [comment]
Thu Jul 16 22:09:48 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=1

**Comment by seldondev** [comment]
Fri Jul 17 15:01:36 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=4

**Comment by seldondev** [comment]
Fri Jul 17 15:01:39 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=3

**Comment by seldondev** [comment]
Fri Jul 17 15:27:51 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=5

**Comment by seldondev** [comment]
Fri Jul 17 15:27:54 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=6

**Comment by seldondev** [comment]
Fri Jul 17 18:18:21 UTC 2020
The logs for [notebooks] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=7

**Comment by seldondev** [comment]
Fri Jul 17 18:20:16 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=8

**Comment by RafalSkolasinski** [comment]
Rebased onto master. Triggering tests to verify if we have flakiness or not (tests passed before).

/test notebooks
/test integration

**Comment by seldondev** [comment]
Tue Jul 21 10:29:09 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=10

**Comment by seldondev** [comment]
Tue Jul 21 10:29:43 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=9

**Comment by seldondev** [comment]
Tue Jul 21 10:29:47 UTC 2020
The logs for [integration] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=12

**Comment by seldondev** [comment]
Tue Jul 21 10:29:55 UTC 2020
The logs for [notebooks] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2150/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2150 --build=11

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2150#issuecomment-661835248 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-661835248/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
