### PR TITLE
WIP: Evaluation of Reverting "Jenkins X add comment when pipeline finishes" to remove test flakiness

### PR DESCRIPTION
**Pull request by axsaucedo**
Reverts SeldonIO/seldon-core#2149

This PR aims to evaluate whether flakiness was introduced due to this PR

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 20 19:27:23 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=1

**Comment by seldondev** [comment]
Mon Jul 20 19:27:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=2

**Comment by seldondev** [comment]
Mon Jul 20 20:09:51 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=3

**Comment by seldondev** [comment]
Mon Jul 20 20:09:53 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=5

**Comment by seldondev** [comment]
Mon Jul 20 20:09:55 UTC 2020
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=4

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b0d674ed9cb9793ab3507c7bcebed4d7e7580d3e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 21 05:44:24 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2174/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2174 --build=6

**Comment by axsaucedo** [comment]
Closing as it seems it's not the docker image dependencies that is causing the issue

**Pull request closed without merging**
