### PR TITLE
WIP: Release 1.5.0

### PR DESCRIPTION
**Pull request by axsaucedo**
Release PR to run tests

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Nov 23 15:48:44 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=1

**Comment by seldondev** [comment]
Mon Nov 23 15:50:12 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=2

**Comment by seldondev** [comment]
Mon Nov 23 17:22:51 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=3

**Comment by seldondev** [comment]
Mon Nov 23 17:24:31 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=4

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c4473b64cbdc553ba10a8e0ae7e552eda9905138 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
In integration tests it seems that `test_text_alibi_explainer` failed. Running again to confirm flakiness:
/test integration

**Comment by seldondev** [comment]
Mon Nov 23 20:20:45 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=5

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c4473b64cbdc553ba10a8e0ae7e552eda9905138 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Nov 23 20:54:13 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c4473b64cbdc553ba10a8e0ae7e552eda9905138 | [link]() | `/test integration`
notebooks | c4473b64cbdc553ba10a8e0ae7e552eda9905138 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Nov 23 21:08:33 UTC 2020
The logs for [notebooks] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=7

**Comment by seldondev** [comment]
Tue Nov 24 06:48:52 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=9

**Comment by seldondev** [comment]
Tue Nov 24 06:48:54 UTC 2020
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=8

**Comment by seldondev** [comment]
Tue Nov 24 06:49:02 UTC 2020
The logs for [securitychecks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=10

**Comment by axsaucedo** [comment]
integration tests pass

**Comment by seldondev** [comment]
Tue Nov 24 10:02:56 UTC 2020
The logs for [notebooks] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=11

**Comment by seldondev** [comment]
Tue Nov 24 15:21:28 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=13

**Comment by seldondev** [comment]
Tue Nov 24 15:21:45 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2696/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2696 --build=12

**Comment by axsaucedo** [comment]
Closing as release is finalised

**Pull request closed without merging**
