### PR TITLE
s2i usage fails with image version 1.15.0-dev

### PR DESCRIPTION
**Pull request by bbalakriz**
running `s2i usage seldonio/seldon-core-s2i-python3:1.15.0-dev` fails with the following error[1]. Changing the version to the release version "1.15.0" works without issues. 

[1]
$ s2i usage seldonio/seldon-core-s2i-python3:1.15.0-dev  ERROR: An error occurred: failed to install [usage] ERROR: Suggested solution: set the scripts URL parameter with the location of the S2I scripts, or check if the image has the "io.openshift.s2i.scripts-url" label set ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3. bbalasub~$ s2i usage seldonio/seldon-core-s2i-python3:1.15.0-dev
ERROR: An error occurred: failed to install [usage]
ERROR: Suggested solution: set the scripts URL parameter with the location of the S2I scripts, or check if the image has the "io.openshift.s2i.scripts-url" label set
ERROR: If the problem persists consult the docs at https://github.com/openshift/source-to-image/tree/master/docs. Eventually reach us on freenode #openshift or file an issue at https://github.com/openshift/source-to-image/issues providing us with a log from your build using log output level 3.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @bbalakriz. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by axsaucedo** [comment]
Not clear why it would fail with -dev but not normal, seems like a label issue - @RafalSkolasinski have you seen this before?

**Comment by axsaucedo** [comment]
I don't really see why this would fail @bbalakriz - we run integration tests that build this, the `-dev` image is the one that would be built in master, and the non dev image is built as part of the release process, so both would work

**Comment by RafalSkolasinski** [comment]
This is failing me but due to yet another issuer on both `1.15.0` and `1.15.0-dev`
```
/bin/sh: line 1: tar: command not found
ERROR: An error occurred: missing requirements
```

Anyway, the `-dev` images have been rebuild after recent merges to master so @bbalakriz could you try again? In any case we want to keep master branch with `1.15.0-dev` in tags and we will have `1.15.0` only in the release (WIP) branch.

**Comment by axsaucedo** [comment]
Closing the PR for now but reopen if still an issue

**Comment by MaratSaidov** [comment]
> This is failing me but due to yet another issuer on both `1.15.0` and `1.15.0-dev`
> 
> ```
> /bin/sh: line 1: tar: command not found
> ERROR: An error occurred: missing requirements
> ```
> 
> Anyway, the `-dev` images have been rebuild after recent merges to master so @bbalakriz could you try again? In any case we want to keep master branch with `1.15.0-dev` in tags and we will have `1.15.0` only in the release (WIP) branch.

@RafalSkolasinski @axsaucedo 

I've been facing this problem in the past week:

```bash
/bin/sh: line 1: tar: command not found
```

Tried to add manually this binary to the builder image, but it seems to be overengineering.
Could you clarify how to fix it properly?

**Comment by RafalSkolasinski** [comment]
I opened https://github.com/SeldonIO/seldon-core/issues/4457

**Pull request closed without merging**
