### PR TITLE
Deprecate Java engine

### LINKED ISSUE #2588: Depricate engine (old Java service orchestrator)
Currently the executor is the core service orchestrator in use, so we can work towards depricating the engine. 

Still dependent on:
* #2505

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

This PR removes:

- Dependabot alerts for Java engine
- JX context to run Java engine's tests
- Flag `executor.enabled` from Seldon Core chart

**Which issue(s) this PR fixes**:

Fixes #2588

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Deprecated Java engine (service orchestrator).
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jan 20 17:00:11 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=2

**Comment by seldondev** [comment]
Wed Jan 20 17:00:20 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=1

**Comment by seldondev** [comment]
Wed Jan 20 17:00:57 UTC 2021
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=5

**Comment by seldondev** [comment]
Wed Jan 20 17:01:01 UTC 2021
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=4

**Comment by seldondev** [comment]
Wed Jan 20 17:02:09 UTC 2021
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=3

**Comment by seldondev** [comment]
Wed Jan 20 17:02:46 UTC 2021
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=6

**Comment by axsaucedo** [comment]
Looks good! Why are there so many reformatting updates? Is this because of the update of `black`?

**Comment by adriangonz** [comment]
@axsaucedo good question. I'm not sure TBH. 

It could be that the linter doesn't check those folders, but the pre-commit handler does? I've got the latter set up in my environment, so maybe that's the one doing the changes.

**Comment by axsaucedo** [comment]
Ok makes sense @adriangonz

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jan 21 09:32:55 UTC 2021
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=7

**Comment by seldondev** [comment]
Thu Jan 21 11:38:00 UTC 2021
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=8

**Comment by seldondev** [comment]
Thu Jan 21 11:38:37 UTC 2021
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=9

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test integration`
lint | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test lint`
integration | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jan 21 16:08:40 UTC 2021
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=10

**Comment by seldondev** [comment]
Thu Jan 21 16:08:49 UTC 2021
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=11

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c06f2c319bdc052d6f405b4d3050bb67a026035b | [link]() | `/test integration`
lint | b668eca62d798227df47f63a05d45e4774600463 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jan 21 16:21:11 UTC 2021
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=12

**Comment by seldondev** [comment]
Thu Jan 21 16:21:24 UTC 2021
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=13

**Comment by seldondev** [comment]
Thu Jan 21 16:55:30 UTC 2021
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=15

**Comment by seldondev** [comment]
Thu Jan 21 16:58:23 UTC 2021
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=14

**Comment by seldondev** [comment]
Thu Jan 21 17:09:04 UTC 2021
The logs for [integration] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=16

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1f4033ebd0269dd72b3e00d5c05b5c37e6d37549 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jan 22 10:05:16 UTC 2021
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=17

**Comment by axsaucedo** [comment]
Looks good!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2857#issuecomment-765409135 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-765409135/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan 22 13:50:59 UTC 2021
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=19

**Comment by seldondev** [comment]
Fri Jan 22 13:51:21 UTC 2021
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=18

**Comment by seldondev** [comment]
Fri Jan 22 14:14:55 UTC 2021
The logs for [lint] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=21

**Comment by seldondev** [comment]
Fri Jan 22 14:14:54 UTC 2021
The logs for [pr-build] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2857/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2857 --build=20

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 1f4033ebd0269dd72b3e00d5c05b5c37e6d37549 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
