### PR TITLE
more flexibility in interface_file

### PR DESCRIPTION
**Pull request by msteijaert**
The proposed changes allow more flexibility in the interface file. For example, the interface file can be a module inside an installed package

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **gsunner**

If they are not already assigned, you can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @msteijaert. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by cliveseldon** [comment]
Also can you add an issue for what this trying to solve and why?
then:
Can we add a test for this to ensure this is not breaking anything?

**Comment by msteijaert** [comment]
> Also can you add an issue for what this trying to solve and why?
I have added this issue: https://github.com/SeldonIO/seldon-core/issues/2068

> Can we add a test for this to ensure this is not breaking anything?
I cannot really comment on this, but I assume you already have tests that try to load a custom model wrapper class in the default way.

**Comment by seldondev** [comment]
Fri Jul  3 12:48:25 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2046/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2046 --build=3

**Comment by seldondev** [comment]
Fri Jul  3 12:48:31 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2046/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2046 --build=2

**Comment by seldondev** [comment]
Fri Jul  3 12:48:39 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2046/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2046 --build=1

**Comment by RafalSkolasinski** [comment]
@msteijaert I don't fully understand the PR. It seems that code is already working exactly in the desired way. We already allow for multiple levels. Both implementation seems identical with current being slightly cleaner:
```python
In [1]: s = "a.b.c.d"

In [2]: parts = s.rsplit(".", 1)
In [3]: parts[0], parts[1]
Out[3]: ('a.b.c', 'd')

In [4]: parts = s.rsplit(".")
In [5]: ".".join(parts[:-1]), parts[-1]
Out[5]: ('a.b.c', 'd')
```

In what case does it fail for you?

**Comment by msteijaert** [comment]
> @msteijaert I don't fully understand the PR. It seems that code is already working exactly in the desired way. We already allow for multiple levels. Both implementation seems identical with current being slightly cleaner:
> 
> ```python
> In [1]: s = "a.b.c.d"
> 
> In [2]: parts = s.rsplit(".", 1)
> In [3]: parts[0], parts[1]
> Out[3]: ('a.b.c', 'd')
> 
> In [4]: parts = s.rsplit(".")
> In [5]: ".".join(parts[:-1]), parts[-1]
> Out[5]: ('a.b.c', 'd')
> ```
> 
> In what case does it fail for you?

Sorry, you are completely right. I didn't notice the rstrip instead of strip. This does indeed exactly what I need. I will cancel the pull request.

**Comment by RafalSkolasinski** [comment]
No worries @msteijaert, glad we got your use case covered!

**Comment by seldondev** [comment]
@msteijaert: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 8e2bab83ea39aec0069f1ba1422ddeedccab5542 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 8e2bab83ea39aec0069f1ba1422ddeedccab5542
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 8e2bab83ea39aec0069f1ba1422ddeedccab5542
* failed to process repo SeldonIO/seldon-core refref 8e2bab83ea39aec0069f1ba1422ddeedccab5542
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request closed without merging**
