### PR TITLE
add gRPC reflection support for seldon-core-executor and python wrapper

### PR DESCRIPTION
**Pull request by CatTail**
**What this PR does / why we need it**:

Enable gRPC reflection for Go seldon-core-executor and the python wrapper, with gRPC reflection we can inspect server APIs easily, for example with [grpcurl](https://github.com/fullstorydev/grpcurl),

```
$ grpcurl -plaintext localhost:8000 list
grpc.reflection.v1alpha.ServerReflection
seldon.protos.Seldon

$ grpcurl -plaintext localhost:8000 list seldon.protos.Seldon
seldon.protos.Seldon.GraphMetadata
seldon.protos.Seldon.ModelMetadata
seldon.protos.Seldon.Predict
seldon.protos.Seldon.SendFeedback
```

**Which issue(s) this PR fixes**:

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
add gRPC reflection support for seldon-core-executor and python wrapper
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @CatTail. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jklaise**
You can assign the PR to them by writing `/assign @jklaise` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by CatTail** [comment]
Hi @jklaise can you help to take a look at this PR?

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2395#issuecomment-689337589 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-689337589/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Sep  9 06:32:54 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=1

**Comment by seldondev** [comment]
Wed Sep  9 06:33:04 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=2

**Comment by seldondev** [comment]
Wed Sep  9 06:33:41 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=3

**Comment by seldondev** [comment]
@CatTail: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
@CatTail you need to run `make fmt` in the python folder

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2395#issuecomment-689337589 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test lint`
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 07:13:53 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=5

**Comment by seldondev** [comment]
Wed Sep  9 07:13:53 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=4

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
lint | d629dd034a6ff8220c18303478d0806c3cc96e93 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 07:29:18 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=6

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
lint | d629dd034a6ff8220c18303478d0806c3cc96e93 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Can you rebase from master as it seems to be failing on new licenses?

**Comment by seldondev** [comment]
Wed Sep  9 08:38:30 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=7

**Comment by seldondev** [comment]
Wed Sep  9 08:38:36 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=8

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
lint | 7fcab5fd2185f38df18e5cc9beb969b5e559d839 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
lint | 7fcab5fd2185f38df18e5cc9beb969b5e559d839 | [link]() | `/test lint`
pr-build | 7fcab5fd2185f38df18e5cc9beb969b5e559d839 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 09:19:14 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=10

**Comment by seldondev** [comment]
Wed Sep  9 09:19:20 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=9

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
pr-build | 7fcab5fd2185f38df18e5cc9beb969b5e559d839 | [link]() | `/test this`
lint | 4ac9131aa1a3bbd323dd68b99b98f190a63f6222 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by CatTail** [comment]
@cliveseldon looks like the lint failed due to license change, should I commit these license changes in this PR?

**Comment by axsaucedo** [comment]
@CatTail apologies for the delayed response, seems this may have slipped - this would be quite a useful addition to merge this. Would you be able to rebase from master and resolve conflicts? If you wouldn't be able let me know and we can help adding some of the changes. Thanks @CatTail !

**Comment by axsaucedo** [comment]
@CatTail just following up with the above, let me know, otherwise happy to rebase and do the changes

**Comment by CatTail** [comment]
@axsaucedo sorry for the late reply, I just update this PR, can you help to review it again.

**Comment by seldondev** [comment]
Wed Nov 25 13:31:36 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=11

**Comment by seldondev** [comment]
Wed Nov 25 13:31:46 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=12

**Comment by seldondev** [comment]
@CatTail: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 788dea353d7a715a61c1ff681f5939a84ac75925 | [link]() | `/test integration`
lint | 92cb5945f45f363819c05765fc5de321bfecbc2d | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Nov 25 14:28:59 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2395/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2395 --build=13

**Comment by axsaucedo** [comment]
Thank you @CatTail !

**Pull request merged**
