### PR TITLE
merge regular python and conda images

### LINKED ISSUE #1125: Merge Conda and regular Python s2i wrappers
## Context

To include support for custom Conda environments on #1108, we added a new `seldonio/seldon-core-s2i-conda` s2i wrapper. However, it could be a good idea  to merge it with the existing `seldonio/seldon-core-s2i-python`. This makes sense if we consider that adding Conda is just extending the feature set of the Python wrapper. It could also help with maintainability of the s2i wrappers.

Before agreeing to this change, one of the caveats that we need to consider is that the new `seldonio/seldon-core-s2i-conda` wrapper uses `continuum/miniconda3` as a Docker base image. This image is based on `debian:buster-slim`, which is a smaller version of `debian:buster` and which could break some uses of the existing `seldonio/seldon-core-s2i-python`.

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
This closes #1125.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **gsunner**

If they are not already assigned, you can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jan 20 22:09:39 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=2

**Comment by seldondev** [comment]
Mon Jan 20 22:09:42 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=1

**Comment by seldondev** [comment]
Mon Jan 20 23:37:59 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=4

**Comment by seldondev** [comment]
Mon Jan 20 23:38:05 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=3

**Comment by seldondev** [comment]
Tue Jan 21 12:14:47 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=5

**Comment by seldondev** [comment]
Tue Jan 21 12:14:53 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=6

**Comment by seldondev** [comment]
Tue Jan 21 12:19:20 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=8

**Comment by seldondev** [comment]
Tue Jan 21 12:19:32 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=7

**Comment by seldondev** [comment]
Tue Jan 21 12:19:45 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=9

**Comment by RafalSkolasinski** [comment]
P.S. As e2e tests only check 3.7 image, see https://github.com/SeldonIO/seldon-core/issues/1357, I did run e2e tests with 3.6 image manually.

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 0fa0252c7a3c8629893841ea5a673fc7e5971af2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jan 21 13:17:30 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=10

**Comment by adriangonz** [comment]
/approve

This looks great @RafalSkolasinski!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1353#issuecomment-576682731" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jan 21 14:21:00 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=11

**Comment by seldondev** [comment]
Tue Jan 21 14:21:04 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=12

**Comment by seldondev** [comment]
Tue Jan 21 14:31:36 UTC 2020
The logs for [integration] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=13

**Comment by seldondev** [comment]
Tue Jan 21 14:58:12 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=14

**Comment by seldondev** [comment]
Tue Jan 21 14:58:23 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=15

**Comment by adriangonz** [comment]
/unhold

Nice! Changes look good @RafalSkolasinski!

**Comment by RafalSkolasinski** [comment]
Thanks @adriangonz!

Just a note of clarification. Now wrappers will by default:
1. if `requirements.txt` is present pip install it into `base` environment
2. elif `setup.py` is present install it into `base` environment
3. elif `environment.yml` is present conda install it into `microservice` environment

Note: the `environment.yml` must contain `seldon-core`!

The name of environment that `environment.yml` will be install into can be specified using `CONDA_ENV_NAME` environmental variable.

**Comment by RafalSkolasinski** [comment]
And final: /test integration

**Comment by seldondev** [comment]
Tue Jan 21 15:08:33 UTC 2020
The logs for [integration] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=16

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 4e4472d96dbffc560c07212070043d655df9a4ca | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jan 21 16:01:51 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=17

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 4e4472d96dbffc560c07212070043d655df9a4ca | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Integration tests failing because of 
```
no matches for kind "SeldonDeployment" in version "machinelearning.seldon.io/v1alpha2"
```

@adriangonz , @axsaucedo any idea what did I break? :-)

**Comment by adriangonz** [comment]
@RafalSkolasinski I think that the tests are not getting to installing Seldon because of this error during the Kind setup:

```
kubectl rollout status deployment.apps/istio-ingressgateway -n istio-system
Waiting for deployment "istio-ingressgateway" rollout to finish: 0 of 1 updated replicas are available...
error: deployment "istio-ingressgateway" exceeded its progress deadline
make: *** [Makefile:39: install_istio] Error 1
```

**Comment by RafalSkolasinski** [comment]
Oh, so it was even on the earlier stage than I thought...

**Comment by seldondev** [comment]
Tue Jan 21 18:13:45 UTC 2020
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=19

**Comment by seldondev** [comment]
Tue Jan 21 18:13:51 UTC 2020
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=18

**Comment by seldondev** [comment]
Tue Jan 21 18:14:36 UTC 2020
The logs for [integration] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1353/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1353 --build=20

**Comment by RafalSkolasinski** [comment]
Seems that adding `gcc`, `make` and `build-essential`  fixed build issues.

/unhold

**Pull request merged**
