### PR TITLE
bump zap from v1.10.0 to v1.15.0

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/2127

Bumps zap from v1.10.0 to v1.15.0.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 13 18:24:45 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=2

**Comment by seldondev** [comment]
Mon Jul 13 18:24:58 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=1

**Comment by seldondev** [comment]
Mon Jul 13 18:25:04 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=3

**Comment by seldondev** [comment]
Mon Jul 13 18:26:30 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=4

**Comment by RafalSkolasinski** [comment]
integration passed
notebooks failed

/test notebooks

**Comment by seldondev** [comment]
Mon Jul 13 21:32:48 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=5

**Comment by RafalSkolasinski** [comment]
No results of notebook tests available. Re-triggering. 
\test notebooks

**Comment by seldondev** [comment]
Tue Jul 14 08:39:20 UTC 2020
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=6

**Comment by RafalSkolasinski** [comment]
again failure on TestNotebooks.test_istio_canary

**Comment by axsaucedo** [comment]
@RafalSkolasinski if it's only that test can you try running locally? It woudl be good to confirm if there are issues given same test failed twice

**Comment by axsaucedo** [comment]
I just ran the istio test locally. It makes sense why the zap change may be causing this (although not sure how it didn't fail for 0.10 unless it's a expected). The count of requests is done by counting the logs in the executor via `canary_count=!kubectl logs $(kubectl get pod -l seldon-app=mnist-classifier-tf-mnist-predictor -o jsonpath='{.items[0].metadata.name}') seldon-container-engine  | grep "Predictions called" | wc -l`

I can see the requests going through via logs of the model. But the executor seems to no longer print the logs. So if this test didn't fail initially when zap 0.10 was added, it means that either they may have changed their defaults, or currently the log printing isn't working. I'll catch up with @adriangonz to see if this may be config or a nuanced change in their API.

**Comment by seldondev** [comment]
Tue Jul 14 13:19:43 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=7

**Comment by seldondev** [comment]
Tue Jul 14 13:19:50 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=8

**Comment by seldondev** [comment]
Tue Jul 14 13:21:06 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=10

**Comment by seldondev** [comment]
Tue Jul 14 13:21:17 UTC 2020
The logs for [notebooks] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=11

**Comment by seldondev** [comment]
Tue Jul 14 13:22:13 UTC 2020
The logs for [notebooks] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2122/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2122 --build=9

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 2002b48c892edabf9e1ac9c4d3ed3b8cbb303c93 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 2002b48c892edabf9e1ac9c4d3ed3b8cbb303c93 | [link]() | `/test lint`
pr-build | 2002b48c892edabf9e1ac9c4d3ed3b8cbb303c93 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Replaced by https://github.com/SeldonIO/seldon-core/pull/2129

**Pull request closed without merging**
