### PR TITLE
Update income explainer resource examples

### PR DESCRIPTION
**Pull request by cliveseldon**

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sat Feb 15 15:30:30 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1448/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1448 --build=2

**Comment by seldondev** [comment]
Sat Feb 15 15:30:31 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1448/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1448 --build=1

**Comment by seldondev** [comment]
Wed Mar 11 19:06:59 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1448/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1448 --build=3

**Comment by seldondev** [comment]
Wed Mar 11 19:07:02 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1448/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1448 --build=4

**Comment by cliveseldon** [comment]
Closing as I don't think these changes are needed

**Pull request closed without merging**
