### PR TITLE
Upgrading 1.2.2

### PR DESCRIPTION
**Pull request by axsaucedo**
Upgrading 1.2.2

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/release-1.2.2/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 27 18:39:34 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2204/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2204 --build=1

**Comment by seldondev** [comment]
Mon Jul 27 18:39:47 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2204/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2204 --build=2

**Comment by seldondev** [comment]
Mon Jul 27 19:28:42 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2204/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2204 --build=4

**Comment by seldondev** [comment]
Mon Jul 27 19:28:50 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2204/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2204 --build=3

**Comment by axsaucedo** [comment]
Closing to re-add latest

**Pull request closed without merging**
