### PR TITLE
Allow feedback for routers and update router examples

### LINKED ISSUE #2827: Executor does not send feedback to Routers.
https://github.com/SeldonIO/seldon-core/blob/master/executor/predictor/predictor_process.go#L135

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

 * Ensure Feedback is sent to Routers
 * Adds a notebook for epsilon greedy router
 * Updates routers case study

**Which issue(s) this PR fixes**:

Fixes #2827

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jan 21 18:28:33 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2865/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2865 --build=2

**Comment by seldondev** [comment]
Thu Jan 21 18:28:42 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2865/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2865 --build=1

**Comment by axsaucedo** [comment]
Looks good!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2865#issuecomment-767538102 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-767538102/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jan 26 13:26:04 UTC 2021
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2865/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2865 --build=4

**Comment by seldondev** [comment]
Tue Jan 26 13:26:25 UTC 2021
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2865/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2865 --build=3

**Pull request merged**
