### PR TITLE
Add executor to dependabot

### PR DESCRIPTION
**Pull request by adriangonz**
## Changelog

- Track executor dependencies in Dependabot

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jun 19 16:07:50 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=2

**Comment by seldondev** [comment]
Fri Jun 19 16:08:37 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=4

**Comment by seldondev** [comment]
Fri Jun 19 16:08:53 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=1

**Comment by seldondev** [comment]
Fri Jun 19 16:09:57 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=3

**Comment by seldondev** [comment]
Fri Jun 19 16:10:51 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=6

**Comment by seldondev** [comment]
Fri Jun 19 16:11:07 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=5

**Comment by cliveseldon** [comment]
I think we need to be careful as discussed before that certain dependencies need to be updated together for k8s but we can see how it goes.

**Comment by adriangonz** [comment]
/approve

@cliveseldon agreed! Let's trial it and see how it goes.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1984#issuecomment-647500893" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 22 12:57:52 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=7

**Comment by seldondev** [comment]
Mon Jun 22 12:58:01 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1984/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1984 --build=8

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1984#issuecomment-647500893" title="Approved">adriangonz</a>*, *<a href="https://github.com/SeldonIO/seldon-core/pull/1984#pullrequestreview-434906301" title="Approved">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski,adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 07791483ac56dd866c4a5d7911279e3726b0bb66
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 07791483ac56dd866c4a5d7911279e3726b0bb66
* failed to process repo SeldonIO/seldon-core refref 07791483ac56dd866c4a5d7911279e3726b0bb66
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
