### PR TITLE
Manager running as non-root

### LINKED ISSUE #2631: Allow seldon manager to run as non-root
## Describe the bug 
the helm installation of seldon-core-operator failed coz `seldon-controller-manager` fails to start with this error 
```
container has runAsNonRoot and image will run as root
```
So it seems that the image tries to run as a root and our pod security policy dissallow that.

Please have a look into this thread https://seldondev.slack.com/archives/CSVSD5S75/p1605193934193300
## To reproduce
- you need to have a pod security policy in place where it restricts running images as root
- run the helm installation (for seldon-core-operator)

## Expected behaviour
Installation completes successfully and all pods should run not with root user.

## Environment
K8s cluster- AKS v1.18
seldon-core-operator version 1.4.0

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

Allow manager to run as non root.

 * Add `managerUserId` to Helm chart values with a default of 8888
 * Update config webhook to use non-root port 4443
 * Update `split-resources.py` to create helm template with managerUserId variable
 * Cleanup Openshift patches that are run

**Which issue(s) this PR fixes**:

Fixes #2631

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jan 19 11:34:28 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2853/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2853 --build=2

**Comment by seldondev** [comment]
Tue Jan 19 11:34:39 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2853/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2853 --build=1

**Comment by seldondev** [comment]
Tue Jan 19 12:00:31 UTC 2021
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2853/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2853 --build=3

**Comment by axsaucedo** [comment]
Nice!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2853#issuecomment-762799284 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-762799284/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
