### PR TITLE
fixed iris sklearn model example

### PR DESCRIPTION
**Pull request by karan6190**
Fixed the tunnel issue in iris sklearn model example, as no 80 port running inside the pod. Tunnel should be created on Istio ingress gateway service

This Pull Request is for fixing the example where there is issue in creating tunnel for executing the REST API from local

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @karan6190. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by karan6190** [comment]
any update ?

**Comment by cliveseldon** [comment]
Thanks for this. I think this issue is historically because at some point istio ingress changed from pot 80 to 8080. All our other examples port-forward to the istio-ingress pod with port 8080. If we change this to use svc its out of step with the other examples. Maybe we could change to port 8080 which I assume works. A different PR could decide if SVC is better long term?

**Comment by RafalSkolasinski** [comment]
Would suggest to put recommended command there as
```
kubectl port-forward  -n istio-system svc/istio-ingressgateway 8003:80
```
this should work fine

**Comment by karan6190** [comment]
@cliveseldon sure that's make sense, I will alter the Pull request to create a tunnel via pod using 8080 port.

**Comment by karan6190** [comment]
@RafalSkolasinski thanks I will do. So basically Doc say we need to create a tunnel from pod not through svc which do confuse the users. 

I will update the Pull request

**Comment by RafalSkolasinski** [comment]
Well, the whole spirit around it is that model URLs are in format:
```
http(s)://{ingress}/seldon/{namespace}/{sdep name}/...
```

and { ingress } can be your public IP of istio / ambassador ingress. For demos / testing it is just convenient to assume that it is port-forwarded to `localhost:8003` or `localhost:8004` so then all of the example URLs takes format
```
http://localhost:8003/seldon/{namespace}/...
```

**Comment by karan6190** [comment]
@RafalSkolasinski yeah I understand that, but the users like me who are new to istio, got stuck in creating a tunnel.

**Comment by karan6190** [comment]
I have updated the pull request, please have a look

**Comment by RafalSkolasinski** [comment]
Yes, then the command of mine should be straightforward and work without issues.

I wonder why do you need to add `--address 0.0.0.0`? If I am not mistaken that will expose that port on your machine beyond your localhost?

**Comment by karan6190** [comment]
yes, your command will works fine as its doing a port fwd via svc.

--address I have used , in case user is working on Minikube and need to hit the model via local machine in that it will work else the port forwarding will be restricted to 127.0.0.0

**Comment by karan6190** [comment]
so make it generic should we remove --address field ??

**Comment by RafalSkolasinski** [comment]
> --address I have used , in case user is working on Minikube and need to hit the model via local machine in that it will work else the port forwarding will be restricted to 127.0.0.0

Once the local `kubectl` is configured against the cluster inside minikube the port-forward command should have the same effect. At least that is what I remember, we haven't use `Minikube` in a long time as `Kind`is easier to handle and more lightweight. 

Adding `--address 0.0.0.0` potentially exposes your services to the outside world when one may not want it.

> so make it generic should we remove --address field ??

Yes, please. I think it's better without it :)

**Review by RafalSkolasinski — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/3762#pullrequestreview-814967105 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by karan6190** [comment]
> 



> > --address I have used , in case user is working on Minikube and need to hit the model via local machine in that it will work else the port forwarding will be restricted to 127.0.0.0
> 
> Once the local `kubectl` is configured against the cluster inside minikube the port-forward command should have the same effect. At least that is what I remember, we haven't use `Minikube` in a long time as `Kind`is easier to handle and more lightweight.
> 
> Adding `--address 0.0.0.0` potentially exposes your services to the outside world when one may not want it.
> 
> > so make it generic should we remove --address field ??
> 
> Yes, please. I think it's better without it :)

Yeah totally make sense. lets keep it unique.

I have removed the --address field

**Comment by karan6190** [comment]
Hi Team, any idea how these changes can be merged to master ?

**Comment by cliveseldon** [comment]
@karan6190  Thanks!

**Pull request merged**
