### PR TITLE
update initializer image to 0.2.2

### PR DESCRIPTION
**Pull request by ryandawsonuk**
I think we're safe to update the default. For a bit there were questions about the 'latest' one but [not about a tagged version](https://github.com/SeldonIO/seldon-core/issues/1106#issuecomment-555059204). On the other hand we don't have an automated test for the pvc stuff (so to be sure we'd have to check that manually) and don't necessarily need to upgrade this.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Dec 11 16:05:35 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1243/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1243 --build=1

**Comment by seldondev** [comment]
Wed Dec 11 16:05:35 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1243/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1243 --build=2

**Comment by ryandawsonuk** [comment]
Now checked this on GKE using https://github.com/SeldonIO/seldon-core/pull/1308

**Comment by ryandawsonuk** [comment]
Also got it working in DigitalOcean

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1243#issuecomment-570531555" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan  3 10:26:47 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1243/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1243 --build=3

**Comment by seldondev** [comment]
Fri Jan  3 10:26:50 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1243/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1243 --build=4

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 713a06197ef9ebd6084e52793fda522fb0eb9a12 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 713a06197ef9ebd6084e52793fda522fb0eb9a12 | [link]() | `/test this`
lint | 713a06197ef9ebd6084e52793fda522fb0eb9a12 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Closing in favour of https://github.com/SeldonIO/seldon-core/pull/1311

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 713a06197ef9ebd6084e52793fda522fb0eb9a12
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 713a06197ef9ebd6084e52793fda522fb0eb9a12
* failed to process repo SeldonIO/seldon-core refref 713a06197ef9ebd6084e52793fda522fb0eb9a12
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
