### PR TITLE
fix(executor): Update proto compilation and package versions

### PR DESCRIPTION
**Pull request by groszewn**
Updates the `compile_seldon_proto` rule to place the updated protobuf in
the correct location, along with correcting the package name and
updating the grpc package version to work with newer versions of the
proto compiler.

Addresses SeldonIO/seldon-core#1663

Signed off by Nick Groszewski (<groszewn@gmail.com>)

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @groszewn. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by groszewn** [comment]
@cliveseldon Opened based off of our conversation in the [Custom protobuf support PR](https://github.com/SeldonIO/seldon-core/pull/1652)

**Comment by groszewn** [comment]
@cliveseldon just wanted to check in and see if you had any feedback based off of [Custom protobuf support PR](https://github.com/SeldonIO/seldon-core/pull/1652).

**Comment by axsaucedo** [comment]
Thank you @groszewn we'll merge this one first so the other one can go first. Looks good so we'll be able to land once the integration tests pass (excluding some flaky ones)

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1681#issuecomment-616563982" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Apr 20 13:46:21 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1681/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1681 --build=2

**Comment by seldondev** [comment]
Mon Apr 20 13:46:22 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1681/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1681 --build=3

**Comment by seldondev** [comment]
Mon Apr 20 13:46:26 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1681/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1681 --build=1

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref f319010215c0e1d2fdbe8533596c34bccd1eaa39
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha f319010215c0e1d2fdbe8533596c34bccd1eaa39
* failed to process repo SeldonIO/seldon-core refref f319010215c0e1d2fdbe8533596c34bccd1eaa39
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
