### PR TITLE
Update Storage.py and initialiser image

### LINKED ISSUE #1341: Update InitContainer Downloader Image to latest kfserving containing s3 fix
There has been issues and challenges working with S3 due to an issue present in the older version of KFServing (see #885). More specifically, reading from S3 would always fail  unless an environment variable is explicitly added with the AWS_URL value, which meant that even if the S3 URLs were public, it would still fail. This has now been fixed in the latest version of KFserving so updating to the latest image would provide the fix in our side as well.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1341 

## Changelog
- Import latest version of `Storage.py` from KFServing, including tests.

## TODO
- [x] Update default `kfserving/storage-initializer` image.

## Notes
To make SSL optional in S3 URLs, both Seldon and KFServing introduced different environment variables with the same finality: `USE_SSL` and `S3_USE_HTTPS`. You can find the respective PRs here:
- https://github.com/SeldonIO/seldon-core/pull/827
- https://github.com/kubeflow/kfserving/pull/362

In order to make `Storage.py` compatible with the `kfserving/storage-initializer` image and to avoid any breaking changes on users who were already using Seldon's `USE_SSL`, I've made both compatible (with priority for `USE_SSL`).

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan 24 17:46:58 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=1

**Comment by seldondev** [comment]
Fri Jan 24 17:47:06 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=2

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by adriangonz** [comment]
I've rebased from `master` which had the latest version of the Helm charts (and already uses the latest `kfserving/storage-initializer` image).

**Comment by seldondev** [comment]
Tue Jan 28 13:17:50 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=3

**Comment by seldondev** [comment]
Tue Jan 28 13:18:02 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=4

**Comment by axsaucedo** [comment]
@adriangonz this looks solid. I think it would be best to add this PR into the KFServing repo, and update the image to use the latest KFServing version of the image downloader - at least that's how we're doing it atm

**Comment by adriangonz** [comment]
@axsaucedo this PR just copies over the latest version of KFServing's `storage.py` so that it's aligned with the `kfserving/storage-initializer` image. It doesn't really add any extra functionality on top of that.

The only change wrt their repo is adding support for different names of the environment variable which disables SSL in S3 links. But that's mainly so that old versions of Seldon Core don't break with this change.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1368#issuecomment-582132848" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Feb  4 21:53:43 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=5

**Comment by seldondev** [comment]
Tue Feb  4 21:53:51 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1368/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1368 --build=6

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 520543462ba4740da94cf8f9fdbce29465e2660d
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 520543462ba4740da94cf8f9fdbce29465e2660d
* failed to process repo SeldonIO/seldon-core refref 520543462ba4740da94cf8f9fdbce29465e2660d
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
