### PR TITLE
Update amabassador retries and restructure tests for Ambassador

### LINKED ISSUE #1378: Possible enhance ambassador customization in seldon deployment
If one wants to customize the ambassador configuration for a certain Seldon deployment, the user needs to add an annotation to the seldondeployment yaml file by following the link at Seldon document page:
https://docs.seldon.io/projects/seldon-core/en/latest/ingress/ambassador.html#custom-amabassador-configuration

For example, if a user wants to set the num_retries of ambassador for a certain backend service, he/she needs to include an annotation in the seldondeployment yaml file (an example is at the bottom of this page). The annotation looks verbose and easy to make errors. Can Seldon team work on an easy way to customize the ambassador? maybe parameterize some params?

One more question here, I checked the envoy document online, the default value for num_retries at envoy is set to 1. At Seldon, it is set to 3 as default. Are there any reason for choosing 3?

https://www.envoyproxy.io/learn/automatic-retries
```By default, Envoy will set the number of retries to one with num_retries. There’s little downside to increasing this to three, especially for relatively short requests, as Envoy will limit the total time spent to the overall request timeout, including the initial request and all retries.```

======================= seldondeployment yaml file annotation =======
```apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: monitor-backend-service-amba
  namespace: seldon-monitor
spec:
  annotations:
    seldon.io/headless-svc: "true"
    seldon.io/ambassador-config: "apiVersion: ambassador/v1\n\
      kind: Mapping\n\
      name: seldon_seldon-monitor_monitor-backend-service-amba_main_rest_mapping\n\
      prefix: /seldon/seldon-monitor/monitor-backend-service-amba/\n\
      service: monitor-backend-service-amba-monitor-backend-service-amba-main.seldon-monitor:8000\n\
      timeout_ms: 3000\n\
      weight: 100\n\
      retry_policy:\n\
      \  retry_on: connect-failure\n\
      \  num_retries: 1\n\
      --- \n\
      apiVersion: ambassador/v1\n\
      kind: Mapping\n\
      name: seldon_seldon-monitor_monitor-backend-service-amba_main_grpc_mapping\n\
      grpc: true\n\
      prefix: /seldon.protos.Seldon\n\
      rewrite: /seldon.protos.Seldon\n\
      service: monitor-backend-service-amba-monitor-backend-service-amba-main.seldon-monitor:5001\n\
      timeout_ms: 3000\n\
      weight: 100\n\
      headers:\n\
      \  namespace: seldon-monitor\n\
      \  seldon: monitor-backend-service-amba\n\
      retry_policy:\n\
      \  retry_on: connect-failure\n\
      \  num_retries: 2\n"
  name: monitor-backend-service-amba
```

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1378

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jan 30 08:21:36 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=2

**Comment by seldondev** [comment]
Thu Jan 30 08:21:44 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=1

**Comment by seldondev** [comment]
Thu Jan 30 08:23:27 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=3

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 903eaf15bc283d66cbaaab9e618f72d1c5018d53 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jan 30 09:02:37 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 903eaf15bc283d66cbaaab9e618f72d1c5018d53 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan 31 17:07:47 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=5

**Comment by seldondev** [comment]
Fri Jan 31 17:07:47 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=6

**Comment by seldondev** [comment]
Tue Feb  4 11:55:30 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=7

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 66fd4a0d536e799d2bb6a1fe68874962cf9c29a4 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Feb 13 15:07:15 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=8

**Comment by seldondev** [comment]
Thu Feb 27 11:30:26 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=9

**Comment by seldondev** [comment]
Thu Feb 27 11:30:25 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=10

**Comment by axsaucedo** [comment]
Looks good! 
/lgtm
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1383#issuecomment-593843719" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by seldondev** [comment]
Tue Mar  3 09:21:38 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=12

**Comment by seldondev** [comment]
Tue Mar  3 09:21:38 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1383/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1383 --build=11

**Pull request merged**
