### PR TITLE
Update Seldon versions for upgrade tests

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Update the lists of Seldon Core versions that are tested for upgrades. To clarify, these tests validate that these upgrade paths work:

- `1.0.2` -> `master`
- `1.1.0` -> `master`
- `1.2.3` -> `master`
- `1.3.0` -> `master`
- `1.4.0` -> `master`

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

This PR will make the integration tests a bit longer. It's **not clear whether we should test for all direct upgrade paths from `1.0` onwards though**. Would be great to hear other people's thoughts. 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jan 21 11:49:06 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=2

**Comment by seldondev** [comment]
Thu Jan 21 11:49:12 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=1

**Comment by seldondev** [comment]
Thu Jan 21 11:51:04 UTC 2021
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=3

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5798ae7ea266770356ba25d9ed6f8f7496c19017 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jan 22 10:10:42 UTC 2021
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=5

**Comment by seldondev** [comment]
Fri Jan 22 10:10:54 UTC 2021
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=4

**Comment by seldondev** [comment]
Fri Jan 22 14:02:23 UTC 2021
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2861/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2861 --build=6

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9f63907e00c4ea11afac46b2e392fb304284005a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@adriangonz integration test seems to fail on the `test_combiner`, which from the previous test seems flaky. May be worth adding an issue if we see this test_combiner test fail again
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2861#issuecomment-767537265 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-767537265/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
