### PR TITLE
correct file extention to match files

### PR DESCRIPTION
**Pull request by kinihun**
**What this PR does / why we need it**: Prometheus rules configmap is empty because rules files are not matched by glob

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**: NONE

```release-note
```

### CODE REVIEW

**Comment by cliveseldon** [comment]
@kinihun can you clarify which issue this fixes?

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[adriangonz](https://github.com/SeldonIO/seldon-core/pull/2308#issuecomment-691081686 "Approved")*, *[SachinVarghese](https://github.com/SeldonIO/seldon-core/pull/2308#pullrequestreview-472559015 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-691081686/SeldonIO/seldon-core/blob/master/OWNERS)~~ [SachinVarghese,adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Sep 11 13:04:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2308/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2308 --build=1

**Comment by seldondev** [comment]
Fri Sep 11 13:30:39 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2308/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2308 --build=3

**Comment by seldondev** [comment]
Fri Sep 11 13:31:10 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2308/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2308 --build=4

**Pull request merged**
