### PR TITLE
Add mermaid diagrams to pipeline docs page

### PR DESCRIPTION
**Pull request by jklaise**
**What this PR does / why we need it**:
Add basic visualizations of example pipelines in the docs.

**Special notes for your reviewer**:
- This is a draft PR meant to discuss if the visual approach is correct. After this initial review, the intention is, if possible, to factor out these diagrams in stand-alone files and include them in the relevant places in both docs and examples.
- I've chosen to try `mermaid` as it's code based and easier to update and manage than external assets like images, produced with another tool. The trade-off is that the layout and styling options are more limited.
- There are some issues with using both `:caption:` and `:align:` directives, which may be due to the [docs theme](https://github.com/mgaitan/sphinxcontrib-mermaid/issues/90)

See relevant docs page here: https://seldon--4837.org.readthedocs.build/projects/seldon-core/en/4837/contents/pipelines/index.html

### CODE REVIEW

**Comment by cliveseldon** [comment]
These are great - they provide an extra layer of understanding which helps

**Comment by matthewlowdon** [comment]
Super! I have two minor points:

- There are a couple of implicit output joins of type 'any'. Maybe better to show them explicitly?
- tfsimple3's INPUT should be called INPUT1.

**Comment by jklaise** [comment]
Examples without and with explicit `stepsJoin` (output) step:

**Model routing via tensors**
Original:
image
Explicit output join:
image

**Trigger joins**
Original:
image

Explicit output join:
image

@cliveseldon on this last example, what happens on the output if both `mul10` and `add10` are triggered?

**Comment by jklaise** [comment]
Last commit also adds a diagram for the pipeline-pipeline example:
image

**Review by cliveseldon — APPROVED** [review]

**Pull request merged**
