### PR TITLE
Add /health/ping and /health/status endpoint to Python REST Microservices

### PR DESCRIPTION
**Pull request by kparaju**
This PR will add two endpoints to the python REST flask app. 

/health/ping: quick check to make sure the flask app is alive
/health/status: more through check to make sure that the model is healthy

(I'm open to changing the url of these endpoints, these seemed to fit well)

There are two ways we are planning on using these endpoints:

1) After we docker image is built, we will load it up and use /health/ping and /health/status to verify that the final artifact is good.
2) Use it in k8s health checks to make sure that the model is up and predicting (using /health/status) and restart the pod if anything funky happens.
3) In the future, it can also be added to the orchestrator so that clients can know the status and potentially use the Circuit Breaker pattern.

Tested by doing:
```
seldon-core-microservice MyModel REST --service-type MODEL --persistence 0 --workers=2
```
and
```
(base) ➜  ~ curl localhost:5000/health/ping
pong%
(base) ➜  ~ curl localhost:5000/health/status
{"data":{"names":[],"tensor":{"shape":[1],"values":[3]}},"meta":{}}
(base) ➜  ~
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @kparaju. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [seldonio](https://github.com/orgs/seldonio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/seldonio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
@kparaju: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5f9f915cb050e8ae9d6c78b60f11e9b5bb7f6f7c | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
This is great @kparaju! Would be great to add something to the docs. I guess we can to this ourselves (unless you want to add something).

By the way, the linter seems to be failing - you can make sure it works by running `make -C python setup_linter run_linter_check` (details for this in https://github.com/SeldonIO/seldon-core/blob/master/CONTRIBUTING.md)

**Comment by kparaju** [comment]
@axsaucedo I added some docs as well as ran the linter -- sorry about that.

**Comment by axsaucedo** [comment]
This looks solid! All tests pass so happy to land, however there's still the GRPC route missing, as currently the implementation is done in Python but not in GRPC. You can see this in this line:

https://github.com/SeldonIO/seldon-core/blob/3483b118ba4e4cbe8bcad19b9dc98759a7e9336a/python/seldon_core/wrapper.py#L170

**Comment by cliveseldon** [comment]
> This looks solid! All tests pass so happy to land, however there's still the GRPC route missing, as currently the implementation is done in Python but not in GRPC. You can see this in this line:
> 
> https://github.com/SeldonIO/seldon-core/blob/3483b118ba4e4cbe8bcad19b9dc98759a7e9336a/python/seldon_core/wrapper.py#L170

@axsaucedo  I don't think we would change the gRPC as that would require updating the prediction protos - but maybe you didn'tmean this. Better would be the have a lightweight Flask running on a separate port that has just the health endpoints exposed on http?

**Comment by axsaucedo** [comment]
> 
> 
> > This looks solid! All tests pass so happy to land, however there's still the GRPC route missing, as currently the implementation is done in Python but not in GRPC. You can see this in this line:
> > https://github.com/SeldonIO/seldon-core/blob/3483b118ba4e4cbe8bcad19b9dc98759a7e9336a/python/seldon_core/wrapper.py#L170
> 
> @axsaucedo I don't think we would change the gRPC as that would require updating the prediction protos - but maybe you didn'tmean this. Better would be the have a lightweight Flask running on a separate port that has just the health endpoints exposed on http?

Oh yeah you are right actually. Even if the model is a GRPC one, we'd still want to have health endpoints! Ok happy with that then, will resolve request for review

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1026#pullrequestreview-310762785" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Oh my bad, resolving the comment automatically approved it. @cliveseldon I've added a `[slash] hold`, to approve just do `[slash] hold remove`

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1026#issuecomment-549405599" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by kparaju** [comment]
@cliveseldon @axsaucedo updated with documentation about how to use these problems in your SeldonDeployment YAML.

**Comment by seldondev** [comment]
@kparaju: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 51ff940283589f4039d14041a71b87e47b03c22a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
