### PR TITLE
Add TreeShap explainer

### LINKED ISSUE #2361: Add TreeShap Explainer example

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
Adds TreeShap explainer

  * Updates explainer wrapper
  * Adds yaml example to explainer_examples notebook
 
**Which issue(s) this PR fixes**:

Fixes #2361

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Sep  1 18:20:27 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2363/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2363 --build=1

**Comment by seldondev** [comment]
Tue Sep  1 18:20:34 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2363/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2363 --build=2

**Comment by axsaucedo** [comment]
Nice - seems like Alibi Explain is now pretty much feature-covered in SC
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2363#issuecomment-685397816 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-685397816/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Sep  2 07:11:52 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2363/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2363 --build=3

**Comment by seldondev** [comment]
Wed Sep  2 07:12:05 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2363/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2363 --build=4

**Pull request merged**
