### PR TITLE
Bump Envoy to 1.26.1 and Go Control Plane to 0.11.0

### PR DESCRIPTION
**Pull request by rajatvig**
```release-note
Envoy version updated to 1.26.1
```

**What this PR does / why we need it**:
Bump included Envoy to 1.26.1

**Which issue(s) this PR fixes**:
NA

**Special notes for your reviewer**:
The tests passed locally. I bumped the version of `go-control-plane` to `0.11`.

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @rajatvig. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by cliveseldon** [comment]
Thanks for this we will probably add this soon.

**Comment by rajatvig** [comment]
> Thanks for this we will probably add this soon.

Thanks. Could this be looked at soon? Have an in progress follow up to add tracing support to Envoy that depends on the new version. OpenTelemetry support is available in new versions only.

**Comment by RafalSkolasinski** [comment]
We can bring it in after 2.5 release - so probably towards the end of this week

**Review by cliveseldon — APPROVED** [review]

**Pull request merged**
