### PR TITLE
feat(svc): Add predictorSpec annotations to service

### LINKED ISSUE #2590: Allow annotations on Service created by operator
Certain integrations expect annotations placed on the service resource in order to work.  One, in particular, is the datadog healthcheck configuration which can seen [here](https://docs.datadoghq.com/agent/cluster_agent/clusterchecks/#template-source-kubernetes-service-annotations).  

Similarly to how the predictorSpec annotations can be used to provide a [custom service name](https://github.com/SeldonIO/seldon-core/blob/f27558629e321345181b3af1f6a515f104343239/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L137), I'm thinking that we can have the predictorSpec annotations be applied to the corresponding created service as well.  It seems like these annotations would need to be added [here](https://github.com/SeldonIO/seldon-core/blob/13762c055f1e9e146d7c1111fc5d5aefcbf56f42/operator/controllers/seldondeployment_controller.go#L674) for the predictor service and [here](https://github.com/SeldonIO/seldon-core/blob/13762c055f1e9e146d7c1111fc5d5aefcbf56f42/operator/controllers/seldondeployment_controller.go#L769) (if needed) for the container service.

### PR DESCRIPTION
**Pull request by groszewn**
**What this PR does / why we need it**: 

In order to leverage integrations that expect annotations on resources with constant IPs (e.g. services), there needs to be a way to specify annotations to be applied.

**Which issue(s) this PR fixes**:

Fixes #2590

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
Apply predictorSpec annotations to created services
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @groszewn. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thanks @groszewn ! Looks great
/ok-to-test
/test integration

**Comment by seldondev** [comment]
Thu Nov 12 10:19:53 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=1

**Comment by seldondev** [comment]
Thu Nov 12 10:20:37 UTC 2020
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=2

**Comment by seldondev** [comment]
Thu Nov 12 10:22:52 UTC 2020
The logs for [lint] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=3

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c134881221bee1ea82adc0e9d2cf014c6d05908f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@groszewn: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c134881221bee1ea82adc0e9d2cf014c6d05908f | [link]() | `/test this`
integration | c134881221bee1ea82adc0e9d2cf014c6d05908f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun Nov 15 16:29:57 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=4

**Comment by seldondev** [comment]
Sun Nov 15 16:29:59 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=5

**Comment by seldondev** [comment]
Sun Nov 15 16:48:27 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=6

**Comment by seldondev** [comment]
Mon Nov 16 16:26:30 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=7

**Comment by seldondev** [comment]
Mon Nov 16 16:26:35 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=8

**Comment by seldondev** [comment]
Mon Nov 16 16:38:58 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=9

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f0494f0299d6388443668fb486c05c79330b2c7a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Nov 16 17:22:40 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=10

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f0494f0299d6388443668fb486c05c79330b2c7a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Nov 16 18:12:18 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=11

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f0494f0299d6388443668fb486c05c79330b2c7a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Nov 24 02:05:25 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=13

**Comment by seldondev** [comment]
Tue Nov 24 02:07:25 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=12

**Comment by seldondev** [comment]
Tue Nov 24 02:36:30 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=14

**Comment by seldondev** [comment]
Thu Dec 10 10:59:55 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=16

**Comment by seldondev** [comment]
Thu Dec 10 10:59:55 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=15

**Comment by seldondev** [comment]
Thu Dec 10 10:59:57 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2618/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2618 --build=17

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 5081a77daf4aad4a204db1481fd1407763c34b24
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 5081a77daf4aad4a204db1481fd1407763c34b24
* failed to process repo SeldonIO/seldon-core refref 5081a77daf4aad4a204db1481fd1407763c34b24
* failed to list files in directory /var/tmp/gitrepo799923688/.lighthouse
* open /var/tmp/gitrepo799923688/.lighthouse
* no such file or directory

**Pull request merged**
