### PR TITLE
Routers not working with new Executor, fix #1876

### LINKED ISSUE #1876: Routers not working with new Executor
Hi,

When using seldon 1.1 with new executor, router always return first children from its inference graph.

The problem is that when using python or R wrapper the format of message returned is:
{"data":{"ndarray":[[1]]}} 
but new executor expects:
{"data":{"ndarray":[1]}} 
where "1" is a route number.

Old java implementation is working ok with [[1]] ndarray.

I see in the api>rest>client_test.go file that there is wrong okRouteResponse expected.

My local build of the Executor works when changing in api>utill>utils.go func ExtractRouteFromSeldonMessage

Line 13: routeArr[i] = int(value.GetListValue().GetValues()[0].GetNumberValue())

### PR DESCRIPTION
**Pull request by neopobo**
Fixes #1876

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @neopobo. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
Fri May 29 07:28:55 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1890/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1890 --build=1

**Comment by seldondev** [comment]
Fri May 29 07:28:52 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1890/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1890 --build=2

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1890#issuecomment-635820457" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cliveseldon** [comment]
@neopobo  Thanks!

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 06b3e9ed386425819b8a8659f88c2646f18bf4fc
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 06b3e9ed386425819b8a8659f88c2646f18bf4fc
* failed to process repo SeldonIO/seldon-core refref 06b3e9ed386425819b8a8659f88c2646f18bf4fc
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
