### PR TITLE
WIP: release v1.4.0

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

testing release 1.4.0

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Oct 26 11:59:08 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2580/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2580 --build=2

**Comment by seldondev** [comment]
Mon Oct 26 11:59:09 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2580/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2580 --build=3

**Comment by seldondev** [comment]
Mon Oct 26 11:59:10 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2580/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2580 --build=1

**Comment by seldondev** [comment]
Mon Oct 26 11:59:27 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2580/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2580 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ea44282d117088f0a99fc4ce3a237595a51312c8 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
It seems the prepackaged server test failed - namely:
```
[gw2] FAILED test_prepackaged_servers.py::TestPrepack::test_sklearn_v2
[gw1] FAILED test_prepackaged_servers.py::TestPrepack::test_xgboost_v2
```

**Comment by axsaucedo** [comment]
Closing as release has been completed

**Pull request closed without merging**
