### PR TITLE
Fixed explainer controller to handle istio hosts annotation

### LINKED ISSUE #4381: Model explainer does not respect isito hosts annotation
## Describe the bug

When deploying model explainer along with a model in the same `SeldonDeployment`.
The explainer does not respect the `seldon.io/istio-host` annotation.

## To reproduce
1. Follow https://docs.seldon.io/projects/seldon-core/en/latest/analytics/explainers.html
2. Add `seldon.io/istio-host` annotations to `spec.annotations`

## Expected behaviour

The host are set on the underlying Virtual Service

## Environment

Kubernetes 1.23.12
Seldon 1.14.1

## Potential Cause
There are discrepancies in how `seldon.io/istio-host` annotation is applied to underlying `VirtualService`: 

https://github.com/SeldonIO/seldon-core/blob/1e06db27cadb70aff35ee9de5bf552cb0a37a773/operator/controllers/seldondeployment_controller.go#L240-L245

https://github.com/SeldonIO/seldon-core/blob/1e06db27cadb70aff35ee9de5bf552cb0a37a773/operator/controllers/seldondeployment_explainers.go#L325-L331

### PR DESCRIPTION
**Pull request by huangyq23**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #4381

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @huangyq23. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@huangyq23: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4401-integration-qx79z) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by huangyq23** [comment]
@cliveseldon Looks like the failure detail is not public so I am not sure how the integration test can be fixed

**Comment by cliveseldon** [comment]
> @cliveseldon Looks like the failure detail is not public so I am not sure how the integration test can be fixed

Looks like 2 tests failed to do with Alibi-Detetct - they may be flaky and running again to see:

```
=================================== FAILURES ===================================
____________________ TestADServer.test_alibi_detect_cifar10 ____________________

self = <Response [503]>, kwargs = {}

    def json(self, **kwargs):
        r"""Returns the json-encoded content of a response, if any.
    
        :param \*\*kwargs: Optional arguments that ``json.loads`` takes.
        :raises requests.exceptions.JSONDecodeError: If the response body does not
            contain valid json.
        """
    
        if not self.encoding and self.content and len(self.content) > 3:
            # No encoding set. JSON RFC 4627 section 3 states we should expect
            # UTF-8, -16 or -32. Detect which one to use; If the detection or
            # decoding fails, fall back to `self.text` (using charset_normalizer to make
            # a best guess).
            encoding = guess_json_utf(self.content)
            if encoding is not None:
                try:
                    return complexjson.loads(self.content.decode(encoding), **kwargs)
                except UnicodeDecodeError:
                    # Wrong UTF codec detected; usually because it's not UTF-8
                    # but some other 8-bit codec.  This is an RFC violation,
                    # and the server didn't bother to tell us what codec *was*
                    # used.
                    pass
                except JSONDecodeError as e:
                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    
        try:
>           return complexjson.loads(self.text, **kwargs)

/opt/conda/lib/python3.7/site-packages/requests/models.py:971: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'
encoding = None, cls = None, object_hook = None, parse_float = None
parse_int = None, parse_constant = None, object_pairs_hook = None, kw = {}

    def loads(s, *, encoding=None, cls=None, object_hook=None, parse_float=None,
            parse_int=None, parse_constant=None, object_pairs_hook=None, **kw):
        """Deserialize ``s`` (a ``str``, ``bytes`` or ``bytearray`` instance
        containing a JSON document) to a Python object.
    
        ``object_hook`` is an optional function that will be called with the
        result of any object literal decode (a ``dict``). The return value of
        ``object_hook`` will be used instead of the ``dict``. This feature
        can be used to implement custom decoders (e.g. JSON-RPC class hinting).
    
        ``object_pairs_hook`` is an optional function that will be called with the
        result of any object literal decoded with an ordered list of pairs.  The
        return value of ``object_pairs_hook`` will be used instead of the ``dict``.
        This feature can be used to implement custom decoders.  If ``object_hook``
        is also defined, the ``object_pairs_hook`` takes priority.
    
        ``parse_float``, if specified, will be called with the string
        of every JSON float to be decoded. By default this is equivalent to
        float(num_str). This can be used to use another datatype or parser
        for JSON floats (e.g. decimal.Decimal).
    
        ``parse_int``, if specified, will be called with the string
        of every JSON int to be decoded. By default this is equivalent to
        int(num_str). This can be used to use another datatype or parser
        for JSON integers (e.g. float).
    
        ``parse_constant``, if specified, will be called with one of the
        following strings: -Infinity, Infinity, NaN.
        This can be used to raise an exception if invalid JSON numbers
        are encountered.
    
        To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``
        kwarg; otherwise ``JSONDecoder`` is used.
    
        The ``encoding`` argument is ignored and deprecated.
        """
        if isinstance(s, str):
            if s.startswith('\ufeff'):
                raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
                                      s, 0)
        else:
            if not isinstance(s, (bytes, bytearray)):
                raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                                f'not {s.__class__.__name__}')
            s = s.decode(detect_encoding(s), 'surrogatepass')
    
        if (cls is None and object_hook is None and
                parse_int is None and parse_float is None and
                parse_constant is None and object_pairs_hook is None and not kw):
>           return _default_decoder.decode(s)

/opt/conda/lib/python3.7/json/__init__.py:348: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7f7a01292cd0>
s = 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'
_w = <built-in method match of re.Pattern object at 0x7f7a00941c30>

    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
        containing a JSON document).
    
        """
>       obj, end = self.raw_decode(s, idx=_w(s, 0).end())

/opt/conda/lib/python3.7/json/decoder.py:337: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7f7a01292cd0>
s = 'upstream connect error or disconnect/reset before headers. reset reason: connection failure'
idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.
    
        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.
    
        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/opt/conda/lib/python3.7/json/decoder.py:355: JSONDecodeError

During handling of the above exception, another exception occurred:

self = <test_alibi_detect_server.TestADServer object at 0x7f79fbb06e90>
namespace = 'test-alibi-detect-cifar10'

    @pytest.mark.sequential
    def test_alibi_detect_cifar10(self, namespace):
        spec = "../resources/adserver-cifar10-od.yaml"
        name = "cifar10-od-server"
        vs_prefix = name
    
        retry_run(f"kubectl apply -f {spec} -n {namespace}")
    
        wait_for_deployment(name, namespace)
    
        time.sleep(AFTER_WAIT_SLEEP)
    
        with open(self.truck_json) as f:
            data = json.load(f)
    
        for attempt in Retrying(
            wait=wait_fixed(TENACITY_WAIT),
            stop=stop_after_attempt(TENACITY_STOP_AFTER_ATTEMPT),
        ):
            with attempt:
                r = requests.post(
                    f"http://localhost:8004/{vs_prefix}/",
                    json=data,
                    headers=self.HEADERS,
                )
>               j = r.json()

test_alibi_detect_server.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [503]>, kwargs = {}

    def json(self, **kwargs):
        r"""Returns the json-encoded content of a response, if any.
    
        :param \*\*kwargs: Optional arguments that ``json.loads`` takes.
        :raises requests.exceptions.JSONDecodeError: If the response body does not
            contain valid json.
        """
    
        if not self.encoding and self.content and len(self.content) > 3:
            # No encoding set. JSON RFC 4627 section 3 states we should expect
            # UTF-8, -16 or -32. Detect which one to use; If the detection or
            # decoding fails, fall back to `self.text` (using charset_normalizer to make
            # a best guess).
            encoding = guess_json_utf(self.content)
            if encoding is not None:
                try:
                    return complexjson.loads(self.content.decode(encoding), **kwargs)
                except UnicodeDecodeError:
                    # Wrong UTF codec detected; usually because it's not UTF-8
                    # but some other 8-bit codec.  This is an RFC violation,
                    # and the server didn't bother to tell us what codec *was*
                    # used.
                    pass
                except JSONDecodeError as e:
                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    
        try:
            return complexjson.loads(self.text, **kwargs)
        except JSONDecodeError as e:
            # Catch JSON-related errors and raise as requests.JSONDecodeError
            # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/opt/conda/lib/python3.7/site-packages/requests/models.py:975: JSONDecodeError

The above exception was the direct cause of the following exception:

self = <test_alibi_detect_server.TestADServer object at 0x7f79fbb06e90>
namespace = 'test-alibi-detect-cifar10'

    @pytest.mark.sequential
    def test_alibi_detect_cifar10(self, namespace):
        spec = "../resources/adserver-cifar10-od.yaml"
        name = "cifar10-od-server"
        vs_prefix = name
    
        retry_run(f"kubectl apply -f {spec} -n {namespace}")
    
        wait_for_deployment(name, namespace)
    
        time.sleep(AFTER_WAIT_SLEEP)
    
        with open(self.truck_json) as f:
            data = json.load(f)
    
        for attempt in Retrying(
            wait=wait_fixed(TENACITY_WAIT),
>           stop=stop_after_attempt(TENACITY_STOP_AFTER_ATTEMPT),
        ):

test_alibi_detect_server.py:58: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/conda/lib/python3.7/site-packages/tenacity/__init__.py:372: in __iter__
    do = self.iter(retry_state=retry_state)
/opt/conda/lib/python3.7/site-packages/tenacity/__init__.py:351: in iter
    six.raise_from(retry_exc, fut.exception())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None
from_value = JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

>   ???
E   tenacity.RetryError: RetryError[<Future at 0x7f79fbb3dc90 state=finished raised JSONDecodeError>]

<string>:3: RetryError
------------------------------ Captured log setup ------------------------------
INFO     root:seldon_e2e_utils.py:168 Successfully ran command: kubectl create namespace test-alibi-detect-cifar10
------------------------------ Captured log call -------------------------------
INFO     root:seldon_e2e_utils.py:168 Successfully ran command: kubectl apply -f ../resources/adserver-cifar10-od.yaml -n test-alibi-detect-cifar10
INFO     root:seldon_e2e_utils.py:127 Waiting for deployment cifar10-od-server
INFO     root:seldon_e2e_utils.py:134 Successfully waited for deployment cifar10-od-server
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server/ HTTP/1.1" 503 19
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server/ HTTP/1.1" 503 91
________________ TestADServer.test_alibi_detect_cifar10_rclone _________________

self = <Response [503]>, kwargs = {}

    def json(self, **kwargs):
        r"""Returns the json-encoded content of a response, if any.
    
        :param \*\*kwargs: Optional arguments that ``json.loads`` takes.
        :raises requests.exceptions.JSONDecodeError: If the response body does not
            contain valid json.
        """
    
        if not self.encoding and self.content and len(self.content) > 3:
            # No encoding set. JSON RFC 4627 section 3 states we should expect
            # UTF-8, -16 or -32. Detect which one to use; If the detection or
            # decoding fails, fall back to `self.text` (using charset_normalizer to make
            # a best guess).
            encoding = guess_json_utf(self.content)
            if encoding is not None:
                try:
                    return complexjson.loads(self.content.decode(encoding), **kwargs)
                except UnicodeDecodeError:
                    # Wrong UTF codec detected; usually because it's not UTF-8
                    # but some other 8-bit codec.  This is an RFC violation,
                    # and the server didn't bother to tell us what codec *was*
                    # used.
                    pass
                except JSONDecodeError as e:
                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    
        try:
>           return complexjson.loads(self.text, **kwargs)

/opt/conda/lib/python3.7/site-packages/requests/models.py:971: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'no healthy upstream', encoding = None, cls = None, object_hook = None
parse_float = None, parse_int = None, parse_constant = None
object_pairs_hook = None, kw = {}

    def loads(s, *, encoding=None, cls=None, object_hook=None, parse_float=None,
            parse_int=None, parse_constant=None, object_pairs_hook=None, **kw):
        """Deserialize ``s`` (a ``str``, ``bytes`` or ``bytearray`` instance
        containing a JSON document) to a Python object.
    
        ``object_hook`` is an optional function that will be called with the
        result of any object literal decode (a ``dict``). The return value of
        ``object_hook`` will be used instead of the ``dict``. This feature
        can be used to implement custom decoders (e.g. JSON-RPC class hinting).
    
        ``object_pairs_hook`` is an optional function that will be called with the
        result of any object literal decoded with an ordered list of pairs.  The
        return value of ``object_pairs_hook`` will be used instead of the ``dict``.
        This feature can be used to implement custom decoders.  If ``object_hook``
        is also defined, the ``object_pairs_hook`` takes priority.
    
        ``parse_float``, if specified, will be called with the string
        of every JSON float to be decoded. By default this is equivalent to
        float(num_str). This can be used to use another datatype or parser
        for JSON floats (e.g. decimal.Decimal).
    
        ``parse_int``, if specified, will be called with the string
        of every JSON int to be decoded. By default this is equivalent to
        int(num_str). This can be used to use another datatype or parser
        for JSON integers (e.g. float).
    
        ``parse_constant``, if specified, will be called with one of the
        following strings: -Infinity, Infinity, NaN.
        This can be used to raise an exception if invalid JSON numbers
        are encountered.
    
        To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``
        kwarg; otherwise ``JSONDecoder`` is used.
    
        The ``encoding`` argument is ignored and deprecated.
        """
        if isinstance(s, str):
            if s.startswith('\ufeff'):
                raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
                                      s, 0)
        else:
            if not isinstance(s, (bytes, bytearray)):
                raise TypeError(f'the JSON object must be str, bytes or bytearray, '
                                f'not {s.__class__.__name__}')
            s = s.decode(detect_encoding(s), 'surrogatepass')
    
        if (cls is None and object_hook is None and
                parse_int is None and parse_float is None and
                parse_constant is None and object_pairs_hook is None and not kw):
>           return _default_decoder.decode(s)

/opt/conda/lib/python3.7/json/__init__.py:348: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7f7a01292cd0>
s = 'no healthy upstream'
_w = <built-in method match of re.Pattern object at 0x7f7a00941c30>

    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
        containing a JSON document).
    
        """
>       obj, end = self.raw_decode(s, idx=_w(s, 0).end())

/opt/conda/lib/python3.7/json/decoder.py:337: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <json.decoder.JSONDecoder object at 0x7f7a01292cd0>
s = 'no healthy upstream', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
        a JSON document) and return a 2-tuple of the Python
        representation and the index in ``s`` where the document ended.
    
        This can be used to decode a JSON document from a string that may
        have extraneous data at the end.
    
        """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/opt/conda/lib/python3.7/json/decoder.py:355: JSONDecodeError

During handling of the above exception, another exception occurred:

self = <test_alibi_detect_server.TestADServer object at 0x7f79fb944d50>
namespace = 'test-alibi-detect-cifar10-rclone'

    @pytest.mark.sequential
    def test_alibi_detect_cifar10_rclone(self, namespace):
        spec = "../resources/adserver-cifar10-od-rclone.yaml"
        name = "cifar10-od-server-rclone"
        vs_prefix = name
    
        retry_run(f"kubectl apply -f {spec} -n {namespace}")
    
        wait_for_deployment(name, namespace)
    
        time.sleep(AFTER_WAIT_SLEEP)
    
        with open(self.truck_json) as f:
            data = json.load(f)
    
        for attempt in Retrying(
            wait=wait_fixed(TENACITY_WAIT),
            stop=stop_after_attempt(TENACITY_STOP_AFTER_ATTEMPT),
        ):
            with attempt:
                r = requests.post(
                    f"http://localhost:8004/{vs_prefix}/",
                    json=data,
                    headers=self.HEADERS,
                )
>               j = r.json()

test_alibi_detect_server.py:120: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Response [503]>, kwargs = {}

    def json(self, **kwargs):
        r"""Returns the json-encoded content of a response, if any.
    
        :param \*\*kwargs: Optional arguments that ``json.loads`` takes.
        :raises requests.exceptions.JSONDecodeError: If the response body does not
            contain valid json.
        """
    
        if not self.encoding and self.content and len(self.content) > 3:
            # No encoding set. JSON RFC 4627 section 3 states we should expect
            # UTF-8, -16 or -32. Detect which one to use; If the detection or
            # decoding fails, fall back to `self.text` (using charset_normalizer to make
            # a best guess).
            encoding = guess_json_utf(self.content)
            if encoding is not None:
                try:
                    return complexjson.loads(self.content.decode(encoding), **kwargs)
                except UnicodeDecodeError:
                    # Wrong UTF codec detected; usually because it's not UTF-8
                    # but some other 8-bit codec.  This is an RFC violation,
                    # and the server didn't bother to tell us what codec *was*
                    # used.
                    pass
                except JSONDecodeError as e:
                    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    
        try:
            return complexjson.loads(self.text, **kwargs)
        except JSONDecodeError as e:
            # Catch JSON-related errors and raise as requests.JSONDecodeError
            # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
>           raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
E           requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/opt/conda/lib/python3.7/site-packages/requests/models.py:975: JSONDecodeError

The above exception was the direct cause of the following exception:

self = <test_alibi_detect_server.TestADServer object at 0x7f79fb944d50>
namespace = 'test-alibi-detect-cifar10-rclone'

    @pytest.mark.sequential
    def test_alibi_detect_cifar10_rclone(self, namespace):
        spec = "../resources/adserver-cifar10-od-rclone.yaml"
        name = "cifar10-od-server-rclone"
        vs_prefix = name
    
        retry_run(f"kubectl apply -f {spec} -n {namespace}")
    
        wait_for_deployment(name, namespace)
    
        time.sleep(AFTER_WAIT_SLEEP)
    
        with open(self.truck_json) as f:
            data = json.load(f)
    
        for attempt in Retrying(
            wait=wait_fixed(TENACITY_WAIT),
>           stop=stop_after_attempt(TENACITY_STOP_AFTER_ATTEMPT),
        ):

test_alibi_detect_server.py:112: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/conda/lib/python3.7/site-packages/tenacity/__init__.py:372: in __iter__
    do = self.iter(retry_state=retry_state)
/opt/conda/lib/python3.7/site-packages/tenacity/__init__.py:351: in iter
    six.raise_from(retry_exc, fut.exception())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

value = None
from_value = JSONDecodeError('Expecting value: line 1 column 1 (char 0)')

>   ???
E   tenacity.RetryError: RetryError[<Future at 0x7f79fbae6610 state=finished raised JSONDecodeError>]

<string>:3: RetryError
------------------------------ Captured log setup ------------------------------
INFO     root:seldon_e2e_utils.py:168 Successfully ran command: kubectl create namespace test-alibi-detect-cifar10-rclone
------------------------------ Captured log call -------------------------------
INFO     root:seldon_e2e_utils.py:168 Successfully ran command: kubectl apply -f ../resources/adserver-cifar10-od-rclone.yaml -n test-alibi-detect-cifar10-rclone
INFO     root:seldon_e2e_utils.py:127 Waiting for deployment cifar10-od-server-rclone
INFO     root:seldon_e2e_utils.py:134 Successfully waited for deployment cifar10-od-server-rclone
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server-rclone/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server-rclone/ HTTP/1.1" 503 19
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server-rclone/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server-rclone/ HTTP/1.1" 503 91
DEBUG    urllib3.connectionpool:connectionpool.py:231 Starting new HTTP connection (1): localhost:8004
DEBUG    urllib3.connectionpool:connectionpool.py:461 http://localhost:8004 "POST /cifar10-od-server-rclone/ HTTP/1.1" 503 19
===Flaky Test Report===

test_rolling_update6[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update6[istio] passed 1 out of the required 1 times. Success!
test_rolling_update7[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update7[istio] passed 1 out of the required 1 times. Success!
test_rolling_update8[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update8[istio] failed (4 runs remaining out of 5).
	<class 'AssertionError'>
	assert 503 == 200
  -503
  +200
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:140>]
test_rolling_update8[istio] passed 1 out of the required 1 times. Success!
test_rolling_update9[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update9[istio] passed 1 out of the required 1 times. Success!

===End Flaky Test Report===
===== 2 failed, 43 passed, 10 skipped, 65 deselected in 7259.21s (2:00:59) =====
```

**Comment by seldondev** [comment]
@huangyq23: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4401-integration-qx79z) | `/test integration`
notebooks | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4401-notebooks-dk5pp) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@huangyq23: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4401-notebooks-dk5pp) | `/test notebooks`
integration | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4401-integration-rvd8d) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@huangyq23: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4401-integration-rvd8d) | `/test integration`
notebooks | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4401-notebooks-8mv8k) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@huangyq23: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 1db82bfd04850300aef5e40c691a9a8967ce3bba | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-4401-notebooks-dqsf7) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by RafalSkolasinski — APPROVED** [review]
@cliveseldon approved this via comment after merging through JX bot was disabled. Approving and merging.

**Pull request merged**
