### PR TITLE
WIP: [DO NOT MERGE] - Testing JX Upgrade

### PR DESCRIPTION
**Pull request by axsaucedo**
Do not merge

### CODE REVIEW

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-xdp7v) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-xdp7v) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-xdp7v) | `/test integration`
notebooks | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-pj65n) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-gdshx) | `/test release`
notebooks | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-pj65n) | `/test notebooks`
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-z7vcb) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-pj65n) | `/test notebooks`
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-z7vcb) | `/test integration`
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-rj9kq) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-z7vcb) | `/test integration`
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-rj9kq) | `/test release`
notebooks | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-n9xnx) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 93806bbd063ee57dbb43cc532a66e3d61e8bd6a7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-rj9kq) | `/test release`
notebooks | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-n9xnx) | `/test notebooks`
integration | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-nnrhr) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-n9xnx) | `/test notebooks`
integration | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-nnrhr) | `/test integration`
release-build-push | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-59559) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-nnrhr) | `/test integration`
release-build-push | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-59559) | `/test release`
notebooks | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-7t2sl) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/release-build-push-59559) | `/test release`
notebooks | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-7t2sl) | `/test notebooks`
integration | 16e1db63d4e138e660daab0bcc0decc9f6b20bc5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-sm2nk) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Upgrade is complete, closing

**Pull request closed without merging**
