### PR TITLE
build operator image when running e2e locally

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1171

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
Waiting for results to appear in https://github.com/SeldonIO/seldon-core/tree/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 029f5d761e25f92a24f3c6ef82fcc62f35431a99 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Ok [looks like this breaks the in-cluster e2e](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/8.log#L387)

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 114508a472e4aee53ff3bd86a26d74eef1f09d1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 114508a472e4aee53ff3bd86a26d74eef1f09d1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 114508a472e4aee53ff3bd86a26d74eef1f09d1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
This time around some of the s2i tests failed. It looks like[ kind itself in the cluster had trouble](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/11.log#L4372) as well as [the seldon controller](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/11.log#L4369) that led to some [failures in the s2i tests](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/11.log#L4374). Most of the tests [actually passed](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/11.log#L3413) and [even most of the s2i tests](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/11.log#L4603). Looks like a resource issue this time.

**Comment by ryandawsonuk** [comment]
Ok integration tests passed this time.
/approve
/lgtm

**Comment by seldondev** [comment]
@ryandawsonuk: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/SeldonIO/seldon-core/pull/1172#issuecomment-561190792):

>Ok integration tests passed this time.
>/approve
>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1172#issuecomment-561190792" title="LGTM">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
The tests are passing as revealed by `kubectl logs seldonio-seldon-core-pr-1172-in-464fg-15-end-to-end-pd67v-pod-238dee step-test-end-to-end` and `jx get activities | grep 1172` but [nothing seems to be getting logged](https://github.com/SeldonIO/seldon-core/tree/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172) anymore.

[`jx get storage` ](https://jenkins-x.io/commands/jx_edit_storage/)still points at `gh-pages`. Could be something like https://github.com/jenkins-x/jx/issues/2877 but not sure how to find where it fails.

**Comment by ryandawsonuk** [comment]
Just took a backup of the gh-pages branch called gh-pages-backup1219 and deleted the gh-pages branch. Will see what happens on a new run now.

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 114508a472e4aee53ff3bd86a26d74eef1f09d1e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Ok that didn't help, it didn't recreate the branch. I've recreated it manually.

**Comment by ryandawsonuk** [comment]
On suggestion from the jx slack I've restarted `jenkins-x-controllerbuild`.

/test integration

**Comment by ryandawsonuk** [comment]
I see things running now through `jx get build logs`. Still nothing going to gh-pages though.

**Comment by ryandawsonuk** [comment]
New idea is to try doing a `jx upgrade platform`

**Comment by ryandawsonuk** [comment]
`jx upgrade boot` fails with:
```
b83cffd859879e54e9973fdb7b9da7617eb2c998 - feat: add ability to configure exposer
381d34686f85375acc0961b688c6644d41225a05 - Check .Requirements.cluster has a key project in external-dns
6b99c30b1d6ded3336646be32f6d3059cd74e5ef - fix: added velero configuration for iks
164d64440f548142342a3a898a5243bd81cd5490 - fix: disable the build and plank microservices of prow
a8c773903c0a96e036eb7bfab8ff97a8b3acb358 - fix: allow bucketrepo to be used as a repository
46096acecabb9ea86d2aa1fd21a55efb99ab7314 - fix: disable chart museum
1fa391fc6324b52da1a066b0331a4a4a092b987d - fix: use of Requirements.repository
84ba05b583dd6eea3a31013dd6a9861626727177 - fix: Add verify-fmt and fmt, fail PR if not formatted
error: failed to update boot configuration: failed to cherry pick upgrade commits: cherry-picking 6065e8417e538cc4e53d719feb3b0337edb76ea1: git output: The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch de04426a-0d57-4565-ad35-377638eb9c47
You are currently cherry-picking commit 6065e84.

nothing to commit, working tree clean: failed to run 'git cherry-pick 6065e8417e538cc4e53d719feb3b0337edb76ea1 --strategy=recursive -X theirs' command in directory '/tmp/803628616', output: 'The previous cherry-pick is now empty, possibly due to conflict resolution.
If you wish to commit it anyway, use:

    git commit --allow-empty

Otherwise, please use 'git cherry-pick --skip'
On branch de04426a-0d57-4565-ad35-377638eb9c47
You are currently cherry-picking commit 6065e84.
```
Seem to be hitting https://github.com/jenkins-x/jx/issues/5582 

Apparently there have been a range of issues around this recently - https://github.com/jenkins-x/jx/issues/6132. Looks like they're on-going

**Comment by ryandawsonuk** [comment]
Did manage to run `jx upgrade platform` and [now there are new logs](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1172/17.log#L4407) !

**Comment by seldondev** [comment]
@ryandawsonuk: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/SeldonIO/seldon-core/pull/1172#issuecomment-561721521):

>/approve
>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1172#issuecomment-561721521" title="LGTM">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1172#issuecomment-561723381" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
