### PR TITLE
Add Alibi notebook references to explainers notebook

### LINKED ISSUE #2371: Add link to alibi notebooks to reference how the explainer models are built
Currently seldon core explainers integration has almost fully covered all the Alibi explain model types - the example provides detailed examples on how to deploy each explainer type. It would provide full insights for people trying the explainer notebooks if each section had a link to the respective alibi notebook used to train the models, as those are the exact model binaries that are being deployed. This would also provide visibility to users who would want to deploy their own alibi explainers via the server.

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
 * Add Alibi notebook references to explainers notebook

**Which issue(s) this PR fixes**:

Fixes #2371

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Sep  4 12:49:09 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2381/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2381 --build=2

**Comment by seldondev** [comment]
Fri Sep  4 12:49:10 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2381/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2381 --build=1

**Comment by axsaucedo** [comment]
great!
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2381#issuecomment-688407853 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-688407853/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Sep  7 16:11:49 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2381/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2381 --build=3

**Comment by seldondev** [comment]
Mon Sep  7 16:11:56 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2381/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2381 --build=4

**Pull request merged**
