### PR TITLE
update maven in core builder

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1094

apt-get doesn't give a particularly new version but can override with steps from https://tecadmin.net/install-apache-maven-on-debian/

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Dec  9 17:14:12 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=1

**Comment by seldondev** [comment]
Mon Dec  9 17:14:24 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=2

**Comment by seldondev** [comment]
Mon Dec  9 17:32:47 UTC 2019
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=3

**Comment by seldondev** [comment]
Mon Dec  9 17:32:59 UTC 2019
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=4

**Comment by seldondev** [comment]
Mon Dec  9 17:36:32 UTC 2019
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=5

**Comment by seldondev** [comment]
Mon Dec  9 17:36:43 UTC 2019
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=6

**Comment by seldondev** [comment]
Mon Dec  9 17:41:15 UTC 2019
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1222/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1222 --build=7

**Comment by ryandawsonuk** [comment]
Closing this as @gsunner is gonna move the build image to java11

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 3655f769e0e23c64e65533884e83951e4b01d7e6
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 3655f769e0e23c64e65533884e83951e4b01d7e6
* failed to process repo SeldonIO/seldon-core refref 3655f769e0e23c64e65533884e83951e4b01d7e6
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
