### PR TITLE
2744 R Language Wrapper Fix for JSON requests

### LINKED ISSUE #2744: Error when using the R language wrapper
## Describe the bug

When trying to deploy either of the R models which Seldon Core provides (be it [this skeleton](https://github.com/SeldonIO/seldon-core/tree/master/incubating/wrappers/s2i/R/test/model-template-app), or [the iris example](https://github.com/SeldonIO/seldon-core/tree/master/incubating/examples/r_iris)) the model endpoint always returns a HTTP 500 error:
`<simpleError: Argument 'txt' must be a JSON string, URL or file.>`

For reference the payloads that have been tested are:
1. `{"data":{"ndarray":[1, 2]}}`
2. `{"jsonData": [1, 2]}`
3. `{"data":{"names":["a","b"],"ndarray":[[1.0,2.0]]}}`

All of these payloads return the same error. The container works locally and when tested with the `seldon-core-tester`, but fails when deployed onto the Seldon Deploy platform. API calls have been made to the model both via cURL and via the UI- both resulting in the same error.

## To reproduce

1. Train and save your iris model. 
2. Containerise using s2i
3. Test locally using `seldon-core-tester`
4. Push image to registry
5. Deploy onto Seldon Deploy cluster
6. Submit request to endpoint --> 500 error

## Expected behaviour

A submitted request should return a 200 status code, and a prediction based upon the data provided.

## Environment

Seldon Deploy 0.8.2

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #2744

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jan 13 17:16:24 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2837/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2837 --build=2

**Comment by seldondev** [comment]
Wed Jan 13 17:16:27 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2837/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2837 --build=1

**Comment by axsaucedo** [comment]
Tested working with @omerfsen so approving 
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2837#issuecomment-761520003 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-761520003/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sat Jan 16 07:13:57 UTC 2021
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2837/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2837 --build=3

**Comment by seldondev** [comment]
Sat Jan 16 07:13:57 UTC 2021
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2837/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2837 --build=4

**Pull request merged**
