### PR TITLE
feat: bump k8s kind to 1.31

### PR DESCRIPTION
**Pull request by sakoush**
This PR updates KinD installation to use k8s ver 1.31 and  kind 0.24

### CODE REVIEW

**Comment by sakoush** [comment]
Tested with a new kind cluster and it works fine.

**Comment by Rajakavitha1** [comment]
Hi @sakoush I tested the installation on kind via helm and it works.
```Last login: Tue Oct  1 18:43:05 on ttys008
➜  ~ kubectl get nodes
NAME                 STATUS   ROLES           AGE    VERSION
kind-control-plane   Ready    control-plane   2d1h   v1.31.0
➜  ~ kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   2d1h
➜  ~ kubectl get namespaces
NAME                 STATUS   AGE
default              Active   2d1h
kafka                Active   2d1h
kube-node-lease      Active   2d1h
kube-public          Active   2d1h
kube-system          Active   2d1h
local-path-storage   Active   2d1h
seldon               Active   2d1h
seldon-logs          Active   2d1h
seldon-system        Active   2d1h
➜  ~ kubectl get svc -n seldon
NAME                     TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)                                                                                     AGE
mlserver-0               ClusterIP      None           <none>        9000/TCP,9500/TCP,9005/TCP                                                                  2d
seldon-mesh              LoadBalancer   10.96.189.45   <pending>     80:32052/TCP,9003:30939/TCP                                                                 2d
seldon-pipelinegateway   ClusterIP      None           <none>        9010/TCP,9011/TCP                                                                           2d
seldon-scheduler         LoadBalancer   10.96.133.65   <pending>     9002:32076/TCP,9004:31978/TCP,9044:32627/TCP,9005:30468/TCP,9055:30523/TCP,9008:32761/TCP   2d
triton-0                 ClusterIP      None           <none>        9000/TCP,9500/TCP,9005/TCP                                                                  2d
➜  ~ 
```

**Comment by sakoush** [comment]
@Rajakavitha1 thanks could you approve the PR then?

**Review by lc525 — APPROVED** [review]
Lgtm. I assume the node image is the one used by default by this kind version, right? There were some problems with mixing & matching in the past, as a function of the particular versions used.

**Comment by sakoush** [comment]
> Lgtm. I assume the node image is the one used by default by this kind version, right? There were some problems with mixing & matching in the past, as a function of the particular versions used.

yes it is.

**Pull request merged**
