### PR TITLE
Fix image version bug to not overwrite non seldon images

### LINKED ISSUE #2511: Triton Server Image Incorrect
## Describe the bug

The triton server image has been set to 1.3.0 by an automated release script.
This image needs to be specific to nvidia and is presently `20.08-py3`

## To reproduce
run http://localhost:8888/notebooks/protocol_examples.ipynb

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

The `release.py` script changes all prepacked server image versions including new Triton image version. It should only change seldon images versions.

https://github.com/SeldonIO/seldon-core/blob/e1fbcfdd4bdde9c101cab1d18a3f50cdbfe8ccb4/helm-charts/seldon-core-operator/values.yaml#L127-L133

**Which issue(s) this PR fixes**:

Fixes #2511 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Oct  1 17:48:17 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2513/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2513 --build=2

**Comment by seldondev** [comment]
Thu Oct  1 17:49:43 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2513/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2513 --build=1

**Comment by axsaucedo** [comment]
It seems that `get_current_version` assumes that the `version.txt` holds the previous version which would be aligned to the one from the images, but normally the version.txt file holds the "next" version, and then the script uses it to then replace all the components.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2513#issuecomment-709281662 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-709281662/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Oct 15 12:35:42 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2513/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2513 --build=3

**Comment by seldondev** [comment]
Thu Oct 15 12:35:45 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2513/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2513 --build=4

**Pull request merged**
