### PR TITLE
fix push of conda base image

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

- fixes push of conda base image: `seldonio/conda-ubi8`
- makes sure that specified version of `conda` is used in derived images
- remove `Dockerfile.redhat` as at this point it is the same as `Dockerfile.local`

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/3405
Closes https://github.com/SeldonIO/seldon-core/issues/3115

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by RafalSkolasinski** [comment]
Licence lint is fixed in https://github.com/SeldonIO/seldon-core/pull/3404

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-5qpp2) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-5qpp2) | `/test notebooks`
integration | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3406-integration-cvlb9) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-5qpp2) | `/test notebooks`
integration | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3406-integration-cvlb9) | `/test integration`
release-build-push | 05c29ef2aadd3aa56291a605b4cb1b9e89b7cda1 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3406-release-build-push-mk8md) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | ba957c66b3a58bd79fbb3259d8f27ce01f5077da | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-5qpp2) | `/test notebooks`
release-build-push | 05c29ef2aadd3aa56291a605b4cb1b9e89b7cda1 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3406-release-build-push-mk8md) | `/test release`
integration | 13796f23bfeae117a3e35a4ba3f1c2e6c50e9e8e | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3406-integration-gkpsw) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 05c29ef2aadd3aa56291a605b4cb1b9e89b7cda1 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3406-release-build-push-mk8md) | `/test release`
integration | 13796f23bfeae117a3e35a4ba3f1c2e6c50e9e8e | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3406-integration-gkpsw) | `/test integration`
notebooks | 13796f23bfeae117a3e35a4ba3f1c2e6c50e9e8e | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-fvbw9) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Notebook and integration tests have already passed. 
Just rebased onto master to include lint fixes. 
Triggering tests again for completness.

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 05c29ef2aadd3aa56291a605b4cb1b9e89b7cda1 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3406-release-build-push-mk8md) | `/test release`
notebooks | ab74a6938800780a7392dcaf35f3efc65c1859e7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-dlr79) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Failure on `TestNotebooks.test_server_examples` that didn't happen before.
Triggering again 

/test notebooks

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 05c29ef2aadd3aa56291a605b4cb1b9e89b7cda1 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3406-release-build-push-mk8md) | `/test release`
notebooks | ab74a6938800780a7392dcaf35f3efc65c1859e7 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3406-notebooks-7vrmx) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
