### PR TITLE
Kafka - Make Producer optional and add the option to add configurations

### PR DESCRIPTION
**Pull request by naor2013**
**What this PR does / why we need it**:
I'll start by saying I have no golang experience at all. I don't know if what I wrote works as I intended or even compiles correctly.
It would be great to get the help of the team or the community to point me into the right direction, or even better, finish this project for me.

This PR is meant to change 2 things with the Kafka executor of Seldon.
The first thing is to make the Producer optional. We want to be able to trigger predictions based on data coming from a Kafka Consumer but in the prediction, we actually save the data in a remote place (a DB, for example) and don't want to return anything to any Kafka Producer.
The second thing is to give the users (us, in this case) the option to add configuration data to the Kafka Consumer/Producer.
For example, in our case, our Kafka infrastructure needs a username and a password to access the broker's topics. It is currently not possible with Seldon.

**Which issue(s) this PR fixes**:

There is no issue at the moment but I can open one if really necessary.

**Special notes for your reviewer**:
One thing I didn't take into account is the "full graph kafka server" option. I didn't understand what it does or how to change things in that part of the codebase so none of my additions is currently available there.

**Does this PR introduce a user-facing change?**:

```release-note
Kafka - Make Producer optional and add the option to add configurations
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @naor2013. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you for the contribution @naor2013 - these are really interesting points. I think it would be worth exploring these a bit further before jumping into the PR, namely as there are quite a few things to take into consideration (as well as two separate components being addressed in a single PR). I would suggest opening an issue so we can discuss these in more detial on how these can be addressed - more on why we'd need further breakdown below.

In regards to the first point - namely the ability to make producer optional - we should consider that the "callers" or producers of inference datapoints may still require an output instance produced to acknowledge end-to-end processing, an example can be found in our implementation of the kafka enabled service orchestrator graph which executes the seldon computational graph with kafka topics, but still has the respective logic to ensure data instances flow through each of the nodes (this is particularly important with combiner/aggregating nodes). Due to this, we may require always the producer outputto be available - although I could see that perhaps there could be cases like yours where you may not want this, so this is still interesting.

In regards to the point about kafkaProducerEnvs and kafkaConsumerEnvs, it makes a lot of sense - I have a couple of questions:
1) Are the expected parameters supposed to be lower case with `"."`? The normal convention of env vars is capital letter and underscores. Is there a standard in which kafka expects these to be in that format or is this assumption on what you're defining?
2) Are there other configurations other than producer / consumer that should also be added when creating the resources?

I think this PR could focus on the latter point, as that's certainly something that could bring immediate value. From the point you mentioned it sounds like you didn't run it locally or try to compile it? If that's the case it's best if you open an issue with the details here and we can then prioritise the work accordingly, as this is quite a key part of the codebase and we need to make sure the code is sound and that the respective tests are added.

**Comment by naor2013** [comment]
@axsaucedo I really appreciate the quick and thoughtful response.
I opened 2 issues, #3224 for the optional producer and #3225 for the configurations.
I answered all your questions and concerns there.
I did not test or compile my code but I think it might still have value to either continue from where I started or at least if starting fresh, to look at what I wrote to save some time.
As you said, the configurations issue is way more important because without it I can't work with the Kafka executor, but the optional producer is important as well because we have a use case for it.

**Comment by axsaucedo** [comment]
Perfect - I have seen both issues, thank you for opening them @naor2013. Coincidentally we are currently doing some evaluations to explore our current roadmap/strategy in regards to interoperability and integrations with Kafka, so we'll be able to take those into consideration. I will sync with the team to see if we'd be able to continue the work from this PR or start a new one, if you are interested/willing to add some tests on this PR and run locally that would certainly help as well.

**Comment by axsaucedo** [comment]
Closing in favour of the open issues

**Pull request closed without merging**
