### PR TITLE
Updating Security CI Script after requirements.txt all moved to setup.py

### PR DESCRIPTION
**Pull request by axsaucedo**
The requirements.txt was removed from the python folder to streamline the management of dependencies. Updating the security scripts to reflect these changes.

### CODE REVIEW

**Comment by axsaucedo** [comment]
Testing securitychecks (expecting to fail only on alredy known CVEs)
/test securitychecks

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Aug 25 16:36:19 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=1

**Comment by seldondev** [comment]
Tue Aug 25 16:37:07 UTC 2020
The logs for [securitychecks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=3

**Comment by seldondev** [comment]
Tue Aug 25 16:37:32 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=2

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
securitychecks | 53ea83f978f15d941bee426930409e691ac2e93f | [link]() | `/test securitychecks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
securitychecks | 53ea83f978f15d941bee426930409e691ac2e93f | [link]() | `/test securitychecks`
pr-build | 53ea83f978f15d941bee426930409e691ac2e93f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Aug 25 16:54:30 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=4

**Comment by seldondev** [comment]
Tue Aug 25 16:54:30 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=5

**Comment by seldondev** [comment]
Tue Aug 25 16:55:23 UTC 2020
The logs for [securitychecks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2325/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2325 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 53ea83f978f15d941bee426930409e691ac2e93f | [link]() | `/test this`
securitychecks | 6850b9e8bbd3f5d184b80b1bd574d91f11430b77 | [link]() | `/test securitychecks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
It seems the issue with the setup.py is beyond the current setup, and have opened an issue in https://github.com/snyk/snyk/issues/1367

**Comment by axsaucedo** [comment]
Closing in favour of #2398

**Pull request closed without merging**
