### PR TITLE
change to 1.3.0-dev

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Run `./release 1.3.0-dev` so we can track a new dev version

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Sep  3 13:18:31 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=2

**Comment by seldondev** [comment]
Thu Sep  3 13:18:37 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=1

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9730cff6ad7672ec5fb76992756f77da8bfe3662 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep  3 14:35:37 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9730cff6ad7672ec5fb76992756f77da8bfe3662 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep  8 10:40:34 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=5

**Comment by seldondev** [comment]
Tue Sep  8 10:40:50 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=6

**Comment by seldondev** [comment]
Tue Sep  8 10:40:59 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=7

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c5a1f20e632becdef5556c7d28e28fad2b540ea5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
this will need to be rebased on master once https://github.com/SeldonIO/seldon-core/pull/2404 is merged

**Comment by RafalSkolasinski** [comment]
@axsaucedo when tagging 1.3.0 I get some engine related errors
```
❯❯❯ ./release 1.3.0-dev                                                                                 (seldon-tests)   (⎈ kind-kind|seldon)
Updated python wrapper in matching files
updated kustomize
updated kustomize
updated operator/config/manager/kustomization.yaml
Updated version.txt
Updated python/seldon_core/version.py
error /work/engine/pom.xml
{'stderr': b'', 'stdout': b"[INFO] Scanning for projects...\nDownloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-starter-parent/2.2.0.RELEASE/spring-boot-starter-parent-2.2.0.RELEASE.pom\n[WARNING] Failed to create parent directories for tracking file /tmp/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.2.0.RELEASE/spring-boot-starter-parent-2.2.0.RELEASE.pom.lastUpdated\n[ERROR] [ERROR] Some problems were encountered while processing the POMs:\n[FATAL] Non-resolvable parent POM for io.seldon.engine:seldon-engine:1.2.3-dev: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.RELEASE from/to central (https://repo.maven.apache.org/maven2): /tmp/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.2.0.RELEASE/spring-boot-starter-parent-2.2.0.RELEASE.pom.part.lock (No such file or directory) and 'parent.relativePath' points at wrong local POM @ line 6, column 11\n @ \n[ERROR] The build could not read 1 project -> [Help 1]\n[ERROR]   \n[ERROR]   The project io.seldon.engine:seldon-engine:1.2.3-dev (/work/engine/pom.xml) has 1 error\n[ERROR]     Non-resolvable parent POM for io.seldon.engine:seldon-engine:1.2.3-dev: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.2.0.RELEASE from/to central (https://repo.maven.apache.org/maven2): /tmp/.m2/repository/org/springframework/boot/spring-boot-starter-parent/2.2.0.RELEASE/spring-boot-starter-parent-2.2.0.RELEASE.pom.part.lock (No such file or directory) and 'parent.relativePath' points at wrong local POM @ line 6, column 11 -> [Help 2]\n[ERROR] \n[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.\n[ERROR] Re-run Maven using the -X switch to enable full debug logging.\n[ERROR] \n[ERROR] For more information about the errors and possible solutions, please read the following articles:\n[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException\n[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException"}
updated /work/helm-charts/seldon-core-operator/Chart.yaml
updated /work/helm-charts/seldon-core-analytics/Chart.yaml
updated operator values yaml for core images
updated operator values yaml for prepackaged server images
updated operator values yaml for prepackaged server images
updated operator kustomize yaml for prepackaged server images
updated operator/Dockerfile.redhat
updated engine/Dockerfile.redhat
updated executor/Dockerfile.executor
updated executor/Dockerfile.executor.redhat
updated servers/tfserving/Dockerfile.redhat
updated components/alibi-detect-server/Dockerfile
updated components/storage-initializer/Dockerfile
updated components/seldon-request-logger/Dockerfile
updated components/alibi-explain-server/Dockerfile
done
```

**Comment by seldondev** [comment]
Tue Sep 15 15:10:30 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=9

**Comment by seldondev** [comment]
Tue Sep 15 15:10:47 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=8

**Comment by seldondev** [comment]
Tue Sep 15 15:11:35 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=11

**Comment by seldondev** [comment]
Tue Sep 15 15:11:36 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=10

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | c5a1f20e632becdef5556c7d28e28fad2b540ea5 | [link]() | `/test integration`
notebooks | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test notebooks`
integration | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 15 15:40:18 UTC 2020
The logs for [notebooks] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=12

**Comment by seldondev** [comment]
Tue Sep 15 15:40:23 UTC 2020
The logs for [integration] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=13

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test integration`
notebooks | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep 15 18:57:26 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=14

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 16 08:29:45 UTC 2020
The logs for [notebooks] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=15

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f11b1c780062d8e320d6fab65a00cb9ad436364e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 16 12:01:07 UTC 2020
The logs for [lint] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=17

**Comment by seldondev** [comment]
Wed Sep 16 12:01:10 UTC 2020
The logs for [integration] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=19

**Comment by seldondev** [comment]
Wed Sep 16 12:01:22 UTC 2020
The logs for [notebooks] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=18

**Comment by seldondev** [comment]
Wed Sep 16 12:01:44 UTC 2020
The logs for [pr-build] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=16

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 50dc0fd01eea30696aff7775ace0cce5d1407f1d | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep 16 14:16:03 UTC 2020
The logs for [notebooks] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=20

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 50dc0fd01eea30696aff7775ace0cce5d1407f1d | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 21 21:28:53 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=21

**Comment by seldondev** [comment]
Mon Sep 21 21:28:58 UTC 2020
The logs for [notebooks] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=23

**Comment by seldondev** [comment]
Mon Sep 21 21:29:01 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=22

**Comment by seldondev** [comment]
Mon Sep 21 21:30:38 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2373/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2373 --build=24

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2373#issuecomment-696645455 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-696645455/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
