### PR TITLE
fix transport missing in executor

### LINKED ISSUE #4101: kafka server with seldon protocol and grpc transport sends requests to REST endpoint, not gRPC
## Describe the bug
The SeldonDeployment is routing kafka messages to the REST endpoint even though the transport defined as gRPC.

We were following the various Seldon + Kafka examples, but notably none are using the `protocol: seldon`, `transport: grpc` and `serverType: kafka` combination.

Our `SeldonDeployment` with manifest-snippet:
```yaml
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
...
spec:
  name: object-detector
  protocol: seldon
  transport: grpc
  serverType: kafka
  predictors:
    - name: default
      componentSpecs:
        - spec:
            containers:
              - name: default
...
```
deploys okay and we can send gRPC requests directly to the service through port 5000.

Tailing the `seldon-container-engine` logs gives messages like:
```bash
2022-05-17T11:50:03.783Z        INFO    entrypoint.maxprocs     maxprocs: Leaving GOMAXPROCS=8: CPU quota undefined
2022-05-17T11:50:03.783Z        INFO    entrypoint      Hostname unset will use localhost
...
2022-05-17T11:50:03.786Z        INFO    entrypoint      Starting        {"worker": 10}
2022-05-17T11:50:03.787Z        INFO    entrypoint      Starting kafka server
2022-05-17T11:50:03.787Z        INFO    entrypoint      Start http kafka graph
...
2022-05-17T11:56:27.344Z        DEBUG   JSONRestClient  Calling HTTP    {"URL": "http://localhost:9000/predict"}
2022-05-17T11:56:27.347Z        INFO    JSONRestClient  httpPost failed {"response code": 500}
2022-05-17T11:56:27.347Z        ERROR   entrypoint.KafkaServer  Failed prediction       {"error": "Internal service call from executor failed calling http://localhost:9000/predict status code 500"}

```

The `Start http kafka graph`  INFO log suggests the [executor/api/kafka/server.go](https://github.com/SeldonIO/seldon-core/blob/d90766da8bfc418c0c339a145cb100e7d8376c58/executor/api/kafka/server.go#L65) is creating a `rest.NewJSONRestclient` instead of a [seldon.NewSeldonGrpcClient`](https://github.com/SeldonIO/seldon-core/blob/d90766da8bfc418c0c339a145cb100e7d8376c58/executor/api/kafka/server.go#L71), as on server.go#L71.

The `seldon-container-engine` log entry
  `2022-05-17T11:56:27.344Z        DEBUG   JSONRestClient  Calling HTTP    {"URL": "http://localhost:9000/predict"}` 
confirms that the kafka consumer is using the JSONRestClient instead of the Grpc one.

Looking through the seldon-core code, I think this can be traced to the [operator/controllers/seldondeployment_engine.go#L187](https://github.com/SeldonIO/seldon-core/blob/17110a520565446688a26a2c385be91685ecca05/operator/controllers/seldondeployment_engine.go#L187).

The `createExecutorContainer` extracts the `protocol` and `serverType` from the deployment spec, **but not the transport**.

Finally, the [main executor](https://github.com/SeldonIO/seldon-core/blob/17110a520565446688a26a2c385be91685ecca05/executor/cmd/executor/main.go#L70) uses the default transport, set to `rest` instead of having the spec passed-through.

## Expected behaviour
gRPC messages serialized to a kafka topic should be forwarded to a gRPC client, not the JSON REST one.

## Environment

* Cloud Provider: AWS and k3d
* Kubernetes Cluster Version
  ```bash
   > kubectl version
   Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", 
   GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
   Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+k3s1", 
   GitCommit:"8432d7f239676dfe8f748c0c2a3fabf8cf40a826", GitTreeState:"clean", BuildDate:"2022-02-24T23:03:47Z", 
   GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
   ```
* Deployed Seldon System Images:
   ```bash
   > kubectl get --namespace seldon-system deploy seldon-controller-manager -o yaml  | grep seldonio
   value: docker.io/seldonio/seldon-core-executor:1.13.1
   image: docker.io/seldonio/seldon-core-operator:1.13.1
   ```

* Logs of your model (tail, upon publishing a gRPC-encoded message):
  ```bash
  2022-05-17 16:42:13,047 - seldon_core.wrapper:handle_generic_exception:53 - ERROR:  {'status': {'status': 1, 'info': "400 Bad   Request: Failed to decode JSON object: 'utf-8' codec can't decode byte 0xc2 in position 1: invalid continuation byte", 'code': -1, 'reason': 'MICROSERVICE_INTERNAL_ERROR'}}
  2022-05-17 16:42:13,047 - werkzeug:_log:225 - INFO:  127.0.0.1 - - [17/May/2022 16:42:13] "POST /predict HTTP/1.1" 500 -

   ```

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

Ensure transport is sent to executor as is needed for Kafka processing. Also adds fixes for cifar10 demo.

**Which issue(s) this PR fixes**:

Fixes #4101

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9766f153dc7cf256cb57802ca09e78f3b6a7a935 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4107-integration-8nrd5) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Merging as both integration tests confirmed (and fixed) via #4142

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/4107#issuecomment-1149794165 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
