### PR TITLE
update version of operator in executor deps

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/2091
Closes https://github.com/SeldonIO/seldon-core/issues/2134

Most changes in this PR are related to https://github.com/SeldonIO/seldon-core/commit/3b4c9905fa2463fe983dd278a557d3ccd73700ec#diff-d7ca7b021e6d991a2ce6ffca9a69e42d in which `PredictorSpec.PredictiveUnit` stopped being a pointer.

~~This is because we bumped version as:
`v0.0.0-20200401123312-d4c435ea5217` -> `v0.0.0-20200713173314-b8a92914e17e`~~

Update:
In last commit I explore possibility to use local copy of operator.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 13 17:15:22 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=1

**Comment by seldondev** [comment]
Mon Jul 13 17:15:25 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=2

**Comment by seldondev** [comment]
Mon Jul 13 17:16:50 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=3

**Comment by seldondev** [comment]
Mon Jul 13 17:16:59 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=4

**Comment by seldondev** [comment]
Mon Jul 13 17:42:52 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=5

**Comment by seldondev** [comment]
Mon Jul 13 17:43:15 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=6

**Comment by seldondev** [comment]
Mon Jul 13 17:43:38 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=7

**Comment by seldondev** [comment]
Mon Jul 13 17:43:43 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=8

**Comment by RafalSkolasinski** [comment]
/hold

I noticed that operator has `go.uber.org/zap v1.10.0` but `go.uber.org/zap v1.15.0` is available. Let's merge that into `operator` first. Opening PR shortly.

**Comment by RafalSkolasinski** [comment]
After https://github.com/SeldonIO/seldon-core/pull/2122 is merged I will update this PR.

**Comment by seldondev** [comment]
Tue Jul 14 09:51:54 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=10

**Comment by seldondev** [comment]
Tue Jul 14 09:51:56 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=9

**Comment by seldondev** [comment]
Tue Jul 14 09:54:54 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=12

**Comment by seldondev** [comment]
Tue Jul 14 09:55:19 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=11

**Comment by seldondev** [comment]
Tue Jul 14 09:58:18 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=13

**Comment by seldondev** [comment]
Tue Jul 14 09:58:49 UTC 2020
The logs for [integration] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=14

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | f17df2bf3feab9844db54d0678ae38bb827d3b20 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ee14258a0a5a02a857c631a0c8dd6359ebff3cd4 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 10:19:12 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=16

**Comment by seldondev** [comment]
Tue Jul 14 10:19:43 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=15

**Comment by RafalSkolasinski** [comment]
Executing tests again as they were garbage collected before I could take a look at results...
/test notebooks
/test integration

**Comment by seldondev** [comment]
Tue Jul 14 14:05:30 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=17

**Comment by seldondev** [comment]
Tue Jul 14 14:05:42 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=18

**Comment by RafalSkolasinski** [comment]
Rebased on https://github.com/SeldonIO/seldon-core/pull/2121 and should go after this one (as there most likely be a tiny merge conflict)

**Comment by seldondev** [comment]
Tue Jul 14 15:33:12 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=19

**Comment by seldondev** [comment]
Tue Jul 14 15:33:13 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=20

**Comment by RafalSkolasinski** [comment]
Integrations passed, waiting for notebooks still.

**Comment by RafalSkolasinski** [comment]
/unhold

rebased on master as https://github.com/SeldonIO/seldon-core/pull/2129 got merged 

/test integration
/test notebooks

**Comment by seldondev** [comment]
Tue Jul 14 19:30:21 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=21

**Comment by seldondev** [comment]
Tue Jul 14 19:30:28 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=22

**Comment by seldondev** [comment]
Tue Jul 14 19:31:18 UTC 2020
The logs for [notebooks] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=23

**Comment by seldondev** [comment]
Tue Jul 14 19:31:36 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2121/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2121 --build=24

**Comment by RafalSkolasinski** [comment]
Integrations passed. Waiting for notebooks.

**Comment by RafalSkolasinski** [comment]
Notebooks passed as well!
Ready to landm @axsaucedo :rocket:

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2121#issuecomment-658694518 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-658694518/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by RafalSkolasinski** [comment]
Initiating manual merge as tests passed but their status on Github didn't get updated.

**Pull request merged**
