### PR TITLE
#646 Move setup outside example notebooks

### PR DESCRIPTION
**Pull request by glindsell**
#646 

- New setup notebook created and referenced in example notebooks.

- Testing of notebooks raised the following issues:

#1177 

#1178 

#1179

#473 is also still appearing in https://github.com/SeldonIO/seldon-core/blob/master/notebooks/helm_examples.ipynb

Signed-off-by: glindsell <gl@seldon.io>

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
@glindsell nice one! RIgh now you seem to have covered the `notebooks` folder, but there are quite a few more in the `examples` folder that would also need modifying (that's where the larger number of examples live)

**Comment by glindsell** [comment]
Replaced by #1187

**Comment by glindsell** [comment]
@axsaucedo Have created separate issue for Example Notebooks https://github.com/SeldonIO/seldon-core/issues/1154

**Pull request closed without merging**
