### PR TITLE
Performance fix for the logger in the executor

### LINKED ISSUE #3726: OOM when stress test the Seldon model, which may be caused by the logging of request and response payloads
Describe the bug

When we stress test the Seldon model, we find that OOM errors occur after sending a large number of requests.We monitored the containers in the pod and discovered the model container reaches its memory limit and is eventually killed due to OOM. And when we disabled the logging of request and response payloads from Seldon Deployment(by comment the logger), it won't be OOM. I wonder what may be the real reason of OOM. Is it because there are too many logs in memory, resulting in oom?

graph:
      children: []
      endpoint:
        type: "REST"
      #logger:
      # mode: "all"

### PR DESCRIPTION
**Pull request by ivan-valkov**
**What this PR does / why we need it**:

The logger in the executor spins a goroutine for each prediction and waits until the payload can be logged. With a slow downstream request logger and a huge spike of requests, the executor can OOM. 

This PR makes a couple of changes to allow for more graceful handling of such spikes of traffic:
* Increase the default work queue size and make it configurable - now we use the channel to buffer work. We no longer use goroutines that wait to write to the channel as a buffer
* Add a configurable timeout for when the buffer is full. This means logs can be dropped if there is too much work for the executor and downstream log processing to handle.
* Increase the default workers - they are waiting on I/O most of the time so they can be more than they used to be.

There is also a general refactor of the consumer/producer pattern we use to make it easier to understand and use without changing the behaviour.

This PR also adds a benchmark for profiling the behaviour of the executor. It was used to confirm that before we can see a linear increase in the number of goroutines with the number of requests. These goroutines also never finished if the request logging was taking ages to process. The new implementation shows a steady number of goroutines allocated for logging no matter how many requests we have.

We will need to expose the following flags in the operator so that they can be configured from there:
* `logger_workers`
* `log_work_buffer_size`
* `log_write_timeout_ms`

**Which issue(s) this PR fixes**:

Fixes #3726

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by michaelcheah — APPROVED** [review]
lgtm

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[michaelcheah](https://github.com/SeldonIO/seldon-core/pull/3734#pullrequestreview-805089370 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cliveseldon** [comment]
@ivan-valkov Great. Will open another PR to add Helm chart parameters.

**Pull request merged**
