### PR TITLE
Change hashicorp/hcl dependency url to match new main branch

### PR DESCRIPTION
**Pull request by ivan-valkov**
**What this PR does / why we need it**:

The new main branch here has changed - https://github.com/hashicorp/hcl
~~It is not master anymore so these `wget`s don't work.~~
It is actually `hcl1` for the dependency we use - https://github.com/hashicorp/hcl/wiki/Version-Selection 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Runnint test only to verify succesful image build 
/test integration

**Comment by seldondev** [comment]
Thu Feb 11 13:29:08 UTC 2021
The logs for [integration] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2948/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2948 --build=1

**Comment by seldondev** [comment]
Thu Feb 11 13:35:22 UTC 2021
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2948/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2948 --build=2

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2948#issuecomment-777467766 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-777467766/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
