### PR TITLE
WIP: Release 1.5.1

### PR DESCRIPTION
**Pull request by axsaucedo**
Cutting the branch on b4a9494. Release includes the following cherry-picks:
* #2743
* #2746
* #2752
* #2782
* #2700
* #2788

### CODE REVIEW

**Comment by seldondev** [comment]
Fri Dec 11 08:34:39 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=2

**Comment by seldondev** [comment]
Fri Dec 11 08:34:40 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=1

**Comment by seldondev** [comment]
Fri Dec 11 08:36:46 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test integration`
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Dec 11 10:14:09 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=5

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
integration | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Dec 11 10:52:31 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
integration | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Dec 14 09:31:04 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=7

**Comment by seldondev** [comment]
Mon Dec 14 09:31:05 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=8

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
integration | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test integration`
lint | 7a6ffc2fedfd72fd7f9c963cdd65adca7d0db719 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Dec 14 09:41:16 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=9

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
lint | 7a6ffc2fedfd72fd7f9c963cdd65adca7d0db719 | [link]() | `/test lint`
integration | 7a6ffc2fedfd72fd7f9c963cdd65adca7d0db719 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Dec 14 09:57:39 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=10

**Comment by seldondev** [comment]
Mon Dec 14 09:57:51 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=11

**Comment by seldondev** [comment]
Mon Dec 14 10:44:27 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=12

**Comment by seldondev** [comment]
Mon Dec 14 10:46:49 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=13

**Comment by axsaucedo** [comment]
Lint and pr built tests pass, running integration tests now
/test integration

**Comment by seldondev** [comment]
Mon Dec 14 12:50:05 UTC 2020
The logs for [integration] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=14

**Comment by seldondev** [comment]
Mon Dec 14 13:54:21 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=16

**Comment by seldondev** [comment]
Mon Dec 14 13:54:25 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=15

**Comment by axsaucedo** [comment]
Integration tests are passing
/test notebooks

**Comment by seldondev** [comment]
Mon Dec 14 15:55:44 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=17

**Comment by seldondev** [comment]
Mon Dec 14 18:33:00 UTC 2020
The logs for [notebooks] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=18

**Comment by seldondev** [comment]
Mon Dec 14 21:40:54 UTC 2020
The logs for [notebooks] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=19

**Comment by seldondev** [comment]
Tue Dec 15 09:04:11 UTC 2020
The logs for [pr-build] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=20

**Comment by seldondev** [comment]
Tue Dec 15 09:04:16 UTC 2020
The logs for [lint] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=21

**Comment by seldondev** [comment]
Wed Dec 16 12:00:41 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=23

**Comment by seldondev** [comment]
Wed Dec 16 12:00:56 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=22

**Comment by seldondev** [comment]
Wed Dec 16 12:55:33 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=24

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
integration | ac05dacd6f07e9bae9705e5662d4abcf5946a987 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Dec 16 14:24:09 UTC 2020
The logs for [notebooks] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=25

**Comment by seldondev** [comment]
Thu Dec 17 10:11:38 UTC 2020
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=27

**Comment by seldondev** [comment]
Thu Dec 17 10:11:56 UTC 2020
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=26

**Comment by seldondev** [comment]
Thu Dec 17 10:22:52 UTC 2020
The logs for [integration] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=28

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 5d11489014afaf050805f39e0be541d254f096d1 | [link]() | `/test notebooks`
integration | c57f246cdea6d3b1f78975ea1bde58b6f677a826 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Dec 17 12:11:14 UTC 2020
The logs for [integration] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=29

**Comment by seldondev** [comment]
Thu Dec 17 15:23:04 UTC 2020
The logs for [notebooks] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=30

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | c57f246cdea6d3b1f78975ea1bde58b6f677a826 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Dec 17 16:11:14 UTC 2020
The logs for [notebooks] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=31

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | c57f246cdea6d3b1f78975ea1bde58b6f677a826 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Dec 17 19:16:34 UTC 2020
The logs for [notebooks] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=32

**Comment by seldondev** [comment]
Thu Dec 17 19:26:29 UTC 2020
The logs for [lint] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=34

**Comment by seldondev** [comment]
Thu Dec 17 19:26:32 UTC 2020
The logs for [pr-build] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=33

**Comment by seldondev** [comment]
Fri Dec 18 08:19:00 UTC 2020
The logs for [notebooks] [35] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/35.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=35

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | c8deb242afd599e250eab18ac99da91b8c5dbadb | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Dec 18 10:34:57 UTC 2020
The logs for [notebooks] [36] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2763/36.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2763 --build=36

**Comment by axsaucedo** [comment]
Confirmed tests all pass locally for integration and notebook tests, so closing PR

**Pull request closed without merging**
