### PR TITLE
Allow deployment name as prefix when default name to long

### LINKED ISSUE #1801: Seldon deployment name in case of complex graph
We have installed new 1.1 version 
The new changes in the k8s deployment name as described in the link below 
https://docs.seldon.io/projects/seldon-core/en/v1.1.0/reference/upgrading.html#deployment-naming-and-rolling-updates

Are working as expected when running one predictor in the graph when running a graph with more than one predictor

For example :
```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  labels:
    app: seldon
  name: seldon-spam-classifier
  namespace: default
spec:
  annotations:
    project_name: seldon-spam-classifier
    deployment_version: v1
    seldon.io/rest-read-timeout: '100000'
    seldon.io/rest-connection-timeout: '100000'
    seldon.io/grpc-read-timeout: '100000'
  name: seldon-spam-classifier
  predictors:
  - componentSpecs:
    - spec:
        containers:
        - name: translator
          image: sandhya1594/translator:1.0.0.1
          imagePullPolicy: Always
        - name: spam-classifier
          image: sandhya1594/spam-classifier:1.0.0.1
          imagePullPolicy: IfNotPresent
        terminationGracePeriodSeconds: 20
    graph:
      children:
      - name: spam-classifier
        endpoint:
          type: REST
        type: MODEL
        children: []
      name: translator
      endpoint:
        type: REST
      type: TRANSFORMER
    name: seldon-transformer
    replicas: 1
    annotations:
      predictor_version: v1
```
We get name seldon-77845c49ae296cbf824be799890890b2
Is there is why we can set the name of the deployment ? 

in case of graph the name should start with the seldon deployment name 
and not the generic name seldon 

for example after deploying 3 seldon graph
```
kubectl get deployment
NAME                                      READY   UP-TO-DATE   AVAILABLE   AGE
seldon-4753724109c3bf4ee202f2b20583de11   1/1     1            1           3h41m
seldon-4b6779613c5d28f51882c9619ad61e4e   1/1     1            1           3h29m
seldon-77845c49ae296cbf824be799890890b2   0/1     1            0           16s
```

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

 * Allows the deployment name to be sdep.name-<hash> rather than seldon-<hash> if an environment variable set for manager
 * Adds environment variable DEPLOYMENT_NAME_AS_PREFIX to manager
 * Adds Helm chart value `.manager.deploymentNameAsPrefix`

**Which issue(s) this PR fixes**:

Fixes #1801

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3768-notebooks-rtk9j) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3768-notebooks-rtk9j) | `/test notebooks`
integration | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3768-integration-vckcx) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3768-integration-vckcx) | `/test integration`
notebooks | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3768-notebooks-whcwc) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Integration tests seem to pass (only flaky ones failed), but notebook tests requires rebase and retesting

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 658f3bd41e7cb7b3f9b8c81f849a1a9990850162 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3768-integration-vckcx) | `/test integration`
notebooks | c8c987a3bc289f93912c6fe2b2c84cf879314d8a | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3768-notebooks-q7z7b) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
All notebooks tests pass. Merging
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/3768#issuecomment-988741513 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
