### PR TITLE
Fix nil interface conversion for predictor payload logger

### PR DESCRIPTION
**Pull request by glindsell**
#1763 
Signed-off-by: glindsell <gl@seldon.io>

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **glindsell**

If they are not already assigned, you can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Apr 29 10:02:18 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1764/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1764 --build=2

**Comment by seldondev** [comment]
Wed Apr 29 10:02:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1764/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1764 --build=1

**Comment by glindsell** [comment]
Small change just to check that `p.Ctx.Value(payload.SeldonPUIDHeader)` can be converted to a string (essentially checking it's not nil) - if it is nil or the conversion can't be done the request ID will be set to a blank string.
Hopefully that's not just sidestepping the problem - is a nil `p.Ctx.Value(payload.SeldonPUIDHeader)` something we should never see and thus be indicative of a bigger problem and perhaps be handled differently with an error rather than a blank string?

**Comment by seldondev** [comment]
Wed Apr 29 13:23:18 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1764/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1764 --build=3

**Comment by glindsell** [comment]
This bug is broader than the fix presented here. The PUID must be added to the context in the gRPC server.

**Comment by glindsell** [comment]
Replaced by #1782

**Pull request closed without merging**
