### PR TITLE
Revert multiplexing in the Executor

### LINKED ISSUE #2364: Revert multiplexing in the Executor
## Describe the bug
See #2189
This Issue is to revert #1772

## Model Details 
* Images of your model: [Output of: `kubectl get seldondeployment -n <yourmodelnamespace> <seldondepname> -o yaml | grep image:` where `<yourmodelnamespace>`]
* Logs of your model: [You can get the logs of your model by running `kubectl logs -n <yourmodelnamespace> <seldonpodname> <container>`]

### PR DESCRIPTION
**Pull request by glindsell**
**What this PR does / why we need it**:
Revert multiplexing in the operator (#1772)

**Which issue(s) this PR fixes**:

Fixes #2364

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **glindsell**
You can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Sep  2 13:57:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=1

**Comment by seldondev** [comment]
Wed Sep  2 13:57:31 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=2

**Comment by seldondev** [comment]
Wed Sep  2 14:01:28 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=3

**Comment by seldondev** [comment]
Wed Sep  2 14:01:31 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=4

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 9829bb58ef987585a5c67bcc8de9778f58a3171c | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | c969f508f86367247e8cf3ff6bf8875a760151cd | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | c969f508f86367247e8cf3ff6bf8875a760151cd | [link]() | `/test lint`
pr-build | 9829bb58ef987585a5c67bcc8de9778f58a3171c | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  2 14:18:26 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=5

**Comment by seldondev** [comment]
Wed Sep  2 14:18:42 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=6

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | c969f508f86367247e8cf3ff6bf8875a760151cd | [link]() | `/test lint`
pr-build | c969f508f86367247e8cf3ff6bf8875a760151cd | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | c969f508f86367247e8cf3ff6bf8875a760151cd | [link]() | `/test this`
lint | a2e2c8756b1bb908cdec69878dea6298ddb14ded | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  2 15:38:50 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=8

**Comment by seldondev** [comment]
Wed Sep  2 15:39:05 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=7

**Comment by seldondev** [comment]
Wed Sep  2 15:39:32 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=10

**Comment by seldondev** [comment]
Wed Sep  2 15:39:44 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=9

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 6eaf05026cbad6c0d78cd02aa3865b29c46b9e5f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | f65f80a83f51e2b0af090193a42a90e3346ba0bd | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  2 16:15:40 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=11

**Comment by seldondev** [comment]
Wed Sep  2 16:15:48 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=12

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ba72120b55e09202b13c7f61c49772d3236d80bd | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@glindsell since the SSL PR was merged it would be good to rebase and make sure that still work (via the example notebook provided)

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ba72120b55e09202b13c7f61c49772d3236d80bd | [link]() | `/test this`
lint | ef174a005c4c56782d3fb76096154f6592246478 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ef174a005c4c56782d3fb76096154f6592246478 | [link]() | `/test lint`
pr-build | ef174a005c4c56782d3fb76096154f6592246478 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep  3 09:12:18 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=15

**Comment by seldondev** [comment]
Thu Sep  3 09:12:42 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=16

**Comment by seldondev** [comment]
Thu Sep  3 09:33:22 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=17

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 053260d39aebdcb3ade3e1221f241e666215f95b | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep  4 14:34:12 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=18

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 053260d39aebdcb3ade3e1221f241e666215f95b | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep  8 10:47:16 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=19

**Comment by seldondev** [comment]
Tue Sep  8 10:47:22 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=20

**Comment by seldondev** [comment]
Tue Sep  8 10:48:19 UTC 2020
The logs for [integration] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=21

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9887381a7e530ab7af05e85365586cd07ec561d2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Sep  8 12:56:57 UTC 2020
The logs for [integration] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=22

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9887381a7e530ab7af05e85365586cd07ec561d2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 08:54:20 UTC 2020
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=23

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9887381a7e530ab7af05e85365586cd07ec561d2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 12:28:11 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=24

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9887381a7e530ab7af05e85365586cd07ec561d2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Sep  9 13:00:53 UTC 2020
The logs for [integration] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=25

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9887381a7e530ab7af05e85365586cd07ec561d2 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 10 08:30:06 UTC 2020
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=27

**Comment by seldondev** [comment]
Thu Sep 10 08:30:08 UTC 2020
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=26

**Comment by seldondev** [comment]
Thu Sep 10 08:33:33 UTC 2020
The logs for [integration] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=28

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9df253bfdcd23f9847931839257ccf16796a7916 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 10 09:30:22 UTC 2020
The logs for [integration] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=29

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9df253bfdcd23f9847931839257ccf16796a7916 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Sep 10 13:29:32 UTC 2020
The logs for [lint] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=31

**Comment by seldondev** [comment]
Thu Sep 10 13:29:45 UTC 2020
The logs for [pr-build] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=30

**Comment by seldondev** [comment]
Thu Sep 10 13:31:30 UTC 2020
The logs for [integration] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=32

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 9df253bfdcd23f9847931839257ccf16796a7916 | [link]() | `/test integration`
lint | 9d9123f42d1fda413107a5e093bad02b6f76765a | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 09:17:19 UTC 2020
The logs for [pr-build] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=33

**Comment by seldondev** [comment]
Fri Sep 11 09:17:37 UTC 2020
The logs for [lint] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=34

**Comment by seldondev** [comment]
Fri Sep 11 09:18:41 UTC 2020
The logs for [pr-build] [35] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/35.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=35

**Comment by seldondev** [comment]
Fri Sep 11 09:18:41 UTC 2020
The logs for [lint] [36] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/36.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=36

**Comment by seldondev** [comment]
Fri Sep 11 09:20:18 UTC 2020
The logs for [integration] [37] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/37.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=37

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 695fd50f71bf08ff394049157cd5405895b33891 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Sep 11 14:33:30 UTC 2020
The logs for [lint] [39] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/39.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=39

**Comment by seldondev** [comment]
Fri Sep 11 14:34:20 UTC 2020
The logs for [pr-build] [38] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/38.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=38

**Comment by seldondev** [comment]
Fri Sep 11 14:34:35 UTC 2020
The logs for [integration] [40] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/40.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=40

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2365#issuecomment-691206021 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-691206021/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Sep 14 07:45:50 UTC 2020
The logs for [pr-build] [41] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/41.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=41

**Comment by seldondev** [comment]
Mon Sep 14 07:45:53 UTC 2020
The logs for [lint] [42] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/42.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=42

**Comment by seldondev** [comment]
Mon Sep 14 10:07:29 UTC 2020
The logs for [lint] [44] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/44.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=44

**Comment by seldondev** [comment]
Mon Sep 14 10:07:29 UTC 2020
The logs for [pr-build] [43] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/43.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=43

**Comment by seldondev** [comment]
Mon Sep 14 11:54:00 UTC 2020
The logs for [lint] [46] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/46.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=46

**Comment by seldondev** [comment]
Mon Sep 14 11:53:56 UTC 2020
The logs for [pr-build] [45] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/45.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=45

**Comment by seldondev** [comment]
Mon Sep 14 12:16:14 UTC 2020
The logs for [pr-build] [47] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/47.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=47

**Comment by seldondev** [comment]
Mon Sep 14 12:16:17 UTC 2020
The logs for [lint] [48] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2365/48.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2365 --build=48

**Pull request merged**
