### PR TITLE
improve reliability of req logging under high load

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Noted that under high load elastic can give transport errors. Could add more elastic nodes but this reduces requests to elastic and makes it more likely that docs will be indexed. On my testing all docs were being indexed that hit the logger, both request and response. When pointing to the logger directly that was simply all docs (when going via knative broker I found processing was much faster but the in-memory broker seemed to lose about a response per thousand).

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Feb 17 12:09:16 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1457/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1457 --build=2

**Comment by seldondev** [comment]
Mon Feb 17 12:09:32 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1457/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1457 --build=1

**Comment by ryandawsonuk** [comment]
Noted that under high load elastic can give transport errors. Could add more elastic nodes but this reduces requests to elastic and makes it more likely that docs will be indexed. On my testing all docs were being indexed that hit the logger, both request and response. When pointing to the logger directly that was simply all docs (when going via knative broker I found processing was much faster but the in-memory broker seemed to lose about a response per thousand).

**Comment by seldondev** [comment]
@ryandawsonuk: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/SeldonIO/seldon-core/pull/1457#issuecomment-586966309):

>/lgtm
>/approve


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1457#issuecomment-586966309" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
