### PR TITLE
Extract SeldonPodSpec Metadata into custom struct to allow structural CRD schema

### LINKED ISSUE #2938: Metadata fields of predictor's component spec are being pruned in k8s
## Describe the bug
When deploying a seldon deployment the metadata fields of predictor's component spec do not get persisted in k8s. 
This seems to occur only when using the CRDs with `apiextensions.k8s.io/v1` as per [the docs](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/#pruning-don-t-preserve-unknown-fields) unknown fields will be pruned. 
The metadata field here https://github.com/SeldonIO/seldon-core/blob/master/operator/apis/machinelearning.seldon.io/v1/seldondeployment_types.go#L292 is probably not recognized when generating the CRDs. 

Possible solutions:
* Add `x-kubernetes-preserve-unknown-fields: true` to that field. This will eventually be deprecated so we should probably avoid it.
* Define all the properties we need for the metadata field in the `properties:` block. Probably there is a better way.
* Use something like https://github.com/kubernetes-sigs/controller-tools/blob/557da250b856e92ac1cf0895b6953060de72b7e1/pkg/crd/markers/validation.go#L233 to get these fields auto registered.

Is there a chance other fields are also affected and not only the SeldonPodSpec's metadata?

## To reproduce
1. Deploy something like this:
```
{
  "kind": "SeldonDeployment",
  "apiVersion": "machinelearning.seldon.io/v1",
  "metadata": {
    "name": "iris",
    "namespace": "seldon",
    "labels": {
      "fluentd": "true"
    }
  },
  "spec": {
    "name": "iris",
    "predictors": [
      {
        "name": "default",
        "graph": {
          "name": "iris-container",
          "implementation": "SKLEARN_SERVER",
          "modelUri": "gs://seldon-models/sklearn/iris",
          "logger": {
            "mode": "all"
          }
        },
        "componentSpecs": [
          {
            "metadata": {
              "creationTimestamp": "2021-02-09T14:05:02Z",
              "labels": {
                "test": "123"
              }
            },
            "spec": {
              "containers": [
                {
                  "name": "iris-container",
                  "resources": {}
                }
              ]
            }
          }
        ],
        "replicas": 1,
        "engineResources": {},
        "svcOrchSpec": {},
        "traffic": 100
      }
    ],
    "annotations": {
      "seldon.io/engine-seldon-log-messages-externally": "true"
    },
    "protocol": "seldon"
  },
  "status": {}
} 
```
1. check the sdep in k8s - 
```
➜ kubectl get sdep iris -nseldon | grep metadata -B 3
  name: iris
  predictors:
  - componentSpecs:
    - metadata: {}
```

## Expected behaviour

The metadata field in the component spec should contain the original fields:
```
"metadata": {
              "creationTimestamp": "2021-02-09T14:05:02Z",
              "labels": {
                "test": "123"
              }
            }
```

## Environment

* Cloud Provider: GKE
* Kubernetes Cluster Version: v1.18.15-gke.800"
* Deployed Seldon System Images: n/a (this is a k8s issue)

### PR DESCRIPTION
**Pull request by ivan-valkov**
**What this PR does / why we need it**:
See #2938 for context. This is one of the proposed solutions. We pull the `metav1.ObjectMeta` next to the `SeldonPodSpec` which:
* Gives us a fully structural schema of the metadata field (see the CRDs)
* Does not break backwords compatibility. All fields that were used in the metadata field can still be used after this PR.

**Which issue(s) this PR fixes**:

Fixes #2938

**Special notes for your reviewer**:

I have tested this in a gke cluster running k8s `v1.18.15-gke.800`. The metadata fields are now successfully persisted in the cluster. I also tested with a `creationTimestamp: null` field and validation was working as with the root level metadata - it allowed this without failing.

**Does this PR introduce a user-facing change?**:

No.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **jklaise**
You can assign the PR to them by writing `/assign @jklaise` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Feb 11 10:21:49 UTC 2021
The logs for [integration] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2940/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2940 --build=1

**Comment by seldondev** [comment]
Thu Feb 11 10:39:20 UTC 2021
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2940/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2940 --build=2

**Comment by seldondev** [comment]
Thu Feb 11 13:12:10 UTC 2021
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2940/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2940 --build=3

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ivan-valkov**
You can assign the PR to them by writing `/assign @ivan-valkov` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ivan-valkov** [comment]
/test integration

After rebase on top of latest master with https://github.com/SeldonIO/seldon-core/pull/2948 should work now

**Comment by seldondev** [comment]
Thu Feb 11 13:51:49 UTC 2021
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2940/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2940 --build=4

**Comment by axsaucedo** [comment]
All integration tests pass
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2940#issuecomment-777745130 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-777745130/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
