### PR TITLE
opendistro elastic

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/2912

Note there's a small change in there to alibi-detect-server too... this will have knock-on to deploy as that will need to point to new image. The reason for the change is that the opendistro setup requires security (can't turn off) and I went for self-signed certs.

Also note I've moved the metrics server into seldon-logs namespace as we've been doing that with other detector components and best to be consistent

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ryandawsonuk**
You can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
Should rebase this now https://github.com/SeldonIO/seldon-core/pull/2972 has gone in as that'll be needed in order to put metrics server in seldon-logs namespace

**Comment by ryandawsonuk** [comment]
After rebasing the multiclass model for the feedback example doesn't come up. It was coming up fine before the rebase. Pod logs:

```
/opt/conda/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.26.0) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/opt/conda/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/opt/conda/lib/python3.7/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/opt/conda/lib/python3.7/site-packages/conda/plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/opt/conda/lib/python3.7/site-packages/conda/core/index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "/opt/conda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/opt/conda/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/opt/conda/lib/python3.7/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/opt/conda/lib/python3.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/conda/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 50, in <module>
    import OpenSSL.SSL
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 664, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
starting microservice
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.0 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/seldon-core-microservice", line 33, in <module>
    sys.exit(load_entry_point('seldon-core', 'console_scripts', 'seldon-core-microservice')())
  File "/opt/conda/bin/seldon-core-microservice", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 96, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/microservice/python/seldon_core/microservice.py", line 15, in <module>
    from seldon_core.app import (
  File "/microservice/python/seldon_core/app.py", line 7, in <module>
    from gunicorn.app.base import BaseApplication
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/opt/conda/lib/python3.7/site-packages/gunicorn/util.py", line 26, in <module>
    import pkg_resources
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (urllib3 1.26.0 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1'), {'requests'})
```

**Comment by ryandawsonuk** [comment]
Also a problem with the alibi-detect image for the feedback server:
```
2021-02-19 17:18:39.184074: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-02-19 17:18:39.184113: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/microservice/adserver/__main__.py", line 3, in <module>
    import tensorflow as tf
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import keras
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/models.py", line 24, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/metrics.py", line 40, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 60, in <module>
    from tensorflow.python.keras.mixed_precision import loss_scale_optimizer
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py", line 20, in <module>
    from tensorflow.python.distribute import collective_all_reduce_strategy
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/collective_all_reduce_strategy.py", line 35, in <module>
    from tensorflow.python.distribute import mirrored_strategy
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/mirrored_strategy.py", line 34, in <module>
    from tensorflow.python.distribute.cluster_resolver import TFConfigClusterResolver
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/cluster_resolver/__init__.py", line 32, in <module>
    from tensorflow.python.distribute.cluster_resolver.kubernetes_cluster_resolver import KubernetesClusterResolver
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver.py", line 28, in <module>
    from kubernetes import client as k8sclient  # pylint: disable=g-import-not-at-top
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/__init__.py", line 20, in <module>
    import kubernetes.config
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/__init__.py", line 19, in <module>
    from .kube_config import (list_kube_config_contexts, load_kube_config,
  File "/opt/conda/lib/python3.7/site-packages/kubernetes/config/kube_config.py", line 29, in <module>
    import google.auth.transport.requests
  File "/opt/conda/lib/python3.7/site-packages/google/auth/transport/requests.py", line 26, in <module>
    import requests
  File "/opt/conda/lib/python3.7/site-packages/requests/__init__.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/opt/conda/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/opt/conda/lib/python3.7/site-packages/OpenSSL/SSL.py", line 664, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

Seems both of these are related to recent upgrades and are being looked at under https://github.com/SeldonIO/seldon-core/pull/2977

**Comment by ryandawsonuk** [comment]
Now all working.

Some weirdness with grafana:

grafanawhatthehelltimeranges

But that doesn't seem to be related to the example specifically.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2923#issuecomment-784168412 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
