### PR TITLE
Seldon CRD Status Removal

### LINKED ISSUE #2132: Remove Status section of generated CRD by kubebuilder
See https://github.com/kubernetes-sigs/controller-tools/issues/456 and https://github.com/kubeflow/manifests/issues/1386

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

 * Removes the status section of the generated CRD. [This is a bug in controller-gen that has not been fixed](https://github.com/kubernetes-sigs/controller-tools/issues/456).
 * Updated controller-gen to latest 0.4.1
 * Updates controller-gen args to create v1beta1 CRD where needed
 * Remove defaults patch as this is fixed in 0.4.1 controller-gen

**Which issue(s) this PR fixes**:

Fixes #2132

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ivan-valkov — APPROVED** [review]

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[ivan-valkov](https://github.com/SeldonIO/seldon-core/pull/2941#pullrequestreview-587746253 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Feb 11 10:21:54 UTC 2021
The logs for [integration] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2941/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2941 --build=1

**Comment by seldondev** [comment]
Thu Feb 11 10:24:16 UTC 2021
The logs for [integration] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2941/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2941 --build=2

**Comment by seldondev** [comment]
Fri Feb 12 08:32:39 UTC 2021
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2941/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2941 --build=3

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[ivan-valkov](https://github.com/SeldonIO/seldon-core/pull/2941#pullrequestreview-587746253 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ivan-valkov]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
