### PR TITLE
added time-series algorithm

### PR DESCRIPTION
**Pull request by narennadig**
Added how to deploy timeseries-model (using holt-winter's algorithm) in seldon-core from source code till model-monitoring.

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @narennadig. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
NIce one! Looks great! Thank you for the contribution @narennadig.

The use of custom metrics is fantastic as well! 

A couple of very small things and it's good to go:
* The notebook should work if people were to just hit the cells through it, so ideally you can add the creation of the files as well any dependencies that need to be installed (ie requirements.txt). You should also make sure that the PR contains all the file assets required
* You can use `%%writefile <filename>` commands at the beginning of the cells to ensure the files are in sync with the notebook (not critical but important)
* It seems there are metrics in the dashboard but the model you provide in the sample doesn't have hte `metrics` function implemented, is this something implemented separate to the example?
* You can list it in the [notebooks.rst](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/notebooks.rst) so it appeasrs in the docs and people can find it
* Your images need to be copied to the [`doc/source/examples/images/`](https://github.com/SeldonIO/seldon-core/tree/master/doc/source/examples/images) folder so that the relative path is visible otherwise they will not appear when the docs are compiled (let me know if you have questions on this as it may be confusing)
* It seems it's not rendering correctly - you can seee it here https://github.com/SeldonIO/seldon-core/blob/507328a5e8d807ac8ad5e41cdcfc8dac38728a4a/examples/models/statsmodels/statsmodels.ipynb
* You can also add links to the dependenices such as installing seldon core (in the docs)

Let me know if you need a hand with these changes, some are quite nuanced, so we're happy to support/help on this.

**Comment by narennadig** [comment]
Hey @axsaucedo ,
Will surely make the changes and come back to you ...Just need a few days of time

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2340#issuecomment-683836344 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-683836344/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Aug 31 15:05:57 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2340/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2340 --build=1

**Comment by seldondev** [comment]
Mon Aug 31 15:05:55 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2340/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2340 --build=2

**Pull request merged**
