### PR TITLE
[DO NOT MERGE] v1.13.0 release

### LINKED ISSUE #3932: Release process for v1.13.0

### PR DESCRIPTION
**Pull request by axsaucedo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Performing release  (https://github.com/SeldonIO/seldon-core/issues/3932)

Also addresses the following issues for release:
* https://github.com/SeldonIO/seldon-core/issues/3936

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-pcjl7) | `/test models`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-pcjl7) | `/test models`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vlhfq) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-pcjl7) | `/test models`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vlhfq) | `/test integration`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-d5hc2) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-pcjl7) | `/test models`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vlhfq) | `/test integration`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-d5hc2) | `/test notebooks`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-hhr6c) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vlhfq) | `/test integration`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-d5hc2) | `/test notebooks`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-hhr6c) | `/test release`
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-wtnsf) | `/test models`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vlhfq) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-hhr6c) | `/test release`
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-wtnsf) | `/test models`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-hhr6c) | `/test release`
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-wtnsf) | `/test models`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-wtnsf) | `/test models`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
models | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-d5p4h) | `/test models`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
models | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-lx9vl) | `/test models`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-fcgkf) | `/test notebooks`
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
models | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/donio-seldon-core-pr-3933-models-5s72c) | `/test models`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-vzsgh) | `/test integration`
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-bgn66) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
notebooks | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-bgn66) | `/test notebooks`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-lvfzl) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-lvfzl) | `/test integration`
notebooks | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-r8wcw) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
notebooks | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-r8wcw) | `/test notebooks`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-7hc7b) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
notebooks | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3933-notebooks-r8wcw) | `/test notebooks`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-9gm9l) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-skzqt) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
integration | f1a8b2e9187624d74d60cbe4654f072791e69d28 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-pttcv) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Models and notebooks tests passing

image

Integration tests are hitting ephimeral limit of 150gi so needs to be update

image

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | e6a60ae0b26ea0b04c9cf9ca075053196bd60849 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/core-pr-3933-release-build-push-mmwx7) | `/test release`
integration | d48c3c5d6dd3279e88b4981d1c70c7ae5da3521f | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3933-integration-kbj4s) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Integration tests pass so we're good to go ahead with the release

**Comment by axsaucedo** [comment]
All test pass, validated for the label update tests locally - finalising the release

image

**Comment by axsaucedo** [comment]
Closing as release complete

**Pull request closed without merging**
