### PR TITLE
Seldon Components Usage Examples

### PR DESCRIPTION
**Pull request by SandhyaaGopchandani**
Adding two examples that illustrate how to use various seldon-core graph components for machine learning models: 
1) uses Seldon Input_Transformer component for Spam Classification.
2) extends the previous example to add Combiner component.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @SandhyaaGopchandani. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [seldonio](https://github.com/orgs/seldonio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/seldonio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by axsaucedo** [comment]
Thank you for your contribution @SandhyaaGopchandani 

@SandhyaaGopchandani  you need to add an `nblink` file in this folder https://github.com/SeldonIO/seldon-core/tree/master/doc/source/examples and an entry in `notebooks.rst` https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/notebooks.rst. 

This is required for your example to appear in the docs.

**Comment by axsaucedo** [comment]
@SandhyaaGopchandani woudl it be possbile for you to include teh code you used to generate the trained models? It seems that the code provided only loads the models but assumes that the fiels are availble, but there's no way to follow the example if this is not there.

THank you Sandhyaa!

**Comment by SandhyaaGopchandani** [comment]
@axsaucedo I wanted it to be generic template where people can load up the model files. But if you think having a working example would be better, I will make the changes! Thanks for the feedback.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by SandhyaaGopchandani** [comment]
> Thank you for your contribution @SandhyaaGopchandani
> 
> @SandhyaaGopchandani you need to add an `nblink` file in this folder https://github.com/SeldonIO/seldon-core/tree/master/doc/source/examples and an entry in `notebooks.rst` https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/notebooks.rst.
> 
> This is required for your example to appear in the docs.

@axsaucedo I have updated the code, included the model files as well as notebook file that generated the binaries.
Regarding `nblink`, Does it have to be a path to Notebook file showing the steps? I have structured the example repository differently. Wonder if that is okay?

**Comment by axsaucedo** [comment]
@SandhyaaGopchandani thank you for adding the updates. In regards to your question, you will have to addd a new file in this folder:
*  https://github.com/SeldonIO/seldon-core/tree/master/doc/source/examples 

Once you add a new file there, you will then just add an entry in `notebooks.rst` which contains the path to that nblink file:
* https://github.com/SeldonIO/seldon-core/blob/master/doc/source/examples/notebooks.rst


One more piece to add. I think I didn't specify what I meant by making sure that the `.h5` and `pkl` files are present, what i meant is that we need to enable people following this example to actually be able to builld it. However we can't just copy the whole binary files in the repo as they would be quite heavy, so what we normally do is providing the code required to train the model, You can see how we do it in this example: https://github.com/SeldonIO/seldon-core/blob/master/examples/models/deep_mnist/deep_mnist.ipynb

**Comment by SandhyaaGopchandani** [comment]
Hello @axsaucedo, thanks for the comment!
I have updated the git repo(s) to add the training code to generate the model files. I have also added nblink files and references in the notebooks.rst file. 
Seems it should be good now! Please let me know if there is anything needed to be updated.
-
Sandhya

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1036#issuecomment-551102628" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you for your contribution @SandhyaaGopchandani

**Comment by seldondev** [comment]
@SandhyaaGopchandani: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 3fec8c85bbb346f1c6b5c07fdb343c16cf77af6b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
