### PR TITLE
ensure data types while extracting data from json

### PR DESCRIPTION
**Pull request by Aiden-Jeon**
**What this PR does / why we need it**:
As mlflow version has upgraded (>=1.17.0), now mlflow supports input type of `datetime`.
But in json, `datetime` type of data can only passed with string type. 
So parsing with default `np.array` led some issues during inference with data types.

Function `extract_request_parts_json` parses json file with using `np.array`.
But with default option of `np.array`, we get result like this below.
```python
>>> request = {
  "data": [
    ["2021-06-17 16:40:00", 1, 2, 3]
  ]
}
>>> np.array(request["data"])
array([['2021-06-17 16:40:00', '1', '2', '3']], dtype='<U21')
```
All of values have been changed to string. And this led error in after process.

**Which issue(s) this PR fixes**:

To resolve this problem, I have added `dtype` argument with `object`.
This ensures that numpy converts only the string values.

```python
>>> np.array(request["data"], dtype=object)
array([['2021-06-17 16:40:00', 1, 2, 3]], dtype=object)
```

And also, adding this argument does not affect to int or float values.
```python
>>> np.array([1, 2, 3, 4.0], dtype=object)
array([1, 2, 3, 4.0], dtype=object)
```

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```
NONE

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @Aiden-Jeon. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **gsunner**
You can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@Aiden-Jeon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 72464d3a3240dbb7ae50a3fa875ae2de466afee5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-27vsk) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@Aiden-Jeon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 72464d3a3240dbb7ae50a3fa875ae2de466afee5 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-jb6rs) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by Aiden-Jeon** [comment]
Is there something to do for me to check for this failure?

**Comment by axsaucedo** [comment]
Thanks again for the contribution @Aiden-Jeon ! Just picking this up, I think we may need to have this as an environment variable as opposed to enabled by default, namely as some models may error if the inputs are not of the type expected and instead just of type object. Would you  be able to rebase to make sure we run the tests with latest master?

**Comment by seldondev** [comment]
@Aiden-Jeon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 25380572b1f61353b6024aab7e88411627ba62f8 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3302-integration-lbt56) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@Aiden-Jeon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 25380572b1f61353b6024aab7e88411627ba62f8 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3302-integration-lbt56) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@Aiden-Jeon thank you for your contribution, again as mentioned above we would be keen to add this under `ndarray` but only if it is disabled by deefault and enabled with an environment variable, as it would otherwise lead to unexpected behaviour. Closing for now but would be great if you could add another with the suggested requirements and tests. Thanks

**Pull request closed without merging**
