### PR TITLE
Expose tracer in userobject to enable child creation capability

### PR DESCRIPTION
**Pull request by harshita-meena**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @harshita-meena. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
@harshita-meena would you be able to provide context on an issue or update the description on the PR for the need and changes (or link to relevant issue for context)? I can see a couple of changes that currently not clear for, the current changes on the user_model modify the user class, and adds a trace in one of the functions but introduces inconsistencies with other functions, as well as with functionalities with other wrappers. There's also context on why executor traces are not covering the requirements as it sets the span traces on each model hop.

**Comment by harshita-meena** [comment]
Hi @axsaucedo Apologies for the lack of context, the PR is linked to this issue https://github.com/SeldonIO/seldon-core/issues/4270. I faced some issue with connecting child traces for grpc requests that is why the changes around predict. I am happy to make changes that will cover all other calls as well.

**Comment by harshita-meena** [comment]
@axsaucedo Thankyou for your reply. I will verify if MLServer (pythonv2) will satisfy all the usecases. I have been using only the v1 python wrapper in seldon core. Also I skimmed quickly, is tracing not enabled in v2?

**Pull request closed without merging**
