### PR TITLE
use alternative multiprocessing library if USE_MULTIPROCESS_PACKAGE i…

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
…s set

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/SeldonIO/seldon-core/issues/3410

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6cfcd79c9f68542bcfacbd6e8613910406b5c242 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4114-integration-ht2k6) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Failure on `test_graph_v2[False]`

**Comment by axsaucedo** [comment]
Validated _v2 test failed passes locally

**Pull request merged**
