### PR TITLE
Executor/deps update - straightforward dependencies update

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/2089.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Jul  9 11:44:46 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=2

**Comment by seldondev** [comment]
Thu Jul  9 11:45:06 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=1

**Comment by seldondev** [comment]
Thu Jul  9 11:45:20 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=3

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5b452b4249427158b8e69eaba67c0e988dd8c992 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Failure on `test_rolling_deployment[graph1.json-graph4.json-True-ambas]`. Probably flakiness.
/test integration

**Comment by seldondev** [comment]
Thu Jul  9 12:29:31 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5b452b4249427158b8e69eaba67c0e988dd8c992 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jul  9 13:01:05 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=5

**Comment by seldondev** [comment]
Thu Jul  9 13:41:56 UTC 2020
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=6

**Comment by axsaucedo** [comment]
Maybe it could make sense to wait for #2093 to be merged and then rebase to ensure all works correctly with the updated deps (that should be the case tho, but just to make sure)

**Comment by RafalSkolasinski** [comment]
Sure, sound good. Though seems the changes are orthogonal. 

On https://github.com/SeldonIO/seldon-core/pull/2093 I wanted to base update of operator dep and k8s.io deps.

**Comment by axsaucedo** [comment]
@RafalSkolasinski seems integration tests pass 👍

**Comment by RafalSkolasinski** [comment]
Nice, momentum is good on this :rocket:

**Comment by seldondev** [comment]
Fri Jul 10 10:16:51 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=7

**Comment by seldondev** [comment]
Fri Jul 10 10:16:54 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=8

**Comment by seldondev** [comment]
Fri Jul 10 10:17:23 UTC 2020
The logs for [notebooks] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=9

**Comment by seldondev** [comment]
Fri Jul 10 10:18:57 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2099/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2099 --build=10

**Comment by axsaucedo** [comment]
Both notebooks and integrations pass 🚀
Merging manually as it's not being reflected
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2099#issuecomment-656659130 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-656659130/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
