### PR TITLE
Release java wrapper

### LINKED ISSUE #1796: Seldon core wrapper support for Spring 2
The existing seldon-core-wrapper uses Spring Boot 1.5, when running H2O example on spring 2 app starts to fail with java.lang.ClassNotFoundException: org.springframework.boot.context.embedded.EmbeddedServletContainerCustomizer.

Can you update the example on how to use warpper with latest version of spring.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Publish new version of the Java wrapper (`0.2.0`), upgrading some of the dependencies.

**Which issue(s) this PR fixes**:

Fixes #1796

**Special notes for your reviewer**:
The `0.2.0` release should be propagated shortly to [Maven Central](https://search.maven.org/artifact/io.seldon.wrapper/seldon-core-wrapper) and [Maven Repository](https://mvnrepository.com/artifact/io.seldon.wrapper/seldon-core-wrapper).

**Does this PR introduce a user-facing change?**:

```release-note
Updated Java `seldon-core-wrapper` package to `0.2.0`.
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jul 31 12:35:06 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2222/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2222 --build=2

**Comment by seldondev** [comment]
Fri Jul 31 12:35:06 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2222/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2222 --build=1

**Comment by amoldavsky** [comment]
@adriangonz 👍

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[adriangonz](https://github.com/SeldonIO/seldon-core/pull/2222#issuecomment-674806195 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-674806195/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
