### PR TITLE
Added black formatter to seldon_core and testing folders 

### PR DESCRIPTION
**Pull request by axsaucedo**
I have ran the black formatter across the `python` and `testing` folders only.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by adriangonz** [comment]
Nice one @axsaucedo !

As part of this PR (or on subsequent ones) we could look at:

- Configuring `pre-commit` to run `black` locally on any commit which includes `*.py` files. The [`.pre-commit-config.yaml` file](https://github.com/SeldonIO/seldon-core/blob/master/.pre-commit-config.yaml) got added already as part of #951. `black` has support for `pre-commit` out of the box, so it would involve simply adding [these lines](https://github.com/psf/black#version-control-integration).
- Adding a `flake8` config to lint the `*.py` files. (we can get inspiration from [`black`'s](https://github.com/psf/black/blob/master/.flake8)). We can later run `flake8` as part of the CI/CD pipeline.

**Comment by jklaise** [comment]
@adriangonz good ideas! In fact I'm keen to steal the pre-commit config for alibi once it's done for seldon-core... For flake8 config we have this in alibi and CI/CD on travis already.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/980#issuecomment-545861088" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
