### PR TITLE
dummy PR to trigger CI (custom_metrics notebook test flakiness)

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Don't merge. Just testing notebook test in CI.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes https://github.com/SeldonIO/seldon-core/issues/2570

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jan 20 15:32:02 UTC 2021
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=1

**Comment by seldondev** [comment]
Wed Jan 20 15:32:11 UTC 2021
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=2

**Comment by seldondev** [comment]
Wed Jan 20 15:32:14 UTC 2021
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=3

**Comment by RafalSkolasinski** [comment]
1/3 passed
/test notebooks

**Comment by seldondev** [comment]
Wed Jan 20 20:10:19 UTC 2021
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=4

**Comment by RafalSkolasinski** [comment]
2/3 passed
/test notebooks

**Comment by seldondev** [comment]
Wed Jan 20 22:18:02 UTC 2021
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=5

**Comment by RafalSkolasinski** [comment]
3 notebooks tests in row passed, launching 4 for sanity check
/test notebooks

**Comment by seldondev** [comment]
Thu Jan 21 00:19:07 UTC 2021
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=6

**Comment by RafalSkolasinski** [comment]
Notebook tests passed 4 times in a row. I cannot confirm that custom_metrics notebook is still flaky as reported in https://github.com/SeldonIO/seldon-core/issues/2570

**Comment by RafalSkolasinski** [comment]
Just failed here: https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2852/24.log#L3983

**Comment by seldondev** [comment]
Mon Jan 25 09:44:24 UTC 2021
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=8

**Comment by seldondev** [comment]
Mon Jan 25 09:44:27 UTC 2021
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=7

**Comment by seldondev** [comment]
Mon Jan 25 09:44:28 UTC 2021
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2855/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2855 --build=9

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5193218e313a39cbf2dd66f947940d7bb7e48fa6 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 5193218e313a39cbf2dd66f947940d7bb7e48fa6
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 5193218e313a39cbf2dd66f947940d7bb7e48fa6
* failed to process repo SeldonIO/seldon-core refref 5193218e313a39cbf2dd66f947940d7bb7e48fa6
* failed to list files in directory /var/tmp/gitrepo799923688/.lighthouse
* open /var/tmp/gitrepo799923688/.lighthouse
* no such file or directory

**Pull request closed without merging**
