### PR TITLE
feat(proto): Add custom proto handling

### PR DESCRIPTION
**Pull request by groszewn**
Additional `customData` field added to the prediction protobuf, as well
as updates to the python package to properly pass the raw protobuf
section down to the `user_model` implementation.

Addresses SeldonIO/seldon-core#1420

Signed off by Nick Groszewski (<groszewn@gmail.com>)

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @groszewn. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by cliveseldon** [comment]
@groszewn Thanks for this. One immediate question: why are the tensorflow compiled protos changed? It looks like it might be a formatting issue. Can we maybe confirm the env you recreated these and try to remove them?

We would need to also ensure the changes reached the executor protos as well: https://github.com/SeldonIO/seldon-core/blob/d4c435ea5217825dacf592ee89db67d7472ff2be/executor/Makefile#L31-L35

**Comment by groszewn** [comment]
Hey @cliveseldon, thanks for taking a look.  Are there pinned versions of `grpcio-tools` or `protoc-gen-mypy` I should be using? I suspect it's the former that may be causing the discrepancies.

```
grpcio-tools==1.27.2
mypy-protobuf==1.20
```
is what I currently have in my env.

**Comment by cliveseldon** [comment]
> Hey @cliveseldon, thanks for taking a look. Are there pinned versions of `grpcio-tools` or `protoc-gen-mypy` I should be using? I suspect it's the former that may be causing the discrepancies.
> 
> ```
> grpcio-tools==1.27.2
> mypy-protobuf==1.20
> ```
> 
> is what I currently have in my env.

I think we have:
```
requirements.txt:grpcio<2.0.0
```

So we might need to tie this down some more

**Comment by groszewn** [comment]
The `grpcio` install itself won't pull in `grpcio-tools`, which is required for the proto compilation.  I can add the specific version of `grpcio-tools` to `requirements-dev.txt` once we pin down which version the previous protos were compiled with.

**Comment by cliveseldon** [comment]
I think the previous version might be quite old - as I tried `1.20.1` and gave me just 1 change.
Maybe it is best to pin to a more recent version and have those changes unless there is a good reason to be more conservative?

**Comment by groszewn** [comment]
I don't see any issues with that approach.  The latest stable release for `grpcio-tools` is `1.27.2`, shall I pin it to that and recompile, or would you rather a different version?

**Comment by adriangonz** [comment]
Is there any chance the changes are `black`-related? They seem to be only related to format.

**Comment by cliveseldon** [comment]
@groszewn sounds good - go ahead

**Comment by groszewn** [comment]
@adriangonz I suspected it might be, but the pre-commit hook specifically ignores the entire `seldon_core/proto` folder https://github.com/SeldonIO/seldon-core/blob/master/.pre-commit-config.yaml#L12

**Comment by groszewn** [comment]
@cliveseldon updated the PR.  Pinned both `mypy-protobuf` and `grpcio-tools` in `requirements-dev.txt` since they're both required to build the protos.  I also went back and compiled the proto for the executor as well.

**Comment by groszewn** [comment]
Hey @cliveseldon, just wanted to see if there's anything else you're looking for on the PR before kicking the tests.

**Comment by cliveseldon** [comment]
No Seems good.
/ok-to-test

**Comment by seldondev** [comment]
Fri Apr  3 16:04:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=2

**Comment by seldondev** [comment]
Fri Apr  3 16:04:44 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=1

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Apr  3 16:08:02 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=3

**Comment by seldondev** [comment]
Fri Apr  3 16:09:05 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=4

**Comment by seldondev** [comment]
@groszewn: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
@groszewn Our Jenkins-x seems flaky today but can you test locally there are no issues with building the engine, executor, operator and running the python tests?

**Comment by seldondev** [comment]
@groszewn: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test this`
integration | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by groszewn** [comment]
Sure thing, I'll run all of those and aggregate the results back here.

**Comment by groszewn** [comment]
Okay @cliveseldon, I've aggregated my tests in [this gist](https://gist.github.com/groszewn/0f0e169444a68db78c789d5a7af525cf).  Everything besides the `executor` build looks good as far as I can tell.

There's some more detail in [building the executor section](https://gist.github.com/groszewn/0f0e169444a68db78c789d5a7af525cf#building-the-executor) of the gist, but there seems to be an issue either with the compiled protobuf for the executor, or in my golang setup.  I had to update the `grpc` package to get things working, along with updating the location that the protobuf was compiled to and manually updating the `package` name.  Let me know how you'd like me to proceed from here, as I'm not 100% sure which part of this may be behaving incorrectly.

**Comment by seldondev** [comment]
Sat Apr  4 00:35:58 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=6

**Comment by seldondev** [comment]
Sat Apr  4 00:36:08 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=5

**Comment by cliveseldon** [comment]
> Okay @cliveseldon, I've aggregated my tests in [this gist](https://gist.github.com/groszewn/0f0e169444a68db78c789d5a7af525cf). Everything besides the `executor` build looks good as far as I can tell.
> 
> There's some more detail in [building the executor section](https://gist.github.com/groszewn/0f0e169444a68db78c789d5a7af525cf#building-the-executor) of the gist, but there seems to be an issue either with the compiled protobuf for the executor, or in my golang setup. I had to update the `grpc` package to get things working, along with updating the location that the protobuf was compiled to and manually updating the `package` name. Let me know how you'd like me to proceed from here, as I'm not 100% sure which part of this may be behaving incorrectly.

Hi @groszewn Maybe what is needed is a separate PR to update the grpc libs and the rationale for this. Once we have that done then this PR can use it?

Can you open an issue and state what needs changing. Obviously we need to make it automatic as you mentioned manual changes in the gist.

**Comment by groszewn** [comment]
I went ahead and opened [this issue](https://github.com/SeldonIO/seldon-core/issues/1663).  I can make a PR based off of discussion we have on that ticket and have this PR leverage those changes after.

**Comment by axsaucedo** [comment]
@groszewn yesterday we were catching up on this work, would you be able to add an accompanying example notebook under the examples/ folder? It would be great to have a practical example that shows how to leverage the custom proto functionality. Here is an example of the notebook that shows how to use the knative eventing functionality for example https://github.com/axsaucedo/seldon-core/blob/bcbbc3fdd691bb1db99d2f1367b16b56df9c7f71/examples/streaming/knative-eventing/README.ipynb

Here is the full PR so you can see how we added the docs: https://github.com/SeldonIO/seldon-core/pull/1653/files

**Comment by groszewn** [comment]
@axsaucedo absolutely.  I should have some time this weekend to put an example notebook together.

**Comment by axsaucedo** [comment]
Awesome, thanks @groszewn !

**Comment by seldondev** [comment]
Sun Apr 12 19:37:44 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=8

**Comment by seldondev** [comment]
Sun Apr 12 19:37:46 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=7

**Comment by groszewn** [comment]
@axsaucedo Added in the custom protobuf example notebook.  Just had a question about how to handle some references, since I had to rebuild a few images locally to get everything working.

Is the python s2i wrapper updated in an automated fashion?  I went ahead and built an updated version with my changes in this PR to test, but wanted to make sure a new version would roll out along with these changes.  The notebook references `seldonio/seldon-core-s2i-python3:0.19-SNAPSHOT`, but that's just what I happened to name my local builder image.

**Comment by groszewn** [comment]
@axsaucedo gentle ping 😄 just wanted to see if you'd had a chance to review the notebook addition to the PR

**Comment by seldondev** [comment]
Wed Apr 15 21:49:37 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=9

**Comment by seldondev** [comment]
Wed Apr 15 21:49:40 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=10

**Comment by seldondev** [comment]
@groszewn: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test integration`
pr-build | 24c641138e979b56d0381ce53d3555e7012ca7a3 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Apr 16 17:27:24 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=11

**Comment by seldondev** [comment]
Thu Apr 16 17:27:32 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=12

**Comment by groszewn** [comment]
@cliveseldon @axsaucedo just wanted to circle back and see if there were any further comments/suggestions for this PR?

**Comment by seldondev** [comment]
Tue Apr 21 01:54:50 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=14

**Comment by seldondev** [comment]
Tue Apr 21 01:54:50 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=13

**Comment by groszewn** [comment]
@axsaucedo went ahead and rebased off of master to get the changes from the other PR reflected here.  Let me know if there's anything else needed on my end.

**Comment by seldondev** [comment]
@groszewn: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | a6d44a60c6d2132b1e961c797fafe2ab40ae957a | [link]() | `/test integration`
pr-build | a01474b54aa31b5b5ee5570e71409026af56ef22 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Apr 21 12:42:11 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=16

**Comment by seldondev** [comment]
Tue Apr 21 12:42:17 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=15

**Comment by axsaucedo** [comment]
Great! Thank you @groszewn , it all seems in place, if integration tests pass we shoudl be good to merge
/test integration

**Comment by seldondev** [comment]
Tue Apr 21 12:50:04 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=17

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1652#issuecomment-617158971" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Apr 21 13:23:57 UTC 2020
The logs for [lint] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=19

**Comment by seldondev** [comment]
Tue Apr 21 13:23:58 UTC 2020
The logs for [pr-build] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1652/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1652 --build=18

**Comment by groszewn** [comment]
Looked like I must've dropped the executor protobuf change in the rebase.  Added that back to the PR.

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 97c809e77c7764a061b5bb35f274dbea039ae961
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 97c809e77c7764a061b5bb35f274dbea039ae961
* failed to process repo SeldonIO/seldon-core refref 97c809e77c7764a061b5bb35f274dbea039ae961
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
