### PR TITLE
fix links do images descriptions, closes #1249

### LINKED ISSUE #1249: broken links to image descriptions
In [Latest Seldon Images](https://github.com/SeldonIO/seldon-core/blob/master/doc/source/reference/images.md) table all links in `Description` column are broken.

- [x] fix links
- [x] document workaround to reference md files outside of `doc/source`

### PR DESCRIPTION
**Pull request by RafalSkolasinski**

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jan 17 15:41:48 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=2

**Comment by seldondev** [comment]
Fri Jan 17 15:41:48 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=1

**Comment by seldondev** [comment]
Fri Jan 17 15:45:31 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=3

**Comment by seldondev** [comment]
Fri Jan 17 15:45:31 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=4

**Comment by seldondev** [comment]
Fri Jan 17 16:58:22 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=6

**Comment by seldondev** [comment]
Fri Jan 17 16:58:23 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=5

**Comment by seldondev** [comment]
Mon Jan 20 10:16:07 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=8

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 50c82898ec2b01dadcea20d3a62ea4e0281ca6f1 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jan 20 10:17:16 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=9

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 50c82898ec2b01dadcea20d3a62ea4e0281ca6f1 | [link]() | `/test this`
lint | e103bb9f0a7b910b14badebe85f12e0d59897c04 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jan 20 10:18:49 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=11

**Comment by seldondev** [comment]
Mon Jan 20 10:18:59 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=12

**Comment by RafalSkolasinski** [comment]
This is ready for review.

**Comment by seldondev** [comment]
Mon Jan 20 10:20:53 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=13

**Comment by seldondev** [comment]
Mon Jan 20 10:21:18 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=14

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1346#issuecomment-576281081" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jan 20 13:45:46 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=15

**Comment by seldondev** [comment]
Mon Jan 20 13:45:59 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1346/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1346 --build=16

**Pull request merged**
