### PR TITLE
WIP: Optimizing image builds 

### LINKED ISSUE #1794: Introduce caching for image builds in our CI pipeline
Currently images are built every time in our dated SNAPSHOT CI pipeline. We'd want to avoid rebuilding images if the respective source code has not been edited. Instead we could just tag the already existing image and push that. That woudl also ensure we avoid replication of layers in the docker side (and faster build times)

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #1794

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed May 27 17:34:08 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1884/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1884 --build=1

**Comment by seldondev** [comment]
Wed May 27 17:35:26 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1884/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1884 --build=2

**Comment by axsaucedo** [comment]
Closing PR until this is picked up again with the new updated JX cluster

**Pull request closed without merging**
