### PR TITLE
move from deprecated apis

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1176

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Dec 10 13:40:26 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1236/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1236 --build=1

**Comment by seldondev** [comment]
Tue Dec 10 13:40:37 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1236/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1236 --build=2

**Comment by ryandawsonuk** [comment]
Actually just upgrading the API version alone isn't enough and leads to `missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec`

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 22cc6c86440a6232d32f5b44aa820902aad01251 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 22cc6c86440a6232d32f5b44aa820902aad01251 | [link]() | `/test this`
lint | 22cc6c86440a6232d32f5b44aa820902aad01251 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Was already addressed by https://github.com/SeldonIO/seldon-core/commit/1d662a0c418bb12dfc1ec3bc6b7584429d2ff485

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 22cc6c86440a6232d32f5b44aa820902aad01251
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 22cc6c86440a6232d32f5b44aa820902aad01251
* failed to process repo SeldonIO/seldon-core refref 22cc6c86440a6232d32f5b44aa820902aad01251
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
