### PR TITLE
Add versions v1 and v1alpha3 to CRD

### LINKED ISSUE #890: Helm Upgrade Process
Check upgrades between versions have a documented process and has tests.

### LINKED ISSUE #1100: Move CRD to v1
* Will need to investigate Kubebuilder multi-version support.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #890.
Fixes #1100. 

## Changelog
- Add versions `v1` and `v1alpha3` of CRD.
- Set version `v1` as storage version.
- Rename previous imports of `v1alpha2` to `v1`.

## TODO

- [x] Add integration and unit tests across different versions of the CRD
- ~Reduce code duplication by importing from `v1` (or from outside)~
  We will raise this as a separate issue, which will involve refactoring the webhooks and types so that they can get imported in `v1alpha2` and `v1alpha3` (from `v1`).

## Note on webhooks

We only need to set up webhooks for the stored version. However, Seldon Core `0.4.1` seems to use `v1alpha3` for storage and Seldon Core `0.5.x` uses `v1alpha2` for storage. Therefore, the webhooks for each `apiVersion` (e.g. `/mutate-machinelearning-seldon-io-v1alpha2-seldondeployment`) also need to be registered.

This is necessary for the `SeldonDeployment` instances to update from `v1alpha2` + `v1alpha3` to `v1`.

On a future version of Seldon Core (e.g. `1.1`), we will be able to remove the `v1alpha2` and `v1alpha3` altogether. Or at least assume that they are not used for storage. This will enable us to unregister their respective webhooks.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Dec 10 09:54:45 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=1

**Comment by seldondev** [comment]
Tue Dec 10 09:54:50 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=2

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7aed3d56578340eef9107a0f3d50c31c0fecb1a1 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7aed3d56578340eef9107a0f3d50c31c0fecb1a1 | [link]() | `/test this`
lint | 7aed3d56578340eef9107a0f3d50c31c0fecb1a1 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Dec 10 15:30:32 UTC 2019
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=5

**Comment by seldondev** [comment]
Tue Dec 10 15:30:53 UTC 2019
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=6

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dcb158985a5a8fe550cda0952d799b4903b1daf2 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | dcb158985a5a8fe550cda0952d799b4903b1daf2 | [link]() | `/test this`
lint | dcb158985a5a8fe550cda0952d799b4903b1daf2 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Dec 10 17:57:25 UTC 2019
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=9

**Comment by seldondev** [comment]
Tue Dec 10 17:57:39 UTC 2019
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=10

**Comment by seldondev** [comment]
Wed Dec 11 09:19:31 UTC 2019
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=11

**Comment by seldondev** [comment]
Wed Dec 11 09:19:37 UTC 2019
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=12

**Comment by seldondev** [comment]
Wed Dec 11 13:29:45 UTC 2019
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=14

**Comment by seldondev** [comment]
Wed Dec 11 13:29:46 UTC 2019
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=13

**Comment by seldondev** [comment]
Wed Dec 11 14:43:29 UTC 2019
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=15

**Comment by seldondev** [comment]
Wed Dec 11 14:43:45 UTC 2019
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=16

**Comment by seldondev** [comment]
Wed Dec 11 17:40:13 UTC 2019
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=18

**Comment by seldondev** [comment]
Wed Dec 11 17:40:20 UTC 2019
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=17

**Comment by seldondev** [comment]
Wed Dec 11 17:49:16 UTC 2019
The logs for [integration] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=19

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | cb4884185c5c42e0111f180ba673e280b93daad0 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Dec 11 18:23:58 UTC 2019
The logs for [lint] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=21

**Comment by seldondev** [comment]
Wed Dec 11 18:24:01 UTC 2019
The logs for [pr-build] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=20

**Comment by seldondev** [comment]
Wed Dec 11 18:30:18 UTC 2019
The logs for [integration] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=22

**Comment by adriangonz** [comment]
/cc @axsaucedo @ryandawsonuk @cliveseldon 

If the integration tests pass, I think this is good to go now. I've added a couple of tests checking that:

- We can deploy models using all three versions: `v1`, `v1alpha2` and `v1alpha3`
- We can update a model's `apiVersion` from `v1alpha2 -> v1` and `v1alpha3 -> v1`

**Comment by cliveseldon** [comment]
Did you run `make clean create` in the `helm` folder of the Operator to create the helm templates from the kustomize?

**Comment by adriangonz** [comment]
@cliveseldon yuup! That added the new versions and webhooks to the `helm-charts/` folder.

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | bc42d1fc1f39867c67285909dfa65c138f08247a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Dec 11 20:57:21 UTC 2019
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=23

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | bc42d1fc1f39867c67285909dfa65c138f08247a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1229#issuecomment-564875179" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Dec 12 09:08:20 UTC 2019
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=24

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | bc42d1fc1f39867c67285909dfa65c138f08247a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Dec 12 09:41:44 UTC 2019
The logs for [integration] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=25

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | bc42d1fc1f39867c67285909dfa65c138f08247a | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
So the previous run there [was 1 failure](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/23.log#L1792) and this run (with no code changes) [there are 2](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/25.log#L1705)

**Comment by ryandawsonuk** [comment]
The 504 is on test_rolling_update5 both times

**Comment by seldondev** [comment]
Fri Dec 13 10:50:03 UTC 2019
The logs for [pr-build] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=26

**Comment by seldondev** [comment]
Fri Dec 13 10:50:09 UTC 2019
The logs for [lint] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=27

**Comment by seldondev** [comment]
Fri Dec 13 10:54:01 UTC 2019
The logs for [integration] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1229/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1229 --build=28

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 645a1e10cc8147aaf04c11818bd836b7c9e6b4b5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
