### PR TITLE
Use production server by default

### LINKED ISSUE #1993: Enable production mode in Python server by default
Currently, the Python server only uses Gunicorn and production settings if there are multiple workers. We should make sure that by default, even if it runs with a single worker, it also runs with production settings.

Additionally, it could be interesting to explore if it's possible (and makes sense) to always run the Python server with Gunicorn (i.e. even with a single worker).

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1993 

## Changelog

- Run Gunicorn by default with 1 worker and 10 threads
- Add `--threads` / `GUNICORN_THREADS` flags to control number of threads
- Add `--debug` / `SELDON_DEBUG` flags to enable Flask's development server
- Apply the same above to the metrics server
- Update docs

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 29 15:24:27 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=1

**Comment by seldondev** [comment]
Mon Jun 29 15:24:38 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=2

**Comment by seldondev** [comment]
Thu Jul  2 08:52:56 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=4

**Comment by seldondev** [comment]
Thu Jul  2 08:53:24 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=3

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 984345a74c184c64a669669924761a891a56e74c | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 984345a74c184c64a669669924761a891a56e74c | [link]() | `/test integration`
notebooks | 984345a74c184c64a669669924761a891a56e74c | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Seems ambassador install failed, strange...
/test integration

**Comment by seldondev** [comment]
Thu Jul  2 13:11:18 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=5

**Comment by seldondev** [comment]
@adriangonz: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 984345a74c184c64a669669924761a891a56e74c | [link]() | `/test notebooks`
integration | 984345a74c184c64a669669924761a891a56e74c | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 09:26:47 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=6

**Comment by seldondev** [comment]
Mon Jul  6 14:58:48 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=7

**Comment by seldondev** [comment]
Mon Jul  6 15:07:34 UTC 2020
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=8

**Comment by seldondev** [comment]
Tue Jul  7 12:18:40 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=9

**Comment by seldondev** [comment]
Tue Jul  7 12:31:21 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2047/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2047 --build=10

**Comment by axsaucedo** [comment]
Integration tests have passed

/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2047#issuecomment-654911157 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-654911157/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
