### PR TITLE
Changed OpenAPI file permissions within image

### LINKED ISSUE #1955: Golang Service Orchestrator (Executor) fails to replace variables since no longer runs root
Currently we have changed such that the container doesn't run as root which brings benefits on security. This causes an error as the golang executor is no longer able to replace the variables on startup on the openapi files. The container runs with user 8888 so currently the solution would be change the owner of the directory to be user with ID 8888.

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #1955

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 15 18:06:15 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=2

**Comment by seldondev** [comment]
Mon Jun 15 18:06:16 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=1

**Comment by seldondev** [comment]
Mon Jun 15 18:08:17 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 154f4448e96071122809e53197480cfacb0d17c8 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 15 19:17:09 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=4

**Comment by seldondev** [comment]
Tue Jun 16 05:28:48 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=6

**Comment by seldondev** [comment]
Tue Jun 16 05:28:58 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=5

**Comment by seldondev** [comment]
Tue Jun 16 05:38:02 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=8

**Comment by seldondev** [comment]
Tue Jun 16 05:38:06 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=7

**Comment by adriangonz** [comment]
/test integration

Interesting! I didn't think this could be a problem but it makes complete sense.

**Comment by seldondev** [comment]
Tue Jun 16 08:33:44 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=9

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 03c4a91b34f2c0291a719423f688376300115b9f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Add for redhat Dockerfile.

**Comment by seldondev** [comment]
Tue Jun 16 10:25:00 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=10

**Comment by seldondev** [comment]
Tue Jun 16 10:25:03 UTC 2020
The logs for [lint] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=11

**Comment by axsaucedo** [comment]
@cliveseldon @adriangonz I've added the changes for the redhat image to also copy the files with the right permissions

**Comment by adriangonz** [comment]
/approve

Looks good to me @axsaucedo!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1956#issuecomment-644741043" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jun 16 12:52:03 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=12

**Comment by seldondev** [comment]
Tue Jun 16 12:52:04 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=13

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 03c4a91b34f2c0291a719423f688376300115b9f | [link]() | `/test integration`
pr-build | c59eae50a84d944c007319d44cf955fca5a0f636 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 16 13:42:08 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1956/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1956 --build=14

**Pull request merged**
