### PR TITLE
Allow modification of flask app configs

### LINKED ISSUE #964: Set JSON_SORT_KEYS and JSONIFY_PRETTYPRINT_REGULAR to False by default
During our testing we have found out that setting [JSON_SORT_KEYS](https://flask.palletsprojects.com/en/1.1.x/config/#JSON_SORT_KEYS) and [JSONIFY_PRETTYPRINT_REGULAR](https://flask.palletsprojects.com/en/1.1.x/config/#JSONIFY_PRETTYPRINT_REGULAR) to False (in older version of flasks this is True by default) in flask increases performance quite a bit. especially if your payload is huge. 

This is because formatting will create lots of whitespace characters that gets sent through the wire and it takes computational resource. JSON_SORT_KEYS=False will also cause us not to unnecessarily sort keys of the dictionary. 

I can work on this in the next ~week or so.

### PR DESCRIPTION
**Pull request by kparaju**
Fixes #964 
```
# with FLASK_JSONIFY_PRETTYPRINT_REGULAR=False FLASK_JSON_SORT_KEYS=False

$ curl -g http://localhost:5000/predict --data-urlencode 'json={"data": {"names": ["test_1"], "ndarray": [{"x": 1, "b": 2}]}}'

{"data":{"ndarray":[{"x":1,"b":2}],"names":[]},"meta":{}}
```

```
# with FLASK_JSONIFY_PRETTYPRINT_REGULAR=True FLASK_JSON_SORT_KEYS=True
$ curl -g http://localhost:5000/predict --data-urlencode 'json={"data": {"names": ["test_1"], "ndarray": [{"x": 1, "b": 2}]}}'
{
  "data": {
    "names": [],
    "ndarray": [
      {
        "b": 2,
        "x": 1
      }
    ]
  },
  "meta": {}
}
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Hi @kparaju. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [seldonio](https://github.com/orgs/seldonio/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/seldonio/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by lennon310** [comment]
Thank you @kparaju. Could you add some documents/examples showing how to set these parameters (I assume it's in the deployment yaml file with `ENV`)?

**Comment by axsaucedo** [comment]
We have a section in the docs where we summarise the env variables you can provide to the container (such as LOG_INFO), I think it would be useful to add this. THanks @kparaju

**Comment by kparaju** [comment]
Will do.

**Comment by seldondev** [comment]
@kparaju: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5f76f897d76f34e3a7adbdff7c12edd00dc8a3f9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by kparaju** [comment]
@axsaucedo can you suggest the best place to put this information? Should I create an optional section here: https://docs.seldon.io/projects/seldon-core/en/latest/python/python_wrapping_docker.html#environment-variables ?

**Comment by axsaucedo** [comment]
That would be the perfect location @kparaju  

Thank you for your contribution

/test integration

**Comment by seldondev** [comment]
@kparaju: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5f76f897d76f34e3a7adbdff7c12edd00dc8a3f9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1030#issuecomment-549979522" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Thank you for your contribution @kparaju !

**Pull request merged**
