### PR TITLE
Upgrade go dependencies: zap istio knative

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/2128 (knative.dev)
Closes https://github.com/SeldonIO/seldon-core/issues/2127 (zap)
Closes https://github.com/SeldonIO/seldon-core/issues/2126 (istio.io)

Knative dev go.mod updated entry generated with
```
go get knative.dev/pkg@release-0.14
```

Replaces https://github.com/SeldonIO/seldon-core/pull/2125 (istio.io)
Updated entry for go.mod generated with
```
go get istio.io/api@release-1.5
go get istio.io/client-go@release-1.5
```

Replaces https://github.com/SeldonIO/seldon-core/pull/2122

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jul 14 14:58:40 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2129/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2129 --build=1

**Comment by seldondev** [comment]
Tue Jul 14 14:59:18 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2129/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2129 --build=2

**Comment by seldondev** [comment]
Tue Jul 14 15:18:18 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2129/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2129 --build=3

**Comment by seldondev** [comment]
Tue Jul 14 15:18:31 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2129/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2129 --build=4

**Comment by RafalSkolasinski** [comment]
Integration fail on `TestLocalOperators.test_labelled_operator` - starting again.

**Comment by seldondev** [comment]
Tue Jul 14 17:00:43 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2129/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2129 --build=5

**Comment by RafalSkolasinski** [comment]
Notebook tests passed, still waiting for integration.

**Comment by RafalSkolasinski** [comment]
@axsaucedo it seems that both integration and notebooks passed! :rocket:

**Comment by axsaucedo** [comment]
Nice one @RafalSkolasinski !

**Pull request merged**
