### PR TITLE
Add release notes template

### LINKED ISSUE #1471: Improve release notes
Right now we generate the release notes automatically from Git's history (using PR titles). However, this information alone may not be enough on some cases. One common example would be breaking changes introduced by the PR (e.g. dependency updates, changes on functionality, naming, etc.).

It would be good to define a process to document these kind of upgrade notes (including breaking changes) so that they also get incorporated on the release notes.

Before deciding on a process, we should research what other open source projects do to compile these notes and to generate the changelogs automatically. Prow may already have an opinion on how to compile and publish breaking changes?

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Fetch the `release-notes` block of every PR merged between 2 particular tags to generate easy-to-follow release notes.

**Which issue(s) this PR fixes**:

Fixes #1471

**Special notes for your reviewer**:
This is mostly a draft PR showing an example format which we could use to generate our release notes. The main goal is to discuss and get people's opinions on the template and how we could integrate them further with our release process.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jul 24 13:15:30 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2190/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2190 --build=1

**Comment by seldondev** [comment]
Fri Jul 24 13:16:09 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2190/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2190 --build=2

**Comment by adriangonz** [comment]
If we are happy with the template for release notes, we can merge this PR and then enable the Prow / Lighthouse plugin to make sure all PRs have a `release-notes` block (or have explicitly disabled).

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2190#issuecomment-694124375 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-694124375/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
