### PR TITLE
WIP: Exploration for fix of integration tests container containers hanging

### PR DESCRIPTION
**Pull request by axsaucedo**
This exploration is related to #2080 but initially to assess potential causes.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul  6 19:17:43 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=2

**Comment by seldondev** [comment]
Mon Jul  6 19:17:52 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=1

**Comment by seldondev** [comment]
Mon Jul  6 19:19:34 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=3

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 46066ae2fdd3d980f277c9cffe67b72db6f28bb1 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 19:29:52 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=5

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 46066ae2fdd3d980f277c9cffe67b72db6f28bb1 | [link]() | `/test integration`
pr-build | b184f4d0b5c77598e9f7c96064daf5a86fa18de7 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 19:35:29 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=8

**Comment by seldondev** [comment]
Mon Jul  6 19:35:46 UTC 2020
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=9

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | b184f4d0b5c77598e9f7c96064daf5a86fa18de7 | [link]() | `/test this`
lint | 51a29851f86364976b780888d995e4b9ba74307d | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 19:42:57 UTC 2020
The logs for [integration] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=12

**Comment by seldondev** [comment]
Mon Jul  6 19:48:48 UTC 2020
The logs for [integration] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=13

**Comment by seldondev** [comment]
Mon Jul  6 19:54:37 UTC 2020
The logs for [integration] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=16

**Comment by seldondev** [comment]
Mon Jul  6 19:59:59 UTC 2020
The logs for [integration] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=17

**Comment by seldondev** [comment]
Mon Jul  6 20:05:19 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=18

**Comment by seldondev** [comment]
Mon Jul  6 20:24:11 UTC 2020
The logs for [integration] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=20

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | b184f4d0b5c77598e9f7c96064daf5a86fa18de7 | [link]() | `/test this`
lint | 51a29851f86364976b780888d995e4b9ba74307d | [link]() | `/test lint`
integration | ba81f9ee0744a614bb9122ce627ff73593de788e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul  6 20:40:27 UTC 2020
The logs for [integration] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=22

**Comment by seldondev** [comment]
Tue Jul  7 05:45:08 UTC 2020
The logs for [integration] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=23

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | b184f4d0b5c77598e9f7c96064daf5a86fa18de7 | [link]() | `/test this`
lint | 51a29851f86364976b780888d995e4b9ba74307d | [link]() | `/test lint`
integration | ba81f9ee0744a614bb9122ce627ff73593de788e | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul  7 06:05:26 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2081/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2081 --build=24

**Comment by axsaucedo** [comment]
It was possible to start the docker daemon on a different cgroup but it seems like it was not possible to ensure the KIND cluster is able to work with that configuration, even when passing the parameter cgroup-root to the kubelet init configuration nodeRegistration component

**Pull request closed without merging**
