### PR TITLE
try allowing unknown istio fields

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Trying this based on @axsaucedo discovering https://github.com/knative-sandbox/net-istio/pull/114/files

Hopefully could resolve https://github.com/SeldonIO/seldon-core/issues/1551, which has resurfaced in 1.2.2

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **ryandawsonuk**
You can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Aug 12 17:56:34 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2266/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2266 --build=1

**Comment by seldondev** [comment]
Wed Aug 12 17:56:58 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2266/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2266 --build=2

**Comment by seldondev** [comment]
Wed Aug 12 17:57:49 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2266/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2266 --build=3

**Comment by axsaucedo** [comment]
Nice one @ryandawsonuk! Looks good to go

/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2266#issuecomment-673115914 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-673115914/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by ryandawsonuk** [comment]
Have checked this against istio 1.1 and was able to see virtualservices created and call services through istio gateway correctly.

**Pull request merged**
