### PR TITLE
Revert "Fix defaulting by api-server differences"

### PR DESCRIPTION
**Pull request by ryandawsonuk**
Reverts SeldonIO/seldon-core#1214

To check whether integration tests pass on this as test_rolling_update5 seems to be failing on master and they were [passing two days ago ](https://github.com/SeldonIO/seldon-core/pull/1231)and the [output from this PR was confusing](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1214/7.log#L336)

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Dec 12 11:33:20 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1250/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1250 --build=1

**Comment by seldondev** [comment]
Thu Dec 12 11:33:21 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1250/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1250 --build=2

**Comment by seldondev** [comment]
Thu Dec 12 11:33:36 UTC 2019
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1250/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1250 --build=3

**Comment by ryandawsonuk** [comment]
This issue is being addressed by https://github.com/SeldonIO/seldon-core/pull/1253

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref d301d98d14ffbdaa39b13b151059519c53215181
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha d301d98d14ffbdaa39b13b151059519c53215181
* failed to process repo SeldonIO/seldon-core refref d301d98d14ffbdaa39b13b151059519c53215181
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
