### PR TITLE
factor out minio setup instructions into single notebook

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Closes https://github.com/SeldonIO/seldon-core/issues/1740.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rafalskolasinski**

If they are not already assigned, you can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sun May 24 16:00:03 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=1

**Comment by seldondev** [comment]
Sun May 24 16:00:08 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=2

**Comment by RafalSkolasinski** [comment]
for tests to pass will have to push new core-builder image to the hub

**Comment by seldondev** [comment]
Sun May 24 18:17:14 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=3

**Comment by seldondev** [comment]
Sun May 24 18:17:22 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=4

**Comment by seldondev** [comment]
Sun May 24 19:06:22 UTC 2020
The logs for [notebooks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=5

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e36e167afa8132c6c738a8ce6cd72fe4f577bc2b | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 24 19:30:11 UTC 2020
The logs for [notebooks] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=6

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e36e167afa8132c6c738a8ce6cd72fe4f577bc2b | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 24 20:15:39 UTC 2020
The logs for [notebooks] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=9

**Comment by seldondev** [comment]
Sun May 24 20:15:41 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=7

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e36e167afa8132c6c738a8ce6cd72fe4f577bc2b | [link]() | `/test notebooks`
pr-build | 6107fe1fc67cc8856752450c7584c1148a3436f1 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Sun May 24 20:19:41 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=8

**Comment by seldondev** [comment]
Sun May 24 20:23:43 UTC 2020
The logs for [pr-build] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=10

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 6107fe1fc67cc8856752450c7584c1148a3436f1 | [link]() | `/test this`
notebooks | 6107fe1fc67cc8856752450c7584c1148a3436f1 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
For some reason minio installation is failing in the CI. Will have to debug.

**Comment by seldondev** [comment]
Mon May 25 10:26:43 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=11

**Comment by seldondev** [comment]
Mon May 25 10:26:53 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=13

**Comment by seldondev** [comment]
Mon May 25 10:28:17 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=12

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7de362fe82a29c315e1748061e52b4a569157ea6 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 10:48:34 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=14

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7de362fe82a29c315e1748061e52b4a569157ea6 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 11:03:22 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=16

**Comment by seldondev** [comment]
Mon May 25 11:03:39 UTC 2020
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=17

**Comment by seldondev** [comment]
Mon May 25 11:03:40 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=15

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 13:49:01 UTC 2020
The logs for [notebooks] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=18

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 13:59:30 UTC 2020
The logs for [integration] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=19

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`
integration | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 14:37:28 UTC 2020
The logs for [notebooks] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=20

**Comment by seldondev** [comment]
Mon May 25 14:37:41 UTC 2020
The logs for [integration] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=21

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`
integration | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test integration`
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 17:13:40 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=22

**Comment by seldondev** [comment]
Mon May 25 17:13:55 UTC 2020
The logs for [notebooks] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=24

**Comment by seldondev** [comment]
Mon May 25 17:14:02 UTC 2020
The logs for [integration] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=25

**Comment by seldondev** [comment]
Mon May 25 17:15:07 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=23

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | cfc4e14f1d65d9312510ec880d09ab91b73afacf | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon May 25 19:11:26 UTC 2020
The logs for [integration] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=26

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue May 26 08:39:37 UTC 2020
The logs for [integration] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=27

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue May 26 17:29:26 UTC 2020
The logs for [integration] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=28

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed May 27 09:48:03 UTC 2020
The logs for [pr-build] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=29

**Comment by seldondev** [comment]
Wed May 27 09:48:03 UTC 2020
The logs for [lint] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=30

**Comment by seldondev** [comment]
Wed May 27 09:57:21 UTC 2020
The logs for [lint] [32] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/32.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=32

**Comment by seldondev** [comment]
Wed May 27 09:57:21 UTC 2020
The logs for [pr-build] [31] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/31.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=31

**Comment by seldondev** [comment]
Wed May 27 09:58:59 UTC 2020
The logs for [lint] [34] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/34.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=34

**Comment by seldondev** [comment]
Wed May 27 10:00:19 UTC 2020
The logs for [pr-build] [33] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/33.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=33

**Comment by seldondev** [comment]
Wed May 27 10:01:04 UTC 2020
The logs for [pr-build] [35] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/35.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=35

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`
pr-build | d3cb71ade1349e90793801d25a0e33a668b5e4a7 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed May 27 10:03:40 UTC 2020
The logs for [lint] [36] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/36.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=36

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test notebooks`
integration | 400f9f3052566b0327e9a52159b08440527dd7a9 | [link]() | `/test integration`
pr-build | d0add7fd98d4cb61ad61eeabfacee7d415e3b37a | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed May 27 10:11:52 UTC 2020
The logs for [lint] [38] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/38.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=38

**Comment by seldondev** [comment]
Wed May 27 10:11:43 UTC 2020
The logs for [pr-build] [37] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/37.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=37

**Comment by RafalSkolasinski** [comment]
This leads no breaking changes to code / CI - modified notebooks do not run in CI (yet).
Merging as discussed! @axsaucedo

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1868#issuecomment-635235009" title="Approved">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu May 28 09:43:16 UTC 2020
The logs for [pr-build] [39] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/39.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=39

**Comment by seldondev** [comment]
Thu May 28 09:43:29 UTC 2020
The logs for [lint] [40] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1868/40.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1868 --build=40

**Pull request merged**
