### PR TITLE
Document custom inference servers

### LINKED ISSUE #1416: Document custom pre-packaged model servers
We added support for custom "pre"-packaged servers back in #959. However it's not very clearly documented how to use them. 

It would be good to add an example and/or more detailed docs on how to edit the `seldon-config` configmap to add custom servers.

### PR DESCRIPTION
**Pull request by adriangonz**
Fixes #1416 

## Changelog

- Add new page on building and adding "Custom Inference Servers".
- Split S2I + Docker link to wrapping your own model in 2 separate lines.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Apr  7 17:05:55 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1673/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1673 --build=1

**Comment by seldondev** [comment]
Tue Apr  7 17:06:00 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1673/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1673 --build=2

**Comment by axsaucedo** [comment]
Awesome!! @adriangonz if you add the link to the index in readme.md it should be good to land

**Comment by RafalSkolasinski** [comment]
If it possible to specify custom inference server without modifying `configmap` it may be worth adding.
It would allow users who only have single-namespace access to deploy such servers without asking admins to modify seldon-core wide configmap.

**Comment by axsaucedo** [comment]
@RafalSkolasinski that's an interesting point, I think we could abstract this eventually, but I think we shoudl create a ticket for that, as I agree that this is something that may be worth exploring - ie how users coudl add their own prepackaged servers withou modifying the global config.. perhaps this could even be a namespace configmap that can overrride the global configmap

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1673#issuecomment-610825907" title="LGTM">RafalSkolasinski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1673#issuecomment-610826008" title="Approved">RafalSkolasinski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by RafalSkolasinski** [comment]
@agm It may be a good idea to link that custom prepackaged servers from mlflow server [docpage](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#conda-environment-creation), what do you think?

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by adriangonz** [comment]
Thanks for the comments @RafalSkolasinski @axsaucedo. Both should be added now!

**Comment by RafalSkolasinski** [comment]
Awesome stuff!
/lgtm
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1673#issuecomment-610986172" title="Approved">RafalSkolasinski</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Apr  8 14:41:57 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1673/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1673 --build=3

**Comment by seldondev** [comment]
Wed Apr  8 14:42:02 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1673/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1673 --build=4

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1673#issuecomment-610986172" title="Approved">RafalSkolasinski</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 9753aa17309bedf4b4f5fa287704e163d08c372b
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 9753aa17309bedf4b4f5fa287704e163d08c372b
* failed to process repo SeldonIO/seldon-core refref 9753aa17309bedf4b4f5fa287704e163d08c372b
* failed to list files in directory /var/tmp/gitrepo660600678/.lighthouse
* open /var/tmp/gitrepo660600678/.lighthouse
* no such file or directory

**Pull request merged**
