### PR TITLE
Remove test dependencies from setup.py

### LINKED ISSUE #2302: Remove depedency on deprecated pytest-runner
It would be great if you could remove the dependency you currently have on the `pytest-runner` package. This uses unsafe methods to install dependencies and has been deprecated.
Deprecation notice taken from [here](https://pypi.org/project/pytest-runner/#description):

> pytest-runner depends on deprecated features of setuptools and relies on features that break security mechanisms in pip. For example ‘setup_requires’ and ‘tests_require’ bypass pip --require-hashes. See also https://github.com/pypa/setuptools/issues/1684.
> 
> It is recommended that you:
> 
>     Remove ‘pytest-runner’ from your ‘setup_requires’, preferably removing the setup_requires option.
>     Remove ‘pytest’ and any other testing requirements from ‘tests_require’, preferably removing the setup_requires option.
>     Select a tool to bootstrap and then run tests such as tox

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Remove test references in `setup.py` since we no longer use it for testing and it introduces some security risks. 

**Which issue(s) this PR fixes**:

Fixes #2302 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Aug 28 15:19:26 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2344/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2344 --build=2

**Comment by seldondev** [comment]
Fri Aug 28 15:19:38 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2344/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2344 --build=1

**Review by RafalSkolasinski — APPROVED** [review]

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2344#pullrequestreview-477820333 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 3bec227c763d3124adc843492a1389f7254bcb5b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@adriangonz are the lint tests failing due to requiring rebase from master branch? If so may require either merging manually after confirming or rebasing and retesting

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by adriangonz** [comment]
Thanks for the heads up @axsaucedo. Let me rebase, that should fix the linting error.

**Comment by seldondev** [comment]
Tue Sep  1 08:28:53 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2344/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2344 --build=4

**Comment by seldondev** [comment]
Tue Sep  1 08:29:00 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2344/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2344 --build=3

**Pull request merged**
