### PR TITLE
Make operator and executor dynamically linked in Dockerfile images

### LINKED ISSUE #1951: Make Operator and Executor Dockefile executable dynamically linked
This will provide the clearest linking to libc libraries used by any Go component.
We presently have no CGO_ENABLED builds in Dockerfile so may not be strictly required.

### PR DESCRIPTION
**Pull request by cliveseldon**
Fixes #1951

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jun 15 17:01:14 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1953/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1953 --build=2

**Comment by seldondev** [comment]
Mon Jun 15 17:01:16 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1953/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1953 --build=1

**Comment by seldondev** [comment]
Tue Jun 16 12:49:14 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1953/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1953 --build=3

**Comment by axsaucedo** [comment]
Looks good! Integration tests seem good (currently running rolling updates which means synchronous ones passed)
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1953#issuecomment-644776457" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jun 16 14:41:24 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1953/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1953 --build=5

**Comment by seldondev** [comment]
Tue Jun 16 14:41:38 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1953/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1953 --build=4

**Pull request merged**
