### PR TITLE
Add SELDON_ENVIRONMENT to Index Name

### LINKED ISSUE #2328: Setting and using SELDON_ENVIRONMENT for Request Logging to use one ELK Cluster for multiple Environment
**MAIN MOTIVATION: Having 1 ELK Cluster for different ENVIRONMENTs ( dev/test/staging/prod)**

Can we put a prefix on index  to Request-Logger's ELK Indices

Right now it is like
```
inference-log-seldon-<NAMESPACE>-<SELDONDEPLOYMENT>-<MODELNAME>
```
what i want is something like

```
inference-log-<SELDON_ENVIRONMENT>-seldon-<NAMESPACE>-<SELDONDEPLOYMENT>-<MODELNAME>
 
````
as i create user based on that and have 1 ELK cluster that dev/staging/prod will log to this cluster. For me to create user via Kibana DevTools: ( I define Index Pattern to access to role).
```
POST _security/role/logstash_writer-dev
{
  "cluster": ["manage_index_templates", "monitor", "manage_ilm"], 
  "indices": [
    {
      "names": [ "k8s_cluster-dev-*" , "inference-log-dev-*" ], 
      "privileges": ["write","create","delete","create_index","manage","manage_ilm"]  
    }
  ]
}



POST _security/user/elastic-seldon-dev
{
  "password" : "PASS",
  "roles" : [ "logstash_writer-dev"],
  "full_name" : "Internal Logstash User for Seldon"
}

```
I can provide prefix to Fluentd part  like:

fluentd-values.yaml: ( via elasticsearch.logstash.prefix 
```
elasticsearch:
  hosts: ["df65d4b2795d481dbe235733219ca518.eu-central-1.aws.cloud.es.io:9243"]
  logstash:
    prefix: k8s_cluster-dev
  auth:
    enabled: true
    user: elastic-seldon-dev
    password: <PASSSWORD>
  sslVerify: false
  scheme: https
```

### PR DESCRIPTION
**Pull request by sercostr**
**What this PR does / why we need it**:

SELDON_ENVIRONMENT variable added to the logging "inference-log"

**Which issue(s) this PR fixes**:

Fixes #2328 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @sercostr. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by ryandawsonuk — APPROVED** [review]
Would be good to also add field to the body of the logged request but that could be handled as a separate issue/follow-up
/lgtm
/approve

**Comment by seldondev** [comment]
Wed Aug 26 12:14:33 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2329/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2329 --build=2

**Comment by seldondev** [comment]
Wed Aug 26 12:14:38 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2329/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2329 --build=1

**Comment by seldondev** [comment]
@sercostr: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7395c53f0d605d0ae65844aef7714342261d03ec | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Aug 26 15:58:11 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2329/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2329 --build=3

**Comment by axsaucedo** [comment]
@omerfsen thank you very much! One small request, could we rename the env var to something more descriptive? "SELDON_ENVIRONMENT" is a bit too generic, and could be confusing. Maybe somethin that mentions elastic / request logger (cc @ryandawsonuk )
/hold

**Comment by axsaucedo** [comment]
Sorry for not mentioning this earlier, completely slipped - @ryandawsonuk if we're happy to do it in a separate pr happy to move forward as I don't want to hold it back if it will take too long (and it is quite a fast change)

**Comment by axsaucedo** [comment]
Actually I think this is definitely good for now in general tbh, and we can make it clear in the documentation. Thanks again for the contribution @omerfsen !
/hold cancel

**Comment by seldondev** [comment]
@sercostr: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7395c53f0d605d0ae65844aef7714342261d03ec | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Looking at the failed tests, we're currnetly aware they are flaky, and they are passing in two of the three TOX runs, so we can go ahead

**Pull request merged**
