### PR TITLE
analytics option to switch nodeExporter port

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/1916

First time I ran the upgrade I hit the immutable field problem https://github.com/helm/helm/issues/7173

Then I had to do:
```
kubectl delete deployment -n seldon-system -l app=grafana
```
If I'd done that once before upgrading that probably would've been enough. But because of the failed attempt I also had to do:
```
kubectl delete -n seldon-system sa seldon-core-analytics-kube-state-metrics
kubectl delete clusterrole seldon-core-analytics-kube-state-metrics
kubectl delete clusterrolebinding seldon-core-analytics-kube-state-metrics
kubectl delete -n seldon-system svc seldon-core-analytics-kube-state-metrics
kubectl delete deployment -n seldon-system seldon-core-analytics-kube-state-metrics
```
Then I was able to run
```
helm upgrade --install seldon-core-analytics ./helm-charts/seldon-core-analytics/ --namespace seldon-system --set prometheus.nodeExporter.service.hostPort=9200 --set prometheus.nodeExporter.service.servicePort=9200
```
Have included a note on upgrading in the upgrading.md

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jun  5 10:26:48 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=1

**Comment by seldondev** [comment]
Fri Jun  5 10:27:54 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=2

**Comment by seldondev** [comment]
Fri Jun  5 10:28:59 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=4

**Comment by seldondev** [comment]
Fri Jun  5 10:29:15 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=3

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | e708c2396bb2ed14b327c9dff28c52c2b29380d8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jun  5 10:43:32 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=5

**Comment by axsaucedo** [comment]
Looks good 
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1917#issuecomment-643321790" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jun 12 15:06:33 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=6

**Comment by seldondev** [comment]
Fri Jun 12 15:06:37 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=7

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | e708c2396bb2ed14b327c9dff28c52c2b29380d8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Not sure how this could break PR build 🤔
/test this

**Comment by seldondev** [comment]
Fri Jun 12 15:14:44 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1917/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1917 --build=8

**Pull request merged**
