### PR TITLE
WIP: Release Release-1.2.3 (PR only to run tests)

### PR DESCRIPTION
**Pull request by axsaucedo**
This PR is only in place to run tests for Release 1.2.3

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Aug 13 14:57:13 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=1

**Comment by seldondev** [comment]
Thu Aug 13 14:57:45 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=2

**Comment by seldondev** [comment]
Thu Aug 13 14:57:54 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=3

**Comment by seldondev** [comment]
Thu Aug 13 14:58:03 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=4

**Comment by seldondev** [comment]
Thu Aug 13 14:59:36 UTC 2020
The logs for [securitychecks] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=5

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
securitychecks | c6df0207dbee6035a78417a22b64dcc795dcba8c | [link]() | `/test securitychecks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
The only vulnerability flagged was on PyYAML, and we already have an open issue that is waiting for the upgrade fix:
```
Issues with no direct upgrade or patch:
  ✗ Arbitrary Code Execution [High Severity][https://snyk.io/vuln/SNYK-PYTHON-PYYAML-590151] in pyyaml@5.3.1
  No upgrade or patch available
```

**Comment by seldondev** [comment]
Fri Aug 14 06:29:36 UTC 2020
The logs for [engine] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=6

**Comment by seldondev** [comment]
Fri Aug 14 09:46:38 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=7

**Comment by seldondev** [comment]
Fri Aug 14 09:46:43 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2275/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2275 --build=8

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
securitychecks | c6df0207dbee6035a78417a22b64dcc795dcba8c | [link]() | `/test securitychecks`
pr-build | 418f3105702600112e958b58d4229e7c86d73e83 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Release has been completed, closing PR

**Pull request closed without merging**
