### PR TITLE
Add licenses to Python images

### PR DESCRIPTION
**Pull request by adriangonz**
Related to #1360 

## Changelog
- Add `tox` environment to generate the licensing info using [`pip-licenses`](https://github.com/raimon49/pip-licenses)
- Add generated `licenses/license.txt` and `licenses/dep.csv` to repo
- Copy licenses explicitly on non-local `s2i` images

## Notes
The `pip-licenses` tool generates the list of deps from the installed packages. To avoid a "dirty" local virtualenv (and pulling in licenses not required by `seldon-core`) I've added a `tox` env which generates the list.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **adriangonz**

If they are not already assigned, you can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jan 28 18:04:01 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=1

**Comment by seldondev** [comment]
Tue Jan 28 18:04:13 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=2

**Comment by axsaucedo** [comment]
Nice! Lgtm from my side 👍

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1379#issuecomment-581390199" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Feb  3 12:25:52 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=3

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 553928752ac21b89c420fea6107c97f49abcfb26 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Feb  4 21:53:01 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=4

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 553928752ac21b89c420fea6107c97f49abcfb26 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
New changes are detected. LGTM label has been removed.

**Comment by seldondev** [comment]
Tue Feb 11 15:25:12 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=6

**Comment by seldondev** [comment]
Tue Feb 11 15:25:17 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=5

**Comment by seldondev** [comment]
Tue Feb 11 15:25:25 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=7

**Comment by seldondev** [comment]
Tue Feb 11 16:51:57 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=8

**Comment by seldondev** [comment]
Tue Feb 11 16:51:58 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=9

**Comment by seldondev** [comment]
Tue Feb 11 16:52:56 UTC 2020
The logs for [integration] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1379/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1379 --build=10

**Pull request merged**
