### PR TITLE
Functionality for model wrapper to return JSON on any Dict return

### LINKED ISSUE #1145: Standardise Data Mappings in Seldon Wrapper
Currently the data conversions from Python data structures into SeldonMessage components (i.e. data, strData, jsonData or binData) are not fully standardised. For example, the only way to retunr a jsonData atm is by sending jsonData as input. A fix would be to set the data to be converted into Dict by default. But it would also be important to consider cases such as when we return "strData" or "binData", as these can be valid jsonData as well.

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #1145

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
It seems the path for the tests is already covered by `test_create_rest_response_jsondata`

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fb72974145ca467361fcf7e61a3d210068afa96 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fb72974145ca467361fcf7e61a3d210068afa96 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
It's a bit scary that we haven't broken any tests after the change. Perhaps it would be good to add one for the new behaviour @axsaucedo?

**Comment by axsaucedo** [comment]
@adriangonz all the current tests (and expected workflows) for jsonData actually do cover this, as it expects that any inputs of jsonData return a dictionary and hence a jsonData, however now the logic is not based on the input being jsonData, but on the return value being a Dict. This would still cover it, but for the sake of explicitness I'll add another tests that sends a numpy array as input and returns a dict, which would explicitly test that no matter what the input, as long as the output is a dict, it will return jsonData.

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fb72974145ca467361fcf7e61a3d210068afa96 | [link]() | `/test integration`
lint | 382af7dfbbe88449be23c213ffa97d253c6b346b | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6fb72974145ca467361fcf7e61a3d210068afa96 | [link]() | `/test integration`
lint | 382af7dfbbe88449be23c213ffa97d253c6b346b | [link]() | `/test lint`
pr-build | 382af7dfbbe88449be23c213ffa97d253c6b346b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
@adriangonz I added now 👍

**Comment by adriangonz** [comment]
/approve

Nice! Looks great!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1174#issuecomment-561126499" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
