### PR TITLE
grpc support for metadata

### PR DESCRIPTION
**Pull request by RafalSkolasinski**

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rafalskolasinski**

If they are not already assigned, you can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jun 17 15:48:37 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=2

**Comment by seldondev** [comment]
Wed Jun 17 15:48:35 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=1

**Comment by seldondev** [comment]
Wed Jun 17 17:33:35 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=4

**Comment by seldondev** [comment]
Wed Jun 17 17:33:47 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=3

**Comment by seldondev** [comment]
Wed Jun 17 17:59:58 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=5

**Comment by seldondev** [comment]
Thu Jun 18 16:57:42 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=8

**Comment by seldondev** [comment]
Thu Jun 18 16:57:53 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=7

**Comment by seldondev** [comment]
Fri Jun 19 09:31:57 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=9

**Comment by seldondev** [comment]
Fri Jun 19 09:31:59 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=10

**Comment by seldondev** [comment]
Fri Jun 19 16:50:51 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=11

**Comment by seldondev** [comment]
Fri Jun 19 16:51:00 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=12

**Comment by seldondev** [comment]
Fri Jun 19 16:56:31 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=14

**Comment by seldondev** [comment]
Fri Jun 19 16:57:42 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=13

**Comment by seldondev** [comment]
Fri Jun 19 17:01:01 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=15

**Comment by seldondev** [comment]
Fri Jun 19 17:01:06 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=16

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 3037354f63daf3938ff7a633cf0406e8a7196eec | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 9721295e581d6d656ff755a348d8954cbbb966a5 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 7e961a058ea5c3f9f1e63b083dd8618e272c42ec | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 22 11:50:27 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=17

**Comment by seldondev** [comment]
Mon Jun 22 11:50:29 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=18

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a0473be54fe6317c074f5e18e43bf9f69fa1ee26 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 22 17:03:07 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=19

**Comment by seldondev** [comment]
Mon Jun 22 17:03:13 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=20

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a0473be54fe6317c074f5e18e43bf9f69fa1ee26 | [link]() | `/test this`
lint | d7bd43418d7e6ff7a391f693744e71059cce4707 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 22 17:12:40 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=22

**Comment by seldondev** [comment]
Mon Jun 22 17:13:38 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=21

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a0473be54fe6317c074f5e18e43bf9f69fa1ee26 | [link]() | `/test this`
lint | 1969ff8586990f230e3202955df467193a3cab92 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 14:20:28 UTC 2020
The logs for [pr-build] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=23

**Comment by seldondev** [comment]
Tue Jun 23 14:20:31 UTC 2020
The logs for [lint] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=24

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | e59b13542a281545551ee7f9970964d623d43375 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 23 14:24:34 UTC 2020
The logs for [pr-build] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=25

**Comment by seldondev** [comment]
Tue Jun 23 14:26:04 UTC 2020
The logs for [lint] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1969/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1969 --build=26

**Comment by RafalSkolasinski** [comment]
closing to open new one with ReviewNB links

**Pull request closed without merging**
