### PR TITLE
Decouple executor's logger from controller-runtime

### LINKED ISSUE #2090: Refactor logging in Executor
Sub Issue of https://github.com/SeldonIO/seldon-core/issues/2088.

Currently we use `go-logr` implementation coming from `sigs.k8s.io/controller-runtime/pkg/runtime/log`.
Using an alternative implementation or providing one on our own would allow to lift that dependency from Executor's `go.mod`.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Add our own version of `controller-runtime`'s log management facility. That way we can remove the `executor`'s dependency on `controller-runtime` and, instead, depend directly on `zap` and `zapr`.

**Which issue(s) this PR fixes**:

Fixes #2090

**Special notes for your reviewer**:

This PR borrows some functionality from https://github.com/SeldonIO/seldon-core/pull/1980/. However, since that one hasn't been merged yet, we've just cherry-picked the changes so that this one can be based directly from `master`. That's why the `SetLogger` method receives 2 `debug` and `logLevel` parameters. These parameters will be read from flags / env vars once https://github.com/SeldonIO/seldon-core/pull/1980/ gets merged.

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jul 10 14:39:27 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=2

**Comment by seldondev** [comment]
Fri Jul 10 14:39:57 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=1

**Comment by seldondev** [comment]
Fri Jul 10 14:42:06 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=3

**Comment by RafalSkolasinski** [comment]
@adriangonz We merged #1980, would you be able to rebase this one so we can fire integration/notebook tests on it?

**Comment by seldondev** [comment]
Mon Jul 13 15:09:07 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=4

**Comment by seldondev** [comment]
Mon Jul 13 15:09:10 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=5

**Comment by seldondev** [comment]
Mon Jul 13 15:10:38 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=6

**Comment by seldondev** [comment]
Mon Jul 13 15:10:44 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=7

**Comment by seldondev** [comment]
Mon Jul 13 15:12:47 UTC 2020
The logs for [lint] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=9

**Comment by seldondev** [comment]
Mon Jul 13 15:12:51 UTC 2020
The logs for [pr-build] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=8

**Comment by seldondev** [comment]
Mon Jul 13 15:15:55 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=11

**Comment by seldondev** [comment]
Mon Jul 13 15:15:58 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=10

**Comment by seldondev** [comment]
Wed Jul 15 08:42:12 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=13

**Comment by seldondev** [comment]
Wed Jul 15 08:42:12 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=12

**Comment by seldondev** [comment]
Wed Jul 15 09:25:44 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=14

**Comment by seldondev** [comment]
Wed Jul 15 09:25:49 UTC 2020
The logs for [integration] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=15

**Comment by seldondev** [comment]
Wed Jul 15 12:26:46 UTC 2020
The logs for [pr-build] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=16

**Comment by seldondev** [comment]
Wed Jul 15 12:26:49 UTC 2020
The logs for [lint] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=17

**Comment by seldondev** [comment]
Wed Jul 15 13:46:10 UTC 2020
The logs for [integration] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=18

**Comment by seldondev** [comment]
Wed Jul 15 14:27:47 UTC 2020
The logs for [notebooks] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2105/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2105 --build=19

**Comment by adriangonz** [comment]
Since we still have the dependency on `controller-runtime` through the `operator`, should we close this one @axsaucedo @RafalSkolasinski ?

**Comment by RafalSkolasinski** [comment]
I think we were trying to remove dependency on `controller-runtime` in order to remove dependency on `go-logr` - but as we decided (?) to keep `go-logr` then yes, I think we can close this one.

**Comment by RafalSkolasinski** [comment]
Just to comment - this is a good PR and if we ever decide to go with it that is most likely the way to go!

**Pull request closed without merging**
