### PR TITLE
WIP: Clientset for seldon operator

### PR DESCRIPTION
**Pull request by SachinVarghese**
This PR adds a clientset for the seldon CRD and the operator is also migrated to a multi-group structure.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **sachinvarghese**

If they are not already assigned, you can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Dec 11 15:36:49 UTC 2019
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1242/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1242 --build=1

**Comment by seldondev** [comment]
Wed Dec 11 15:36:54 UTC 2019
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1242/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1242 --build=2

**Comment by seldondev** [comment]
Wed Dec 11 15:56:12 UTC 2019
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1242/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1242 --build=3

**Comment by seldondev** [comment]
@SachinVarghese: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6eeddedd07d334ba53bfae8be70f4f00bfeb84c5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Let's wait for #1229 before proceeding further with this

**Comment by seldondev** [comment]
Thu Dec 12 09:51:48 UTC 2019
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1242/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1242 --build=4

**Comment by seldondev** [comment]
@SachinVarghese: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6eeddedd07d334ba53bfae8be70f4f00bfeb84c5 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Just [the usual intermittent ambassador 503 issue this time](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1242/4.log#L3194)

**Comment by SachinVarghese** [comment]
Worked on #1258

**Comment by seldondev** [comment]
failed to trigger Pull Request pipeline
* failed to create agent
* failed to calculate in repo config
* failed to load trigger config for repository SeldonIO/seldon-core for ref 6eeddedd07d334ba53bfae8be70f4f00bfeb84c5
* failed to find any lighthouse configuration files in repo SeldonIO/seldon-core at sha 6eeddedd07d334ba53bfae8be70f4f00bfeb84c5
* failed to process repo SeldonIO/seldon-core refref 6eeddedd07d334ba53bfae8be70f4f00bfeb84c5
* failed to list files in directory /var/tmp/gitrepo283418320/.lighthouse
* open /var/tmp/gitrepo283418320/.lighthouse
* no such file or directory

**Pull request closed without merging**
