### PR TITLE
Use FQDN in the host field of Istio resources

### LINKED ISSUE #4387: How to use an FQDN in a host of Istio VirtualService Destination field
When we go through the tutorial, the following VirtualService object will be created.
Is there a way to use a fully qualified domain name (FQDN) in `host` of the Destination field?
I'm asking this because our k8s has a rule that an FQDN must be specified to the field as [Istio recommends](https://istio.io/latest/docs/reference/config/networking/virtual-service/#Destination-host).

```yaml
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: iris-model
  namespace: seldon
spec:
  gateways:
  - istio-system/seldon-gateway
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: /seldon/seldon/iris-model/
    rewrite:
      uri: /
    route:
    - destination:
        host: iris-model-default
        port:
          number: 8000
        subset: default
  - match:
    - headers:
        namespace:
          exact: seldon
        seldon:
          exact: iris-model
      uri:
        regex: .*tensorflow.*|.*seldon.protos.*|.*inference.*
    route:
    - destination:
        host: iris-model-default
        port:
          number: 5001
        subset: default
```

https://github.com/SeldonIO/seldon-core/blob/v1.14.1/operator/controllers/seldondeployment_controller.go#L353
It doesn't seem possible to me because `pSvcName` is expected to be a service name. It can be customized by passing `seldon.io/svc-name`, but it's still just a service name.

If it's not possible, as I really need this feature, I may be going to contribute to this project.
I have the following ideas to implement the feature. Let me know which you think is better or if you have a better idea than mine.

1. Use an FQDN by default
    - I think it's OK to use an FQDN by default because SeldonDeploument creates a VS and a service in the same namespace, so IIUC using the short name or FQDN doesn't matter.
2. Add a new option as a helm value such as `istio.use_fqdn` or as an annotation such as `seldon.io/istio-use-fqdn` to the SeldonDeployment

### PR DESCRIPTION
**Pull request by ysk24ok**
**What this PR does / why we need it**:

This PR enables the Istio VirtualService and DestinationRule to use FQDN in the `host` field, as [Istio recommends doing so](https://istio.io/latest/docs/reference/config/networking/virtual-service/#Destination-host).

> To avoid potential misconfiguration, it is recommended to always use fully qualified domain names over short names

**Which issue(s) this PR fixes**:

Fixes #4387

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @ysk24ok. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **gsunner**
You can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by adriangonz — APPROVED** [review]
Hey @ysk24ok ,

Apologies for the long delay to review this one.

Just had a look and changes look good! Integration tests seem to pass, so this should be ready to go.

Thanks a lot for your contribution! :rocket:

**Pull request merged**
