### PR TITLE
Updating inference logic to add node level request-response logging

### LINKED ISSUE #3873: The seldon executor doesn't log node level request-response pairs in complex inference graphs
## Describe the bug

In complex inference graphs involving one or more transformers, models, or other prediction components, the seldon executor doest' log the correct node-level request response pairs. 

For example if you have an input transformer, model and output transformer, the current executor logs the model 

Lets say a prediction request sends the following data through the seldon deployment,

 A  ->   **Input Transformer** ->  B   -> **Model**  ->  C -> **Output Transformer** -> D
 

 **Current Paylod Logs for each node**
| Node name| Request | Response|
|---|---|---|
| Input Transformer | A | C |
| Model | B | C |
| Output Transformer | A | D |

 **Expected Paylod Logs for each node**
| Node name| Request | Response|
|---|---|---|
| Input Transformer | A | B |
| Model | B | C |
| Output Transformer | C | D |

## Expected behaviour

The executor is expected to log the request and response paylods for each node correctly.

### PR DESCRIPTION
**Pull request by SachinVarghese**
**What this PR does / why we need it**:
This PR corrects the paylod logging mechanism in seldon executor for logging node level request-response pairs in complex inference graphs
**Which issue(s) this PR fixes**:
Fixes #3873

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **sachinvarghese**
You can assign the PR to them by writing `/assign @sachinvarghese` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@SachinVarghese: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6bf82ab7cc41fdf1b76cdb50671970c117a247e1 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3874-integration-q8vkv) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
logs of integration tests are quite confusing, it is not clear if there was an actual failure or not
```
===Flaky Test Report===

test_namespace_update[1.10.0] passed 1 out of the required 1 times. Success!
test_namespace_update[1.11.0] passed 1 out of the required 1 times. Success!
test_namespace_update[1.12.0] passed 1 out of the required 1 times. Success!
test_rolling_update6[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update6[istio] passed 1 out of the required 1 times. Success!
test_rolling_update7[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update7[istio] passed 1 out of the required 1 times. Success!
test_rolling_update8[ambas] failed (4 runs remaining out of 5).
	<class 'AssertionError'>
	assert 503 == 200
  -503
  +200
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:140>]
test_rolling_update8[ambas] failed (3 runs remaining out of 5).
	<class 'AssertionError'>
	assert 503 == 200
  -503
  +200
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:140>]
test_rolling_update8[ambas] failed (2 runs remaining out of 5).
	<class 'AssertionError'>
	assert 500 == 200
  -500
  +200
	[<TracebackEntry /workspace/source/testing/scripts/test_rolling_updates.py:140>]
test_rolling_update8[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update8[istio] passed 1 out of the required 1 times. Success!
test_rolling_update9[ambas] passed 1 out of the required 1 times. Success!
test_rolling_update9[istio] passed 1 out of the required 1 times. Success!

===End Flaky Test Report===

========== 52 passed, 6 skipped, 67 deselected in 6307.24s (1:45:07) ===========
Test returned errors
kind delete cluster
Deleting cluster "kind" ...
Stopping Docker: dockerProgram process in pidfile '/var/run/docker-ssd.pid', 1 process(es), refused to die.
[31m
Pipeline failed on stage 'integration-test-task' : container 'step-integration-step'. The execution of the pipeline has stopped.[0m
```

if it was, it could have been on `test_rolling_update8[ambas] failed` but why it does not count towards total number in the summary?

**Comment by RafalSkolasinski** [comment]
Actually, I also see failure on `TestPrepack.test_mlflow_v2`. 

Triggered tests again anyway to rule out flakiness first

**Comment by seldondev** [comment]
@SachinVarghese: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 6bf82ab7cc41fdf1b76cdb50671970c117a247e1 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3874-integration-nhhsr) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
The `TestPrepack.test_mlflow_v2` seem to passed I do see failure now on `test_rolling_deployment[graph1.json-graph4.json-True-ambas]`.

**Pull request merged**
