### PR TITLE
Allow custom predictor service name

### LINKED ISSUE #950: Make it possible to override seldon prediction service's service name
Currently, the seldon service's name is comprised of several components according to the manifest, see https://github.com/SeldonIO/seldon-operator/blob/89e3b5ee3d78bf7e1dacfffbfcaff2ba873b7d6a/pkg/apis/machinelearning/v1alpha2/seldondeployment_types.go#L117, and the name will be hashed first if the length exceeds 63. The reason for combining the serval components, as @cliveseldon explained, is to make sure there is no clash of service names for complex graphs.

Given there could be further changes in the above function, the actual service name would become unpredictable. Especially, in some situations, one needs to know the service's name in order to be able to know where exactly to curl the prediction service even before the service is deployed.

@cliveseldon suggests to add a feature so that the prediction service's service name can be overridden by the user, and then it is the user's responsibility to make sure the services don't clash.

### PR DESCRIPTION
**Pull request by cliveseldon**
* Adds an annotation option to predictor `seldon.io/svc-name` to allow a custom service name to be provided for predictor.

Fixes #950

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by adriangonz** [comment]
Looks good to me!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/953#issuecomment-542675748" title="Approved">adriangonz</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [adriangonz]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
