### PR TITLE
Improve Kafka config handling in executor

### PR DESCRIPTION
**Pull request by agrski**
**What this PR does / why we need it**:
* Fix typos in names of Kafka security protocol values.
* Simplify setup of SSL & SASL Kafka config
* Rename Kafka config structs & helper functions for consistency & clarity.
* Formatting changes for legibility in the affected parts of the code.

**Which issue(s) this PR fixes**:
N/A

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by agrski** [comment]
> [APPROVALNOTIFIER] This PR is **NOT APPROVED**
> 
> This pull-request has been approved by: To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **agrski** You can assign the PR to them by writing `/assign @agrski` in a comment when ready.

Well that's convenient!

**Comment by seldondev** [comment]
@agrski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b077bc28be204be3b0b0de3d457c3b5f8bb8bd66 | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-4435-integration-zhdlk) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
@agrski the alibiexlainer tests were just flakienss - they did just pass above 
image

and also confirmed in https://github.com/SeldonIO/seldon-core/pull/4436

**Comment by axsaucedo** [comment]
@RafalSkolasinski following from morning discussion are we good to merge this one?

**Review by RafalSkolasinski — APPROVED** [review]
LGTM

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/4435#pullrequestreview-1174109470 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4435]: [Method Not Allowed]

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [4435]: [Method Not Allowed]

**Pull request merged**
