### PR TITLE
Fix Go license linting

### LINKED ISSUE #1932: Automate license check in CI linting pipeline
Reject of licenses have changed.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
This is a follow-up to PR #1995, to fix the license linting in Go. This PR also adds some `Makefile` targets to the `operator` and `executor` to generate the licenses automatically (unless there are problems fetching the license info).

**Which issue(s) this PR fixes**:

Fixes #1932 (as a follow-up)

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jul 15 10:57:54 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=2

**Comment by seldondev** [comment]
Wed Jul 15 10:58:03 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=1

**Comment by RafalSkolasinski** [comment]
Was just thinking... Should we have a step in CI that verifies if go.sum is up to date?

**Comment by adriangonz** [comment]
@RafalSkolasinski that's a good point. We could include that on the `Makefile` and take a similar approach as what's done in `make lint`. 

Do you know what's the right command to update the `go.sum`? Otherwise, we could just do `go build` and see if anything changes.

**Comment by axsaucedo** [comment]
PR looks good! That's a good idea @RafalSkolasinski! Yeah it would be good to update go.mod without having to build fully

**Comment by seldondev** [comment]
Wed Jul 15 14:27:08 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=3

**Comment by seldondev** [comment]
Wed Jul 15 14:27:12 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=4

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | e41527605e2d0be41399ca5f596958eae161ce36 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Jul 16 10:38:48 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=5

**Comment by seldondev** [comment]
Thu Jul 16 10:38:49 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=6

**Comment by seldondev** [comment]
Thu Jul 16 13:31:25 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=7

**Comment by seldondev** [comment]
Thu Jul 16 13:31:33 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2136/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2136 --build=8

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2136#issuecomment-659467770 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-659467770/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
