### PR TITLE
reference to kfserving storage initializer from dockerhub

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

kfserving/storage-initializer images were temporarily not available for download due to gcr project issues https://github.com/kserve/kserve/issues/1976

this move reference to source of images from dockerhub as suggested in the reference issue

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by agrski — COMMENTED** [review]
I've found some other references:

* operator/controllers/suite_test.go
  ```
  127:	"image" : "gcr.io/kfserving/storage-initializer:v0.4.0",
  ```
* operator/controllers/model_initializer_injector_test.go
  ```
  37:	g.Expect(d.Spec.Template.Spec.InitContainers[0].Image).To(Equal("gcr.io/kfserving/storage-initializer:v0.4.0"))
  ```
* operator/utils/k8s/testdata/configmap.yaml
  ```
  5:  storageInitializer: '{"cpuLimit":"1","cpuRequest":"100m","image":"gcr.io/kfserving/storage-initializer:v0.4.0","memoryLimit":"1Gi","memoryRequest":"100Mi"}'
  ```
* operator/config/manager/configmap.yaml
  ```
  87:        "image" : "gcr.io/kfserving/storage-initializer:v0.4.0",
  ```

**Comment by RafalSkolasinski** [comment]
Thanks @agrski, for some reason my search+replace didn't catch all of these

**Review by agrski — APPROVED** [review]
LGTM

**Pull request merged**
