### PR TITLE
Executor 1.2.4/add summary to metrics

### LINKED ISSUE #2765: Add Summary and _max to Executor exposed metrics
Currently `Executor` exposes [Histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) metrics for 
- seldon_api_executor_server_requests
- seldon_api_executor_client_requests

Depricate `Engine` exposed also [Sumamry](https://prometheus.io/docs/concepts/metric_types/#summary) for these.

The main difference between these two metrics is that `Summary` includes quantiles, see [prometheus documentation](https://prometheus.io/docs/practices/histograms/#quantiles).
```
The essential difference between summaries and histograms is that summaries calculate streaming 
φ-quantiles on the client side and expose them directly, while histograms expose bucketed observation 
counts and the calculation of quantiles from the buckets of a histogram happens on the server side 
using the histogram_quantile() function.
```

Quantiles can be calculated server-side from the histogram but accuracy is limited to set buckets.
```
Choose a summary if you need an accurate quantile, no matter what the range and 
distribution of the values is.
```

The `Engine` metrics also exposed the `_max` value which cannot be accurately estimated from currently exposed metrics.

----

**Example why histogram information with fixed buckets does not provide `_max` value:** 

Let's say buckets are set as
```
[0, 1, 2, 3, 4, 5, inf]
```
You get raw values  you create histogram from as:
```
[1.1, 1.2, 2.2]
```
So you get histogram:
```
[0, 2, 1, 0, 0, 0, 0]
```
From this you only know that max is in range `[2, 3]`. You don't have information that it was `2.2`.
Worse case scenario, you can one more value of `42`, now it is
```
[0, 2, 1, 0, 0, 0, 1]
```
and the only thing you know about max is that it belongs to `[5, inf]`

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:
Closes #2765

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/release-1.2.4/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Jan 27 19:03:25 UTC 2021
The logs for [notebooks] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=2

**Comment by seldondev** [comment]
Wed Jan 27 19:03:25 UTC 2021
The logs for [integration] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=1

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
It will be fun to test it with all legacy problems...
 https://github.com/SeldonIO/seldon-core/blob/27cf4e4f310a82d7c24665dea0613eac93f2be36/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/1.log#L9486

**Comment by axsaucedo** [comment]
@RafalSkolasinski I saw it as well and was confused... I'm thinking and it may be worth for you to edit the main e2e file and comment out all of the image builds except for the executor one. This way it will not build these images and just use the ones that are in master (you would just have to pull 1.2.3 and tag+push)

**Comment by RafalSkolasinski** [comment]
If I am not reading it wrong this is failing on building `alibi-detect-server`. One thing puzzles me, why is it building it if there are no changes? Maybe we added logic to build images only on change later?

**Comment by RafalSkolasinski** [comment]
I wonder why it is not running unit tests, any idea @axsaucedo?

**Comment by seldondev** [comment]
Tue Feb  2 15:38:18 UTC 2021
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=3

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | d737bc337021ec932685c39a59d4cec11e221f05 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 09:29:15 UTC 2021
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | 0ac102828742a6e42fe59ba25eded78c81029219 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 10:33:42 UTC 2021
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=5

**Comment by seldondev** [comment]
Wed Feb  3 10:46:27 UTC 2021
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=6

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | 722979bae546a5f05e67de71190102884bc0ee0f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 11:07:31 UTC 2021
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=7

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | 0ac102828742a6e42fe59ba25eded78c81029219 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 14:04:51 UTC 2021
The logs for [integration] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=9

**Comment by seldondev** [comment]
Wed Feb  3 14:05:04 UTC 2021
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=8

**Comment by seldondev** [comment]
Wed Feb  3 14:24:16 UTC 2021
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=10

**Comment by seldondev** [comment]
Wed Feb  3 14:24:22 UTC 2021
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=11

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7c2d51a1e651c82f6687e5f33a3b0ef41d56d397 | [link]() | `/test notebooks`
integration | f5f70b28c57ecaee069afed421766dcf115fc020 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f5f70b28c57ecaee069afed421766dcf115fc020 | [link]() | `/test integration`
notebooks | f5f70b28c57ecaee069afed421766dcf115fc020 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f5f70b28c57ecaee069afed421766dcf115fc020 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 17:38:19 UTC 2021
The logs for [notebooks] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=12

**Comment by seldondev** [comment]
Wed Feb  3 17:38:59 UTC 2021
The logs for [integration] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=13

**Comment by seldondev** [comment]
Wed Feb  3 17:49:36 UTC 2021
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=14

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | f5f70b28c57ecaee069afed421766dcf115fc020 | [link]() | `/test notebooks`
integration | 5b30a6f40fb3a737b96705e449251f51e6e61dae | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5b30a6f40fb3a737b96705e449251f51e6e61dae | [link]() | `/test integration`
notebooks | 5b30a6f40fb3a737b96705e449251f51e6e61dae | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Feb  3 18:10:32 UTC 2021
The logs for [notebooks] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=15

**Comment by seldondev** [comment]
Wed Feb  3 18:10:37 UTC 2021
The logs for [integration] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=16

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5b30a6f40fb3a737b96705e449251f51e6e61dae | [link]() | `/test integration`
notebooks | 7c3761e4d8604ffba5f923391af01cdd2489b7e0 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 5b30a6f40fb3a737b96705e449251f51e6e61dae | [link]() | `/test integration`
notebooks | 9c48a2091541c9528de61e84d41f39f63aa9d85b | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Feb  4 10:11:13 UTC 2021
The logs for [notebooks] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=17

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 9c48a2091541c9528de61e84d41f39f63aa9d85b | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Feb  4 13:22:35 UTC 2021
The logs for [notebooks] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2895/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2895 --build=18

**Comment by RafalSkolasinski** [comment]
Notebook and integration tests passed in the CI.
Change is limited to `executor`'s code and executor's unit tests run before image build -> so also tested in the CI; and anyway I run them locally.

**Comment by axsaucedo** [comment]
@RafalSkolasinski do all the unit tests pass? Seems the tests are not running in this branch, did you get a chance to run them locally with `act`?

**Comment by RafalSkolasinski** [comment]
> @RafalSkolasinski do all the unit tests pass? Seems the tests are not running in this branch, did you get a chance to run them locally with `act`?

Did not have yet a chance to play with `act`. I only verified unit tests of `executor` (as didn't really affect any other components here).

**Comment by RafalSkolasinski** [comment]
Did run locally:
- operator unit tests
- executor unit tests
- python unit tests

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2895#issuecomment-773550677 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-773550677/SeldonIO/seldon-core/blob/release-1.2.4/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
