### PR TITLE
WIP: Basic stateful metrics 

### PR DESCRIPTION
**Pull request by axsaucedo**
# Basic stateful metrics (Accuracy, Precision, Recall, etc)

This PR contains an initial exploration on the workflow and infrastructure for basic stateful metrics that are persisted, as well as brief assessment on how more advanced/custom metrics could also be calculated and displayed in real time.

This PR contains an overview of the feedback workflow with ELK, and shows two examples (with two different proposed architectures to consider), and evaluates some potential extensions. 

You can find the [worked notebook](https://github.com/axsaucedo/seldon-core/blob/basic_stateful_metrics/examples/stateful-feedback/basic-metrics/README.ipynb) and [README export](https://github.com/axsaucedo/seldon-core/blob/basic_stateful_metrics/examples/stateful-feedback/basic-metrics/README.md).

Here we include ways in which we can introduce stateful metrics tracking:

image

This allows for more advanced statistical metrics to be used when comparing model performance:

image

This is also extended to multi-class classification:

image

The two architectures explore are namely:
* A knative-eventing stateful metrics server 
* A default seldon wrapper with custom metrics

Namely the architectures are the following:

<table>
<tr>
<td>
    
</td>
<td>
    
</td>
</tr>
</table>

Below the sections and examples are covered in more detail

## Overview of feedback with ELK

The initial section of the notebook expores in detail detail of how the request logger structure together with the feedback request path can be leveraged to store feedback, which can contain "truths" as well as "reward" (next steps section has suggested extensions for feedback structure). 

Once we send a few documents that are stored, we actually can show how the elasticsearch database, and more specifically the aggregate functionality of the elasticsearch interface allows us to easily compute basic stateful metrics, taking into consideration even time-ranges without much complexity. In the notebook we initially just simply display the metrics with matplotlib:

It's worth mentioning that in regards to the feedback workflow, one of the most valuable components is the ability to store "manually remediated truths", as it is quite common in large scale ML use-cases to bring in domain experts to correct / remediate a percentage of predictions, especially when the predictions need to be used for highly critical usecases (such as models that may identify sections from legal documents, predictions would help reduce manual process, but ultiamtely still need to checked and corrected). 

## Example 1 - Real Time Metrics with Stateful Component

The first example dives into an overview of how this architecture above could be leveraged to provide real time metrics. As it was covered above, it may be more common that the main benefit of this feature is to be able to store and manage "corrected predictions", but for systems that could benefit from automated feedback, it could provide real time insights.

An example for this could be the automation of routing of tickets for a support ticket system. Whilst the predictions are routing the tickets to the most possible departments, the feedback could be provided automatically as the "correct labels" would be the department where the query was actually resolved. So in this case, the feedback could be based on whether the ticket was resolved in the location where it was initially routed to (for simplicity I won't go into detail on the multi-class classification piece, but this is discussed in the next steps).

The architecture for this approach is basically adding a component that follows a similar architecture to the outlier detector server, howver the output doesn't get routed into the request logger (as it is done as the step after the outlier detector) given that in this case the "stateful metrics service" only serves as a component that provides real time metrics. The architecture for this is outliend below:

The "stateful metrics service" can be found in [its folder under components](https://github.com/axsaucedo/seldon-core/tree/basic_stateful_metrics/components/stateful-metrics-server), and consists of a very simple server that does the following:
1) On startup loads the historical feedback "so far" (this could be limited based on a timerange)
2) It receives any instance of feedback throuhg a trigger 
3) Every time a feedback comes in, it's taken into account for the global measure
4) The component exposes metrics which are collected by the seldon-core-analytics service

In the example we show how we can get real time accuracy by sending prediction and feedback with a random probability on correct/incorrect, with a skew towards incorrect to show performance drift. This is visualised in real time through grafana in a simple dashboard that is set up in the example, screenshot below:

In this case the further exploration shows that this could allow for custom components being built which could have different patterns and approaches to computing more advanced metrics, but further exploration may be required as the following questions came up. The main question was that the structure of the code is very similar to the one adding custom metrics to the model (it even uses the [Seldon Core metrics component](https://github.com/axsaucedo/seldon-core/blob/312d805ca848e8cff1f25f83f6752c1d80ab1356/components/stateful-metrics-server/app/main.py#L7)), and could be done much more simply by implementing a custom metric that uses the `/feedback` / `def feedback(...)` python wrapper functionality. The main disadvantage is that the implementation above is "graph-level" feedback, whereas a python model would be python-level feedback, althoguh this may not be a massive drawback (something to discuss further)

It would be better from code reusability perspecive (and much easier for users to extend custom metrics) if we actually do this through the model wrapper instead of a custom component separate to the model itself - also if bundled with the model, this could be functionality that could be "out of the box" when request logging is enabled, and may no longer even be "custom metrics". Certainly something worth exploring.

# Example 2 - Custom Server

In the second example we explore doing a similar approach to  the one mentioned above, but by leveraging the custom server. When putting this together it was possible to identify that there is quite a lot of value on the custom metrics, which could be used for this purpose.

In this example we build a simple wrapper, and then show how it can be extended with quite a few of the concepts outlined above. This then allows us to compare the performance of two models side by side in real time (as per the screenshot below)
image

## Next steps

There were quite a lot of interesting insights putting this together. Some key questions and discussion points to explore further include:
* Adding tags to feedback proto to extend for custom fields (for information like user who submitted feedback, etc) as currently this can only be done through the seldonmessage tags
* If tags are added this may not be needed, but if tags are not added we may need to support more flexibility than just a single-float "reward" as the reward could be more complex (ie multiple for multi-class, etc)
* Explore how other basic metrics can be supported besides accuracy such as precision, recall, specificity, f1-score, etc  (this would require more than just reward if we want to avoid checking actual vs prediction every time data is fetched, which should be possible but not required)
* Ensure that besides adding the "latest feedback" to each prediction, we also keep an audit of all revisions of feedback provided (ie another index just for feedback). This would be quite critical if more than one feedback is provided.
    + For this we actually may require creating a feedback UID from the executor
* Explore the most sensible ways in which users would be able to easily add custom stateful metrics
* How to disambiguate the intra-graph model feedback (ie multi-armed bandit) vs graph-level feedback (what is being discused in this PR) 
* Explore how calculations for global metrics can be done (ie metrics that need to be calcualted with all the dataset such as global explanations), although given the stateful metrics server fetches the relevant data at start, this could actually be quite feasible now as it would just be a matter of keeping that in memory.
* Explore how this could be explored with out of the box metrics in the wrapper (without custom metrics server)
* Explore how the feedback proto can be extended for the model to be able to return the processed feedback (currnetly the proto structure limits this)

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Sun Jul 12 10:08:52 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=2

**Comment by seldondev** [comment]
Sun Jul 12 10:08:53 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=1

**Comment by seldondev** [comment]
Sun Jul 12 10:13:42 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=3

**Comment by seldondev** [comment]
Sun Jul 12 10:13:50 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=4

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ae18f82c2aa9905a5722b80081ac73b84e3a9314 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jul 13 20:04:47 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=5

**Comment by seldondev** [comment]
Mon Jul 13 20:05:04 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=6

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ae18f82c2aa9905a5722b80081ac73b84e3a9314 | [link]() | `/test this`
lint | 3e83d99ef9a7ed8ec3d583e45f3d137f98e0fba6 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 3e83d99ef9a7ed8ec3d583e45f3d137f98e0fba6 | [link]() | `/test lint`
pr-build | 3e83d99ef9a7ed8ec3d583e45f3d137f98e0fba6 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 07:24:13 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=7

**Comment by seldondev** [comment]
Tue Jul 14 07:24:16 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=8

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 3e83d99ef9a7ed8ec3d583e45f3d137f98e0fba6 | [link]() | `/test this`
lint | ca2ba2a3bb60a98873a7f31df46f04fdfad7c4d5 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | ca2ba2a3bb60a98873a7f31df46f04fdfad7c4d5 | [link]() | `/test lint`
pr-build | ca2ba2a3bb60a98873a7f31df46f04fdfad7c4d5 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 08:26:47 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=9

**Comment by seldondev** [comment]
Tue Jul 14 08:27:01 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=10

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ca2ba2a3bb60a98873a7f31df46f04fdfad7c4d5 | [link]() | `/test this`
lint | 79196344d190b557cb8ab0702846bab5401b2f3a | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 79196344d190b557cb8ab0702846bab5401b2f3a | [link]() | `/test lint`
pr-build | 79196344d190b557cb8ab0702846bab5401b2f3a | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 09:09:34 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=12

**Comment by seldondev** [comment]
Tue Jul 14 09:09:51 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=11

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 79196344d190b557cb8ab0702846bab5401b2f3a | [link]() | `/test this`
lint | 6adde004c912693733d2a6e3587b079abd42e2b9 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 6adde004c912693733d2a6e3587b079abd42e2b9 | [link]() | `/test lint`
pr-build | 6adde004c912693733d2a6e3587b079abd42e2b9 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 14 20:19:49 UTC 2020
The logs for [lint] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=14

**Comment by seldondev** [comment]
Tue Jul 14 20:19:52 UTC 2020
The logs for [pr-build] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=13

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 5dfc5a706f337293c294b7a41366af794f9f12c0 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jul 28 13:47:23 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=15

**Comment by seldondev** [comment]
Tue Jul 28 13:47:26 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=16

**Comment by seldondev** [comment]
Tue Jul 28 13:57:14 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=18

**Comment by seldondev** [comment]
Tue Jul 28 13:57:31 UTC 2020
The logs for [pr-build] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=19

**Comment by seldondev** [comment]
Tue Jul 28 13:57:39 UTC 2020
The logs for [lint] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=20

**Comment by seldondev** [comment]
Tue Jul 28 13:58:06 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2110/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2110 --build=17

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 5dfc5a706f337293c294b7a41366af794f9f12c0 | [link]() | `/test this`
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 5dfc5a706f337293c294b7a41366af794f9f12c0 | [link]() | `/test this`
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 5dfc5a706f337293c294b7a41366af794f9f12c0 | [link]() | `/test this`
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`
pr-build | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`
pr-build | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test lint`
pr-build | 210f0709860a0b0d2ed0472aaafaeb2b43975c06 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by jklaise** [comment]
@axsaucedo picking up the discussion on data structures for the multi-class classification case.

As discussed, if we track the raw confusion matrix (n*n counters where n is the number of classes), we can derive most supervised metrics from there. In Python this might look like this:

```
class CM:
    def __init__(self, n_classes):
        self.n_classes = n_classes
        self._cm = np.zeros((n_classes, n_classes), dtype=int)
    
    def update(self, pred_index, true_index):
        self._cm[pred_index, true_index] += 1
```

The modified `MulticlassClassifier` code would then be:

```
class MulticlassClassifier:
    def __init__(self, model_name="multiclass-lr.joblib", class_num=3, proba=False):
        self.cm = CM(n_classes=class_num)
        self.model = joblib.load(model_name)
        self.proba = proba
        self.n_classes = class_num

    def predict(self, X, features_names=None, meta=None):
        return self.model.predict(X)

    def send_feedback(self, features, feature_names, reward, truth, routing=""):
        predicted = self.predict(features)
        print(f"Predicted: {predicted}")
        print(f"Truth: {truth}")

        # update confusion matrix
        self.cm.update(pred_index=int(predicted[0]),
                       true_index=int(truth[0]))

    def metrics(self):
        # expose counters to Prometheus for further derived metrics
        
        # raw counts
        raw_counts = []
        for pred_index in range(self.cm.n_classes):
            for true_index in range(self.cm.n_classes):
                metric = {
                    "type": "COUNTER",
                    "key": f"count_{pred_index}_{true_index}",
                    "value": self.cm._cm[pred_index, true_index],
                    "tags": {"pred_class": pred_index, "true_class": true_index}
                }
                raw_counts.append(metric)      
                
        # TP etc. per class (easier to expose in the wrapper than query in Prometheus)
        scores = {
            "TP": np.zeros(self.n_classes, dtype=int),
            "FP": np.zeros(self.n_classes, dtype=int),
            "FN": np.zeros(self.n_classes, dtype=int),
            "TN": np.zeros(self.n_classes, dtype=int),
        }
        score_metrics = []

        
        for cls in range(self.n_classes):
            """
            The following illustrates which cells contribute to which
            calculations for class A:
              A  B  C
            A|TP|FP|FP|
            B|FN|TN|TN|
            C|FN|TN|TN|
            """
            scores["TP"][cls] = self.cm._cm[cls, cls]
            scores["FP"][cls] = self.cm._cm[cls, :].sum() - scores["TP"][cls]
            scores["FN"][cls] = self.cm._cm[:, cls].sum() - scores["TP"][cls]
            scores["TN"][cls] = self.cm._cm.sum() - scores["TP"][cls] - scores["FP"][cls] - scores["FN"][cls]
            
            for score_type in scores.keys():
                metric = {
                    "type": "COUNTER",
                    "key": f"{score_type}_{cls}",
                    "value": scores[score_type][cls],
                    "tags": {"class": cls, "score_type": score_type}
                }
                score_metrics.append(metric)
        
        # TP etc. global we add up class-specific ones NB: these do not
        # correspond to the usual TP etc. in the binary case as we usually
        # designate one class to be positive and the other negative
        for score_type in scores.keys():
            if score_type == "TN":
                continue # total TN is meaningless
            metric = {
                "type": "COUNTER",
                "key": f"{score_type}_total",
                "value": scores[score_type].sum(),
                "tags": {"score_type": score_type}
            }
            score_metrics.append(metric)
            
        # total number of instances
        total = self.cm._cm.sum()
        total = [{"type": "COUNTER", "key": "total", "value": total}]
        
        return raw_counts + score_metrics + total
```

In a nutshell:

- User sends the truth, the feedback updates the internal state of the confusion matrix using the prediction of the model (this will work if the model returns labels, if not we would need a decision threshold - supplied by user or we could guess argmax - but remember caveats for guessing)
- When `metrics` is called, we return various counters - raw counts (basically flattened matrix), and aggregates of TPs etc. by class as well as total. Then Prometheus queries can further be used to calculate e.g. accuracy per class and overall.

Output (truncated) of a call to `metrics()` for a confusion matrix state
```
array([[45,  0,  0],
       [ 0, 45, 25],
       [ 0,  1, 19]])
```
is as follows:

```
[{'type': 'COUNTER',
  'key': 'count_0_0',
  'value': 45,
  'tags': {'pred_class': 0, 'true_class': 0}},
 {'type': 'COUNTER',
  'key': 'count_0_1',
  'value': 0,
  'tags': {'pred_class': 0, 'true_class': 1}},
 {'type': 'COUNTER',
  'key': 'count_0_2',
  'value': 0,
  'tags': {'pred_class': 0, 'true_class': 2}},
 
...

 {'type': 'COUNTER',
  'key': 'TP_2',
  'value': 19,
  'tags': {'class': 2, 'score_type': 'TP'}},
 {'type': 'COUNTER',
  'key': 'FP_2',
  'value': 1,
  'tags': {'class': 2, 'score_type': 'FP'}},
 {'type': 'COUNTER',
  'key': 'FN_2',
  'value': 25,
  'tags': {'class': 2, 'score_type': 'FN'}},
 {'type': 'COUNTER',
  'key': 'TN_2',
  'value': 90,
  'tags': {'class': 2, 'score_type': 'TN'}},
 {'type': 'COUNTER',
  'key': 'TP_total',
  'value': 109,
  'tags': {'score_type': 'TP'}},
 {'type': 'COUNTER',
  'key': 'FP_total',
  'value': 26,
  'tags': {'score_type': 'FP'}},
 {'type': 'COUNTER',
  'key': 'FN_total',
  'value': 26,
  'tags': {'score_type': 'FN'}},
 {'type': 'COUNTER', 'key': 'total', 'value': 135}]
```

**Comment by jklaise** [comment]
@axsaucedo what happens if a service goes down, loses state and starts recording a new confusion matrix? If the outputs to Prometheus are counters, will this result in an error or is Prometheus smart enough to aggregate these? I suspect in your example using gauge instead would cause no errors other than the usual metrics being wrong if state is not persisted and restored upon failure of a service.

**Comment by axsaucedo** [comment]
@jklaise in this example it would indeed fail because it uses GAUGES, but in the one we've designed it wouldn't given that it would use COUNTERs, so all the state is on the prometheus databse instead of on the actual microservice itself

**Comment by axsaucedo** [comment]
Closing as this has been added through two separate PRs

**Pull request closed without merging**
