### PR TITLE
WIP: V1.11.1 release

### PR DESCRIPTION
**Pull request by axsaucedo**
Cherrypicks (todo / done):
* [x] #3628
* [x] #3623
* [x] #3630
* [x] #3631

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/v1.11.0-release/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
# Benchmark results - Testing Service Orchestrator

* Orch added mean latency under 4ms: True
* Orch added 95th latency under 5ms: True
* Orch added 99th latency under 10ms: True
* No errors: False

### Results table

|    |    mean |    50th |    90th |    95th |    99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri   | image                                  | server   | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|--------:|--------:|--------:|--------:|--------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:-----------|:---------------------------------------|:---------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  2 | 3.69181 | 3.47699 | 4.60599 | 5.29505 | 7.18875 |              268.017 |      8042 |        1 | seldon-benchmark-sdep-2 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  1 | 3.13908 | 2.94848 | 4.0554  | 4.66897 | 6.41886 |              314.395 |      9435 |        1 | seldon-benchmark-sdep-3 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | true                  |
|  0 | 5.21445 | 5.00774 | 6.33588 | 7.04691 | 9.35879 |              191.702 |      5753 |        0 | seldon-benchmark-sdep-0 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  3 | 4.47134 | 4.18668 | 5.68792 | 6.44585 | 8.72136 |                0     |         0 |     6707 | seldon-benchmark-sdep-1 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | true                  |

**Comment by seldondev** [comment]
# Benchmark results - Testing Workers Performance


### Results table

|    |      mean |      50th |      90th |      95th |      99th |   throughputAchieved |   success |   errors | iteration_name           |   replicas |   serverWorkers |   serverThreads | modelUri   | image                                  | server   | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|----------:|----------:|----------:|----------:|----------:|---------------------:|----------:|---------:|:-------------------------|-----------:|----------------:|----------------:|:-----------|:---------------------------------------|:---------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  0 |   20.2388 |   19.8902 |   23.3903 |   25.1308 |   30.5324 |              492.796 |     14781 |        9 | seldon-benchmark-sdep-0  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
|  2 |  203.042  |  199.901  |  224.048  |  233.984  |  272.27   |              491.621 |     14662 |       99 | seldon-benchmark-sdep-1  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
|  6 | 1946.85   | 2008.04   | 2159.1    | 2216.29   | 2568.49   |              510.579 |     14415 |      974 | seldon-benchmark-sdep-2  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |
|  8 | 2056.83   | 2137.09   | 2376.81   | 2457.76   | 2549.09   |              483.635 |     13540 |      997 | seldon-benchmark-sdep-14 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |
|  9 |   20.7315 |   20.1974 |   24.4557 |   27.0186 |   33.0797 |              481.082 |     14429 |       10 | seldon-benchmark-sdep-12 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
| 17 |  201.926  |  200.133  |  216.909  |  224.886  |  252.908  |              494.451 |     14744 |      100 | seldon-benchmark-sdep-13 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
| 12 |  203.54   |  200.254  |  222.397  |  238.19   |  268.919  |              490.616 |     14630 |       99 | seldon-benchmark-sdep-7  |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
| 15 |   21.5915 |   21.1028 |   25.3991 |   27.7959 |   33.6755 |              461.903 |     13853 |       10 | seldon-benchmark-sdep-6  |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
| 16 | 2011.76   | 2091.78   | 2204.41   | 2239.77   | 2406.07   |              494.336 |     13860 |      996 | seldon-benchmark-sdep-8  |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |
|  3 |  210.255  |  203.368  |  245.487  |  260.843  |  289.005  |              472.615 |     14317 |        0 | seldon-benchmark-sdep-4  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
|  4 |   23.0803 |   21.5844 |   32.9911 |   38.8637 |   47.7619 |              432.764 |     12991 |        0 | seldon-benchmark-sdep-3  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
|  5 | 2142.77   | 2100.17   | 2311.27   | 2483.46   | 3655.36   |              450.128 |     14468 |        0 | seldon-benchmark-sdep-5  |          1 |               1 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |
| 10 |  191.759  |  195.098  |  254.354  |  281.441  |  302.362  |              518.33  |     15584 |        0 | seldon-benchmark-sdep-16 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
| 11 |   22.294  |   14.1772 |   53.296  |   57.4306 |   64.6289 |              447.641 |     13445 |        0 | seldon-benchmark-sdep-15 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
| 14 | 2016.2    | 1985.82   | 2516.62   | 2800.85   | 3023.97   |              486.937 |     15160 |        0 | seldon-benchmark-sdep-17 |          1 |              10 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |
|  1 |   22.2806 |   13.6616 |   54.9281 |   58.5883 |   64.2256 |              448.051 |     13445 |        0 | seldon-benchmark-sdep-9  |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |            10 | 30s        |      0 | false                 |
|  7 |  204.955  |  200.083  |  279.958  |  293.378  |  315.502  |              484.659 |     14610 |        0 | seldon-benchmark-sdep-10 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |           100 | 30s        |      0 | false                 |
| 13 | 2189.87   | 2112.68   | 2929.75   | 3280.29   | 3794.8    |              448.195 |     13927 |        0 | seldon-benchmark-sdep-11 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 4000Mi        | 500Mi            | 4000Mi      | 500Mi          |              1 |          1000 | 30s        |      0 | false                 |

**Comment by seldondev** [comment]
# Benchmark Results - Python Wrapper V1 vs V2

* V1 base mean performance latency under 10ms: True
* V1 base 99th performance latenc under 10ms: True
* V1 base throughput above 180rps: True
* V1 base throughput above 250rps: True
* V2 mean performance latency under 5ms: True
* V2 99th performance latenc under 10ms: True
* V2 REST throughput above 250rps: True
* V2 throughput above 300rps: True

### Python V1 Wrapper Results table

|    |    mean |     50th |    90th |    95th |    99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri                                | image   | server         | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|--------:|---------:|--------:|--------:|--------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:----------------------------------------|:--------|:---------------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  1 | 276.67  | 246.624  | 605.711 | 678.463 | 798.628 |              539.967 |     16135 |      137 | seldon-benchmark-sdep-5 |          1 |               5 |               1 | gs://seldon-models/v1.11.0/sklearn/iris |         | SKLEARN_SERVER | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  0 | 118.863 |  55.3064 | 241.76  | 260.021 | 302.115 |              419.907 |     12547 |       50 | seldon-benchmark-sdep-4 |          1 |               5 |               1 | gs://seldon-models/v1.11.0/sklearn/iris |         | SKLEARN_SERVER | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |


### Python V2 MLServer Results table

|    |      mean |      50th |      90th |      95th |      99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri                                        | image   | server         | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|----------:|----------:|----------:|----------:|----------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:------------------------------------------------|:--------|:---------------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  4 |   5.79807 |   4.97456 |   6.95108 |   7.93157 |   10.4851 |              170.892 |      5128 |        1 | seldon-benchmark-sdep-3 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  0 |   7.22894 |   6.24641 |   8.51839 |   9.56566 |   12.843  |              138.287 |      4150 |        0 | seldon-benchmark-sdep-0 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  2 | 357.612   | 317.404   | 386.734   | 411.079   | 3380.28   |              418.182 |     12445 |      141 | seldon-benchmark-sdep-5 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  5 | 445.407   | 370.808   | 582.461   | 628.834   | 2887.46   |              335.182 |     10184 |        0 | seldon-benchmark-sdep-2 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  3 | 122.904   | 108.286   | 138.182   | 151.501   |  227.801  |              405.509 |     12142 |       43 | seldon-benchmark-sdep-4 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
|  1 | 154.668   | 126.295   | 198.581   | 218.861   |  279.012  |              322.725 |      9715 |        0 | seldon-benchmark-sdep-1 |          1 |               5 |               1 | gs://seldon-models/sklearn/iris-0.23.2/lr_model |         | SKLEARN_SERVER | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1fe463bdfabe40e6593d88ea8bff0c9b8ea508f9 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-cjcl9) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
# Benchmark results - Testing Seldon V1 Data Types


### Results for NDArray

|    |       mean |       50th |      90th |      95th |      99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri   | image                                  | server   | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|-----------:|-----------:|----------:|----------:|----------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:-----------|:---------------------------------------|:---------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  4 |   72.2372  |   70.2696  |   93.3308 |  102.861  |  125.694  |              13.8166 |       414 |        1 | seldon-benchmark-sdep-3 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  0 |    9.76008 |    8.51858 |   15.0841 |   17.9325 |   24.3571 |             102.432  |      3074 |        0 | seldon-benchmark-sdep-0 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  5 | 5931.12    | 6925.05    | 7411.59   | 7676.14   | 8786.35   |              25.2456 |       610 |      149 | seldon-benchmark-sdep-5 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  1 |  487.585   |  486.922   |  586.572  |  613.75   |  722.223  |             302.235  |      9144 |        0 | seldon-benchmark-sdep-2 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  2 | 2251.5     | 2348.35    | 2527.44   | 2596.25   | 3037.4    |              22.1752 |       616 |       50 | seldon-benchmark-sdep-4 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
|  3 |  162.297   |  177.755   |  201.873  |  210.285  |  258.543  |             303.805  |      9128 |        0 | seldon-benchmark-sdep-1 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
### Results for Tensor

|    |      mean |      50th |     90th |     95th |     99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri   | image                                  | server   | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|----------:|----------:|---------:|---------:|---------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:-----------|:---------------------------------------|:---------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  2 |   7.28855 |   5.50989 |  12.8681 |  16.7272 |  27.6278 |              135.973 |      4081 |        1 | seldon-benchmark-sdep-3 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  0 |  10.2766  |   9.33709 |  15.436  |  18.7562 |  27.1793 |               97.287 |      2920 |        0 | seldon-benchmark-sdep-0 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  4 | 387.627   | 410.886   | 607.803  | 660.815  | 799.133  |              384.518 |     11416 |      142 | seldon-benchmark-sdep-5 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  3 | 496.983   | 494.067   | 602.095  | 651.727  | 698.294  |              296.412 |      8955 |        0 | seldon-benchmark-sdep-2 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  5 | 143.323   | 140.64    | 203.963  | 215.606  | 265.373  |              345.778 |     10356 |       33 | seldon-benchmark-sdep-4 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
|  1 | 164.37    | 176.256   | 204.977  | 217.85   | 268.097  |              296.93  |      8927 |        0 | seldon-benchmark-sdep-1 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
### Results for TFTensor

|    |      mean |      50th |      90th |     95th |     99th |   throughputAchieved |   success |   errors | iteration_name          |   replicas |   serverWorkers |   serverThreads | modelUri   | image                                  | server   | apiType   | requestsCpu   | requestsMemory   | limitsCpu   | limitsMemory   |   benchmarkCpu |   concurrency | duration   |   rate | disableOrchestrator   |
|---:|----------:|----------:|----------:|---------:|---------:|---------------------:|----------:|---------:|:------------------------|-----------:|----------------:|----------------:|:-----------|:---------------------------------------|:---------|:----------|:--------------|:-----------------|:------------|:---------------|---------------:|--------------:|:-----------|-------:|:----------------------|
|  3 |   5.70877 |   4.66669 |   9.18995 |  11.4983 |  17.5863 |              173.332 |      5203 |        1 | seldon-benchmark-sdep-3 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  0 |   8.80869 |   7.78277 |  13.0228  |  15.4908 |  21.683  |              113.489 |      3406 |        0 | seldon-benchmark-sdep-0 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |             1 | 30s        |      0 | false                 |
|  5 | 452.236   | 453.52    | 498.817   | 524.153  | 588.182  |              330.91  |      9797 |      144 | seldon-benchmark-sdep-5 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  2 | 551.414   | 549.267   | 662.672   | 695.61   | 864.261  |              267.821 |      8066 |        0 | seldon-benchmark-sdep-2 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |           150 | 30s        |      0 | false                 |
|  4 | 150.981   | 148.818   | 173.58    | 188.142  | 214.82   |              330.343 |      9870 |       50 | seldon-benchmark-sdep-4 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | grpc      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |
|  1 | 185.683   | 191.803   | 217.865   | 262.051  | 287.867  |              265.927 |      8001 |        0 | seldon-benchmark-sdep-1 |          1 |               5 |               1 |            | seldonio/seldontest_predict:1.10.0-dev |          | rest      | 2000Mi        | 500Mi            | 2000Mi      | 500Mi          |              1 |            50 | 30s        |      0 | false                 |

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1fe463bdfabe40e6593d88ea8bff0c9b8ea508f9 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-cjcl9) | `/test integration`
notebooks | 1fe463bdfabe40e6593d88ea8bff0c9b8ea508f9 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3629-notebooks-l6869) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 1fe463bdfabe40e6593d88ea8bff0c9b8ea508f9 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-cjcl9) | `/test integration`
notebooks | 1fe463bdfabe40e6593d88ea8bff0c9b8ea508f9 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3629-notebooks-l6869) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ea8092bd4aeaef09922faa0d429f81aa83905534 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-cdk95) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ea8092bd4aeaef09922faa0d429f81aa83905534 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-8dn5p) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | ea8092bd4aeaef09922faa0d429f81aa83905534 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/seldon-core-pr-3629-integration-8mbfc) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Release is good to merge

image

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 86dc01a551c3f78b031f08cb4ca0203d81ff575b | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3629-release-build-push-hh5kz) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | 86dc01a551c3f78b031f08cb4ca0203d81ff575b | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3629-release-build-push-lvlsx) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
release-build-push | d665f5841df4bd70d8dd582130f4f3bad649d148 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/core-pr-3629-release-build-push-92w4b) | `/test release`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Closing as release finalised

**Pull request closed without merging**
