### PR TITLE
Updated cert-manager API version

### LINKED ISSUE #3887: Legacy cert-manager API versions are no-longer served: v1alpha2, v1alpha3, and v1beta1
## Describe the bug

cert-manager v1 API version [was released around 1 year ago](https://github.com/cert-manager/website/blob/master/content/en/docs/installation/upgrading/upgrading-0.16-1.0.md
). cert-manager 1.6 onwards [deprecates v1alpha2, v1alpha3, and v1beta1](https://cert-manager.io/docs/release-notes/release-notes-1.6/
).

When `certManager.enabled` is `true`, seldon-core-operator chart [uses cert-manager v1alpha2/3](https://github.com/SeldonIO/seldon-core/blob/master/helm-charts/seldon-core-operator/templates/certificate_seldon-serving-cert.yaml#L2), not allowing the usage of newer cert-manager versions.

## To reproduce
1. install cert-manager 1.6 using helm.
2. install seldon-core (using helm) with `certManager.enabled` set to `true`, 
3. see the error.

## Expected behaviour

Update chart to use v1 API from cert-manager.

## Environment
Any

### PR DESCRIPTION
**Pull request by jonathansp**
**What this PR does / why we need it**:

Updates deprecated cert-manager API versions.

**Which issue(s) this PR fixes**:

Fixes #3887

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @jonathansp. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) or [todo](https://github.com/orgs/todo/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/todo/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jonathansp** [comment]
cc @cliveseldon

**Comment by seldondev** [comment]
@jonathansp: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | bb15f7be9c55f18680ed9b1d9e176cfb3061c1bb | [link](http://dashboard-jx.34.121.152.94.nip.io/namespaces/jx/pipelineruns/io-seldon-core-pr-3888-notebooks-s425k) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by jonathansp** [comment]
@cliveseldon @RafalSkolasinski CI step `Docs Test / docs-build (pull_request)` has failed, but it seems to be unrelated to the PR changes.

**Comment by cliveseldon** [comment]
Thanks. Looks good. @jonathansp

**Pull request merged**
