### PR TITLE
volume mount names upgrade fix

### PR DESCRIPTION
**Pull request by ryandawsonuk**
fixes https://github.com/SeldonIO/seldon-core/issues/2017

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jun 26 16:56:28 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=2

**Comment by seldondev** [comment]
Fri Jun 26 16:57:36 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=1

**Comment by seldondev** [comment]
Fri Jun 26 17:06:06 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=3

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 02e79687c19500727aacbafb9d4515102c1dce66 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Seems I [can't use the curly-braces for jsonpath inside the run command](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/3.log#L1476)

**Comment by seldondev** [comment]
Fri Jun 26 17:39:21 UTC 2020
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=5

**Comment by seldondev** [comment]
Fri Jun 26 17:40:53 UTC 2020
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=4

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 02e79687c19500727aacbafb9d4515102c1dce66 | [link]() | `/test integration`
lint | 275a34f6b7d3e26370cacf6a098c292feffec33d | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jun 26 17:44:44 UTC 2020
The logs for [integration] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=6

**Comment by seldondev** [comment]
Fri Jun 26 17:58:06 UTC 2020
The logs for [pr-build] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=7

**Comment by seldondev** [comment]
Fri Jun 26 17:58:10 UTC 2020
The logs for [lint] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=8

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 02e79687c19500727aacbafb9d4515102c1dce66 | [link]() | `/test integration`
pr-build | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test this`
integration | 275a34f6b7d3e26370cacf6a098c292feffec33d | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Seems this change [breaks apparently unrelated tests](https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/6.log#L1981). Not sure why as it stands.

**Comment by seldondev** [comment]
Mon Jun 29 07:47:32 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=9

**Comment by cliveseldon** [comment]
rebase from master and check notebook in #2021 @ryandawsonuk

**Comment by seldondev** [comment]
Mon Jun 29 07:55:02 UTC 2020
The logs for [notebooks] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=10

**Comment by seldondev** [comment]
Mon Jun 29 12:48:56 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=12

**Comment by seldondev** [comment]
Mon Jun 29 12:49:20 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=11

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 275a34f6b7d3e26370cacf6a098c292feffec33d | [link]() | `/test integration`
notebooks | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test notebooks`
lint | 40a36179cd9144669f0f59cc25cedbbdc110d2d7 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 12:51:39 UTC 2020
The logs for [integration] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=13

**Comment by seldondev** [comment]
Mon Jun 29 13:10:27 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=14

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test notebooks`
lint | 40a36179cd9144669f0f59cc25cedbbdc110d2d7 | [link]() | `/test lint`
integration | 40a36179cd9144669f0f59cc25cedbbdc110d2d7 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 13:38:02 UTC 2020
The logs for [lint] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=16

**Comment by seldondev** [comment]
Mon Jun 29 13:38:15 UTC 2020
The logs for [pr-build] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=15

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test notebooks`
integration | 40a36179cd9144669f0f59cc25cedbbdc110d2d7 | [link]() | `/test integration`
lint | 18eb3b7b0851008660ae856037d18dab03abb7ac | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 13:47:02 UTC 2020
The logs for [pr-build] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=17

**Comment by seldondev** [comment]
Mon Jun 29 13:47:16 UTC 2020
The logs for [lint] [18] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/18.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=18

**Comment by seldondev** [comment]
Mon Jun 29 13:49:10 UTC 2020
The logs for [integration] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=19

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test notebooks`
integration | 0b220241b7fbade64ab41b161e55b1fcb805cd6c | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 14:54:23 UTC 2020
The logs for [lint] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=21

**Comment by seldondev** [comment]
Mon Jun 29 14:54:46 UTC 2020
The logs for [pr-build] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=20

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | aac34c3bca811ce91eba261bccb47d7b53931330 | [link]() | `/test notebooks`
integration | 0b220241b7fbade64ab41b161e55b1fcb805cd6c | [link]() | `/test integration`
lint | ee6e4a5c369187739d9313092e5b1ba1ae5a8af9 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 15:08:58 UTC 2020
The logs for [pr-build] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=22

**Comment by seldondev** [comment]
Mon Jun 29 15:08:59 UTC 2020
The logs for [lint] [23] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/23.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=23

**Comment by seldondev** [comment]
Mon Jun 29 15:10:24 UTC 2020
The logs for [integration] [24] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/24.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=24

**Comment by ryandawsonuk** [comment]
Have now been trying to test it manually. It seems the fix does not work. It prevents it adding a new seldon podinfo mount but that's not enough. The SeldonDeployment still ends up going to Failed status with description 

```
Deployment.apps "iris-default-0-iris-container" is invalid: spec.template.spec.containers[0].volumeMounts[0].name:
    Not found: "podinfo"'
```
Seems it ends up creating an invalid Deployment. Not sure why. The controller logs basically just say the same thing.

**Comment by seldondev** [comment]
@ryandawsonuk: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 0b220241b7fbade64ab41b161e55b1fcb805cd6c | [link]() | `/test integration`
notebooks | 40a36179cd9144669f0f59cc25cedbbdc110d2d7 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Jun 29 17:32:13 UTC 2020
The logs for [lint] [26] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/26.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=26

**Comment by ryandawsonuk** [comment]
Have now taken a different approach. Am modifying the volume mount from the mutator. This 'works' but unfortunately doesn't get fed back to the SeldonDeployment in the cluster that was previously already mutated.

**Comment by seldondev** [comment]
Mon Jun 29 17:33:49 UTC 2020
The logs for [pr-build] [25] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/25.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=25

**Comment by seldondev** [comment]
Mon Jun 29 17:36:17 UTC 2020
The logs for [integration] [27] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/27.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=27

**Comment by seldondev** [comment]
Mon Jun 29 17:38:00 UTC 2020
The logs for [notebooks] [28] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/28.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=28

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | fe75da7a62bdffa2581dab540398adcda72b5c85 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Jun 30 07:05:23 UTC 2020
The logs for [notebooks] [29] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/29.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=29

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | fe75da7a62bdffa2581dab540398adcda72b5c85 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by ryandawsonuk** [comment]
Turns out the reason why the podinfo name doesn't get changed automatically is because the mutator doesn't get called as a webhook on upgrade. It is only called when there's an actual change to the SeldonDeployment. Slightly confusingly, our reconcile loop calls the mutator code so upgrading the controller does result in the code getting called and hence the SeldonDeployment doesn't go to Failed. But it doesn't get updated in k8s because the webhook hasn't actually been invoked as a webhook.

If you make an edit to the SeldonDeployment (any trivial edit) then the webhook will be called and it then changes from podinfo to seldon-podinfo.

**Comment by seldondev** [comment]
Tue Jun 30 10:38:19 UTC 2020
The logs for [notebooks] [30] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2019/30.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2019 --build=30

**Comment by seldondev** [comment]
@ryandawsonuk: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | fe75da7a62bdffa2581dab540398adcda72b5c85 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
