### PR TITLE
Adding overrides to remove step that creates tag for Jenkins X pipeline

### LINKED ISSUE #1124: Jenkins X currently creates a new changelog tag / version every time a PR is landed
Currently our release is manual, so we need to disable the default Jenkins X functionality that creates a tag every time a PR / commit is added into master.

### PR DESCRIPTION
**Pull request by axsaucedo**
Fixes #1124

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **axsaucedo**

If they are not already assigned, you can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by adriangonz** [comment]
That's awesome! Is it skipping the `promote` stage what does the trick @axsaucedo?

**Comment by axsaucedo** [comment]
@adriangonz that is correct, although it seems that right now there is still an issue as the pipeline expects the branch with the same name as the version exists, so we need to decide whether we are happy to overide the tag every time or whether we want to create a unique tag every time (although I can't think of a way to keep track. Here is all the detail: https://github.com/jenkins-x/jx/issues/6230

**Comment by axsaucedo** [comment]
It's now been addressed by continuously pushing the latest master into a branch v${VERSION}-SNAPSHOT branch. This branch is overriden every time there is a merged PR. There could be a race condition if two PR release pipelines are triggered at the exact same time. For the near to medium term we could have a look at creating a branch for all the releases to master, with either a counter, or with the github hash

**Comment by seldondev** [comment]
@axsaucedo: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/SeldonIO/seldon-core/pull/1161#issuecomment-559921554):

>/approve 
>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1161#issuecomment-559921554" title="LGTM">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
