### PR TITLE
Add executor rest server tests for with/without tracing code paths

### LINKED ISSUE #1858: add tests for tracing-enabled code path in executor's rest API
Commenting out for example a following block of code
https://github.com/SeldonIO/seldon-core/blob/787bb8b510f9590b05d3118395ac5e2a9e5c89fc/executor/api/rest/server.go#L304-L309
will not fail tests but will lead to obscure errors on prediction request.

Bellow example (using (new) metadata endpoint without the tracing code block):
```
{"level":"info","ts":1589987540.2213755,"logger":"SeldonRestApi","msg":"Graph Metadata called."}
{"level":"info","ts":1589987540.221461,"logger":"JSONRestClient","msg":"Calling HTTP","URL":"http://0.0.0.0:9001/metadata"}
2020/05/20 16:12:20 http: panic serving 127.0.0.1:42208: runtime error: invalid memory address or nil pointer dereference
goroutine 40 [running]:
net/http.(*conn).serve.func1(0xc0003c4000)
	/usr/lib/go-1.14/src/net/http/server.go:1772 +0x139
panic(0x1580900, 0x25f3140)
	/usr/lib/go-1.14/src/runtime/panic.go:975 +0x3e3
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).doHttp(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0x17879e9, 0x9, 0xc0000b2280, 0x0, 0x0, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:168 +0x830
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).call(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0x17879e9, 0x9, 0xc00036c3e0, 0x7, 0x2329, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:228 +0x251
github.com/seldonio/seldon-core/executor/api/rest.(*JSONRestClient).Metadata(0xc000143720, 0x19d7560, 0xc0003c2240, 0xc00036c3f0, 0x7, 0xc00036c3e0, 0x7, 0x2329, 0x0, 0x0, ...)
	/home/rskolasinski/work/seldon-core/executor/api/rest/client.go:238 +0x1c7
github.com/seldonio/seldon-core/executor/predictor.(*PredictorProcess).MetadataMap(0xc0004656a0, 0xc00014ca00, 0xc000314000, 0xc000314000, 0x0)
	/home/rskolasinski/work/seldon-core/executor/predictor/predictor_process.go:335 +0xa6
github.com/seldonio/seldon-core/executor/predictor.NewGraphMetadata(0xc00045b6a0, 0xc0000ee120, 0xa, 0x19e0ec0, 0xc0003e4060)
	/home/rskolasinski/work/seldon-core/executor/predictor/metadata.go:30 +0x3d
github.com/seldonio/seldon-core/executor/api/rest.(*SeldonRestApi).graph_metadata(0xc0000ee360, 0x7fb25c62d380, 0xc0007b4050, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:364 +0x219
net/http.HandlerFunc.ServeHTTP(0xc000372730, 0x7fb25c62d380, 0xc0007b4050, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/go/pkg/mod/github.com/prometheus/client_golang@v1.3.0/prometheus/promhttp/instrument_server.go:68 +0x11c
net/http.HandlerFunc.ServeHTTP(0xc000479d10, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/seldonio/seldon-core/executor/api/rest.(*CloudeventHeaderMiddleware).Middleware.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:183 +0xd4
net/http.HandlerFunc.ServeHTTP(0xc0003e4000, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/seldonio/seldon-core/executor/api/rest.puidHeader.func1(0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/home/rskolasinski/work/seldon-core/executor/api/rest/server.go:198 +0x111
net/http.HandlerFunc.ServeHTTP(0xc0003e4020, 0x19d4520, 0xc0003d6000, 0xc0003cc200)
	/usr/lib/go-1.14/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fc000, 0x19d4520, 0xc0003d6000, 0xc0003cc000)
	/home/rskolasinski/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc0001f42a0, 0x19d4520, 0xc0003d6000, 0xc0003cc000)
	/usr/lib/go-1.14/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc0003c4000, 0x19d74a0, 0xc0003c8000)
	/usr/lib/go-1.14/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/lib/go-1.14/src/net/http/server.go:2933 +0x35c
```

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
Fixes #1858.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **rafalskolasinski**

If they are not already assigned, you can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu May 28 14:58:43 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1891/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1891 --build=2

**Comment by seldondev** [comment]
Thu May 28 14:58:43 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1891/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1891 --build=1

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ab9d9ddf802330e1e6a62e6b39604837f1985f63 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu May 28 15:09:13 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1891/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1891 --build=3

**Comment by RafalSkolasinski** [comment]
Wrong approach to testing this. Closing for now.

**Pull request closed without merging**
