### PR TITLE
646 notebooks install

### PR DESCRIPTION
**Pull request by glindsell**
(Replaces #1180)

#646

- New setup notebook created and referenced in example notebooks.

- Testing of notebooks raised the following issues:

#1177

#1178

#1179

#473 is also still appearing in https://github.com/SeldonIO/seldon-core/blob/master/notebooks/helm_examples.ipynb

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ryandawsonuk**

If they are not already assigned, you can assign the PR to them by writing `/assign @ryandawsonuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Dec  6 11:46:03 UTC 2019
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1187/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1187 --build=4

**Comment by seldondev** [comment]
Fri Dec  6 11:46:14 UTC 2019
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1187/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1187 --build=5

**Comment by glindsell** [comment]
@ryandawsonuk please take a look at changes discussed today re: bringing helm commands into setup notebook.

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1187#issuecomment-562608448" title="Approved">ryandawsonuk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [ryandawsonuk]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Dec  6 15:09:32 UTC 2019
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1187/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1187 --build=7

**Comment by seldondev** [comment]
Fri Dec  6 15:09:38 UTC 2019
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1187/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1187 --build=6

**Pull request merged**
