### PR TITLE
Update distributed-tracing.md

### PR DESCRIPTION
**Pull request by omerfsen**
Update it to reflect latest version (which right now corresponds to 1.18). They automatically link latest to the version number so `latest` will always work

**What this PR does / why we need it**:

Updates jaeger to latest version

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
Hi @omerfsen. Thanks for your PR.

I'm waiting for a [SeldonIO](https://github.com/orgs/SeldonIO/people) member to verify that this patch is reasonable to test. If it is, they should reply with `/ok-to-test` on its own line. Until that is done, I will not automatically test new commits in this PR, but the usual testing commands by org members will still work. Regular contributors should [join the org](https://github.com/orgs/SeldonIO/people) to skip this step.

Once the patch is verified, the new status will be reflected by the `ok-to-test` label.

I understand the commands that are listed [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository.
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **glindsell**
You can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Aug 25 12:45:11 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=1

**Comment by seldondev** [comment]
Tue Aug 25 12:45:15 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=2

**Comment by cliveseldon** [comment]
@omerfsen would it not be better to choose a fixed version otherwise we risk breaking changes? Could we not set to 1.18?

**Comment by omerfsen** [comment]
Sure.

**Comment by seldondev** [comment]
Wed Aug 26 14:35:45 UTC 2020
The logs for [lint] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=4

**Comment by seldondev** [comment]
Wed Aug 26 14:35:49 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=3

**Comment by omerfsen** [comment]
1.16 --> 1.18

**Comment by omerfsen** [comment]
> 
> 
> @omerfsen would it not be better to choose a fixed version otherwise we risk breaking changes? Could we not set to 1.18?

done!

**Comment by seldondev** [comment]
Wed Aug 26 14:36:58 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=6

**Comment by seldondev** [comment]
Wed Aug 26 14:37:06 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=5

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[cliveseldon](https://github.com/SeldonIO/seldon-core/pull/2323#issuecomment-680928140 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-680928140/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@omerfsen: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 27e5438dc5eb6532532e1bf5a6ec16fd3360e78c | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by cliveseldon** [comment]
Can you rebase from master to fix lint error @omerfsen ?

**Comment by seldondev** [comment]
Thu Aug 27 09:51:37 UTC 2020
The logs for [notebooks] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2323/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2323 --build=7

**Comment by seldondev** [comment]
@omerfsen: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 27e5438dc5eb6532532e1bf5a6ec16fd3360e78c | [link]() | `/test lint`
notebooks | 27e5438dc5eb6532532e1bf5a6ec16fd3360e78c | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
