### PR TITLE
upgrade core-builder to 0.18 and fix last 2 failing notebook tests

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

* adds `jq` to core-builder image and change references to 0.18 version
* adjusts `TestNotebooks.test_grpc_metadata` to reverse multiplexing-related changes
* fixes `TestNotebooks.test_explainer_examples` by forcing `shap==0.35.0` in integration tests `dev_requirements.txt`

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2454

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by RafalSkolasinski** [comment]
Waiting for `core-builder:0.18` to be pushed  before triggering integration and notebook tests

**Comment by seldondev** [comment]
Fri Sep 18 13:07:01 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=2

**Comment by seldondev** [comment]
Fri Sep 18 13:07:20 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=1

**Comment by seldondev** [comment]
Fri Sep 18 13:24:23 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=3

**Comment by seldondev** [comment]
Fri Sep 18 13:25:00 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=4

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 026b042ea06c917f242667547365808be7145495 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Integration failure on `test-label-update-1-0-2` (well known flakiness).
/retest

**Comment by seldondev** [comment]
Fri Sep 18 15:15:48 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=5

**Comment by axsaucedo** [comment]
Looks good! We should merge once the metadata_grpc test passes 
/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2453#issuecomment-694929390 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-694929390/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | 026b042ea06c917f242667547365808be7145495 | [link]() | `/test integration`
notebooks | 026b042ea06c917f242667547365808be7145495 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
> Looks good! We should merge once the metadata_grpc test passes
> /approve

This one passed but `TestNotebooks.test_explainer_examples` decided to fail still.... Maybe there was something more in it than just `jq` missing

**Comment by RafalSkolasinski** [comment]
Hmm... in logs I can see `No module named 'shap.common'` - seems like notebook is running in environment with  a wrong `shap` version

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2453#issuecomment-694929390 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Sep 21 09:17:55 UTC 2020
The logs for [pr-build] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=6

**Comment by seldondev** [comment]
Mon Sep 21 09:17:59 UTC 2020
The logs for [lint] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=7

**Comment by seldondev** [comment]
Mon Sep 21 09:18:00 UTC 2020
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=8

**Comment by seldondev** [comment]
Mon Sep 21 09:18:50 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=9

**Comment by seldondev** [comment]
Mon Sep 21 09:20:01 UTC 2020
The logs for [notebooks] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=11

**Comment by seldondev** [comment]
Mon Sep 21 09:20:51 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=10

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 995f2f714b7b8910e04312adca88a7e61c70321e | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | 7d80bf93447f359a9a8b0988149d2a219425b400 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Mon Sep 21 11:36:50 UTC 2020
The logs for [pr-build] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=12

**Comment by seldondev** [comment]
Mon Sep 21 11:37:03 UTC 2020
The logs for [lint] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=13

**Comment by seldondev** [comment]
Mon Sep 21 11:37:30 UTC 2020
The logs for [notebooks] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2453/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2453 --build=14

**Pull request merged**
