### PR TITLE
WIP: Updated jenkins x to have base limits

### PR DESCRIPTION
**Pull request by axsaucedo**
Initial work for #2175

### CODE REVIEW

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 1 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/1.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=1

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 4 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/4.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=4

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 3 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/3.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=3

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 2 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/2.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=2

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **axsaucedo**
You can assign the PR to them by writing `/assign @axsaucedo` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
## SUCCESS [lint # 2] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 6 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/6.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=6

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 8 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/8.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=8

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 7 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/7.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=7

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 9 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/9.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=9

**Comment by seldondev** [comment]
## SUCCESS [lint # 7] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 11 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/11.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=11

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 10 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/10.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=10

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 13 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/13.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=13

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 12 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/12.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=12

**Comment by seldondev** [comment]
@axsaucedo: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test lint`
pr-build | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test lint`
pr-build | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@axsaucedo: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test lint`
pr-build | 4e2f85d7e9d8429f397bb8ffbafc3bc18d84cfd8 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 15 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/15.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=15

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 14 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/14.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=14

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 17 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/17.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=17

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 16 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/16.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=16

**Comment by seldondev** [comment]
## SUCCESS [lint # 15] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 19 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/19.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=19

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 18 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/18.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=18

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 21 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/21.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=21

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 20 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/20.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=20

**Comment by seldondev** [comment]
## SUCCESS [lint # 19] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 23 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/23.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=23

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 22 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2176/22.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2176 --build=22

**Comment by seldondev** [comment]
## SUCCESS [lint # 23] TEST PASSED ✅

Well done! 😎

**Comment by axsaucedo** [comment]
Closing PR as needs to be re-assessed once JX resources / requests / limits is addressed

**Pull request closed without merging**
