### PR TITLE
Update tracing dependencies

### LINKED ISSUE #2143: Update version of Jaeger in Python wrapper
The version of Jaeger that we are using is pinning down some of its dependencies to older versions (e.g. `tornado`). It would be good to bump it up, however the version of Jaeger is very coupled with the versions of Opentracing and Flask-Opentracing.

We'll need to check if there is a newer version of the three which is compatible between them.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:
Update `opentracing` and `jaeger-client` dependencies.

**Which issue(s) this PR fixes**:

Fixes #2143

**Special notes for your reviewer**:
There doesn't seem to be any newer versions for `Flask-Opentracing` and `grpcio-opentracing`. No breaking changes are documented for the upgraded deps.

**Does this PR introduce a user-facing change?**:

```release-note
Update tracing dependencies for Python inference server.
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Jul 20 10:29:33 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2166 --build=1

**Comment by seldondev** [comment]
Mon Jul 20 10:29:44 UTC 2020
The logs for [notebooks] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2166 --build=3

**Comment by seldondev** [comment]
Mon Jul 20 10:29:52 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2166 --build=2

**Comment by seldondev** [comment]
Mon Jul 20 10:30:02 UTC 2020
The logs for [engine] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2166 --build=4

**Comment by seldondev** [comment]
Mon Jul 20 10:31:45 UTC 2020
The logs for [integration] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2166 --build=5

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e6c940448c5b3d25b0a617073832cfc8154a7fc0 | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by adriangonz** [comment]
The only failed test was running `TestNotebooks.test_istio_examples`, with error message below. Could be due to flakiness on the notebook tests? Everything else (`engine` and `integration`) passes.

```python
AssertionError                            Traceback (most recent call last)
/workspace/source/notebooks/istio_example.py in <module>
    204
    205 r = sc.predict(gateway="istio",transport="rest")
--> 206 assert(r.success==True)
    207 print(r)
    208
```

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2166#issuecomment-661068324 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-661068324/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ notebooks # 6 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/6.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2166 --build=6

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2166#issuecomment-661068324 "Approved")*, *[RafalSkolasinski](https://github.com/SeldonIO/seldon-core/pull/2166#issuecomment-661081239 "LGTM")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-661081239/SeldonIO/seldon-core/blob/master/OWNERS)~~ [RafalSkolasinski,axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
## SUCCESS [notebooks # 6] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 7 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/7.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2166 --build=7

**Comment by seldondev** [comment]
## STARTING TEST [ lint # 8 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/8.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2166 --build=8

**Comment by seldondev** [comment]
## SUCCESS [lint # 8] TEST PASSED ✅

Well done! 😎

**Comment by seldondev** [comment]
@adriangonz: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | e6c940448c5b3d25b0a617073832cfc8154a7fc0 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
## STARTING TEST [ pr-build # 9 ]

Logs will be available when test completes in the following link:
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2166/9.log

Impatient try:
jx get build logs SeldonIO/seldon-core/PR-2166 --build=9

**Comment by seldondev** [comment]
## SUCCESS [pr-build # 9] TEST PASSED ✅

Well done! 😎

**Pull request merged**
