### PR TITLE
do not act on resources that have deletion timestamp set

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
**What this PR does / why we need it**:

This avoids having `Operator` re-creating Pods (and other resources) that are being removed through `foreground` deletion mechanism, e.g. ArgoCD-powered gitops.

**Which issue(s) this PR fixes**:

Closes https://github.com/SeldonIO/seldon-core/issues/2781

**Special notes for your reviewer**:

For reference, [this](https://github.com/kubeflow/kfserving/blob/master/pkg/controller/v1beta1/inferenceservice/controller.go#L84-L114) is how it is done in kfserving. 

This is important because in [foreground](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion) deletion resource is still available through the API while it is being deleted. 
If we don't stop early on the `reconcile` logic we would be recreating the pods that are being deleted. 

Logic here differs from one in kfserving as we do not use finalizers. 

**Does this PR introduce a user-facing change?**:

```release-note
None
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **rafalskolasinski**
You can assign the PR to them by writing `/assign @rafalskolasinski` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Mon Dec 14 17:05:47 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=2

**Comment by seldondev** [comment]
Mon Dec 14 17:06:00 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=1

**Comment by seldondev** [comment]
Mon Dec 14 17:09:46 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=4

**Comment by seldondev** [comment]
Mon Dec 14 17:09:54 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=3

**Comment by seldondev** [comment]
Mon Dec 14 18:14:34 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=6

**Comment by seldondev** [comment]
Mon Dec 14 18:14:44 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=5

**Comment by seldondev** [comment]
Tue Dec 15 10:43:12 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=7

**Comment by seldondev** [comment]
Tue Dec 15 10:44:46 UTC 2020
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=8

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | c09e1d05b9260c5da8e5074cf7ba6d6329a339bf | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Dec 15 14:43:13 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=9

**Comment by seldondev** [comment]
Tue Dec 15 14:43:30 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=10

**Comment by seldondev** [comment]
Tue Dec 15 14:43:58 UTC 2020
The logs for [pr-build] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=11

**Comment by seldondev** [comment]
Tue Dec 15 14:44:13 UTC 2020
The logs for [lint] [12] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/12.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=12

**Comment by seldondev** [comment]
Tue Dec 15 14:44:32 UTC 2020
The logs for [notebooks] [13] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/13.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=13

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | c09e1d05b9260c5da8e5074cf7ba6d6329a339bf | [link]() | `/test notebooks`
lint | dd1ee23aca89dc04f477320612c4ff97ac9917d2 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Dec 15 18:24:46 UTC 2020
The logs for [pr-build] [14] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/14.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=14

**Comment by seldondev** [comment]
Tue Dec 15 18:24:53 UTC 2020
The logs for [lint] [15] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/15.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=15

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 826cec0adb7b463434e869975fda54a79f492300 | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 826cec0adb7b463434e869975fda54a79f492300 | [link]() | `/test lint`
pr-build | 826cec0adb7b463434e869975fda54a79f492300 | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Tue Dec 15 18:40:42 UTC 2020
The logs for [pr-build] [16] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/16.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=16

**Comment by seldondev** [comment]
Tue Dec 15 18:40:54 UTC 2020
The logs for [lint] [17] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/17.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=17

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 826cec0adb7b463434e869975fda54a79f492300 | [link]() | `/test this`
lint | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test lint`
notebooks | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Meant to trigger integration (stopped the notebooks pipeline)

**Comment by seldondev** [comment]
Tue Dec 15 19:40:42 UTC 2020
The logs for [integration] [19] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/19.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=19

**Comment by seldondev** [comment]
@RafalSkolasinski: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test lint`
notebooks | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test notebooks`
integration | f77fb1c51428d3286671a2468b2e717c2947071f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Wed Dec 16 08:36:27 UTC 2020
The logs for [integration] [20] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/20.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=20

**Comment by seldondev** [comment]
Wed Dec 16 09:58:02 UTC 2020
The logs for [lint] [22] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/22.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=22

**Comment by seldondev** [comment]
Wed Dec 16 09:58:07 UTC 2020
The logs for [pr-build] [21] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2782/21.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2782 --build=21

**Pull request merged**
