### PR TITLE
Switch on executor enabled for service ports

### PR DESCRIPTION
**Pull request by glindsell**
Signed-off-by: glindsell <gl@seldon.io>

Fixes: #1975

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **glindsell**

If they are not already assigned, you can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Jun 19 09:58:14 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=2

**Comment by seldondev** [comment]
Fri Jun 19 09:58:29 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=1

**Comment by seldondev** [comment]
Fri Jun 19 10:00:51 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=3

**Comment by seldondev** [comment]
Fri Jun 19 10:01:16 UTC 2020
The logs for [notebooks] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=4

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test this`
integration | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@glindsell: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test this`
integration | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test integration`
notebooks | a7ebff3fe3c2041563b951816c71233bc1e7cb6b | [link]() | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Jun 19 10:26:51 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=6

**Comment by seldondev** [comment]
Fri Jun 19 10:26:58 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=5

**Comment by seldondev** [comment]
Fri Jun 19 10:27:54 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=7

**Comment by seldondev** [comment]
Fri Jun 19 10:27:55 UTC 2020
The logs for [notebooks] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=8

**Comment by chengcheng-pei** [comment]
@glindsell can we get this merged ASAP?

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1981#issuecomment-647947658" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Tue Jun 23 06:57:51 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=9

**Comment by seldondev** [comment]
Tue Jun 23 06:59:08 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1981/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1981 --build=10

**Pull request merged**
