### PR TITLE
Transformers example

### LINKED ISSUE #3732: Add model chaining example for the V2 protocol
Currently, the executor should support chaining of multiple models when using the V2 protocol. This is done by mapping the upstream model outputs, to the next model's inputs.

The scope of this task is to add an end-to-end example showcasing this, as well as showing how one can use MLServer's support for custom images to easily write a pre-/post-processor.

### PR DESCRIPTION
**Pull request by adriangonz**
**What this PR does / why we need it**:

Add example on how to build a custom pre-processor / transformer compatible with the V2 inference protocol, to then deploy it alongside a GPT-2 model in a `SeldonDeployment` inference graph.

**Which issue(s) this PR fixes**:

Fixes #3732

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by cliveseldon** [comment]
looks great @adriangonz

**Comment by axsaucedo** [comment]
Looks good! Seems image doesn't render when opening the notebook in github but assuming it would work in notebook (as is svg)

It seems the docs test is failing (normally the build has been failing but the lint is passsing so wondering if its anything related)

**Review by edshee — APPROVED** [review]
Adrian this is great. Well written and explains the components you're using at each step :clap:

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[edshee](https://github.com/SeldonIO/seldon-core/pull/3743#pullrequestreview-808395321 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **adriangonz**
You can assign the PR to them by writing `/assign @adriangonz` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
