### PR TITLE
Adding AWS Marketplace Install page to docs site

### PR DESCRIPTION
**Pull request by JoelH96**
Currently referncing the AWS Marketplace install option at the bottom of the 'install' docs page. And then the main page is hosted in the 'Reference' section.

Maybe once the other Marketplaces are updated, I could add a new section for Marketplace installs?

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **cliveseldon**

If they are not already assigned, you can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by cliveseldon** [comment]
Can you check your indent as there are a lot of changed files with a different indent for some reason in the generated API docs?

**Comment by seldondev** [comment]
Thu Dec  5 21:58:19 UTC 2019
The logs for [pr-build] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1182/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1182 --build=4

**Comment by seldondev** [comment]
Thu Dec  5 21:58:34 UTC 2019
The logs for [lint] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1182/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1182 --build=5

**Comment by JoelH96** [comment]
@cliveseldon - I've updated the docs and fixed the indent back to the original 4 spacing indent. It appears with the latest versions of Sphinx, the default indent for generated .rst files is 3 spaces. So I had to pin the versions to those in the requirements file for the 4 space indent. This post discusses in further detail:

https://stackoverflow.com/questions/48311159/is-3-space-indentation-required-in-rest

**Comment by JoelH96** [comment]
Should the 3 space indent be accepted in future to use the latest versions of Sphinx?

**Comment by cliveseldon** [comment]
> Should the 3 space indent be accepted in future to use the latest versions of Sphinx?

Suggest you create an issue and PR for updating to the latest Sphinx?

The rest looks good!

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1182#issuecomment-562350878" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
