### PR TITLE
Fix 1.22 Webhook Create by ensuring v1 is used

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
 * Ensure v1 and not v1beta1 Webhook is created when `managerCreateResources=true`
 * Add extra logging to help with any failures and fixes missing catches of errors not handled

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Updates look good, would be worth adding a note on the UPGRADING.md page just as heads up that this would be the case. 

I just ran a test locally with 1.11.2 to test `--set managerCreateResources=true` to validate that the upgrade actually works, and I can confirm there are no issues, but also I've realised that there's actually no difference that this changes add as the webhook loaded from file is created as v1 even in 1.11.2 when managerCreateResources is true.

Another thing I noticed is that the webhook in the helm chart is created with name `seldon-validating-webhook-configuration-seldon-system` whereas the controller creates it with the name `seldon-validating-webhook-configuration` - may be worth aligning the names (can be done as separate PR)

/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/3736#issuecomment-968102970 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Failed to merge this PR due to:
>failed merging [3736]: [Method Not Allowed]

**Pull request merged**
