### PR TITLE
add notebook test deps to integration tesets requirements file

### PR DESCRIPTION
**Pull request by RafalSkolasinski**
closes https://github.com/SeldonIO/seldon-core/issues/1504

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **gsunner**

If they are not already assigned, you can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Wed Mar 11 23:19:22 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=1

**Comment by seldondev** [comment]
Wed Mar 11 23:19:23 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=2

**Comment by seldondev** [comment]
Wed Mar 11 23:22:33 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=3

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f7e035931ee9dca18d9d69a3b884d78e5dc54720 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1535#issuecomment-598049447" title="Approved">cliveseldon</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [cliveseldon]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Thu Mar 12 07:44:04 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=4

**Comment by RafalSkolasinski** [comment]
Actually... started to think if I need to increment `DOCKER_IMAGE_VERSION=0.12` and push new image to hub for it to work? @cliveseldon

**Comment by seldondev** [comment]
@RafalSkolasinski: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | f7e035931ee9dca18d9d69a3b884d78e5dc54720 | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by RafalSkolasinski** [comment]
Hmm... very interesting error message in the last failure:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/workspace/source/examples/istio/canary_update/canary.py in <module>
    158 
    159 
--> 160 predict_rest_mnist(mnist,"mnist-classifier","seldon",ISTIO_GATEWAY)
    161 
    162 
/workspace/source/examples/istio/canary_update/canary.py in predict_rest_mnist(mnist, deployment_name, namespace, istio_gateway)
    113     r = sc.predict(gateway="istio",transport="rest",shape=(1,784),data=data,payload_type='ndarray',names=features)
    114     predictions = r.response
--> 115     fpreds = [ '%.2f' % elem for elem in predictions["data"]["ndarray"][0] ]
    116     m = dict(zip(predictions["data"]["names"],fpreds))
    117     print(json.dumps(m,indent=2))
TypeError: 'NoneType' object is not subscriptable
```

**Comment by seldondev** [comment]
Thu Mar 12 12:00:49 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=7

**Comment by seldondev** [comment]
Thu Mar 12 12:01:48 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=5

**Comment by seldondev** [comment]
Thu Mar 12 12:02:27 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1535/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1535 --build=6

**Pull request merged**
