### PR TITLE
Fix tracing debug

### LINKED ISSUE #3158: Setting TRACING=0 does not disable Jaeger tracing
## Describe the bug

According to the [docs](https://docs.seldon.io/projects/seldon-core/en/stable/graph/distributed-tracing.html?highlight=TRACING), we need to set `TRACING` to `1`, but in my case I want to disable and set it to `0`since it overwrite all my log (some random `print` statement) but the tracer is still there. I even went 1 step further to check the source code [here](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/microservice.py#L339), [here](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/gunicorn_utils.py#L87) and [here](https://github.com/SeldonIO/seldon-core/blob/master/python/seldon_core/gunicorn_utils.py#L87) and I found that they are always activated no matter what.

Here's some of the log:
```
starting microservice
2021-05-04 10:11:56,458 - seldon_core.microservice:main:203 - INFO:  Starting microservice.py:main
2021-05-04 10:11:56,459 - seldon_core.microservice:main:204 - INFO:  Seldon Core version: 1.8.0-dev
2021-05-04 10:11:56,460 - seldon_core.microservice:main:345 - INFO:  Parse JAEGER_EXTRA_TAGS []
2021-05-04 10:11:56,460 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation deployment_version:v1
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation false:
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation kubernetes.io/config.seen:2021-05-04T10:11:52.258244784Z
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation kubernetes.io/config.source:api
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation predictor_version:v1
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation project_name:NLP Pipeline
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation prometheus.io/path:/prometheus
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation prometheus.io/scrape:true
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation seldon.io/rest-timeout:100000
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation sidecar.istio.io/inject:false
2021-05-04 10:11:56,461 - seldon_core.microservice:load_annotations:155 - INFO:  Found annotation v1:
2021-05-04 10:11:56,461 - seldon_core.microservice:main:348 - INFO:  Annotations: {'deployment_version': 'v1', 'false': '', 'kubernetes.io/config.seen': '2021-05-04T10:11:52.258244784Z', 'kubernetes.io/config.source': 'api', 'predictor_version': 'v1', 'project_name': 'NLP Pipeline', 'prometheus.io/path': '/prometheus', 'prometheus.io/scrape': 'true', 'seldon.io/rest-timeout': '100000', 'sidecar.istio.io/inject': 'false', 'v1': ''}
2021-05-04 10:11:56,461 - seldon_core.microservice:main:352 - INFO:  Importing Preprocess
2021-05-04 10:11:56,475 - seldon_core.microservice:main:433 - INFO:  REST gunicorn microservice running on port 9000
2021-05-04 10:11:56,475 - seldon_core.microservice:main:488 - INFO:  REST metrics microservice running on port 6000
2021-05-04 10:11:56,475 - seldon_core.microservice:main:498 - INFO:  Starting servers
2021-05-04 10:11:56,481 - seldon_core.wrapper:_set_flask_app_configs:213 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
2021-05-04 10:11:56,483 - seldon_core.wrapper:_set_flask_app_configs:213 - INFO:  App Config:  <Config {'ENV': 'production', 'DEBUG': False, 'TESTING': False, 'PROPAGATE_EXCEPTIONS': None, 'PRESERVE_CONTEXT_ON_EXCEPTION': None, 'SECRET_KEY': None, 'PERMANENT_SESSION_LIFETIME': datetime.timedelta(days=31), 'USE_X_SENDFILE': False, 'SERVER_NAME': None, 'APPLICATION_ROOT': '/', 'SESSION_COOKIE_NAME': 'session', 'SESSION_COOKIE_DOMAIN': None, 'SESSION_COOKIE_PATH': None, 'SESSION_COOKIE_HTTPONLY': True, 'SESSION_COOKIE_SECURE': False, 'SESSION_COOKIE_SAMESITE': None, 'SESSION_REFRESH_EACH_REQUEST': True, 'MAX_CONTENT_LENGTH': None, 'SEND_FILE_MAX_AGE_DEFAULT': datetime.timedelta(seconds=43200), 'TRAP_BAD_REQUEST_ERRORS': None, 'TRAP_HTTP_EXCEPTIONS': False, 'EXPLAIN_TEMPLATE_LOADING': False, 'PREFERRED_URL_SCHEME': 'http', 'JSON_AS_ASCII': True, 'JSON_SORT_KEYS': True, 'JSONIFY_PRETTYPRINT_REGULAR': False, 'JSONIFY_MIMETYPE': 'application/json', 'TEMPLATES_AUTO_RELOAD': None, 'MAX_COOKIE_SIZE': 4093}>
2021-05-04 10:11:56,491 - seldon_core.microservice:grpc_prediction_server:463 - INFO:  GRPC microservice Running on port 5000
[2021-05-04 10:11:56 +0000] [49] [INFO] Starting gunicorn 20.0.4
[2021-05-04 10:11:56 +0000] [49] [INFO] Listening at: http://0.0.0.0:6000 (49)
[2021-05-04 10:11:56 +0000] [49] [INFO] Using worker: sync
[2021-05-04 10:11:56 +0000] [58] [INFO] Booting worker with pid: 58
[2021-05-04 10:11:56 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2021-05-04 10:11:56 +0000] [1] [INFO] Listening at: http://0.0.0.0:9000 (1)
[2021-05-04 10:11:56 +0000] [1] [INFO] Using worker: threads
[2021-05-04 10:11:56 +0000] [59] [INFO] Booting worker with pid: 59
2021-05-04 10:11:56,516 - seldon_core.gunicorn_utils:load:88 - INFO:  Tracing branch is active
2021-05-04 10:11:56,520 - seldon_core.utils:setup_tracing:724 - INFO:  Initializing tracing
2021-05-04 10:11:56,562 - seldon_core.utils:setup_tracing:731 - INFO:  Using default tracing config
2021-05-04 10:11:56,562 - jaeger_tracing:_create_local_agent_channel:446 - INFO:  Initializing Jaeger Tracer with UDP reporter
2021-05-04 10:11:56,565 - jaeger_tracing:new_tracer:384 - INFO:  Using sampler ConstSampler(True)
2021-05-04 10:11:56,567 - jaeger_tracing:_initialize_global_tracer:436 - INFO:  opentracing.tracer initialized to <jaeger_client.tracer.Tracer object at 0x7feaca72a450>[app_name=Preprocess]
2021-05-04 10:11:56,567 - seldon_core.gunicorn_utils:load:93 - INFO:  Set JAEGER_EXTRA_TAGS []
2021-05-04 10:12:16,733 - jaeger_tracing:report_span:73 - INFO:  Reporting span 69f4ad23b28f24a3:bfd2bebe67143e14:0:1 Preprocess.static
2021-05-04 10:12:31,731 - jaeger_tracing:report_span:73 - INFO:  Reporting span 7206c784d8f152e0:e6ccaf4dadbbd6a0:0:1 Preprocess.static
2021-05-04 10:13:04,732 - jaeger_tracing:report_span:73 - INFO:  Reporting span 3c87fb1d4f524af5:c59a416e69daeb72:0:1 Preprocess.static
2021-05-04 10:13:16,732 - jaeger_tracing:report_span:73 - INFO:  Reporting span f134e20a0852e208:1af69c064573625b:0:1 Preprocess.static
2021-05-04 10:13:31,731 - jaeger_tracing:report_span:73 - INFO:  Reporting span 76713d4b2fc95dc3:35c5169936b5003b:0:1 Preprocess.static
```
## To reproduce

My deployment file is similar to the [example](https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/kubeflow_seldon_e2e_pipeline.html) but the predict function is very simple (I'm just setting up so no fancy stuff):

```
    def predict(self, X, features_names=None, meta=None):
        print("X:", X)
        print("features_names:", features_names)
        print("meta:", meta)
        X[0] += 2
        return X
```

Also I'm using `seldonio/seldon-core-s2i-python37:1.7.0`

## Expected behaviour

Jaeger client is disable and I get my log back

## Environment
I'm using Kubernetes v1.16.15 installed on our server

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:

 Ensures tracing is not activated if TRACING=0 in python wrapper.

**Which issue(s) this PR fixes**:

Fixes #3158

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | b57a31adcadddc03c370590e2aa625af136a6f40 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-vnnmb) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b57a31adcadddc03c370590e2aa625af136a6f40 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-bsgh5) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b57a31adcadddc03c370590e2aa625af136a6f40 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-bsgh5) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | b57a31adcadddc03c370590e2aa625af136a6f40 | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-bsgh5) | `/test notebooks`
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-7p4sq) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-7p4sq) | `/test integration`
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-6jx7h) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-6jx7h) | `/test notebooks`
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-gfwtj) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-gfwtj) | `/test integration`
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-h4x57) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-h4x57) | `/test notebooks`
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-s62m5) | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/integration-s62m5) | `/test integration`
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-5jtxz) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
All tests seem to pass - merging

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
notebooks | e04cc2f4fabff4d5ade793c2dab3649d5be6393d | [link](http://dashboard-jx.34.66.17.27.nip.io/namespaces/jx/pipelineruns/notebooks-mztfj) | `/test notebooks`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Pull request merged**
