### PR TITLE
Add headers to curl request for executor sample

### LINKED ISSUE #1770: Metrics executor local sample REST request fails
https://github.com/SeldonIO/seldon-core/tree/master/executor/samples/local/metrics

The following command from this sample:
`make curl_rest`

Fails with the following:
```
curl -v localhost:8000/api/v0.1/predictions -d '{"data":{"ndarray":[[1.0,2.0]]}}' 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8000 (#0)
> POST /api/v0.1/predictions HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 32
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 32 out of 32 bytes
< HTTP/1.1 400 Bad Request
< Seldon-Puid: cbb894b6-f4af-443c-9b1f-a9362620f79d
< Date: Thu, 30 Apr 2020 13:52:48 GMT
< Content-Length: 100
< Content-Type: text/plain; charset=utf-8
< 
{"status":{"code":-1,"info":"Can't find JSON in data","reason":"MICROSERVICE_BAD_DATA","status":1}}
* Connection #0 to host localhost left intact
```

### PR DESCRIPTION
**Pull request by glindsell**
Fixes #1770 
Signed-off-by: glindsell <gl@seldon.io>

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **glindsell**

If they are not already assigned, you can assign the PR to them by writing `/assign @glindsell` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
@glindsell: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | ab6ca38d6c7b0a197bab055a81fc36731f13698f | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Thu Apr 30 14:35:18 UTC 2020
The logs for [pr-build] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-1771/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-1771 --build=3

**Comment by glindsell** [comment]
@ryandawsonuk I spoke to @cliveseldon about this one - he suggested you might have worked on this area of SC before. Do you know if this is expected behaviour that we force the client to specify the Content-Type in the Header of a request? Or should there be logic to work out what the Content-Type is from the payload?

**Comment by RafalSkolasinski** [comment]
Isn't requesting `Conte-Type` to be `application/json` just a web standard?
When sending requests from `Python` if you specify your post data using `json=...` argument it adds that automatically for example.

**Pull request merged**
