### PR TITLE
Updated GPU wrapper to uninstall TF without GPU

### PR DESCRIPTION
**Pull request by JoelH96**
Updated the Python TF-GPU wrapper to uninstall Tensorflow (without GPU) after the Seldon-core install and only install Tensorflow-GPU. An install of Numpy=1.16.1 was also added to clear Warnings due to version 1.17 of Numpy with TF-GPU.

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **gsunner**

If they are not already assigned, you can assign the PR to them by writing `/assign @gsunner` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by axsaucedo** [comment]
Looks solid - tensorflow is actually not a required install from v0.5.0 so if we wait for that release we could make sure the pip uninstall is not required, and given it's an image file we'd be able to push a snapshot for 1.0. Did you test it in a GPU instance with the loaded models?

**Comment by axsaucedo** [comment]
@adeepsri this fixes #914

**Comment by axsaucedo** [comment]
@JoelH96 it would be good to address #868 on this PR as well given it's quite relevant

**Comment by JoelH96** [comment]
Ok, maybe if we wait then until the v0.5.0 release, then I will change the wrapper to ensure the seldon-core pip install is with that version, to remove the pip uninstall.

For now though the newly built seldonio/seldon-core-s2i-python3-tf-gpu does not contain the CPU version of TF, and yes I tested it using the deep mnist models in a GPU instance.

**Comment by axsaucedo** [comment]
Now that 0.5 is out we can add this one :+1: tf doesn't come installed by default so you can just install it on top

**Comment by seldondev** [comment]
@JoelH96: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 1de6b1506805adb2e46155112c520264351f6b8d | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@JoelH96: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 57e105bf80ea4dce8846e8764fbb6dad43e92cad | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by JoelH96** [comment]
@axsaucedo - Updated the wrapper to not include the uninstall of TF. The new image also pushed to the Dockerhub repo

**Comment by axsaucedo** [comment]
Nice one! Lint seems to be failing just on the version.py so /lgtm
/

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/SeldonIO/seldon-core/pull/1011#issuecomment-550382971" title="Approved">axsaucedo</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
