### PR TITLE
k8s 1.18 fix

### LINKED ISSUE #641: Update CRD to be Structural
https://kubernetes.io/blog/2019/06/20/crd-structural-schema/

### LINKED ISSUE #926: DownwardAPI fails validation in CRD
The latest CRD has full OpenAPI validation auto-generated by Kubebuilder. However, the PodSpec validation has issues with downwardAPI which will cause failures of the form:

```
type in spec.predictors.componentSpecs.spec.volumes.downwardAPI is required
```
This is caused by: https://github.com/go-openapi/validate/issues/108
A fix has been created: https://github.com/go-openapi/validate/pull/107 but does not seem to be in a k8s release yet.

A temporary solution may be needed. 

This will become a greater issue if not fully fixed when k8s only allows structural schema as then all valid fields must be defined in the OpenAPI validationspec.

### LINKED ISSUE #1675: seldon-core-operator CRD's incompatible with K8s v1.18
Installing the seldon-core-operator on a fresh v1.18 Kubernetes install throws an error:

```
Error: CustomResourceDefinition.apiextensions.k8s.io "seldondeployments.machinelearning.seldon.io" is invalid: [spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[containers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[componentSpecs].items.properties[spec].properties[initContainers].items.properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property, spec.validation.openAPIV3Schema.properties[spec].properties[predictors].items.properties[explainer].properties[containerSpec].properties[ports].items.properties[protocol].default: Required value: this property is in x-kubernetes-list-map-keys, so it must have a default or be a required property]
```

I believe this is due to an [API change in v1.18](https://kubernetes.io/docs/setup/release/notes/).

> CustomResourceDefinition schemas that use x-kubernetes-list-map-keys to specify properties that uniquely identify list items must make those properties required or have a default value, to ensure those properties are present for all list items. See https://kubernetes.io/docs/reference/using-api/api-concepts/&#35;merge-strategy for details. (#88076, @eloyekunle) [SIG API Machinery and Testing]

I was able to work around by installing a crd definition exported from a successful v1.17 install and installing seldon-core-operator with `crd.create=false`.

Steps to reproduce:
```
curl https://get.helm.sh/helm-v3.1.2-linux-amd64.tar.gz -o helm-v3.1.2-linux-amd64.tar.gz
tar -xzvf helm-v3.1.2-linux-amd64.tar.gz
chmod a+x linux-amd64/helm
mv linux-amd64/helm /usr/local/bin/

helm repo add ambassador https://www.getambassador.io
helm repo add seldon https://storage.googleapis.com/seldon-charts

helm upgrade ambassador ambassador/ambassador --install
helm upgrade seldon-core seldon/seldon-core-operator --install --version=1.0.3-SNAPSHOT --set ambassador.enabled=true --set crd.create=true
```

### LINKED ISSUE #1864: OpenAPI Validation for PredictiveUnits limited to 5 levels
As CRD OpenApi Validation does not allow recursive definitions at present the CRD has a fixed expanded definition of the children Predictive Units:

https://github.com/SeldonIO/seldon-core/blob/master/operator/config/crd/patches/graph_children.yaml

This needs to be expanded as a short term fix to more levels as users are hitting these levels of graph complexity.

A long term solution would be when CRD OpenAPI validation allows recursive definitions.
At present this seems to have not moved forward: https://github.com/kubernetes/kubernetes/issues/54579

### PR DESCRIPTION
**Pull request by cliveseldon**
**What this PR does / why we need it**:
Allows Seldon Core to be deployed on k8s >=1.18

 * Adds a v1 CRD to kustomize.
 * Updates helm to choose between v1beta1 and v1 CRDs based on k8s version.
 * Adds a script to generate graph childen to a greater depth. Unfortunately references are still not allowed in OpenAPISchema and anyway this structure is recursive.

Notes:

 * v1 CRD is structural.
 * v1 CRD does not need volumes hack due to k8s fixes in k8s 1.18

**Which issue(s) this PR fixes**:

Fixes #1675 
Fixes #926 
Fixes #1864
Fixes #641 

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
k8s 1.18 compatability
```

### CODE REVIEW

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **cliveseldon**
You can assign the PR to them by writing `/assign @cliveseldon` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/SeldonIO/seldon-core/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by seldondev** [comment]
Fri Aug 28 10:36:01 UTC 2020
The logs for [pr-build] [1] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/1.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=1

**Comment by seldondev** [comment]
Fri Aug 28 10:36:48 UTC 2020
The logs for [lint] [2] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/2.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=2

**Comment by seldondev** [comment]
Fri Aug 28 10:41:27 UTC 2020
The logs for [integration] [3] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/3.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=3

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5bc2b9a22b419fb9ac6d69c13e61d74c517375cf | [link]() | `/test lint`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5bc2b9a22b419fb9ac6d69c13e61d74c517375cf | [link]() | `/test lint`
integration | 5bc2b9a22b419fb9ac6d69c13e61d74c517375cf | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Aug 28 15:19:25 UTC 2020
The logs for [integration] [4] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/4.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=4

**Comment by seldondev** [comment]
@cliveseldon: The following tests **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
lint | 5bc2b9a22b419fb9ac6d69c13e61d74c517375cf | [link]() | `/test lint`
integration | 5bc2b9a22b419fb9ac6d69c13e61d74c517375cf | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by seldondev** [comment]
Fri Aug 28 16:48:28 UTC 2020
The logs for [lint] [6] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/6.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=6

**Comment by seldondev** [comment]
Fri Aug 28 16:48:32 UTC 2020
The logs for [pr-build] [5] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/5.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=5

**Comment by seldondev** [comment]
Fri Aug 28 17:39:06 UTC 2020
The logs for [integration] [7] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/7.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=7

**Comment by seldondev** [comment]
Sat Aug 29 07:52:25 UTC 2020
The logs for [integration] [8] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/8.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=8

**Comment by seldondev** [comment]
Sat Aug 29 10:15:19 UTC 2020
The logs for [lint] [10] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/10.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=10

**Comment by seldondev** [comment]
Sat Aug 29 10:15:37 UTC 2020
The logs for [pr-build] [9] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/9.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=9

**Comment by seldondev** [comment]
Sat Aug 29 11:21:05 UTC 2020
The logs for [integration] [11] will show after the pipeline context has finished.  
https://github.com/SeldonIO/seldon-core/blob/gh-pages/jenkins-x/logs/SeldonIO/seldon-core/PR-2339/11.log

impatient try  
jx get build logs SeldonIO/seldon-core/PR-2339 --build=11

**Comment by seldondev** [comment]
@cliveseldon: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
integration | af843c0675248e4ec9b23f69f25dd225ca377f2f | [link]() | `/test integration`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [jenkins-x/lighthouse](https://github.com/jenkins-x/lighthouse/issues/new?title=Command%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by axsaucedo** [comment]
Nice one! I've tested in kubernetes 1.18 and Kubernetes 1.12 and can confirms it works as expected. 

Two things that would be good to add issues for to follow up:
* Pinning the version of the integration tests to k8s 1.18 (or a specific version
* Updating the operator and executor golang dependencies to 1.18 (from 1.17)

/approve

**Comment by seldondev** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[axsaucedo](https://github.com/SeldonIO/seldon-core/pull/2339#issuecomment-683394835 "Approved")*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=SeldonIO%2Fseldon-core).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com#issuecomment-683394835/SeldonIO/seldon-core/blob/master/OWNERS)~~ [axsaucedo]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
